### ISSUE TITLE
Unable to collect coverage from exe .net framework application

### ISSUE THREAD

**Issue by pkruk2** [coverlet-coverage/coverlet#1001]
Hello,

Is it possible to collect application coverage from .net framework executable (console application)?

For example I have created new .net framework 4.7.2 project in Visual Studio and tried to collect coverage using the approach described in [Code Coverage for integration tests and end-to-end tests](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage-for-integration-tests-and-end-to-end-tests) but no coverage was collected.

The same approach worked for .net core 3.1 console application (created with "dotnet new console -f netcoreapp3.1")

Here's how it looked for .net framework application:

```
pkruk@SCORPION MINGW64 ~/source/repos/consoleFramework/consoleFramework
$ coverlet bin/Debug --target bin/Debug/consoleFramework.exe
Hello there

Calculating coverage result...
  Generating report 'C:\Users\pkruk\source\repos\consoleFramework\consoleFramework\coverage.json'
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```

And for .net core application:

```
$ coverlet bin/Debug/netcoreapp3.1/ --target bin/Debug/netcoreapp3.1/console2.exe
Hello World!

Calculating coverage result...
  Generating report 'C:\Users\pkruk\source\repos\console2\coverage.json'
+----------+------+--------+--------+
| Module   | Line | Branch | Method |
+----------+------+--------+--------+
| console2 | 100% | 100%   | 100%   |
+----------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | 100% | 100%   | 100%   |
+---------+------+--------+--------+
```

Attaching .net framework console application sources for your convenience:
[consoleFramework.zip](https://github.com/coverlet-coverage/coverlet/files/5597369/consoleFramework.zip)

**Comment by MarcoRossignoli** [comment]
That feature will be in next release, for not try with

```
coverlet C:\git\coverletissue\consoleFramework\bin\Debug\consoleFramework.exe --target C:\git\coverletissue\consoleFramework\bin\Debug\consoleFramework.exe --include-test-assembly
```
And set pdb type to portable
![image](https://user-images.githubusercontent.com/7894084/100331463-7e15e800-2fd0-11eb-886e-6a2d68368c8b.png)
```
❯ coverlet C:\git\coverletissue\consoleFramework\bin\Debug\consoleFramework.exe --target C:\git\coverletissue\consoleFramework\bin\Debug\consoleFramework.exe --include-test-assembly
Hello there

Calculating coverage result...
  Generating report 'C:\git\coverletissue\consoleFramework\coverage.json'
+------------------+------+--------+--------+
| Module           | Line | Branch | Method |
+------------------+------+--------+--------+
| consoleFramework | 100% | 100%   | 100%   |
+------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | 100% | 100%   | 100%   |
+---------+------+--------+--------+
```

**Comment by pkruk2** [comment]
Thanks, it works like that.

> That feature will be in next release

Do you mean support for Full PDBs ? Or something else?

**Comment by MarcoRossignoli** [comment]
No I mean the possibility to pass as first argument a directory and not a file

**Comment by MarcoRossignoli** [comment]
Coverlet uses cecil that support only portable pdb

**Comment by pkruk2** [comment]
I'm pretty sure mono.cecil supports both full and portabl pdb formats? Unless they removed full pdb format support recently (which would be weird...)

**Comment by MarcoRossignoli** [comment]
Sorry, I think you're right we support only portable because we use `MetadataReaderProvider.FromPortablePdbImage` to open pdb. I didn't know why at the moment, I started to contribute to coverlet after that.

**Comment by MarcoRossignoli** [comment]
So for the moment we support only portable pdb and there is no plan to support full.

**Comment by pkruk2** [comment]
ok thanks

**Comment by MarcoRossignoli** [comment]
Feel free to close if solved

**Comment by pkruk2** [comment]
Well I'd prefer if there was support for Full PDB format. If not, at least documenting this would be useful. From this point of view, I'd prefer to keep this open as "please add full pdb support" or "please document limitation" issue. But if you choose to close it anyway, I'll accept and won't reopen it ;)

**Comment by MarcoRossignoli** [comment]
Pls open a new issue for that and I'll tag as requested "feature" and we'll wait for some thumbs up. It's first time we get a request like that but maybe other guys from community need it.
