### ISSUE TITLE
Unable to instrument module

### ISSUE THREAD

**Issue by subramaniamb** [coverlet-coverage/coverlet#1007]
I have a Xamarin Forms project which has unit tests written using NUnit targeting .Net Core 3.1. I am unable to get the code coverage generated due to an error/warning. Please find below the logs

`````
/usr/local/bin/dotnet test /Users/runner/work/1/s/App.Test/App.Test.csproj --logger trx --results-directory /Users/runner/work/_temp --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/Users/runner/work/1/s/TestResults/Coverage/ /p:CopyLocalLockFileAssemblies=true

/Users/runner/.nuget/packages/coverlet.msbuild/2.9.0/build/coverlet.msbuild.targets(31,5): warning : [coverlet] Unable to instrument module: /Users/runner/work/1/s/App.Test/bin/Release/netcoreapp3.1/Xamarin.Forms.Core.dll because : No symbol found for file: /Users/runner/work/1/s/App.Test/bin/Release/netcoreapp3.1/Xamarin.Forms.Core.dll [/Users/runner/work/1/s/App.Test/App.Test.csproj]

Test run for /Users/runner/work/1/s/App.Test/bin/Release/netcoreapp3.1/App.Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Results File: /Users/runner/work/_temp/_Mac-1606664309627_2020-11-29_15_42_20.trx

Test Run Successful.
Total tests: 15
     Passed: 15
 Total time: 1.4592 Seconds

Calculating coverage result...
  Generating report '/Users/runner/work/1/s/TestResults/Coverage/coverage.cobertura.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```

Any help to resolve the issue is highly appreciated. Thanks.
`````

**Comment by subramaniamb** [comment]
@MarcoRossignoli : I am kind of stuck with this issue. It would be really helpful if you can take a look at this issue. Thanks.

**Comment by MarcoRossignoli** [comment]
the warning for `Xamarin.Forms.Core.dll` shouldn't be an issue...you don't have source file of that so it's ok that coverlet skip it, it's a warning not an error.
Can you add some logging and attach here?Be sure to not share secrets sometimes it appears in logging
This is the guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration

Also can you try to use collectors https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
There is a known issue that sometimes raise with msbuild and .NET tool driver https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test

**Comment by subramaniamb** [comment]
@MarcoRossignoli : I think I figured out the root cause for the issue. If I change the build configuration from Release to Debug, it is working. Any idea why?

**Comment by tonerdo** [comment]
@subramaniamb it's a lot more ideal to run code coverage in Debug mode because that is when the structure of the compiled code most resembles the source code. In Release mode, applied optimizations could drastically deviate from the source code

**Comment by hello-ccchen** [comment]
@MarcoRossignoli I have the same issue for net5.0 as well. 😭

**Comment by MarcoRossignoli** [comment]
@subramaniamb @hello-ccchen  have you tried with collectors driver?

**Comment by subramaniamb** [comment]
> @subramaniamb @hello-ccchen have you tried with collectors driver?

I haven't. Could you please elaborate on collectors driver?

**Comment by MarcoRossignoli** [comment]
Collectors driver is a way where we use VSTest platform as orchestrator of coverage workflow. Today is the most reliable way to use coverlet due to default behavior of test platform.
Take a look at guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
And known issue of other driver(.NET Tool and msbuild) https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by hello-ccchen** [comment]
@MarcoRossignoli 
> Collectors driver is a way where we use VSTest platform as orchestrator of coverage workflow. Today is the most reliable way to use coverlet due to default behavior of test platform.
> Take a look at guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
> And known issue of other driver(.NET Tool and msbuild) https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

Tried but not working. No code coverage at all
![image](https://user-images.githubusercontent.com/34128411/103983842-f6bbb700-51c0-11eb-8cf5-501a562c0c49.png)

Report:  
```<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1610087877" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

**Comment by MarcoRossignoli** [comment]
@hello-ccchen are you using last version of coverlet lib?

**Comment by hello-ccchen** [comment]
> @hello-ccchen are you using last version of coverlet lib?

@MarcoRossignoli Yes. is the latest coverlet lib. My dotnet is the latest as well net5.0

**Comment by MarcoRossignoli** [comment]
Can yoy try to enable logs?Pay attention in logs could be present sensitive data

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
