### ISSUE TITLE
About Coverlet

### ISSUE THREAD

**Issue by jt4000** [coverlet-coverage/coverlet#1024]
Hello,

1.
What is the purpose to use this tool?

2.
What benefit can you use when you install Coverlet?

3.
What context is it relevant to use Coverlet? Any example?

Thank you!

**Comment by MarcoRossignoli** [comment]
> What is the purpose to use this tool?
What benefit can you use when you install Coverlet?

The purpose of coverlet is to provide code coverage metrics for .NET applications

> What context is it relevant to use Coverlet? Any example?

You can take a look at our guides and sample https://github.com/coverlet-coverage/coverlet#how-it-works

**Comment by jt4000** [comment]
I have a foundation of this tool and my followup question is:

*Is this tool Coverlet has as a unique skills that Microsoft's Test explorer from Visual Studio 2019 don't have it?
*Should I use Microsoft's Test explorer or Coverlett and why? 
*Any Cons and Pros of using  Coverlett?

Thank you!


> > What is the purpose to use this tool?
> > What benefit can you use when you install Coverlet?
> 
> The purpose of coverlet is to provide code coverage metrics for .NET applications
> 
> > What context is it relevant to use Coverlet? Any example?
> 
> You can take a look at our guides and sample https://github.com/coverlet-coverage/coverlet#how-it-works

I have a foundation of this tool and my followup question is:

*Is this tool Coverlet has as a unique skills that Microsoft's Test explorer from Visual Studio 2019 don't have it?
*Should I use Microsoft's Test explorer or Coverlett and why? 
*Any Cons and Pros of using  Coverlett?

Thank you!

**Comment by MarcoRossignoli** [comment]
The main plus of coverlet is that is open source and is cross platform https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows

AFAIK today is the only cross platform open source coverage tool, is used also by https://github.com/dotnet the .NET Core runtime repo https://github.com/dotnet/runtime/blob/master/docs/workflow/building/libraries/code-coverage.md

**Comment by MarcoRossignoli** [comment]
Closing because answered. Feel free to reopen if needed.
