### ISSUE TITLE
Empty-body methods reduce code coverage

### ISSUE THREAD

**Issue by Serg046** [coverlet-coverage/coverlet#1025]
I know that empty methods which exist just because of some inherited interface actually break Interface Segregation Principle. But the thing is that I have it intentionally. I have the methods like BeforeProcessing() and AfterProcessing() which are kind of hooks. Many implementations use them but some of them don't need them. Eventually, I have some empty methods which reduce code coverage that's why I am forced to annotate them by [ExcludeFromCodeCoverageAttribute]. Have you already considered to exclude such methods automatically? What is your opinion on this?

**Comment by MarcoRossignoli** [comment]
Hi @Serg046,

it's not clear to me, if the method is empty is accounted correctly, what do you mean for "reduce code coverage"?

![image](https://user-images.githubusercontent.com/7894084/103134640-f5fc2e80-46b2-11eb-9f73-7f18b2dde8ca.png)

Are you meaning that there are no test that pass through that empty method?

**Comment by Serg046** [comment]
Yes, I don’t write such tests because I find them useless.

**Comment by MarcoRossignoli** [comment]
In that case my personal opinion is that the behavior as-is is correct and also you usage of attribute. If we add a new feat(new switch)  to skip all empty method could be too invasive and a dev could miss something.
What do you think @tonerdo @petli?

**Comment by tonerdo** [comment]
I agree with @MarcoRossignoli, if you have an empty method that absolutely must be there and won't have corresponding tests, it's best to exclude it from coverage using the supported attributes
