### ISSUE TITLE
Merge Coverage Files generated using collectors integration

### ISSUE THREAD

**Issue by nedgrady** [coverlet-coverage/coverlet#1027]
We're suffering from the first issue mentioned [here](https://github.com/coverlet-coverage/coverlet/blob/a1d47d37753460911853cc3f1e6ee41775f910fc/Documentation/KnownIssues.md), we see 0% code coverage when running integration tests (The tests use the asp.net core WebApplicationFactory/testhost method for spinning up an in-memory web hostserver)

Example:
`dotnet test src\Project.IntegrationTests -c Release --no-build --logger:trx ^
    --results-directory %testresults%/IntegrationTests ^
    /p:CollectCoverage=true ^
    /p:CoverletOutput=%testresults%\Coverage\ ^
    /p:\"CoverletOutputFormat=cobertura,json\" `

This sadly produces the 0% coverage on all lines/methods/classes etc as mentioned in the known issue document.

The suggested fix in the Known Issues document works a charm, using

`dotnet test src\Project.IntegrationTests -c Release --no-build --logger:trx  --results-directory %testresults%/IntegrationTests --collect:"XPlat Code Coverage"`

Produces plenty of code coverage metrics as expected, and can see those when we feed the coverage.cobertura.xml file into reportgenerator.

However as far as I know, the above dotnet test ONLY produces test coverage data in the coverage.cobertura.xml format, which can't be merged with coverage.coberatura.xml files from further test projects (e.g see [this error](https://github.com/coverlet-coverage/coverlet/issues/262)).

Is there a way to achieve any of the following:
 
1. Have collect:"XPlat Code Coverage spit out JSON coverage data to merge future dotnet tests with?
2. Merge the coverage.cobertura.xml files instead? (n.b. we are also relying on the 
    > | Total   | 100% | 100% | 100%  | 
getting spat out in the console to ensure 100% coverage)

**Comment by MarcoRossignoli** [comment]
> Have collect:"XPlat Code Coverage spit out JSON coverage data to merge future dotnet tests with?

For now there are only workaround like https://github.com/coverlet-coverage/coverlet/pull/225#issuecomment-573896446
In future we'll support it by design https://github.com/coverlet-coverage/coverlet/issues/1015#issuecomment-746174446

>getting spat out in the console to ensure 1

There is an open issue for it https://github.com/coverlet-coverage/coverlet/issues/681 and also here we need to talk to VSTest guys cc: @jakubch1

**Comment by nedgrady** [comment]
Thanks I'll give that a real go, couldn't seem to get the code coverage happening in proc the last time but will try with confidence this time.

Will close if no further issues

**Comment by nedgrady** [comment]
Forgive me still can't seem to get any reported coverage using the runsettings file. 

Example:

> dotnet test src\Project.IntegrationTests --collect:"XPlat Code Coverage" --settings CodeCoverage.runsettings --no-build --logger trx --results-directory %cd%

With runsettings file:

`<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
		<DataCollectionRunSettings>
				<DataCollectors>
						<DataCollector friendlyName="XPlat code coverage">
								<Configuration>
										<Format>opencover,json,cobertura</Format>
										<ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
										<SingleHit>false</SingleHit>
								</Configuration>
						</DataCollector>
				</DataCollectors>
		</DataCollectionRunSettings>
		<InProcDataCollectionRunSettings>
				<InProcDataCollectors>
						<InProcDataCollector assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null"
																 friendlyName="XPlat Code Coverage"
																 enabled="True"
																 codebase="coverlet.collector.dll" />
				</InProcDataCollectors>
		</InProcDataCollectionRunSettings>
</RunSettings>`

(n.b. took out the merging steps out, so I can be sure that there's any coverage generated for this project)

Results in three files, _coverage.json_, _coverage.cobertura.xml_ and _coverage.opencover.xml_. Have attached example coverage.cobertura.xml (1).
[1.coverage.cobertura.xml.txt](https://github.com/coverlet-coverage/coverlet/files/5755735/1.coverage.cobertura.xml.txt)

With no coverage hits reported, example report:

![image](https://user-images.githubusercontent.com/22095387/103381511-eed68580-4ae3-11eb-9b03-23536944b599.png)

Now if I remove the --settings CodeCoverage.runsettings:

> dotnet test src\Project.IntegrationTests --collect:"XPlat Code Coverage" --no-build --logger trx --results-directory %cd%

We only see the _coverage.cobertura.xml_ file, however it DOES contain coverage. (Sorry lots of stuff to anonymize in the file and not sure its worth to upload). With a report looking as expected:

![image](https://user-images.githubusercontent.com/22095387/103381776-b1bec300-4ae4-11eb-89b6-549a3b7ffe14.png)

Anything obviously missing etc from how we've got this setup?

**Comment by MarcoRossignoli** [comment]
You not need to add `InProcDataCollectors` collection section inside runsettings, it's inject automatically(we're embedded in VSTest platform).
Take a look at runsettings sample https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings 
Try also our hello world sample https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
