### ISSUE TITLE
Lower coverage reported than Visual Studio

### ISSUE THREAD

**Issue by subramaniamb** [coverlet-coverage/coverlet#1029]
I have a query on the coverage reported by coverlet. In my Xamarin project, the coverage reported by Visual Studio with the runsettings is 80% where as the coverage reported by coverlet with the same runsettings is 44%. I am unable to figure out the root cause. @MarcoRossignoli : Could you please help?

**Comment by MarcoRossignoli** [comment]
Can you try to compare the report generated by visual studio and for instance https://github.com/danielpalme/ReportGenerator 

I mean to understand which pieces of code are different.

**Comment by subramaniamb** [comment]
Really appreciate your quick response.

On comparing the report with VS, I could see that the folders/files excluded in runsettings is not being considered. Also, noticed that the coverage is same with/without runsettings. Any thoughts?

**Comment by mmuecke** [comment]
I have the same issue.
You can find an example here: https://github.com/mmuecke/RxMQTTnet/pull/18 
In VS 100% and  84.21% with coverlet collector (https://codecov.io/gh/mmuecke/RxMQTTnet/compare/dc6b99f4e2024a2a37feb83651c3b4022626e236...cc663c761b2117d3445d4b3ba0aa7d384a6e5bfe/changes)

**Comment by MarcoRossignoli** [comment]
@mmuecke I think you issue is different, you're using version 3.0.0 and there is a bug we found and fixed, well release 3.0.1 soon https://github.com/coverlet-coverage/coverlet/issues/1037
