### ISSUE TITLE
Version 3.0.0 Release Date

### ISSUE THREAD

**Issue by mikes-gh** [coverlet-coverage/coverlet#1033]
- I am consuming nightly as I need 2 features in it.
- Any news on 3.0.0.  The nuget configuration is making it hard for my CI and clone builds.
- Great project thankyou

**Comment by MarcoRossignoli** [comment]
> I am consuming nightly as I need 2 features in it.

Just released, we apologize the delay, it was a crazy year not only for covid for me. 
Anyway we're trying to expand our maintainer team to be more "productive", the eternal OSS issue of small project. 

> Any news on 3.0.0. The nuget configuration is making it hard for my CI and clone builds.

Mmm sorry I don't understand what you mean

> Great project thankyou

THANKS A LOT FOR THESE FEW WORDS THAT MAKES THE DIFFERENCE.

**Comment by mikes-gh** [comment]
Thanks I just updated my project all working great and I can no do conditional reporting with the new MSBuild variable.
The problem was having a nuget outside the default source made the CI build fail

**Comment by MarcoRossignoli** [comment]
Cool, feel free to close this if solved!
