### ISSUE TITLE
Coverage 0% for implicit used netstandard project

### ISSUE THREAD

**Issue by schrufygroovy** [coverlet-coverage/coverlet#1034]
I have a .NET core web API solution, that is covered by .NET integration tests (https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests).

The web API solution is using some own library projects, that are netstandard projects and part of the solution. PDB file for the library does exist.

When I try to figure out the coverage then:
- the coverage for the controllers of the API and whole API project is correct.
- even the coverage of another "shared" API project that is implicitly used, is correct.

The coverage for the netstandard library that is used by the API is 0 %. Even though the exact line in the controller, that uses the library is marked as `covered`.

I have reduced the solution to the bare minimum and can still reproduce the issue:
https://github.com/schrufygroovy/coveragenotworking

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this.

**Comment by schrufygroovy** [comment]
updated to `3.0.1` -> still 0 % coverage

**Comment by MarcoRossignoli** [comment]
I see on test you're using msbuild integration, can you try with collectors one?Maybe you're hitting known issue https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by schrufygroovy** [comment]
thx @MarcoRossignoli 
this seems to resolve the problem.

I missunderstood the known issue. I thought I would receive a warning when it occures.

**Comment by MarcoRossignoli** [comment]
> I missunderstood the known issue when I saw it. I thought I would receive a warning when it occures.

Unfortunately not because it's a kill from vstest plat and it's randomic, depends on how much time tests run.
