### ISSUE TITLE
Getting intermediate (current) coverage percent during tests execution

### ISSUE THREAD

**Issue by IgorBuchelnikov** [coverlet-coverage/coverlet#1046]
Is there a way? I need it for generating code of tests

**Comment by Malivil** [comment]
If you mean showing coverage while in Visual Studio, there are a couple 3rd-party add-ins you can read about here: https://github.com/coverlet-coverage/coverlet#Visual-Studio-Add-In

**Comment by IgorBuchelnikov** [comment]
I mean the opportunity to get a coverage percent within the test code (C#) during it is executed

**Comment by Malivil** [comment]
If you look at those Visual Studio add-ins, they will give you line markings and coverage numbers right in VS while you execute your tests.

**Comment by IgorBuchelnikov** [comment]
Thanks, I will look at https://github.com/FortuneN/FineCodeCoverage

**Comment by IgorBuchelnikov** [comment]
@Malivil I didn't find what I want. When I run Code Coverage I see results (including line markings) only when all the tests have been executed.
Do you mean Live Unit Testing? I'm assuming Live Unit Testing executes every test method separately and calculate coverage after each test has been executed. This allows Live Unit Testing to show line-markings when you **type code**. 
My problem is that my test method takes 4 hours. It combines many variants of input data. I want to get only useful variants, that increase coverage to minimize the time of unit test execution.

**Comment by IgorBuchelnikov** [comment]
I expect to write something like this:

```
[Test]
public void TestMethod()
{
    int lastDistinctVisitedLocationsCount = 0;
	
    for (int i = 0, i < 10000; i++)
            for (int j = 0, j < 10000; j++)  
            {
		test(i, j);
				
		int currentDistinctVisitedLocationsCount = 
			CoverletApi.GetCurrentDistinctVisitedLocationsCount("AssemblyName");
					
		if (currentDistinctVisitedLocationsCount > lastDistinctVisitedLocationsCount)
		{
			File.AppendLines("UsefulCombinations.txt", new []{$"{i} {j}"});
			lastDistinctVisitedLocationsCount = currentDistinctVisitedLocationsCount;
		}
            }
}
```

**Comment by MarcoRossignoli** [comment]
> I mean the opportunity to get a coverage percent within the test code (C#) during it is executed

This is not supported yet, I did some experiment in past https://github.com/coverlet-coverage/coverlet/pull/628 where you can instrument and read instrumentation level live.

Something like https://twitter.com/MarcoRossignoli/status/1201546945589841922?

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation, feel free to reopen if needed.

**Comment by IgorBuchelnikov** [comment]
Are you planning to implement this feature?

**Comment by MarcoRossignoli** [comment]
@IgorBuchelnikov at the moment we don't have a lot of requests for this feature, usually we prioritize issue in this order bugs, feature with high thumb up interest.

You could open an issue with the feature proposal(i.e. code sample/flag to add and behavior) and we can wait for community interest in the idea.

Does it work for you?
