### ISSUE TITLE
Wrong coverage report

### ISSUE THREAD

**Issue by muriloebsantos** [coverlet-coverage/coverlet#1050]
Please follow this thread on Stackoverflow: https://stackoverflow.com/questions/65721281/dotnet-test-coverlet-wrong-coverage

I think this might be an issue with coverlet. I appreciate any help

**Comment by petli** [comment]
Please see #1037, it's a known issue in 3.0.0 that you reference in that project.  Tomorrow the nightly builds of 3.0.1 will contain a fix for this, and there's a patch release coming soon. There is an out-of-band build in https://github.com/coverlet-coverage/coverlet/issues/1037#issuecomment-759232073 that you can try in the meantime, if you don't want to wait.
