### ISSUE TITLE
Some .Net core 3.1 projects reporting 0% coverage

### ISSUE THREAD

**Issue by harshinipriya** [coverlet-coverage/coverlet#1051]
We have a .NET core 3.1 solution which contains an integration test project for a Hosted background service. We are using xunit v2.4.1 as the testing framework and Microsoft.AspNetCore.Mvc.Testing nuget to start the long running IHostedService from our test project. The coverage report is generated by using coverlet.msbuild v2.8.1 and Microsoft.NET.Test.Sdk v16.4.0. 

The results show that some of the library projects referenced by our .Net core Generic Host Application are not being reported by coverlet even though they are invoked by the service being tested. The screenshot below shows the two projects of interest(highlighted) which are reporting 0% coverage.

![ConsumerCoverage](https://user-images.githubusercontent.com/15010037/104676818-26cdf300-56b6-11eb-97eb-9a52ea5b8849.png)

On the other hand, we also have an API Integration test project in the same solution with same configurations as mentioned above, except we are using Microsoft.AspNetCore.TestHost nuget to start a TestServer instance. The same library projects now have a coverage greater than 0% which is expected.

![APICoverage](https://user-images.githubusercontent.com/15010037/104676836-2f262e00-56b6-11eb-9b8f-89de6e2ae62e.png)

We are unsure as to what is causing a 0% coverage on these selective projects in the first scenario.

**Troubleshooting Steps:**
1. Checked with the latest coverlet nuget v3.0, the issue persists. 
2. Started test run with Diagnostic logs enabled, noticed that the projects of interest are being instrumented but the results are not being generated in _C:\Users\<user>\AppData\Local\Temp_ as shown in the image. No errors though!

![image](https://user-images.githubusercontent.com/15010037/104676212-f3d72f80-56b4-11eb-963b-6b14ce1cf853.png)

**Comment by MarcoRossignoli** [comment]
Can you try with collectors version?
Maybe you're suffering of a known issue related to premature test process kill by test platform https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by harshinipriya** [comment]
Just did a test run with coverlet.collector v3.0.1 with Microsoft.NET.Test.Sdk v16.5.0. The results are still 0% for the two projects mentioned previously.

**Comment by harshinipriya** [comment]
Update: As mentioned earlier, we have an API Integration test project in the same solution where we are using _Microsoft.AspNetCore.TestHost_ package to start a TestServer in-memory instead of _Microsoft.AspNetCore.Mvc.Testing_ and found the coverage reports to be as expected. 

I did a quick test and changed the API Integration test project to use _Microsoft.AspNetCore.Mvc.Testing_ instead of _Microsoft.AspNetCore.TestHost_ and noticed that the coverages dropped to 0%. Are there any known issues around this scenario?

P.S. I'm also working on creating a sample solution which will help reproduce this issue, I'll attach to this thread when ready.

**Comment by MarcoRossignoli** [comment]
> I did a quick test and changed the API Integration test project to use Microsoft.AspNetCore.Mvc.Testing instead of Microsoft.AspNetCore.TestHost and noticed that the coverages dropped to 0%. Are there any known issues around this scenario?

Mmm nothing come into my mind, but one question can you attach your command line are you using `dotnet test /p:CollectCoverage=true` or `dotnet test --collect:"XPlat Code Coverage"` ?

**Comment by harshinipriya** [comment]
Thank you, that solved our issue. Our cake script was using `dotnet test /p:CollectCoverage=true`. Used `dotnet test --collect:"XPlat Code Coverage"`, we're now getting the expected coverage.
