### ISSUE TITLE
Multi-line lambda false negatives in 3.0.1

### ISSUE THREAD

**Issue by ulrichb** [coverlet-coverage/coverlet#1056]
Okay, it got way better with 3.0.1 (after 3.0.0's  #1037 has been fixed), but there are still false negatives (compared to coverlet.collector 1.3.0).

Example 1:
![image](https://user-images.githubusercontent.com/388796/104809319-c2fa1600-57ec-11eb-960d-fe4471fd9558.png)

Example 2:
![image](https://user-images.githubusercontent.com/388796/104809354-fa68c280-57ec-11eb-8be2-e99689d294f5.png)

_Originally posted by @ulrichb in https://github.com/coverlet-coverage/coverlet/issues/1037#issuecomment-761539715_

... I'm trying to create a repro sample.

**Comment by ulrichb** [comment]
Okay, it's simply a multi-line lamba:

```C#
    public class SampleTest
    {
        [Fact]
        public void T1()
        {
            Do(x => Console.WriteLine(x.GetType().Name));

            Do(x => Console.WriteLine(x
                .GetType()
                .Name));

            Do2(x => x.GetType().Name.Length);

            Do2(x => x.GetType()
                .Name
                .Length);
        }

        private static void Do(Action<object> action)
        {
            action(new object());
        }

        private static object Do2(Func<object, object> func)
        {
            return func(new object());
        }
    }
```

![image](https://user-images.githubusercontent.com/388796/104809930-5fbeb280-57f1-11eb-8ee0-c06cb62a2068.png)

**Comment by MarcoRossignoli** [comment]
Thanks

**Comment by MarcoRossignoli** [comment]
ok I was able to repro 

![image](https://user-images.githubusercontent.com/7894084/104810144-1ec79d80-57f3-11eb-8a9b-cec1a99aaaea.png)

**Comment by ulrichb** [comment]
Nice. And btw. thanks for this great, great tool!

**Comment by MarcoRossignoli** [comment]
We changed a bit the accounting alg because it was a bit a mess, now we need to adjust a bit. Np we'll fix it.

**Comment by MarcoRossignoli** [comment]
@ulrichb can you try the fix?


[coverlet.console.3.0.2-preview.2.g6741924090.zip](https://github.com/coverlet-coverage/coverlet/files/5824778/coverlet.console.3.0.2-preview.2.g6741924090.zip)

**Comment by ulrichb** [comment]
Hmm, do you also have a prerelease .collector nuget package?

**Comment by MarcoRossignoli** [comment]
It's a zip with all three packages inside

**Comment by ulrichb** [comment]
Yipee, just tested your build and my repro and my real code is 100% covered again. Thank you very much!

**Comment by MarcoRossignoli** [comment]
@martincostello @JSkimming @Malivil @Dave-EMIS someone of you can try the package on your project and let us know if it's all ok? https://github.com/coverlet-coverage/coverlet/issues/1056#issuecomment-761595855

**Comment by Malivil** [comment]
Looks good on my solution. The only unexpected change I saw was marking a line as covered that ended a multi-line ternary statement with multi-line lambdas inside. I think it's completely understandable to show that as covered, though, so I don't think it's a problem. For example:

```
return DoThing ? 
    HandleThingTrue(() => // Entire lambda covered
    {
        DoOtherThing();
    })
    : HandleThingFalse(() => // Entire lambda uncovered
    {
        DoThirdThing();
    }); // Covered
```

In terms of the coverage numbers:

MSBuild 2.9.0: ![2 9 0 Coverage](https://user-images.githubusercontent.com/1238511/104844032-c00a2e80-589b-11eb-9e1d-86e08635a8ce.png)
MSBuild 3.0.1: ![3 0 1 Coverage](https://user-images.githubusercontent.com/1238511/104844039-c698a600-589b-11eb-9727-5eccd41c39af.png)
MSBuild 3.0.2: ![3 0 2 Coverage](https://user-images.githubusercontent.com/1238511/104844046-cb5d5a00-589b-11eb-964e-9c5fe8f3e6c6.png)

Overall, looks good to me =)

**Comment by MarcoRossignoli** [comment]
> I think it's completely understandable to show that as covered, though, so I don't think it's a problem.

It's ok...lambda accounting it's a bit complex, coverlet uses sequence points(strong choice sometimes uncomfortable) and sometimes are "nested" i.e. 

sequence A
line 1 {
line 2    ...
line 3   ...
line 4 }

sequence B (lambda closure object)
line 2 ...
line 3 ...

When we have an hit for A and not for B we account for covered line 1 and 4 from A but we use sequence B for 2 and 3.

**Comment by JSkimming** [comment]
@MarcoRossignoli Results comparing different version of coverlet and OpenCover.

## Summary

All looks good.

## Results

| | coverlet.msbuild 2.9.0 | coverlet.msbuild 3.0.1 | coverlet.msbuild 3.0.2-preview.2.g6741924090 | OpenCover 4.7.922 |
| - | - | - | - | - |
| [Castle.Core.AsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor) (Debug)   | 100% (328 of 328) | 100% (328 of 328) | 100% (328 of 328) | 100% (333 of 333) |
| [Castle.Core.AsyncInterceptor](https://github.com/JSkimming/Castle.Core.AsyncInterceptor) (Release) | 100% (220 of 220) | 100% (220 of 220) | 100% (220 of 220) | 100% (227 of 227) |
| [abioc](https://github.com/JSkimming/abioc) (Debug)   | 99.8% (2215 of 2219) | 99.8% (2216 of 2219) | 99.8% (2216 of 2219) | 99.8% (2219 of 2222) |
| [abioc](https://github.com/JSkimming/abioc) (Release) | 99.8% (1743 of 1745) | 99.9% (1744 of 1745) | 99.9% (1744 of 1745) | no longer works 🤷 |
| [Tesla.NET](https://github.com/JSkimming/tesla-net) (Debug)   | 100% (683 of 683) | 100% (683 of 683) | 100% (683 of 683) | 100% (683 of 683) |
| [Tesla.NET](https://github.com/JSkimming/tesla-net) (Release) | 100% (589 of 589) | 100% (589 of 589) | 100% (589 of 589) | 100% (589 of 589) |

It looks like I incorrectly compared debug and release version when I stated coverlet was now giving comparable results as OpenCover, though the good news is, it already was 😃

**Comment by JSkimming** [comment]
I'm, not a big user of lambdas, I tend to use local functions or private methods for anything more complex than `x => x.Property`, which may be why my libraries are unaffected.

**Comment by MarcoRossignoli** [comment]
Thx for the test @JSkimming

**Comment by MarcoRossignoli** [comment]
After midnight will be on nightly. 
I'd like need to check another issue before release, if I won't find a solution I'll release in a week.

**Comment by MarcoRossignoli** [comment]
Just released new version https://github.com/coverlet-coverage/coverlet/releases/tag/v5.6.2
