### ISSUE TITLE
Unable to resolve method reference

### ISSUE THREAD

**Issue by JayDZimmerman** [coverlet-coverage/coverlet#1063]
We have an ASP.NET Core 3.1 application being built, tested, and deployed in an Azure DevOps pipeline.  The associated unit test project makes use of xunit, coverlet.collector, and coverlet.msbuild.  The following statement is executed by the pipeline:

`D:\a\_temp\dotnet\dotnet.exe test D:\a\1\s\test\MyService.Api.UnitTests\MyService.Api.UnitTests.csproj --logger trx --results-directory D:\a\_temp --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:settings=codecoverage.runsettings`

It has been running like a champ.  Today I attempted to update the coverlet.msbuild package from 2.9 to 3.0.1, and a series of warnings began appearing, such as these:

`D:\a\1\.nuget\packages\coverlet.msbuild\3.0.1\build\coverlet.msbuild.targets(39,5): warning : [coverlet] Unable to resolve method reference "Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions::AddSingleton<MyCompany.MyService.Interfaces.IDocumentStoreProxyClient,MyCompany.MyService.Infrastructure.Persistence.DocumentStoreProxyClient>(Microsoft.Extensions.DependencyInjection.IServiceCollection)", assuming calls to will return [D:\a\1\s\test\MyService.Api.UnitTests\MyService.Api.UnitTests.csproj]`

`D:\a\1\.nuget\packages\coverlet.msbuild\3.0.1\build\coverlet.msbuild.targets(39,5): warning : [coverlet] Unable to resolve method reference "System.Threading.Tasks.Task Microsoft.Extensions.Hosting.BackgroundService::StopAsync(System.Threading.CancellationToken)", assuming calls to will return [D:\a\1\s\test\MyService.Api.UnitTests\MyService.Api.UnitTests.csproj]`

Research pointed to people experiencing this in the past, so I tried out some suggestions around using the "RestorePackagesWithLockFile" feature, both as part of the project configuration and as a switch on the dotnet test command, but to no avail.  Rolling back to 2.9 cleared it up.

Any additional things I should look at?  I am unsure of what changes between versions 2.9 and 3.0.1 might explain it.  Below is the contents of my "codecoverage.runsettings" file, just in case it is helpful:

`<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector
				friendlyName="Code Coverage"
				uri="datacollector://Microsoft/CodeCoverage/2.0"
				assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Culture=neutral">
				<Configuration>
					<CodeCoverage>
						
						<ModulePaths>
							<Include>
								<ModulePath>.*.MyCompany.MyService.*.dll</ModulePath>
							</Include>
							<Exclude>
								<ModulePath>.*.UnitTests.dll</ModulePath>
								<ModulePath>.*.IntegrationTests.dll</ModulePath>
								<ModulePath>.*.FunctionalTests.dll</ModulePath>
							</Exclude>
						</ModulePaths>
					</CodeCoverage>
				</Configuration>
			</DataCollector>
		</DataCollectors>
	</DataCollectionRunSettings>
</RunSettings>`

**Comment by KinNeko-De** [comment]
i have this problem too with .NET 5 and the same setup (xunit, azure pipeline, same coverlet versions)

dotnet test MyProject.csproj --logger trx --results-directory /_temp -c Release --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

For me there is no negative result from this. code coverage reports are upload  and displayed as normal. So i do not rollback the version.

**Comment by MarcoRossignoli** [comment]
They're warning from new feature, I'll move to info next release to avoid noise.

**Comment by JayDZimmerman** [comment]
As far as I can tell, coverage information is being generated as expected.  The reason for my filing the issue was to a) ensure there were no difficult-to-detect analysis failures happening under the covers and b) request the possible elimination of the noise so that developers don't spend time investigating.  As long as it has been identified as a non-issue and will be looked into for a future release, I can live with it.

**Comment by MarcoRossignoli** [comment]
The idea is for now to move new reachability helper as opt-in, so that warnings should disappear.
