### ISSUE TITLE
Coverage loss chained lambdas

### ISSUE THREAD

**Issue by SebastienPortier** [coverlet-coverage/coverlet#1064]
Hi !

I have updated "coverlet.collector" Version="3.0.1" with the fix you provided on severe coverage loss in 3.0.0.

Even if the situation is clearly better, I am still missing some coverage with lambda "chained".

I saw on this [commit ](https://github.com/coverlet-coverage/coverlet/commit/070f2b47ef616a62e7fedc89cfec02eac9560ca9) you worked on the lambda coverage, but the tests doesn't take in account scenarios like the screenshot below

![Capture d’écran 2021-01-20 212502](https://user-images.githubusercontent.com/5903868/105230832-422d7800-5b66-11eb-861b-7e1be30ffd8f.png)
![Capture d’écran 2021-01-20 212717](https://user-images.githubusercontent.com/5903868/105230856-49548600-5b66-11eb-90a9-35ea682bb19e.png)

Modifying the code to be on a single line will correct the coverage OK 👍 

![Capture d’écran 2021-01-21 101846](https://user-images.githubusercontent.com/5903868/105330260-61fa8580-5bd2-11eb-9c8b-b4b43563d698.png)

Thanks you in advance for support ;-)

Regards,

**Comment by MarcoRossignoli** [comment]
Yep it's a dup of https://github.com/coverlet-coverage/coverlet/issues/1056
is fixed on master this weekend I'll release the fix officially.
You can try with nightly for now https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by SebastienPortier** [comment]
Nice ! Thanks for answer regards
