### ISSUE TITLE
What is "XPlat Code Coverage"

### ISSUE THREAD

**Issue by stricq** [coverlet-coverage/coverlet#1065]
I looked through the documentation and I could not anyplace that explains what "XPlat Code Coverage" is or even why it was needed.

**Comment by petli** [comment]
As I understand it it is just how to tell the underlying vstest driver to activate `coverlet.collector` to collect coverage information during test runs.  It is not something that's designed by Coverlet, but by vstest.  There's full documentation on how coverlet interacts with vstest on this page:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by MarcoRossignoli** [comment]
Yep @petli is correct `"XPlat Code Coverage"` is handled by VSTest plat to inject our collectors.

Take a look here https://github.com/microsoft/vstest/blob/master/src/vstest.console/Processors/CollectArgumentProcessor.cs#L253

**Comment by voroninp** [comment]
Is there any alias or another way to reference collector with something which does not contain spaces?

I've run into a TC's [issue](https://youtrack.jetbrains.com/issue/TW-24064/TeamCity-inserts-additional-quotes-in-command-line-parameters-when-using-command-line-build-step#focus=Comments-27-6614999.0-0).

**Comment by MarcoRossignoli** [comment]
Unfortunately not, you should have a way to escape the "

**Comment by voroninp** [comment]
Single quotes are also working!

**Comment by voroninp** [comment]
Ah, no =( They do not. But runsettings file does ;-)
Anyway, there's a way to get what I need.

**Comment by 8chan-co** [comment]
> Single quotes are also working!

\`\`*double quotes are better anyway*''
