### ISSUE TITLE
XMLException when deserializing CoverageResult from TestInstrumentationHelper

### ISSUE THREAD

**Issue by daveMueller** [coverlet-coverage/coverlet#1071]
I recently set up a new PC and now I can't execute the CoverageTests anymore (master branch). I feel really stupid for opening this ticket but I can't figure out what the issue is. Most likely it's something really trivial but I'm out of ideas. 

![image](https://user-images.githubusercontent.com/19378678/105921357-03e9fa00-6039-11eb-8990-c9a4c934becc.png)

The exception is always the same:

```
System.Xml.XmlException
Unexpected end of file.
   at System.Xml.EncodingStreamWrapper.ReadBOMEncoding(Boolean notOutOfBand)
   at System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)
   at System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
   at Coverlet.Core.CoveragePrepareResult.Deserialize(Stream serializedInstrumentState) in D:\Repos\coverlet\src\coverlet.core\CoveragePrepareResult.cs:line 26
   at Coverlet.Core.Tests.TestInstrumentationHelper.GetCoverageResult(String filePath) in D:\Repos\coverlet\test\coverlet.core.tests\Coverage\InstrumenterHelper.cs:line 65
   at Coverlet.Core.Tests.CoverageTests.AsyncAwait_Issue_669_2() in D:\Repos\coverlet\test\coverlet.core.tests\Coverage\CoverageTests.AsyncAwait.cs:line 118
```

**Comment by MarcoRossignoli** [comment]
> I feel really stupid for opening this ticket but I can't figure out what the issue is. 

You don't np at all sometimes happened also to me 😄 


Can you try to run out of IDE?
```
git clean -fdx
dotnet pack
dotnet test
```

**Comment by daveMueller** [comment]
OK you were right, running it without IDE works fine. So it must be that my current studio installation is missing something.

![grafik](https://user-images.githubusercontent.com/19378678/106057100-c1cfbf80-60ef-11eb-9aef-fe86e853135f.png)

**Comment by daveMueller** [comment]
Mhh seems to be the Resharper Test Explorer. I could swear that I saw the same results on the Visual Studio Test Explorer yesterday. And before I set up my new PC it also worked with Resharper. Never mind, I now can execute the tests again without getting these errors so this is fixed.

**Comment by MarcoRossignoli** [comment]
Can you try with Visual Studio to compare?
Honestly I never tried to run with test explorer in VS I debug a single test and after run all on console.

**Comment by daveMueller** [comment]
Yes in the VS test explorer the tests also fail but it throws another exception. Here it points to ```Tmds.ExecFunction```.

![image](https://user-images.githubusercontent.com/19378678/106243359-8e815380-6209-11eb-8920-2a4a18e8d539.png)

In the Resharper test explorer it throws the XmlException.

![image](https://user-images.githubusercontent.com/19378678/106243489-ca1c1d80-6209-11eb-83bd-a91b19eb55ad.png)

Maybe I need another sdk or so? Before I had set up my new PC I could use both test explorers to execute them.

**Comment by MarcoRossignoli** [comment]
Oh visual studio one it's ok...our way to run out of process tests are not supported inside vs...I use only console for testing...and for debugging a move `FuncExecutor.Run` to `FuncExecutor.RunInProcess` and when test works revert back and run all in console. So I don't have any idea of Resharper issue, is it worked in past?

**Comment by daveMueller** [comment]
Mhh ok I really think that both was working but I also could be wrong. Maybe I also just debugged the test I was working on and let the build job execute the other tests. 
But usually I execute all test in a solution before creating a PR and I'm 100% sure that I triggered them via visual studio or resharper ui. But never mind, now I know how to run them all again.
Thanks for the info.

**Comment by MarcoRossignoli** [comment]
I mean I'm sure about out process tests(no `RunInProcess`), others should run with no problem.
