### ISSUE TITLE
Wrong branch coverage on non-ranch code

### ISSUE THREAD

**Issue by valadas** [coverlet-coverage/coverlet#1076]
I don't know where to start troubleshooting this, but I have this:

![image](https://user-images.githubusercontent.com/6371568/106374924-6999f700-6355-11eb-9534-9c9a21b8a233.png)

And well, there is no if or anything causing this to show up as a branch. Any clue where to begin troubleshooting this issue ?

**Comment by MarcoRossignoli** [comment]
Which version are you using?

**Comment by petli** [comment]
There's a branch on row 73, do you know if you have a test for both `page < 1` and `page >= 1`?  That branch might get accounted on row 70 instead of 73, for some reason. Do you test a debug or release build?  A release build might move things around and make results less precise.

**Comment by valadas** [comment]
Hmm, yeah, so testing both < 1 and > 1 did fix it, it's odd though that it's indicating that on the wrong line, but I can see how this is kinda really one big statement from line 70-77 since the `;` for line 70 is on line 77.

So I guess it really statement coverage and not line-coverage. Anyway, that solved the issue, just have to think if terms of statements I guess. Thanks for the quick reply on this.
