### ISSUE TITLE
Unable to instrument module: [...] because : Failed to resolve assembly: 'System, Version=4.0.0.0, [...]

### ISSUE THREAD

**Issue by pkrukp** [coverlet-coverage/coverlet#1082]
Hi,

On https://github.com/ccnet/CruiseControl.NET one module is not instrumented. In log from vstest I can see:

```
TpTrace Warning: 0 : 9456, 1, 2021/02/09, 17:19:30.756, 22365378322705, datacollector.exe, [coverlet]Unable to instrument module: C:\Users\pkruk\source\OpenSource\CruiseControl.NET\project\UnitTests\bin\Debug\ThoughtWorks.CruiseControl.Core.dll because : Failed to resolve assembly: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

Indeed, there is no System dll next to the test assembly. I've seen https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#failed-to-resolve-assembly-during-instrumentation but I think System dll is not expected to be copied to the output?

How to reproduce:
1. clone CruiseControl.NET, build, download and unpack nugets for coverlet.collectors, vstest (microsoft.testplatform), nunit3testadapter
2. run:
```
'C:\Users\pkruk\Downloads\vstest\microsoft.testplatform.16.8.3.nupkg\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe' project/UnitTests/bin/Debug/ThoughtWorks.CruiseControl.UnitTests.dll '/TestAdapterPath:c:\Users\pkruk\Downloads\vstest\nunit3testadapter.3.17.0.nupkg\build\net35;c:\Users\pkruk\Downloads\coverlet\coverlet.collector.3.0.2.nupkg\build\netstandard1.0' /Collect:"XPlat Code Coverage" /Diag:vstest.log.txt
```

Expected result: coverage for ThoughtWorks.CruiseControl.Core.dll ("core" project) is collected, no errors about unable to instrument module in vstest.log.datacollector.*.txt

**Comment by MarcoRossignoli** [comment]
Which version of coverlet are you using?If you're using last one `3.0.2` does it work with past one `1.3.0`?

**Comment by pkruk2** [comment]
CruiseControl.NET is a .net framework, not .net core/.net project, `dotnet test` does not work.

It targets .net framework 4.5 mainly (the "core" project too).

The VSTestIntegration.md says versions before did not support .net framework fully, does it make sense to test it?

**Comment by pkruk2** [comment]
I tried using collectors `1.3.0` (same command line as previously just point to different collectors) but it does not find the collectors ("Unable to find a datacollector with friendly name 'XPlat Code Coverage'")

**Comment by MarcoRossignoli** [comment]
> CruiseControl.NET is a .net framework, not .net core/.net project, dotnet test does not work.

Do you mean you're not using new sdk?
Because `dotnet test` works for .NET framework application if the project file using new SDK https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview

**Comment by pkruk2** [comment]
(I'm not the owner of the CruiseControl.NET, just tried Coverlet on it)
Yes, it is a traditional project: https://github.com/ccnet/CruiseControl.NET/blob/master/project/core/core.csproj

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
