### ISSUE TITLE
Code coverage threshold does not fail if no coverage generated

### ISSUE THREAD

**Issue by martincostello** [coverlet-coverage/coverlet#1083]
If coverlet.msbuild is configured with a `Threshold` value for a minimum code coverage required by tests, but then no coverage is output for coverlet for some reason, then rather than fail the build, it instead passes because the total coverage is given as 100%.

```
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```

You can also see the average is reported as `NaN%`.

See https://github.com/reactiveui/refit/issues/1073 for a scenario where this behaviour masked an issue with code coverage generation because tests still passed.

Coverlet should fail the build and draw the developer's attention to the issue, rather than give a false impression that code coverage is being maintained above previous thresholds configured by the repository.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this.

**Comment by daveMueller** [comment]
I start to work on this.

**Comment by MarcoRossignoli** [comment]
Thx Dave!
