### ISSUE TITLE
Code coverage showing 0% and sometimes higher than 0%

### ISSUE THREAD

**Issue by MikaelFerland** [coverlet-coverage/coverlet#1085]
Hi,

I'm trying to have a repeatable code coverage report, but unfortunately it's not working as expected. 
As you can see in the title most of the time my coverage is 0%, but sometimes I had higher than 0%.
I expect higher than 0% because I have 14 tests written on that module.
It's only happening on a specific module, because I have another module that has more than 0%

I checked the binlog at GenerateCoverageResult and I have the following message :
`[coverlet] Hits file:'C:\Users\%USERPROFILE%\AppData\Local\Temp\$MYPROJECTNAME%_5216fbc5-bea1-4490-9c0b-bde6cb3f9140' not found for module: '%MYPROJECTNAME%'`

Where your can substitute %USERPROFILE% with my username and %MYPROJECTNAME% with my .csproj name.

Again I expect some hits instead of "not found module".

Here is the command :
```
    $excludedAssemblies = (Get-Content .\ExcludedAssemblies.txt) -join "%2c"
    $excludedFiles = (Get-Content .\ExcludedFiles.txt) -join "%2c"
    dotnet test ../../CustomPrj/CELDAS300_MASTER.sln `
        --filter "FullyQualifiedName!~.Integration.Tests" `
        --logger "trx" --results-directory $testResultsDirectory `
        -verbosity:diagnostic `
        -bl:msbuild.binlog `
        -noconsolelogger `
        /p:CopyLocalLockFileAssemblies=true `
        /p:CollectCoverage=true `
        /p:Exclude=$excludedAssemblies `
        /p:ExcludeByAttribute="Obsolete%2cGeneratedCodeAttribute%2cCompilerGeneratedAttribute" `
        /p:ExcludeByFile=$excludedFiles `
        /p:CoverletOutput="$testResultsDirectory/reports/" `
        /p:CoverletOutputFormat="opencover%2ccobertura%2cjson" `
        /p:MergeWith="$testResultsDirectory/reports/coverage.json" `
        -m:1 `
```

Thank you!

**Comment by petli** [comment]
This is a common occurrence in CI environments when using the MSBuild driver: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md

If you can, switch to using the VSTest integration that does not suffer this issue: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by MikaelFerland** [comment]
I saw that but it's rarely more that 0% in local too.
How do you deal with MergeWith and CoverletOutput in that case?

Is it possible to merge all .json at the end and output in Cobertura at the same time?

**Comment by petli** [comment]
Even local test runs can hit this issue, if you are unlucky.

Merging is not yet supported, but there is an issue you can track to follow progress on that (though depending on vstest): https://github.com/coverlet-coverage/coverlet/issues/1015#issuecomment-746174446

Meanwhile the recommended way is to use https://github.com/danielpalme/ReportGenerator to merge the reports after running the tests.

**Comment by MikaelFerland** [comment]
Yeah, thank you I just found that as it supports gobbling it's easy to merge from ReportGenerator instead of coverlet.
