### ISSUE TITLE
Docker RUN with coverlet.msbuild 3.0.2 empty report

### ISSUE THREAD

**Issue by goolzerg** [coverlet-coverage/coverlet#1089]
How I use it in Dockerfile:
``RUN dotnet nuget add source $nexus_url/repository/sod-nuget/index.json -n nexus && \
dotnet add package coverlet.msbuild && \
dotnet test Domain.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover``

and what I get during build:
```
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```
I tried to use coverlet.collector, it works fine, but it generates report which is not comatible with sonarqube.
Is there some options to solve this issue?
Maybe there is some way to convert coverlet.collector report to approptiate for sonarqube format?

**Comment by petli** [comment]
You can configure the coverlet.collector output format, see the section on runsettings here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings
Try that and see if it works for you.

**Comment by goolzerg** [comment]
> You can configure the coverlet.collector output format, see the section on runsettings here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings
> Try that and see if it works for you.

Sorry, my mistake. When I use coverlet.collector I get an empty report too:
```
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
```

I see this behavior just when I build appliction with `docker build`
But when I just run a container with `docker run` and then start analyse, all works fine:
```

+-----------------------------------------+--------+--------+--------+

| Module                                  | Line   | Branch | Method |

+-----------------------------------------+--------+--------+--------+

| Infinitum.Mpc.VerificationWorker.Domain | 73.14% | 65.62% | 62.5%  |

+-----------------------------------------+--------+--------+--------+



+---------+--------+--------+--------+

|         | Line   | Branch | Method |

+---------+--------+--------+--------+

| Total   | 73.14% | 65.62% | 62.5%  |

+---------+--------+--------+--------+

| Average | 73.14% | 65.62% | 62.5%  |

+---------+--------+--------+--------+
```

**Comment by petli** [comment]
So coverlet.collector produces an empty report without any other logging messages in a `docker build`, but not when running a similar command in `docker run`?  Can you share the full Dockerfile and command lines in the two cases?

If you can please also try enabling logging and attach the output to the issue (described here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md )

It sounds quite similar to #1088. I'm beginning to wonder if a slight difference in SDK versions might result in these different behaviours, or whatever else it might be.

**Comment by goolzerg** [comment]
> So coverlet.collector produces an empty report without any other logging messages in a `docker build`, but not when running a similar command in `docker run`? Can you share the full Dockerfile and command lines in the two cases?

Absolutely yes
Here is my Dockerfile (docker build way):
```
FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine as build-box
COPY . /app

FROM build-box as publish

# Init variables
ARG nexus_url
ARG SONAR_PROJECT
ARG SONAR_API_KEY
ARG testpath
ENV SONAR_API_KEY=$SONAR_API_KEY
ENV SONAR_PROJECT=$SONAR_PROJECT
ENV projectpath=$projectpath
ENV nexus_url=$nexus_url
ENV testpath=$testpath


# Build and static analyse
WORKDIR $testspath
RUN dotnet nuget add source $nexus_url/repository/sod-nuget/index.json -n nexus && \
    dotnet add package coverlet.msbuild && \
    dotnet test Domain.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
```

Here is bash commands (docker run way):
```
docker run -it --rm -v /src:/src mcr.microsoft.com/dotnet/sdk:3.1-alpine /bin/sh -c "cd /src/Domain.UnitTests; dotnet add package coverlet.msbuild; dotnet test Domain.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover"
 ```

> 
> If you can please also try enabling logging and attach the output to the issue (described here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md )
> 
Sure I'll turn on logging and try again to run tests, thanks for your help!

> It sounds quite similar to #1088. I'm beginning to wonder if a slight difference in SDK versions might result in these different behaviours, or whatever else it might be.


As I see he uses net5.0,  and I'm not sure that he uses Docker

**Comment by goolzerg** [comment]
I've just tried to start docker build with follow RUN command:
```
RUN  dotnet nuget add source $nexus_url/repository/sod-nuget/index.json -n nexus && \
         dotnet add package coverlet.msbuild && \
         dotnet test -c debug /p:CollectCoverage=True /p:CoverletOutputFormat=opencover -verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger
```
![image](https://user-images.githubusercontent.com/49819707/108362246-52904b80-7215-11eb-8b1e-86b5b27ab2ae.png)


And it works. But I don't understand why.

**Comment by petli** [comment]
Those commands are using `coverlet.msbuild` however, which is sensitive to timeouts (especially pronounced in CI environments, but I also think docker can show that.) Did you say that you run this with coverlet.collector too? If it is just `coverlet.msbuild` that shows the odd behaviour then it's a known issue with limitations in that driver (https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md), but if you also get empty reports with coverlet.collector in some situations but not all then it is something else (and there I'm seeing similarities in symptoms if nothing else with #1088).

**Comment by goolzerg** [comment]
> Those commands are using `coverlet.msbuild` however, which is sensitive to timeouts (especially pronounced in CI environments, but I also think docker can show that.) Did you say that you run this with coverlet.collector too? If it is just `coverlet.msbuild` that shows the odd behaviour then it's a known issue with limitations in that driver (https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md), but if you also get empty reports with coverlet.collector in some situations but not all then it is something else (and there I'm seeing similarities in symptoms if nothing else with #1088).

Coverlet.collector have the same behavior as coverlet.msbuild. When I run this command:
``` 
dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
 ````
 during build docker image - I get an empty report.
 
Attached diag log of coverlet.collector
[log.txt](https://github.com/coverlet-coverage/coverlet/files/6004266/log.txt)

**Comment by petli** [comment]
Thanks, that's a good clarification. Did you get additional log files?  https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md mentions additional filenames that may be produced.

**Comment by petli** [comment]
There's a similar issue #1121, and thinking about that one there may be an issue with the source code files if they target binaries have been built outside the docker image, and then the source code files are either not present or not having the same path names inside the image as outside that could cause coverlet to skip instrumenting the binaries.  If you got a `log.datacollector...txt` file it should say something about that.

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
