### ISSUE TITLE
Skipping code coverage for constructors that only set properties/fields.

### ISSUE THREAD

**Issue by Tylertron1998** [coverlet-coverage/coverlet#1090]
Currently, it appears coverage is generated for constructors that only set a property or a field - and this could be considered noise. From what I can gather - there is no way to avoid this. This would be a really nice feature as it'll make the coverage report a lot more accurate (are supposed to unit test a constructor that only inits fields?) - adding an attribute to every constructor would not be great.

**Comment by MarcoRossignoli** [comment]
If they're auto implemented prop you can try with https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#skip-auto-implemented-properties

**Comment by MarcoRossignoli** [comment]
Sorry do you mean the ctor instrumentation?

**Comment by Tylertron1998** [comment]
https://github.com/skyra-project/skyra/blob/main/services/Skyra.Grpc/Services/MemberService.cs#L16

this is a really good example - this is showing up as 'uncovered' when in reality, this isn't something you'd test.

For the auto props, I actually discovered that flag a few minutes after making the issue!

**Comment by MarcoRossignoli** [comment]
Ctor is a method so I think should be in the coverage. 
If you want to exclude some method from coverage you can use exclude by attribute feature https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#attributes

**Comment by Tylertron1998** [comment]
The issue with the attribute feature - it would mean that we'd have to add an attribute to every initialization constructor. While I agree this shouldn't be a feature by default - it would be a nice feature. I tried to see if there was a way to filter by name (i.e. if the name is .ctor, then ignore) but that doesn't seem like an option either.

**Comment by MarcoRossignoli** [comment]
At the moment we have filters for types...maybe we could extend it for methods name https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#filters

**Comment by MarcoRossignoli** [comment]
@Tylertron1998 if you're interested in that feature please open a new issue I'll tag it as `feature-request` and we'll prioritize it in relation to community interest(thumbs up/comments)

**Comment by MarcoRossignoli** [comment]
Closing because as-designed for now.
