### ISSUE TITLE
Ask for Package ID prefix reservation

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#1095]
https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

@tonerdo we should open an org on https://docs.microsoft.com/en-us/nuget/nuget-org/organizations-on-nuget-org for coverlet so we can register a "prefix reservation" and avoid "personal" one. 
After that we need to upload package with that new org administrator.
We can use same user/account of github organization.

cc: @petli

**Comment by tonerdo** [comment]
Reserving a package ID sounds good but I'm not sure we meet all the criteria. Specifically these ones:
```
Does the package ID prefix properly and clearly identify the reservation owner?
Is the package ID prefix something common that should not belong to any individual owner or organization?
```

**Comment by MarcoRossignoli** [comment]
Done
