### ISSUE TITLE
Unable to instrument module - due to Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by deacoder** [coverlet-coverage/coverlet#1102]
I try to run coverage with a .Net 5 NUnint test project using Coverlet collector 3.0.3. The project is not producing coverage project under test but for referenced class libraries there are coverage.

I'm running the following command:
`dotnet test <MY_TEST_PROJECT> --collect:"XPlat Code Coverage"  --diag:log.txt`

When examining the data collector log it seems to be related to Microsoft.Extensions.DependencyInjection.Abstractions is missing:
```
TpTrace Verbose: 0 : 36966, 1, 2021/03/01, 22:24:13.727, 4049879208140, datacollector.dll, [coverlet]TryWithCustomResolverOnDotNetCore exception: System.InvalidOperationException: Cannot find reference assembly 'WindowsBase.dll' file for package WindowsBase
   at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver[] customResolvers)
   at Coverlet.Core.Instrumentation.NetstandardAwareAssemblyResolver.TryWithCustomResolverOnDotNetCore(AssemblyNameReference name) in /_/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs:line 157
TpTrace Warning: 0 : 36966, 1, 2021/03/01, 22:24:13.728, 4049879564668, datacollector.dll, [coverlet]Unable to instrument module: /Users/sensitive_path/sensitive.dll because : AssemblyResolutionException for 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line
```
(_A lot more of the first kind of log `Cannot find reference assembly 'X.dll' file for package Y`._)

I've tried to add `<PreserveCompilationContext>true</PreserveCompilationContext>` but it didn't help. 

The only thing helping has been to manually copy the file `Microsoft.Extensions.DependencyInjection.Abstractions.dll` to the same path as test dll `/Users/sensitive_path/bin/Debug/net5.0/`. That generates coverage for project under test as well.

Any advise what I'm doing wrong? I can provide more logs if necessary (just have to wash out some sensitive data)

**Comment by daveMueller** [comment]
Looks to me like this [known issue](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#failed-to-resolve-assembly-during-instrumentation). Could you try a ```dotnet  publish``` before because then all references are resolved to the output directory.

**Comment by MarcoRossignoli** [comment]
> The only thing helping has been to manually copy the file Microsoft.Extensions.DependencyInjection.Abstractions.dll

Also as workaround you could add direct reference of that lib(same version) to test project.

**Comment by laghamn** [comment]
Running `dotnet <MY_TEST_PROJECT> --collect:"XPlat Code Coverage"  --diag:log.txt` will output to: 
`<MY_TEST_PROJECT>/bin/Debug/net5.0/Myapp.dll`

However publish puts it's output in:
<MY_TEST_PROJECT>/bin/Debug/net5.0/publish/Myapp.dll

But publishing to the same folder, with `-o`, as build it works. Not really convenient in a CI-pipeline but works...

@MarcoRossignoli: Unfortunately it didn't work by reference Microsoft.Extensions.DependencyInjection.Abstractions direct in test project. The Microsoft.Extensions.DependencyInjection.Abstractions.dll is not copied to output directory even if it's referenced(!).

**Comment by dea82** [comment]
Running `dotnet <MY_TEST_PROJECT> --collect:"XPlat Code Coverage" --diag:log.txt` will output to:
`<MY_TEST_PROJECT>/bin/Debug/net5.0/Myapp.dll`

However publish puts it's output in:
`<MY_TEST_PROJECT>/bin/Debug/net5.0/publish/Myapp.dll`

But publishing to the same folder, with `-o`, as build it works. Not really convenient in a CI-pipeline but works...

@MarcoRossignoli: Unfortunately it didn't work by reference Microsoft.Extensions.DependencyInjection.Abstractions direct in test project. The Microsoft.Extensions.DependencyInjection.Abstractions.dll is not copied to output directory even if it's referenced(!).

**Comment by m4rs2k** [comment]
Same problem here.

- Publishing to the same folder, with -o works well.
- Including Microsoft.Extensions.DependencyInjection.Abstractions.dll in the test project also works.

![image](https://user-images.githubusercontent.com/25437282/124504247-10ffd780-dd95-11eb-9ecf-cab0c8b102dc.png)

**Comment by m4rs2k** [comment]
Same issue here since upgrading from dotnet core 3.1 to dotnet 5

- Publishing to the test project output folder works well.
- Including Microsoft.Extensions.DependencyInjection.Abstractions.dll in the test project also works.

![image](https://user-images.githubusercontent.com/25437282/124504964-743e3980-dd96-11eb-81cf-547ac63e0e35.png)

**Comment by m4rs2k** [comment]
Same issue here

**Workaround 1** : Publishing to the test project output folder
**Workaround 2** : Adding Microsoft.Extensions.DependencyInjection.Abstractions.dll to the root of the test project. (Don't need to copy the file to the output folder)

![image](https://user-images.githubusercontent.com/25437282/124505808-4c4fd580-dd98-11eb-88b9-c6f0b7d55e1e.png)

**Comment by d1820** [comment]
any good update on a fix to this

**Comment by BlackGad** [comment]
To make this work you need proper `*.deps.json` file with additional `compile` elements which can be [omitted](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md#targets-section-depsjson) in generic build but present when you publish your project/solution.

In depth - **Microsoft.Extensions.DependencyInjection.Abstractions** assembly on generic build become conflicted between:
**CopyLocal**
```
ItemName=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  ConflictItemType=CopyLocal
  NuGetPackageId=Microsoft.Extensions.DependencyInjection.Abstractions
  FullPath=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  RootDir=C:\
  Filename=Microsoft.Extensions.DependencyInjection.Abstractions
  Extension=.dll
  RelativeDir=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\
  Directory=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\
  RecursiveDir=
  Identity=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  ModifiedTime=2021-10-23 02:48:34.0000000
  CreatedTime=2022-05-31 18:05:37.7765097
  AccessedTime=2023-03-15 10:39:06.6255910
  DefiningProjectFullPath=C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets
  DefiningProjectDirectory=C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\
  DefiningProjectName=Microsoft.NET.ConflictResolution
  DefiningProjectExtension=.targets
```
and **Reference**
```
ItemName=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  ConflictItemType=Reference
  NuGetPackageId=Microsoft.Extensions.DependencyInjection.Abstractions
  FullPath=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  RootDir=C:\
  Filename=Microsoft.Extensions.DependencyInjection.Abstractions
  Extension=.dll
  RelativeDir=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\
  Directory=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\
  RecursiveDir=
  Identity=<userFolder>\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\6.0.0\lib\net6.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
  ModifiedTime=2021-10-23 02:48:34.0000000
  CreatedTime=2022-05-31 18:05:37.7765097
  AccessedTime=2023-03-15 10:39:06.6255910
  DefiningProjectFullPath=C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets
  DefiningProjectDirectory=C:\Program Files\dotnet\sdk\7.0.101\Sdks\Microsoft.NET.Sdk\targets\
  DefiningProjectName=Microsoft.NET.ConflictResolution
  DefiningProjectExtension=.targets
```

So on **GenerateBuildDependencyFile msuild** target they will be just skipped
```
<ItemGroup>
      <ResolvedCompileFileDefinitions Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' == 'Reference'" />
      <NativeCopyLocalItems Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' != 'Reference'" />
      <ResourceCopyLocalItems Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' != 'Reference'" />
      <RuntimeCopyLocalItems Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' != 'Reference'" />
      <RuntimeTargetsCopyLocalItems Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' != 'Reference'" />
      <RuntimePackAsset Remove="@(_ConflictPackageFiles)" Condition="'%(_ConflictPackageFiles.ConflictItemType)' != 'Reference'" />
    </ItemGroup>

    <GenerateDepsFile ProjectPath="$(MSBuildProjectFullPath)"
                      AssetsFilePath="$(ProjectAssetsFile)"
                      DepsFilePath="$(ProjectDepsFilePath)"
                      TargetFramework="$(TargetFramework)"
                      AssemblyName="$(AssemblyName)"
                      AssemblyExtension="$(TargetExt)"
                      AssemblyVersion="$(Version)"
                      AssemblySatelliteAssemblies="@(IntermediateSatelliteAssembliesWithTargetPath)"
                      ReferencePaths="@(ReferencePath)"
                      ReferenceDependencyPaths="@(ReferenceDependencyPaths)"
                      ReferenceSatellitePaths="@(ReferenceSatellitePaths)"
                      ReferenceAssemblies="@(_ReferenceAssemblies)"
                      RuntimePackAssets="@(RuntimePackAsset)"
                      IncludeMainProject="$(IncludeMainProjectInDepsFile)"
                      RuntimeIdentifier="$(RuntimeIdentifier)"
                      PlatformLibraryName="$(MicrosoftNETPlatformLibrary)"
                      RuntimeFrameworks="@(RuntimeFramework)"
                      CompilerOptions="@(DependencyFileCompilerOptions)"
                      CompileReferences="@(ResolvedCompileFileDefinitions)"
                      ResolvedNuGetFiles="@(NativeCopyLocalItems);@(ResourceCopyLocalItems);@(RuntimeCopyLocalItems)"
                      UserRuntimeAssemblies="@(UserRuntimeAssembly)"
                      ResolvedRuntimeTargetsFiles="@(RuntimeTargetsCopyLocalItems)"
                      IsSelfContained="$(SelfContained)"
                      IncludeRuntimeFileVersions="$(IncludeFileVersionsInDependencyFile)"
                      RuntimeGraphPath="$(BundledRuntimeIdentifierGraphFile)"/>
```

When you publish your output folder there are no **Copy local** assemblies so there are no conflict and `*.deps.json` contains all this missed assemblies.
