### ISSUE TITLE
Partially covered throw statement (async handler)

### ISSUE THREAD

**Issue by mjeanrichard** [coverlet-coverage/coverlet#1103]
Hi, 

In the following code the ``throw`` statement is marked as partially covered (because of the async statemachine), even though I see no way to cover that hidden branch. Could this be detected and marked as covered by coverlet?

```csharp
public class AsyncThrowReproduction
{
	public async Task Execute(bool throwException)
	{
		try
		{
			if (throwException)
			{
				throw new InvalidOperationException();
			}
		}
		catch (InvalidOperationException)
		{
			await Task.Delay(1);
			throw;
		}
	}
}
```

Unit Tests:
```csharp
public class AsyncThrowReproductionFixture
    {
        [Fact]
        public async Task Execute_ShouldWork_Exception()
        {
            // Arrange
            var sut = new AsyncThrowReproduction();

            // Act
            async Task TestFunc() => await sut.Execute(true);

            // Assert
            await Assert.ThrowsAsync<InvalidOperationException>(TestFunc);
        }

        [Fact]
        public async Task Execute_ShouldWork_NoException()
        {
            // Arrange
            var sut = new AsyncThrowReproduction();

            // Act
            await sut.Execute(false);
        }
    }
```

Reported Coverage:
![image](https://user-images.githubusercontent.com/778448/109629829-8ab45a00-7b44-11eb-9058-719a07949de0.png)

Coverlet Version: 3.0.3

**Comment by msallin** [comment]
Find Repros for #1104 #1103 #914 here: https://github.com/meggima/coverlet-reproductions

**Comment by daveMueller** [comment]
Thanks for reporting and providing a repro. I had a quick peek on this. It seems this is a issue related to IL compiled with ```release``` configuration. At a first view when compiling with ```debug``` configuration the coverage looks as expected.

![image](https://user-images.githubusercontent.com/19378678/113072562-a81e2780-91c7-11eb-81c9-5af9016c96cd.png)

Really suspicious are the additional branches in the coverage result that are totally misplaced.

![image](https://user-images.githubusercontent.com/19378678/113072732-0f3bdc00-91c8-11eb-8696-9d1a04301f6f.png)

I'll take a look and do the deep dive. :wink:
