### ISSUE TITLE
Partially covered `await foreach` statement

### ISSUE THREAD

**Issue by meggima** [coverlet-coverage/coverlet#1104]
Hello

In the following code the `await foreach` as well as the `for` and the `yield` statements are marked as partially covered due to the hidden async/await logic of the compiler. Can this be reported as covered by coverlet?

Reproduction class:

```csharp
public class AwaitForeachReproduction
{
    public async Task<int> Execute()
    {
        int sum = 0;

        await foreach (int result in AsyncEnumerable())
        {
            sum += result;
        }

        return sum;
    }

    private async IAsyncEnumerable<int> AsyncEnumerable()
    {
        for(int i = 0; i < 100; i++)
        {
            await Task.Delay(10);
            yield return i;
        }
    }
}
```

Test Case for it:
```csharp
public class AwaitForeachReproductionFixture
{
    [Fact]
    public async Task Execute_ShouldWork()
    {
        // Arrange
        var sut = new AwaitForeachReproduction();

        // Act
        int result = await sut.Execute();

        // Assert
        Assert.Equal(4950, result);
    }
}
```

Reported coverage:
![image](https://user-images.githubusercontent.com/22348611/109637331-f3073980-7b4c-11eb-9e22-d79aa948543f.png)

Coverlet version: 3.0.3

**Comment by meggima** [comment]
You can find the full reproduction code (and also for some other cases) in this repository: https://github.com/meggima/coverlet-reproductions

**Comment by MarcoRossignoli** [comment]
assigned to @alexthornton1

**Comment by MarcoRossignoli** [comment]
Closed in https://github.com/coverlet-coverage/coverlet/pull/1107

**Comment by ipetrushevskiy** [comment]
If you change the _AsyncEnumerable_ method in the original example by changing method like that (code below), it will be partially covered again.

private async IAsyncEnumerable<int> AsyncEnumerable([EnumeratorCancellation] CancellationToken cancellationToken)
{
    for(int i = 0; i < 100; i++)
    {
        await Task.Delay(10, cancellationToken);
        yield return i;
    }
}
