### ISSUE TITLE
Make docs for consuming nightly more generic

### ISSUE THREAD

**Issue by daveMueller** [coverlet-coverage/coverlet#1105]
The docs for consuming the nightly build have a fixed preview version. This should be more generic to avoid misunderstandings.

[https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md)

>Yep we should remove the real version and add something like  `xxxx`

_Originally posted by @MarcoRossignoli in https://github.com/coverlet-coverage/coverlet/issues/1042#issuecomment-789080342_

**Comment by MarcoRossignoli** [comment]
Thx Dave
