### ISSUE TITLE
how to get coverlet command line tool

### ISSUE THREAD

**Issue by dickensas** [coverlet-coverage/coverlet#1109]
In this documentation [Coverlet as a Global Tool](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md)

a command is givern `coverlet --help`

But, how get this tool ?

**Comment by daveMueller** [comment]
You just have to install it as a .NET global tool. Here is the description how to do this.

[https://github.com/coverlet-coverage/coverlet#installation-2](https://github.com/coverlet-coverage/coverlet#installation-2)

**Comment by dickensas** [comment]
Thanks
