### ISSUE TITLE
Could not find data collector 'XPlat Code Coverage' when targetting .dll

### ISSUE THREAD

**Issue by captainjono** [coverlet-coverage/coverlet#1118]
`> dotnet add package coverlet.collector`
`dotnet test my.csproj  --collect:\"XPlat Code Coverage\"` works. great!

`dotnet test bin/debug/netcoreapp3.1/test.dll --collect:\"XPlat Code Coverage\"`

```
Data collection : Unable to find a datacollector with friendly name 'XPlat Code Coverage'.
Data collection : Could not find data collector 'XPlat Code Coverage'
```

What am i missing here? Im writing a tool that integrates with coverage so i would like to support both scenarios.

>dotnet --version = `5.0.101`

**Comment by MarcoRossignoli** [comment]
Can you try with

`dotnet vstest bin/debug/netcoreapp3.1/test.dll --collect:\"XPlat Code Coverage\"`

As explained in guide for published project https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by captainjono** [comment]
Can you explain why I cant use `dotnet test`  ?

[None of the examples here use](
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test) `vstest` ?

Like i said, Im writing a tool that is supposed to let users execute any
test written by any test framework. My understanding was `dotnet test`
facilitated this.

https://github.com/dotnet/docs/issues/14786#issuecomment-642280142

**Comment by MarcoRossignoli** [comment]
It's an implementation detail of test platform, we don't load collectors we implement one, you should open an issue here https://github.com/microsoft/vstest/issues

**Comment by RussKie** [comment]
The solution is described here: https://github.com/coverlet-coverage/coverlet/issues/521#issuecomment-824135206
