### ISSUE TITLE
0 coverage when running integration tests in ASP.NET Core #SonarQube

### ISSUE THREAD

**Issue by sw-ms-ankitsangani** [coverlet-coverage/coverlet#1128]
Hello @All,

Please Help... 
We have a  solution with some Integration tests, but no unit tests.
And I was stuck cant generate code coverage. here is my command Line. 

dotnet restore "<SolutionName>"

dotnet sonarscanner begin /k:"<Name>" /d:sonar.host.url="<HostUrl>" /d:sonar.login="<token>"

dotnet build "<SolutionName>" -c Release -o /app/build

dotnet test "<UnitTest SourcesPath>" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

dotnet sonarscanner end /d:sonar.login=<token>

NOTE : We have get coverage % on unit test using this command line but not integration test. 

Thanks In Advanced...

**Comment by nikita030493** [comment]
Same issue. coverage is missing for 3.0.0 <  
Rolling back to 2.9.0 solved the issue.

**Comment by tai-yi** [comment]
Resolved with command `dotnet test --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover` , only add `--collect:"XPlat Code Coverage"`, I'm using `.net5`

**Comment by MarcoRossignoli** [comment]
If you've integration it's possible that you're suffering of known problem(related to slow tests shutdown)

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

You should try with collectors integration(like @tai-yi did) https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by Bertk** [comment]
This issue was already fixed using recommended [coverlet.collector vstest integration](https://github.com/coverlet-coverage/coverlet#vstest-integration-preferred-due-to-known-issue).

>[!NOTE]  
>Use [SonarAnalyzer.CSharp](https://www.nuget.org/packages/SonarAnalyzer.CSharp) nuget package instead of  [sonarscanner ](https://www.nuget.org/packages/SonarAnalyzer.CSharp) tool. 
>The sonarqube warnings are also available in visual studio and can be configured as well using `.editorconfig`.
