### ISSUE TITLE
Dotnet --filter flag doesn't work with coverlet global tool

### ISSUE THREAD

**Issue by kjczarne** [coverlet-coverage/coverlet#1129]
Hi, I've got a project .NET Framework 4.7.2 project. A number of tests in the project are categorized as benchmarks and I want to skip them from the coverage analysis. Unfortunately running the following command:

```powershell
coverlet ./bin/Debug/net472/Project.Test.exe `   
                 --target "dotnet" `
                 --targetargs "test --no-build --filter TestCategory!='Benchmark'" `                                                     
                 --format opencover  
```

I seem to get all the Benchmarks pulled into the test execution. Am I doing something improperly or is this a bug? Thanks!

**Comment by daveMueller** [comment]
I assume you marked the benchmarks somehow like this?
```csharp
        [TestCategory("Benchmark")]
        [TestMethod]
        public void TestMethod1()
        {
        ...
```

Could you try to remove the quotes from the filter -> ```--targetargs "test --no-build --filter TestCategory!=Benchmark"```

**Comment by kjczarne** [comment]
Thank you! Without the quotes it works as expected.

**Comment by daveMueller** [comment]
Closed as solved, feel free to re-open if needed
