### ISSUE TITLE
Unable to exclude dependency projects

### ISSUE THREAD

**Issue by HT2207** [coverlet-coverage/coverlet#1133]
I have to test Numbers.cs. It has dependency of TestDependancyProj1. I attached solution and directory structure picture.
CodeCoverageSolutionLevel and CodeCoverageSolutionLevel2 are unit test projects

now I run command being at solution directory to exclude TestDependancyProj1 from coverage report
dotnet test ./CodeCoverageSolutionLevel2/CodeCoverageSolutionLevel2.csproj -l trx -r TestResults /p:CollectCoverage=true /p:CoverletOutput=../TestResults/coverage2 /p:Exclude=\"[TestDependancyProj1*]*"\ /p:CoverletOutputFormat=cobertura 

but it fails
![IssuePic](https://user-images.githubusercontent.com/81422892/112634888-6e51c780-8e3b-11eb-9312-b743688752d9.png)

![image](https://user-images.githubusercontent.com/81422892/112634712-3b0f3880-8e3b-11eb-8774-757357a26c0c.png)

could you please help here to exclude project dependencies from coverage report

**Comment by petli** [comment]
Are you running the command in bash or powershell? It could be something with quoting the Exclude parameter.

There is also a backslash just after the Exclude parameter, it may also interfere. Try removing it and see if it helps.

**Comment by HT2207** [comment]
Thank you for your help. Now I used /p:Exclude=[TestDependancyProj1*]* and it works fine . And yes I am using command line

Now could you please guide me if I want to exclude all 3 dependencies.  TestDependancyProj1,TestDependancyProj2 and TestDependancyProj3

I tried /p:Exclude=[TestDependancyProj1*]*,[TestDependancyProj2*]*,[TestDependancyProj3*]* --------------------- It won't work
I tried /p:Exclude="[TestDependancyProj1*]*,[TestDependancyProj2*]*,[TestDependancyProj3*]*" --------------------- It won't work (I found this on help doc  --"Both Exclude and Include properties can be used together but Exclude takes precedence. You can specify multiple filter expressions by separting them with a comma (,).")

I tried /p:Exclude=\"[TestDependancyProj1*]*,[TestDependancyProj2*]*,[TestDependancyProj3*]*\" ------ It works... means back slash works for multiple assemblies or type filters
