### ISSUE TITLE
Unable to merge results in cobertura format

### ISSUE THREAD

**Issue by HT2207** [coverlet-coverage/coverlet#1134]
I have one result file generated using

dotnet test ./CodeCoverageSolutionLevel/CodeCoverageSolutionLevel.csproj -l trx -r TestResults /p:CollectCoverage=true /p:CoverletOutput=../TestResults/coverage1 /p:CoverletOutputFormat=cobertura

now I am running code coverage for other project and want to merge the results by executing

dotnet test ./CodeCoverageSolutionLevel2/CodeCoverageSolutionLevel2.csproj -l trx -r TestResults /p:CollectCoverage=true /p:CoverletOutput=../TestResults/coverage2 /p:CoverletOutputFormat=cobertura /p:MergeWith="../TestResults/coverage1.cobertura"

But after running this coverage2.cobertura is generated with only coverage of CodeCoverageSolutionLevel2.csproj. I think it is overwritten the result file not merged with coverage1.cobertura

Please help here to merge the results of different projects in solution
Note : I am using command line

**Comment by MarcoRossignoli** [comment]
Please take a look at our working sample to understand where is the problem https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/MSBuild/MergeWith
