### ISSUE TITLE
No support for collecting coverage from multiple test projects in the same solution together

### ISSUE THREAD

**Issue by gremlm** [coverlet-coverage/coverlet#1135]
_dotnet test_  can be executed in the directory where solution file exists.
In this case each test project will be executed one after another, creating coverage files for each separate project.
Unfortunately, there will be no one combined file for all of them together,

**Comment by MarcoRossignoli** [comment]
For msbuild integration it's possible https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/MSBuild/MergeWith

For collectors we're waiting for VSTest support https://github.com/coverlet-coverage/coverlet/issues/1015#issuecomment-746174446
