### ISSUE TITLE
Fix SkipAutoProps to work for records as well.

### ISSUE THREAD

**Issue by wdspider** [coverlet-coverage/coverlet#1139]
```csharp
    public sealed record RouteResponse
    {
        public string Id { get; init; } = string.Empty;
    }
```

I'm still experiencing that autoprops like these in records are still counting against coverage even though SkipAutoProps is set to true.

I originally was under the impression that #328  would fix it for both classes and records; however, I was told to open this new issue since it doesn't.  Please fix so that we don't have to keep manually exclude them via the [ExcludedFroCodeCoverage] attribute.

**Comment by Malivil** [comment]
I don't believe it's related to records. I've think I've seen this happen for non-record properties that have inline assignments.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this, maybe it's not related to records but to inline init.

**Comment by StefanOssendorf** [comment]
The same goes for one-line declarations like `public record Foo(String Prop1, String Prop2)`. These are counted as not covered eventhough SkipAutoProps is enabled.

**Comment by Malivil** [comment]
I created a repro for this: https://github.com/Malivil/Coverlet1139Repro
See GenerateCoverageReport.bat in the Tests project folder for settings and to generate coverage.

If you add tests that instantiate the uncovered records and class then it all shows as covered but since SkipAutoProps is enabled those should be ignored, right?

**Comment by wdspider** [comment]
> 
> 
> I created a repro for this: https://github.com/Malivil/Coverlet1139Repro
> See GenerateCoverageReport.bat in the Tests project folder for settings and to generate coverage.
> 
> If you add tests that instantiate the uncovered records and class then it all shows as covered but since SkipAutoProps is enabled those should be ignored, right?

The SkioAutoProps should make those tests unnecessary, yes.  I noticed that your repo is using coverlet.msbuild while we use coverlet.collector.  Therefore, it seems like the issue is more internal rather than in just one of the collection methods.

**Comment by Malivil** [comment]
Yea, that's generally the case. The interior logic is the same regardless of collector method

**Comment by daveMueller** [comment]
I will work on this.

**Comment by daveMueller** [comment]
I analyzed this and would suggest we make another issue for the one-line declarations record. There are two issues here, ```skipAutoProps``` ignoring the inline init auto properties and ignoring the one-line declaration record. 
I can confirm that the issues are related but there is one important difference for records. The constructor of the record creates an instance of ```System.Object``` and I'm currently not sure if I can just ignore this.
Or to be precise I'm a bit afraid that when I just skip this sequence point I will break something, e.g. for inheritance or so. I have to analyze this a bit more.
What is your opinion on that?

![image](https://user-images.githubusercontent.com/19378678/116513546-0bd06900-a8ca-11eb-84f8-1f2c5410745f.png)

**Comment by daveMueller** [comment]
I analyzed this a bit more and did both in one PR [https://github.com/coverlet-coverage/coverlet/pull/1159](https://github.com/coverlet-coverage/coverlet/pull/1159).

**Comment by MarcoRossignoli** [comment]
> The constructor of the record creates an instance of System.Object and I'm currently not sure if I can just ignore this.

It's ok...every ref object inherits from `System.Object`

**Comment by daveMueller** [comment]
Yes thanks. I guess whats new for records is that the inheritance from ```System.Object``` can have a own sequence point as you can see in the screenshot above. I still can't really think of a reason for this sequence point but I concluded that we can skip it.

**Comment by wdspider** [comment]
I see that the PR got merged.  What's the turn around time for release?

**Comment by daveMueller** [comment]
AFAIK there is no fixed time. Looking at the changelog I would assume we are close to the next release.

In the meantime you can consume the nightly [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md)
