### ISSUE TITLE
Wrong/Different information at the README.md and the VSTestIntegration.md

### ISSUE THREAD

**Issue by dennismaxjung** [coverlet-coverage/coverlet#1142]
The README file says that the vstest integration does not work with .net framework.

https://github.com/coverlet-coverage/coverlet/blob/master/README.md#vstest-integration-preferred-due-to-known-issue-supports-only-net-core-application
![image](https://user-images.githubusercontent.com/29334964/114351314-b6c2f200-9b6a-11eb-9472-9dd2980ce5a9.png)

The documentation of vstest integration instead shows that it is compatible with .net framework.

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
![image](https://user-images.githubusercontent.com/29334964/114351748-554f5300-9b6b-11eb-9b8b-6c3d7e29172e.png)

**Comment by MarcoRossignoli** [comment]
You're right @dennismaxjung we missed to update the Readme.md, do you want to propose a PR for it?

**Comment by MarcoRossignoli** [comment]
Closed in https://github.com/coverlet-coverage/coverlet/pull/1161
