### ISSUE TITLE
Unable to instrument module - AssemblyResolutionException - no code coverage for an assembly reported

### ISSUE THREAD

**Issue by xcellsoft** [coverlet-coverage/coverlet#1147]
To help other users out and possibly to add to the known issues as a resolution, I figured out how to overcome the issue I was having whereas an assembly was not getting code coverage due to the "AssemblyResolutionException" error.

Initial symptom was all my assemblies received code coverage properly except for 1 of them.

I tried the <PreserveCompilationContext>true</PreserveCompilationContext> and <RestoreProjectStyle>PackageReference</RestoreProjectStyle> along with /p:CopyLocalLockFileAssemblies=true setting. None of these worked.

After hours of random troubleshooting using different ideas on the web and coverlet site, I ended with the discovery of the -d switch on the dotnet test where running the test created data collector log files with a name such as "log.datacollector.21-04-18_09-21-20_41913_4.txt". I opened this file and looked for the missing assembly and found this (I changed my assemblies to xxx to hide their names):

`TpTrace Warning: 0 : 22184, 1, 2021/04/18, 09:21:23.353, 527629491496, datacollector.dll, [coverlet]Unable to instrument module: C:\Test\xxx.xxx.xxx.UnitTest\bin\DebugCodeCoverage\netcoreapp3.1\xxx.xxx.xxx.dll because : AssemblyResolutionException for 'Microsoft.AspNetCore.Http.Features, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Try to add <PreserveCompilationContext>true</PreserveCompilationContext> to test projects </PropertyGroup> or pass '/p:CopyLocalLockFileAssemblies=true' option to the 'dotnet test' command-line
`

After retrying the suggestions in the error message nothing worked.

Next, I scoured the internet and found a post where the only resolution was to manually copy the dll (Microsoft.AspNetCore.Http.Features.dll) to the bin\debug folder as this dll was not there, but was used by the program and coverlet MUST have all the referenced libraries in the bin\debug folder to be able to instrument the target assembly. 

What did work though was going to the .csproj for the target assembly and adding the reference directly to the missing assembly. 

`<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.5" />`

Once added and after the next dotnet test was run, the dll was outputted to the bin\debug and code coverage was performed - yay!

I hope this helps someone else.

**Comment by MarcoRossignoli** [comment]
> What did work though was going to the .csproj for the target assembly and adding the reference directly to the missing assembly.

Yep, this is the last resort to fix this issue. Thx for the record.
