### ISSUE TITLE
Function Filter is not working

### ISSUE THREAD

**Issue by jessensam** [coverlet-coverage/coverlet#1149]
Hi Team,
Is there any way, we can filter the functions using coverlet. I need to include only functions that starts with "Search" in Code coverage report . I have tried this --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.CodeCoverage.Functions.Include.Function=".*\.Search.*" DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Include="[company.namespace.class]*".

https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019. Here i can see the Function in runsetting file.

**Comment by petli** [comment]
Hi, that configuration is not for coverlet but the code coverage function in VS. You can find the documentation on how to filter when using coverlet.collector here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings

**Comment by jessensam** [comment]
Thanks, Here am not seeing anything related to filter the function. Can you please help me on this. I need to include only functions that starts with "Search" in Code coverage report .

**Comment by daveMueller** [comment]
Currently you can only pass types and assemblies to the coverlet ```Include/Exclude``` properties. The only way you can exclude functions is to add ```ExcludeFromCodeCoverage``` attribute over the functions that should be excluded.
[https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#attributes](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#attributes)

For your use case this most likely isn't really convenient, but I can't think of another option. Also feel free to create a feature request for extending the ```Include/Exclude``` properties to filter functions.

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
