### ISSUE TITLE
No coverage file generated on Linux

### ISSUE THREAD

**Issue by NQbbe** [coverlet-coverage/coverlet#1151]
Like the topic says, I'm getting no coverage file no matter what I try :-(

The issue can be reproduced (for me at least) in a new xunit project like so:

```
mkdir Test
cd Test
dotnet new xunit
# Verify csproj contains reference to coverlet, it usually does by default
dotnet test /p:CollectCoverage=true
```
No coverage.json file is generated.

I'm using Linux Mint 20.1 (which currently is based on Ubuntu 20.04 LTS), and I'm running the latest dotnet version from Microsofts APT repositories.

**Comment by petli** [comment]
It seems that the template installs the coverlet.collector driver, which requires a different option (documented under VSTest integration in the README). Try running this instead:

    dotnet test --collect:"XPlat Code Coverage"

The flag you tested with is for the msbuild driver, which is generally not recommended for new projects.

**Comment by NQbbe** [comment]
Ah you're right, my bad for misreading the documentation. It properly generates files when using --collect:"XPlat Code Coverage". thanks for the fast reply.
