### ISSUE TITLE
No coverage for some files defining xUnit tests

### ISSUE THREAD

**Issue by NQbbe** [coverlet-coverage/coverlet#1153]
I just got an lcov generated for my test project, however oddly enough 3 of my files containing xUnit tests (marked with[Fact]) aren't included in the lcov file at all.

Is there some filter to what's included in the lcov and what's not?
The odd pattern is the 3 files all contain purely async test methods e.g.

```
[Fact]
public async Task TestFoo()
{
}
```

However I also recently added these 3 files to the project, so I don't know if it's the async keyword that's messing something up.

To generate the lcov I run
dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings

and coverlet.runsettings look like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>lcov</Format>          
          <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
          <SingleHit>false</SingleHit>
          <UseSourceLink>true</UseSourceLink>
          <IncludeTestAssembly>true</IncludeTestAssembly>
          <SkipAutoProps>true</SkipAutoProps>
          <DeterministicReport>false</DeterministicReport>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

**Comment by petli** [comment]
Is this the project you created in #1151 ? I took another look at the csproj generated by the template, and it uses a really old version of coverlet (1.3.0).  There's been a lot of fixes around async code, so you can try to update to the latest version of `coverlet.collector` to see if you get better results.

**Comment by NQbbe** [comment]
Sorry about the lack of information, I'm running coverlet 3.0.3 in my actual project.
The quick "dotnet new xunit" was just for demonstration purpose (and mostly demonstrated me not reading your documentation :-D )

Here's the relevant parts of my test project's csproj:
 ```
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

**Comment by NQbbe** [comment]
Further testing: I added this method to one of the classes that are properly included in the lcov file:

```
[Fact]
public async Task SimpleTest()
{
	await Task.Delay(50);
}
```

The file is still included, however this method isn't. It simply isn't mentioned at all in the lcov file.
Removing async and await causes it to be included right away.

**Comment by petli** [comment]
Does this only happen for unit tests? I.e. does the async non-test methods the unit test methods call get included in the coverage?

**Comment by NQbbe** [comment]
Any code called from within the non-async test methods is included in the coverage.
Any code called from within the async test methods isn't.

It seems like it's entirely ignoring the async test method "entry points" (in lack of better term)
I can however see dotnet is actually running the tests, so it's not because "dotnet test" itself ignores them.

**Comment by petli** [comment]
Do you think you can put together a small solution that reproduces this and share it?  Or if that is difficult, share the whole project file so we see versions of .NET, the test SDK etc.  Thanks!

**Comment by NQbbe** [comment]
> Do you think you can put together a small solution that reproduces this and share it? Or if that is difficult, share the whole project file so we see versions of .NET, the test SDK etc. Thanks!

I can setup a repro solution later today, but you're also welcome to checkout the entire project: https://github.com/NQbbe/Ckode.Dapper.Repository
Note: You'll need to build the Dockerfile included in the project to actually run the IntegrationTests, which is the one containing the async tests. There's a build.sh included, but it probably only works on Linux.
However when I tried to add the SimpleTest I did so in the UnitTests project, and that one builds and tests fine without the docker.

Will you let me know if you want the repro, or the actual project is enough?

**Comment by petli** [comment]
Thanks, that should be enough!

**Comment by petli** [comment]
I've tried this now, and I think it's just `CompilerGeneratedAttribute` in `ExcludeByAttribute` that causes it. When I remove that the async methods are included.  The async state engines must be decorated with that attribute.

**Comment by NQbbe** [comment]
Well spotted @petli, it works like a charm when I remove `CompilerGeneratedAttribute`, all my async tests have coverage now :+1: 

Thank you very much for the assistance :-)
