### ISSUE TITLE
If some test case are failing then code coverage report is not generating 

### ISSUE THREAD

**Issue by sbambrule** [coverlet-coverage/coverlet#1157]
if some xunit test case are failing then opencover code coverage report is not generating in Linux Docker 

coverlet.msbuild version 3.0.3
coverlet.collector version 3.0.3
.Net core 2.2 

command:
dotnet test   /p:CollectCoverage=true   /p:CoverletOutputFormat=opencover

dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=json,cobertura,lcov,teamcity,opencover

**Comment by MarcoRossignoli** [comment]
>  in Linux Docker

Does it work on your local or it happens only on docker?

**Comment by sbambrule** [comment]
Both local and docker Linux  image is not working

**Comment by pavel-usachev** [comment]
Is it the same question as #287?
