### ISSUE TITLE
DeterministicReport not working as expected

### ISSUE THREAD

**Issue by chlopes** [coverlet-coverage/coverlet#1160]
Hi guys!

First of all, thank you so much for providing us such an amazing tool!

I'm trying to generate the code coverage reports using the 'DeterministicReport' flag, but the generated reports still map to the full path of the files.

The project used for the test was [this](https://github.com/coverlet-coverage/coverlet/tree/2e2b578fcc7ba1e63d5482938c93b33c4ed638bd/Documentation/Examples/MSBuild/DeterministicBuild) with the following modifications:
- The file 'Directory.Build.props' was removed (not interested in Source Link for the moment).
- The file 'Directory.Build.target' was removed (not needed when .NET SDK 3.1.300+ is used, according to 'HowTo' doc).
- The file 'DeterministicBuild.targets' was removed (same reason as above)
- The file 'XUnitTestProject1.csproj' was modified to remove 'coverlet.collector' dependency and set 'coverlet.msbuild' dependency version to 3.0.3.

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/10310060/117045734-38c7b600-ace6-11eb-9047-e0743b37d1e2.png)
![image](https://user-images.githubusercontent.com/10310060/117046055-9c51e380-ace6-11eb-9b87-40f9e732ae1f.png)
![image](https://user-images.githubusercontent.com/10310060/117045885-6b71ae80-ace6-11eb-93e3-4981d06227a7.png)

P.S. I also tried with the 'DeterministicSourcePaths' flag in place of the 'DeterministicReport' flag and the result is the same.

**Comment by MarcoRossignoli** [comment]
Deterministic report is not released yet...to try it you should use the nightly build https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

This is the changelog https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Changelog.md#unreleased

**Comment by chlopes** [comment]
My mistake. I thought it was already released, sorry.
 I'll play with the nightly builds and test how the feature works.

By the way, is there an ETA for this feature to be released?

**Comment by MarcoRossignoli** [comment]
No ETA atm...we have some PR to merge...but we should be close.

Anyway not your mistake, it's not the first time, we tried to fix a bit but seems that it's not enough
![image](https://user-images.githubusercontent.com/7894084/117065672-148cc900-ad28-11eb-88b6-e5ed518064b0.png)

When a user struggles is our fault not your one at all, sorry 😞
