### ISSUE TITLE
Incorrect branch coverage with .NET 472

### ISSUE THREAD

**Issue by alessandroste** [coverlet-coverage/coverlet#1167]
I am having issues with the branch coverage on a .NET 472 based project. In particular some awaited methods result in two or more branches in the coverage report. I was able to reproduce on a small scale [here](https://github.com/alessandroste/coverlet-test). The project on .NET standard looks good, but the project on .NET 472 results in some suspicious behavior.
The class is exactly the same, but the coverage is different.
![image](https://user-images.githubusercontent.com/4490045/119161592-ca128880-ba59-11eb-9817-44c9030e7082.png)
![image](https://user-images.githubusercontent.com/4490045/119161688-e57d9380-ba59-11eb-84e1-439624296ed8.png)
The await on the semaphore ` await this.semaphore.WaitAsync();` results in two branches for .NET 472 and one branch for .NET standard, and the same happens to `await Task.Delay(TimeSpan.FromMilliseconds(1));`. In the second case, both the branches are visited, but, in the first case, only one is visited. This is probably related to the state machine of the task framework.
Is this something that can be solved on coverlet side? I tested with versions back to 3.0.1 and I see the same behavior.

**Comment by sergiusignacius** [comment]
@daveMueller any ETA on getting some feedback on this one? Or maybe a few directions on how we can test and debug this ourselves?

**Comment by daveMueller** [comment]
Sorry really busy at the moment. We fixed a couple of issues with ```async``` patterns in the last months. I had high hopes that we already fixed this but I just checked it and I'm having the same issue. I will find some time in the next days to dig into the different  dlls and report immediately.
