### ISSUE TITLE
Branch coverage ignoring catch

### ISSUE THREAD

**Issue by Witt1503** [coverlet-coverage/coverlet#1175]
I get 100% branch coverage, but only 42.85% line coverage, on a method with two Catch blocks. Branch coverage does not see catch'es as different branches.
![image](https://user-images.githubusercontent.com/10807987/121174673-74601d80-c85a-11eb-8650-d6105105176c.png)

![image](https://user-images.githubusercontent.com/10807987/121176158-306e1800-c85c-11eb-9bf0-bdb6af68f9a1.png)

coverlet.collector Version="3.0.3"
coverlet.msbuild Version="3.0.3"
Microsoft.NET.Test.Sdk Version="16.9.4"
Microsoft.Net SDK Version = 5.0.103

**Comment by MarcoRossignoli** [comment]
Can you verify if it's fixed on nightly?  https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by Hadaps** [comment]
I don't see it as fixed. We see same behavior as before.
I have created an updated coveragereport using:
coverlet.collector Version="3.0.4-preview.31.g4902c245c8"
coverlet.msbuild Version="3.0.4-preview.31.g4902c245c8"

I get branch coverage on 50% when the is an if-statement inside the catch, and only one condition is tested (as expected).
But it does not count the last catch as missing in the branch coverage.

![image](https://user-images.githubusercontent.com/10565831/122894694-b6538e00-d347-11eb-9bb6-4b13038acff0.png)

**Comment by MarcoRossignoli** [comment]
@Hadaps  are you able to provide a repro?
