### ISSUE TITLE
"coverlet.console": How do I pass `--targetargs` that also contains a `--` style argument

### ISSUE THREAD

**Issue by Smurf-IV** [coverlet-coverage/coverlet#1178]
The `--targetargs` in the following also has a `--` style argument.

`coverlet.console` is interpreting that as a a command also!
What am I missing ?

Because after the following message it dumps out the help text.

```
coverlet "D:\_work\2\s/Data_Server/Prod/Database.Builder/bin/Debug/net5.0" --target "D:\_work\2\s/Data_Server/Prod/Database.Builder/bin/Debug/net5.0/Database.Builder.exe" --targetargs '--connectionString "Server=(localdb)\MSSQLLocalDB;Database=TestDb;Trusted_Connection=True;"  --StartupAction Migrate --Run true --Type Domain' -f cobertura --verbosity detailed --exclude-by-attribute 'GeneratedCode' --exclude-by-attribute 'CompilerGenerated' -o "D:\_work\2\s/TestResults/DataService.Database.Builder/"
Specify --help for a list of available options and commands.
Unrecognized command or argument 'Server=(localdb)\MSSQLLocalDB;Database=TestDb;Trusted_Connection=True;'
```

Edit: Version 3.0.3

**Comment by daveMueller** [comment]
I'm afraid this is an issue of the cli library coverlet is using ([https://github.com/natemcmaster/CommandLineUtils/issues/154](https://github.com/natemcmaster/CommandLineUtils/issues/154)).
In my eyes the suggested solution here isn't something we can use in production. 
@MarcoRossignoli any idea on how to solve this without writing a own parser? Do we want to solve this?
@Smurf-IV Is there another way to pass the arguments to your Database.Builder e.g. ```/connectionString "..."```.
