### ISSUE TITLE
Add support for strong-named assemblies

### ISSUE THREAD

**Issue by kevingosse** [coverlet-coverage/coverlet#1184]
Currently, Coverlet does not sign the instrumented assemblies. This is already known for causing issues with xunit, and there's a workaround for that scenario. However I also need to sign the assemblies for tests that use the GAC.

I propose to add a `StrongNameKey` parameter that takes the path to a `.snk` file. When the parameter is provided and the original assembly is signed, Coverlet would use that signature to sign the instrumented version of the assembly.

I've already done the bulk of the work [here](https://github.com/DataDog/coverlet/tree/kevin/strongnaming) and made sure it works for my use-case. I think more work is needed to merge it upstream (for instance on parameters validation), but I'll be happy to take care of it if the feature is accepted.

**Comment by MarcoRossignoli** [comment]
Hi Kevin, feel free to propose a PR, we have 3 drivers 
- .NET Tool
- msbuild integration
- Collectors

So we should flow parameter to all three "drivers".
Anyway feel free to update the drivers you're using we can keep this issue open and complete the work for all drivers if/when needed.

I think this is a good addition.

cc: @tonerdo @petli @daveMueller
