### ISSUE TITLE
Failing to generate report for solution with several test assemblies

### ISSUE THREAD

**Issue by zetroot** [coverlet-coverage/coverlet#1185]
## Steps to reproduce 

1. Get solution with multiple test projects (we have 18)
2. Projects are using xunit and have no configuration about running tests in parallel.
3. Run tests with `"C:\Program Files\dotnet\dotnet.exe" test C:\agent\_work\10\s\src\SolutionName.sln --configuration Release --collect "XPlat Code Coverage" --logger xunit;LogFileName={assembly}.xml --no-build --results-directory C:\agent\_work\10\s\test_results /property:CollectCoverage=True /property:CoverletOutput=C:\agent\_work\10\s\test_coverage\report /property:CoverletOutputFormat=cobertura`
4. You may need several runs to reproduce. Multithreading issues are difficult to reproduce

## Current behaviour (bug)
Report writing to file failes with `IOException`:
```
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error : The process cannot access the file 'C:\agent\_work\10\s\test_coverage\report.cobertura.xml' because it is being used by another process. 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.StreamWriter..ctor(String path) 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at System.IO.File.WriteAllText(String path, String contents) 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at Coverlet.Core.Helpers.FileSystem.WriteAllText(String path, String contents) in /_/src/coverlet.core/Helpers/FileSystem.cs:line 16 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at Coverlet.MSbuild.Tasks.ReportWriter.WriteReport() in /_/src/coverlet.msbuild.tasks/ReportWriter.cs:line 50 
##[error]C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\coverlet.msbuild\3.0.3\build\coverlet.msbuild.targets(70,5): error :    at Coverlet.MSbuild.Tasks.CoverageResultTask.Execute() in /_/src/coverlet.msbuild.tasks/CoverageResultTask.cs:line 119 
```

## Expected behaviour (correct)

Writer retries to write report after some delay.

## Workaround

Disabled parallel assemblies testing by adding `xunit.runner.json`:
```json
{
  "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
  "parallelizeAssembly": false
}
```

## Versions
- xunit - 2.4.1
- coverlet.collector - 3.0.3
- coverlet.msbuild - 3.0.3
- dotnet - 5.0.101

**Comment by zetroot** [comment]
Added a pr for this

**Comment by MarcoRossignoli** [comment]
`/property:CollectCoverage=True` is not needed if you're using collectors. Which driver are you using collectors or msbuild?
We never had issue with report file because it's the last thing that coverlet does and it's sync also with collectors every report should be in a new guild folder. Can you double check if you've some antivirus or stuff like that on build agent? Sometimes we saw issue where agent for some reason blocks temporary access to files during write.

**Comment by zetroot** [comment]
May be i am doing something wrong, but without `/property:CollectCoverage=True` the total report is not generated here `C:\agent\_work\10\s\test_coverage\report`.
I need a single report for all my 18 testprojects to publish coverage results in Azure DevOps Server. It seems not to accept multiple report files.

> Which driver are you using collectors or msbuild?

I haven't understand what do you mean, sorry. I have added both packages `coverlet.collector` and `coverlet.msbuild`.


---- UPDATE
I have removed `coverlet.collector`, to generate only single report from `coverlet.msbuild`. It seems everything works fine. Will take a look how it works in CI.

Yes, we have Windows Defender enabled on agents, and it can affect accessebility of the report file. May be retry strategy from #1186 will help in this situation.

**Comment by MarcoRossignoli** [comment]
Can you try to merge in this way? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Examples/MSBuild/MergeWith/HowTo.md

**Comment by zetroot** [comment]
@MarcoRossignoli thank you for your help. I've solved this problem in another way - i've quitted this project. So, unfortunately, I can't check if your solution.
Thank you again!
