### ISSUE TITLE
Does coverlet support statement coverage?

### ISSUE THREAD

**Issue by trumhemcut** [coverlet-coverage/coverlet#1202]
Hi all,

While working with Jest, it's showing **statement coverage** (as below). Not sure Coverlet also support this feature?

![image](https://user-images.githubusercontent.com/5198341/126461958-5df331b7-9d42-42f9-bab8-b466e59a63cf.png)

**Comment by MarcoRossignoli** [comment]
Hi, sorry for late answer, nope coverlet at the moment support lines and branches coverage.
Also it's optimized for C# syntax and we try to remove "invisible" branches injected by compiler.
