### ISSUE TITLE
Exclude coverage lines contains specific text

### ISSUE THREAD

**Issue by NadavShaked** [coverlet-coverage/coverlet#1203]
How can I exclude from coverage lines that contain specific text
![image](https://user-images.githubusercontent.com/19892483/127326499-11d8d02b-5fdb-45b2-968d-5c5940df143e.png)

I have to ignore all lines that contain this text: "throw new NotSupportedException();"
at whole files

**Comment by MarcoRossignoli** [comment]
Coverlet doesn't support code line exclusion also because it's useful to know that you're not testing that branches and it's the goal of coverage tool report uncovered lines.
My advice is to add a test to cover the not supported path.
