### ISSUE TITLE
Running coverage on individual methods

### ISSUE THREAD

**Issue by bonbon12** [coverlet-coverage/coverlet#1207]
Would like to run coverage on an individual unit test in the assembly.

Essentially like this:

`dotnet test "Path/Tests.dll" --filter "test1" --collect:"XPlat Code Coverage"`

Is this possible?

**Comment by petli** [comment]
Yes, that should work.  The test discovery and selection process is the same whether you have enabled code coverage analysis or not, so you should end up with a code coverage report from executing just the selected tests.

**Comment by bonbon12** [comment]
Thank you! I was actually running the command correctly, I just first thought the error was command related when the reality was I didn't have the reference in all of the test project files. Everything is working now, thanks again!
