### ISSUE TITLE
Multiple branch points created for F# string slice

### ISSUE THREAD

**Issue by rhewitt316** [coverlet-coverage/coverlet#1208]
Hello, I have a bit of F# code at [https://github.com/rhewitt316/coverlet-fsharp-substring-branch-point-example](url) which contains a simple function that returns a slice of a given string. When I build the project and run through Coverlet 3.1, the line of code that slices the string generates 8 branch points, which drastically elevates the cyclomatic complexity. I am new to F# so I am not sure if I am missing something, but I don't see where the 8 branch points come from. Is this correct behavior?

Thanks in advance

Platform: Red Hat Enterprise Linux 8

**Comment by daveMueller** [comment]
I guess those are branch point that the compiler auto generated. We have to look into the compiled assembly to see if we can detect a pattern to ignore them.

**Comment by MarcoRossignoli** [comment]
At the moment coverlet is "very" tuned for C# compiler(Roslyn) we don't have a lot of F# pattern recognitions. We should improve also for functional friends.
