### ISSUE TITLE
Data collector 'Code Coverage' message: No code coverage data available. Code coverage is currently supported only on Windows..

### ISSUE THREAD

**Issue by runhli** [coverlet-coverage/coverlet#1209]
Hi,
We run command like this in pipeline: 
`dotnet test $_.FullName --no-build --no-restore --filter "TestCategory=Unit | TestCategory=Component" --collect "XPlat Code Coverage" --logger trx --settings "$(DatacacheRootDir)/.devops/CodeCoverage.runsettings" --results-directory "$(Agent.TempDirectory)"`
We didn't change anything from pipeline yaml set up, but this error shows up recently:
`Data collector 'Code Coverage' message: No code coverage data available. Code coverage is currently supported only on Windows..`
Donet test command runs on linux machine though but it worked before, so I'm not sure why does it say "it is currently supported only on windows.."
I also didn't change the version of `coverlet.msbuild` `coverlet.collector` in our *.tests.csproj. I tried bumping the version but it doesn't work too.

Does it indicate the dotnet version we use is not correct?

**Comment by petli** [comment]
That sounds like you might have activated the old .NET code coverage collector (which does only work on Windows) instead of coverlet. Check which package references you have in your test project.

**Comment by runhli** [comment]
> That sounds like you might have activated the old .NET code coverage collector (which does only work on Windows) instead of coverlet. Check which package references you have in your test project.

We didn't change anything from our test project, the reference is like that:
![image](https://user-images.githubusercontent.com/87873226/128402845-fd2f22b6-4976-4e04-bc36-de5794878326.png)
I also tried bumping the version to 3.1.0, it doesn't work too.
Could this be caused by dotnet test command issue? I saw the dotnet test command tool version was bumped in our infra right after the last successful fun.
Thanks!

**Comment by runhli** [comment]
I think recently we upgrade to .net 5.0, could .net 5.0 cause this error? Are they any difference in usage?

**Comment by petli** [comment]
This sounds similar to #1181 where the Microsoft coverage collector was enabled through runsettings and causing a conflict with coverlet.

**Comment by runhli** [comment]
> This sounds similar to #1188 where the Microsoft coverage collector was enabled through runsettings and causing a conflict with coverlet.

You are right, we've found the issue in runsettings and made the fix. Thank you very much for the help.
