### ISSUE TITLE
Wrong coverage for "await foreach" when method is generic

### ISSUE THREAD

**Issue by msallin** [coverlet-coverage/coverlet#1210]
I'm using coverlet.msbuild v3.1.0 (and tried also with the current nightly build) and there is an uncovered statement reported.
![image](https://user-images.githubusercontent.com/7792779/128574173-70a05457-923f-43b6-8cee-ecd02c15d47d.png)

I tried to reproduce it but I didn't managed to get an reproduction.
Any ideas what the problem could be and how I can provide an reproduction?

```csharp
public class AsyncForeachReproduction
{
    private static async IAsyncEnumerable<int> RangeAsync(int start, int count)
    {
        for (int i = 0; i < count; i++)
        {
            await Task.Delay(i);
            yield return start + i;
        }
    }

    public async Task Execute()
    {
        await foreach (var a in RangeAsync(1, 5))
        {
            Console.WriteLine(a);
            await Task.CompletedTask;
        }

        await Task.CompletedTask;
    }
}
```

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this.

**Comment by msallin** [comment]
@MarcoRossignoli this is still the case with 3.1.1

**Comment by MarcoRossignoli** [comment]
We need a repro to find out why/when that branch is emitted by the compiler, to repro you should create the same method using mocked object, but the "shape" needs to be "identical" to mimic the same context for the compiler.

**Comment by msallin** [comment]
Any hints/idea what could cause this i.e. Why my repro doesnt work?

**Comment by MarcoRossignoli** [comment]
The code in the repro and the code that is failing are a lot different from compiler perspective, state machine are built in a different way because different object structure are involved...you should create the same classes, mock those and retry.

**Comment by msallin** [comment]
![image](https://user-images.githubusercontent.com/7792779/152659214-3e70d497-5f6b-45cf-a5a6-982848c88162.png)

![image](https://user-images.githubusercontent.com/7792779/152659225-8b391b6f-a1b7-4d8d-9d48-b5c7a59475fa.png)

```csharp
public class AwaitForeachReproductionFixture2
{
    [Fact]
    public async Task Execute_ShouldWork()
    {
        // Arrange
        var sut = new AwaitForeachReproduction2();

        // Act
        await sut.Execute<object>(RangeAsync(1, 3));
    }

    static async IAsyncEnumerable<int> RangeAsync(int start, int count)
    {
        for (int i = 0; i < count; i++)
        {
            await Task.Delay(i);
            yield return start + i;
        }
    }
}
```

```csharp
public class AwaitForeachReproduction2
{
    public virtual async Task Execute<T>(IAsyncEnumerable<int> messages)
    {
        await foreach (int obj in messages)
        {
            await Task.Delay(1);
        }
    }
}
```

**Comment by msallin** [comment]
See https://github.com/meggima/coverlet-reproductions AwaitForeachReproduction2.cs & AwaitForeachReproductionFixture2.cs

**Comment by daveMueller** [comment]
I started working on this issue.
