### ISSUE TITLE
Not able install coverlet.msbuild nuget package to .Net project targeting framework 4.7.2

### ISSUE THREAD

**Issue by gautamksr** [coverlet-coverage/coverlet#1212]
Hi,
I have successfully generated the cobertura code coverage report for .Net core project. But i want to try the same to setup for project targeting the framework 4.7.2. When i try to install the coverlet.msbuild to unitTest project . it not able to install . Any help?

```
Attempting to gather dependency information for package 'coverlet.msbuild.3.1.0' with respect to project 'WebApp.Tests', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 127 ms
Attempting to resolve dependencies for package 'coverlet.msbuild.3.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'coverlet.msbuild.3.1.0'
Resolved actions to install package 'coverlet.msbuild.3.1.0'
Adding package 'coverlet.msbuild.3.1.0' to folder 'C:\GitSource\codecoveragedotnetfremwork\WebApp\packages'
Added package 'coverlet.msbuild.3.1.0' to folder 'C:\GitSource\codecoveragedotnetfremwork\WebApp\packages'
Install failed. Rolling back...
Package 'coverlet.msbuild.3.1.0' does not exist in project 'WebApp.Tests'
Removing package 'coverlet.msbuild.3.1.0' from folder 'C:\GitSource\codecoveragedotnetfremwork\WebApp\packages'
Removed package 'coverlet.msbuild.3.1.0' from folder 'C:\GitSource\codecoveragedotnetfremwork\WebApp\packages'
Executing nuget actions took 614 ms
Time Elapsed: 00:00:00.8447746
========== Finished ==========
```

**Comment by MarcoRossignoli** [comment]
I don't see issue for a simple console app 472. Can you attach here a repro? What project template are you using?

**Comment by gautamksr** [comment]
What I have done, create a default .Net web project targeting framework 4.7.2 ( that is default selected) with UnitTest project using VS2019. Then added `coverlet.msbuild` nuget package and run the test. The build get failed after added to `coverlet.msbuild`

The link of repo - [https://github.com/gautamksr/coverletdotnetframework.git](url)

**Comment by daveMueller** [comment]
Hi coverlet supports only SDK-style projects [https://github.com/coverlet-coverage/coverlet#quick-start](https://github.com/coverlet-coverage/coverlet#quick-start)
Could you try to migrate your .csproj files an give it another try?

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
