### ISSUE TITLE
Coverlet not showing coverage of assembly which is part of another solution

### ISSUE THREAD

**Issue by manishi2V** [coverlet-coverage/coverlet#1215]
I have a class library project named "**MainProcessing**" which contains my main code. This project is part of solution named "**Processor**". This class library project is written in .Net core 3.1.
I have another solution named "**MainProcessing.Test**" which contains a .Net core 3.1 class library project named "**MainProcessingTest.Helper**". I have added reference of **MainProcessing.dll** in this project. 
This solution also contains unit test (MSTest) project named "**Medical.Test**" which contains reference of "**MainProcessingTest.Helper**" and "**MainProcessing.dll**". This project also written in .Net core 3.1 only.

I am using below mentioned command to run test cases and get code coverage results. But this command always gives me results of "**MainProcessingTest.Helper**" project instead of "**MainProcessing.dll**". 

All code of "**MainProcessing.dll**" executed whenever I run unit test cases of project "**Medical.Test**" but it is not showing coverage results of my main project "**MainProcessing.dll**".

I want coverlet to show me results of only "MainProcessing.dll". 

**Command I use:**
`dotnet test 'Medical.Test.csproj' /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,lcov\" /p:CoverletOutput='Coverage/ProviderTestsCoverage' /p:Include=[*]MainProcessing.* /p:Exclude=[*]MainProcessing.Test* --logger:"trx;LogFileName=Logs/trxFile/ProviderTest.trx" `

**Current Output:**

+-------------------+------+--------+--------+
| Module            | Line | Branch | Method |
+-------------------+------+--------+--------+
| MainProcessingTest.Helper | 40%  | 37.5%  | 63.63% |
+-------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 40%  | 37.5%  | 63.63% |
+---------+------+--------+--------+
| Average | 40%  | 37.5%  | 63.63% |
+---------+------+--------+--------+

**Comment by petli** [comment]
How does the projects in `MainProcessing.Test.sln` access the `MainProcessing` project? I.e., is it a direct reference to the csproj in the source code of `Processor.sln`, or is the project built and published on e.g. an internal nuget with a package reference. In the latter case the coverlet instrumentor will likely not find some or all the sources on disk for `MainProcessing`, which it interprets as a third-party DLL that should be excluded from analysis.

You can try enabling loggin (https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md) and see if the resulting log files (there are several) say something along the lines of

```
Unable to instrument module: MainProcessing.dll, pdb without local source files: ...
```

See e.g. #1164 and #1193 for discussions about this heuristic.

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
