### ISSUE TITLE
Partially deterministic report in .NET 5

### ISSUE THREAD

**Issue by darjanbogdan** [coverlet-coverage/coverlet#1216]
Hi,

I ran into quite strange situation with generating deterministic cobertura reports using .NET 5 on Windows.

Firstly, I build solution using both flags which enable deterministic build. Next, I enable `DeterministicReport` flag and get a cobertura report in which `<sources>` node is correctly emptied, however `filename` attributes still hold full paths:

```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.2909" branch-rate="0.1776" version="1.9" timestamp="1630530790" lines-covered="373" lines-valid="1282" branches-covered="27" branches-valid="152">
  <sources />
  <packages>
    <package name="Example" line-rate="0.3757" branch-rate="0.0833" complexity="71">
      <classes>
        <class name="Example.Program" filename="C:\Projects\<redacted>\example\Program.cs" line-rate="0" branch-rate="1" complexity="1">
          <methods>
    ....
```

I'm using coverlet.collector package (3.1.0) which is enabled and configured via `.runsettings` file. coverlet.msbuild package is not added to test projects:
```xml
    <DataCollectionRunSettings>
        <DataCollectors>
            <DataCollector friendlyName="XPlat Code Coverage">
                <Configuration>
                    <Format>cobertura</Format>
                    <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
                    <IncludeTestAssembly>false</IncludeTestAssembly>
                    <SkipAutoProps>true</SkipAutoProps>
                    <UseSourceLink>false</UseSourceLink> <!-- Private GitLab not supported -->
                    <DeterministicReport>true</DeterministicReport>
                    <SingleHit>false</SingleHit>
                </Configuration>
            </DataCollector>
        </DataCollectors>
    </DataCollectionRunSettings>
```
I simply run `dotnet test --settings tests.runsettings` and it correctly generates coverage report, just without deterministic file paths.

Does anyone have some ideas or maybe ran into similar issue? 

Thanks!

**Comment by MarcoRossignoli** [comment]
Can you provide a repro?

**Comment by darjanbogdan** [comment]
Unfortunately don't have time to focus on this atm, I'm closing the issue for now
