### ISSUE TITLE
Reporting uncovered branches before a try...catch

### ISSUE THREAD

**Issue by mstrong64** [coverlet-coverage/coverlet#1218]
I have a couple of async methods in a class where Coverlet is reporting uncovered branches that don't exist. Both methods are async and contain try...catch blocks. If I **move all the code inside the try...catch** then the problem disappears.

<html>
<body>

  |   | 206 |   | async Task<Ticket> PerformAction(TicketUpdateParams queryParams, Ticket ticket, WorkflowLifeCycleEnum lifeCycle,
-- | -- | -- | -- | --
  | 14 | 207 |   | {
  | 14 | 208 |   | TicketLock ticketLock = null;
  |   | 219 |   |  ... code omitted ...
  | 13 | 220 |   | **await _dataManager.BeginTransaction();** _<- this line has only 1 of 21 branches covered_
  |   | 221 |   | try
  | 13 | 222 |   | {
  | 13 | 223 |   | ticket.UserID = -1;  // this means the ticket is edited in Seeker

</body>
</html>

Looking at the IL I found the 21 branches (apparently):

```
IL_02c5:  nop
    .try
    {
      IL_02c6:  ldloc.0
      IL_02c7:  ldc.i4.3
      IL_02c8:  sub
      IL_02c9:  switch     ( 
                            IL_0320,
                            IL_0325,
                            IL_032a,
                            IL_032f,
                            IL_0334,
                            IL_0339,
                            IL_033e,
                            IL_0343,
                            IL_0348,
                            IL_034d,
                            IL_0352,
                            IL_0357,
                            IL_035c,
                            IL_0361,
                            IL_0366,
                            IL_036b,
                            IL_0370,
                            IL_0375,
                            IL_037a,
                            IL_037f)
      IL_031e:  br.s       IL_0384
      IL_0320:  br         IL_03e8
      IL_0325:  br         IL_04d1
      IL_032a:  br         IL_054a
      IL_032f:  br         IL_05be
      IL_0334:  br         IL_0632
      IL_0339:  br         IL_06a6
      IL_033e:  br         IL_0741
      IL_0343:  br         IL_07d5
      IL_0348:  br         IL_084a
      IL_034d:  br         IL_08cb
      IL_0352:  br         IL_0946
      IL_0357:  br         IL_09d7
      IL_035c:  br         IL_0a69
      IL_0361:  br         IL_0b32
      IL_0366:  br         IL_0bc1
      IL_036b:  br         IL_0c3c
      IL_0370:  br         IL_0cf2
      IL_0375:  br         IL_0d97
      IL_037a:  br         IL_0e11
      IL_037f:  br         IL_0e80
      IL_0384:  nop

```
I don't know anything about the C# compiler or why it is generating this switch. This problem is dramatically affecting the branch coverage % on this class so I'd like to fix it. Is there something I can do or is this a Coverlet issue?

**Comment by MarcoRossignoli** [comment]
It's normal that compiler emits more branches/types that what we see on C# code. Coverlet tries to "remove" these "hidden" branches trying to recognize patterns.

If your provide a repro we can try to work on it to cleanup "hidden" branches and have a better report.

**Comment by mstrong64** [comment]
Thanks @MarcoRossignoli. I tried to duplicate this issue with a simpler project and failed. In the end I moved all the code inside the try..catch and made some adjustments accordingly.
