### ISSUE TITLE
Problem with run coverlet.msbuild on .net framework project

### ISSUE THREAD

**Issue by netmajor** [coverlet-coverage/coverlet#1219]
Hi,
I have old .net framework 4.6.1 test project. I add coverlet.msbuild nuget. When I try to run tests:
dotnet test Tests.csproj
I get:

C:\Source\project\packages\coverlet.msbuild.3.1.0\build\coverlet.msbuild.targets(11,36): error MSB4184: The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long. (Parameter 'input') [C:\Source\project\Tests.csproj]
I see that in mention line in coverlet.msbuild.targets is:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <UsingTask TaskName="Coverlet.MSbuild.Tasks.InstrumentationTask" AssemblyFile="$(CoverletToolsPath)coverlet.msbuild.tasks.dll"/>
  <UsingTask TaskName="Coverlet.MSbuild.Tasks.CoverageResultTask" AssemblyFile="$(CoverletToolsPath)coverlet.msbuild.tasks.dll"/>

  <PropertyGroup>
    <_CoverletSdkNETCoreSdkVersion>$(**NETCoreSdkVersion**)</_CoverletSdkNETCoreSdkVersion>
    <_CoverletSdkNETCoreSdkVersion Condition="$(_CoverletSdkNETCoreSdkVersion.Contains('-'))">$(_CoverletSdkNETCoreSdkVersion.Split('-')[0])</_CoverletSdkNETCoreSdkVersion>
    <_CoverletSdkMinVersionWithDependencyTarget>3.1.300</_CoverletSdkMinVersionWithDependencyTarget>
    <_CoverletSourceRootTargetName>CoverletGetPathMap</_CoverletSourceRootTargetName>
    <_CoverletSourceRootTargetName Condition="'$([System.Version]::Parse($(**_CoverletSdkNETCoreSdkVersion**)).CompareTo($([System.Version]::Parse($(_CoverletSdkMinVersionWithDependencyTarget)))))' &gt;= '0' ">InitializeSourceRootMappedPaths</_CoverletSourceRootTargetName>
```

But my project is .net framework, not .net core. Is coverlet compatible with my project ?

**Comment by petli** [comment]
Maybe the same as #1119?  

The documentation states

> Coverlet supports only SDK-style projects https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

so if this is the case, can you try to convert your project files?

**Comment by MarcoRossignoli** [comment]
Yep you should convert to SDK-style the project. Coverlet support .NET Framework.
Closing for stale conversation, feel free to reopen if needed.
