### ISSUE TITLE
Version miss match with dotnet-public

### ISSUE THREAD

**Issue by Sanan07** [coverlet-coverage/coverlet#1220]
The latest version of `coverlet.collector` in nuget.org is `3.1.0` and the latest version in [dotnet-public](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-public%40Local&package=coverlet.collector&protocolType=NuGet&version=3.0.3&view=versions) is `3.0.3`

Should they be in sync? I am updating [test-template](https://github.com/dotnet/test-templates) and latest version which I can get is `3.0.3`.

**Comment by MarcoRossignoli** [comment]
Hi @Sanan07,

honestly we don't handle/use that feeds so I don't know. 
For sure last version is `3.1.0`

**Comment by MarcoRossignoli** [comment]
Closing because fixed
