### ISSUE TITLE
Coverlet as global tool always generates zero percentage code coverage regardless of the increase in the number of tests

### ISSUE THREAD

**Issue by milica-nikolic** [coverlet-coverage/coverlet#1222]
Hi,

I have commented this issue but on other closed question so I am not sure is ti visibile, sorry for replication. 

Running this command:

`coverlet Path.To.Tests --target "dotnet" --targetargs "test . --no-build" --threshold 0 --threshold-stat total --format opencover
`

gives this output

```

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+

```
In that package I have few tests but i still get zeros in report regadless of those test.

Am I doing something wrong here ?

Additional info I am using this in GitLab CI pipeline as .NET global tool.

I would appreciate any help here!

**Comment by daveMueller** [comment]
I reopened the old issue and will close this one.
