### ISSUE TITLE
Can't use msbuild integration when running test with dll path

### ISSUE THREAD

**Issue by mabead** [coverlet-coverage/coverlet#1223]
I have been successfully using coverlet with the [msbuild integration](dotnet test --no-build --configuration Release) for a few years. Here's how I would typically run coverlet in our CI:

```
cd <test_project>
dotnet test --configuration Release /p:CollectCoverage=true
```

I am now trying something a little bit different. For some convoluted reason, I need to run `dotnet test` against a dll that is already compiled. Ex:

```
cd <test_project>
dotnet build --configuration Release
dotnet test .\bin\Release\netcoreapp3.1\MyProject.dll /p:CollectCoverage=true
```

Unfortunately, the `dotnet` cli is not happy. Here's the output that I get:

> Microsoft (R) Test Execution Command Line Tool Version 16.10.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> The argument /p:CollectCoverage=true is invalid. Please use the /help option to check the list of valid arguments.

Do you have any idea why the `/p` option is invalid when providing a dll path? Do you have a suggested workaround?

**Comment by daveMueller** [comment]
It is just an assumption but the `msbuild` documentation states: `-p:name=value | Set or override the specified project-level properties`.
And by specifying a dll we aren't on project-level anymore. If you are not bound to use the msbuild driver you can use [coverlet.console](https://github.com/coverlet-coverage/coverlet#usage-2).

**Comment by mabead** [comment]
Thanks for the hint @daveMueller and sorry for taking so long to try it out.

I have tried the coverlet global tool and it works really fine. I think that this global tool is way more convenient to use than the msbuild integration 👍 .

There is just one issue: I was not able to run within docker without recompiling my code as explained in https://github.com/coverlet-coverage/coverlet/issues/1271.
