### ISSUE TITLE
CopyCoverletDataCollectorFiles overwrites newer version of NewtonSoft.Json.dll

### ISSUE THREAD

**Issue by sturnberg** [coverlet-coverage/coverlet#1226]
I recently upgraded my project to .NET 5. When I publish the project I find that the latest version of NewtonSoft.Json.dll 13.0.1 is being overwritten by the version used by coverlet, 9.0.1. The version of Coverlet I'm using is 3.1.0.

If I publish with increased verbosity I can see exactly where the dll is being copied over.
  10:6>CopyCoverletDataCollectorFiles:
         Copying file from "C:\st\.nuget\packages\coverlet.collector\3.1.0\build\netstandard1.0\Newtonsoft.Json.dll" to "C:\src\myProject\Source\Tests\Unit\MyProject.Tests.Unit\bin\Release\net5.0\publish\Newtonsoft.Json.dll".

**Comment by petli** [comment]
Could this be the same issue as discussed in #1045?

**Comment by daveMueller** [comment]
Yes I think it is the same and there are also workarounds. Maybe you can try one of the workarounds there until someone has time to analyze and fix this.

**Comment by sturnberg** [comment]
The issues are the same but the workaround does not work for me. If I don't publish the tests I get the error "Could not find data collector 'XPlat Code Coverage" as explained in this issue https://github.com/coverlet-coverage/coverlet/issues/521.

**Comment by scnanney** [comment]
When is a new version containing this fix going to be released to Nuget?

**Comment by MarcoRossignoli** [comment]
@scnanney can you try the nightly build to confirm that is properly fixed?

https://f.feedz.io/marcorossignoli/coverletunofficial/nuget/index.json version 3.1.1-preview.10

**Comment by willemk** [comment]
@MarcoRossignoli I just tried the 3.1.1 preview on our code, and I can confirm that it's now working as expected.
