### ISSUE TITLE
Uncovered branch at the of "finally" block when "await" appears within it

### ISSUE THREAD

**Issue by alexthornton1** [coverlet-coverage/coverlet#1233]
I wrote a method in which there was an `await` statement in a `finally` block.  The code was fully covered, but Coverlet reported an uncovered branch at the end of the `finally` block.  I had a few things going on in that method -- `ConfigureAwait` was used in multiple places, there were multiple `await` statements in the `finally` block, including one in an `if` statement -- but I was able to narrow the problem down to something much simpler.

Suppose that we have these methods:
![image](https://user-images.githubusercontent.com/1596274/135939190-0426170c-8403-4232-a88c-0c2c3e8357cd.png)

Suppose, also, that we have one test that calls into them, which should fully cover them, since there's no (user-written) branching logic in the code under test:
![image](https://user-images.githubusercontent.com/1596274/135939225-563905d0-5ba7-495f-836b-95d2c396b899.png)

If I run that test under Coverlet 3.1.0 (in .NET 5 or .NET 6 RC 1), here's what I see:
![image](https://user-images.githubusercontent.com/1596274/135939307-d688de60-908f-41f8-979c-027e28acd7cc.png)

The missing branch coverage is here (which turns out to be the curly brace closing the `finally` block):
![image](https://user-images.githubusercontent.com/1596274/135939400-0dcf2dfa-e412-470d-bb5a-542e9fd49d5e.png)

This is the IL instruction that's left uncovered:
![image](https://user-images.githubusercontent.com/1596274/135939942-5ef0f209-f134-47db-a043-bf649cfc95ce.png)

I will attach a repro solution, as well.

Many thanks!

**Comment by alexthornton1** [comment]
Repro:
[AwaitInFinally.zip](https://github.com/coverlet-coverage/coverlet/files/7281894/AwaitInFinally.zip)

**Comment by daveMueller** [comment]
I'll work on that.
