### ISSUE TITLE
DoesNotReturnAttribute does not automatically do what one would think

### ISSUE THREAD

**Issue by Saborion** [coverlet-coverage/coverlet#1234]
I and my colleague got curious to as why we did not get full line coverage on the closing curly brace in a block-statement that ended on a method that does not return, especially since we had added the [System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute?view=net-5.0) to the method. We began to research this and managed to stumble upon coverlets --does-not-return-attribute command line argument, which solved the problem. We do, however, find it more than a little strange that coverlet does not automatically handle that attribute the way one would expect, given intended usage of the attribute.

Is this a "missing feature" or is it working as intended?

**Comment by petli** [comment]
It is the intended function, as far as I can read from the discussion in the PR #904 that introduced it. I think the logic is that it is similar to having to specify which attributes tag generated code, so the user has to opt-in to reducing the lines considered for coverage.

**Comment by Saborion** [comment]
Mk. Thanks for quick responses. Seems like you have things under control.
