### ISSUE TITLE
Question : way to get coverage percent on CLI ?

### ISSUE THREAD

**Issue by b3b00** [coverlet-coverage/coverlet#1239]
Hello , I am the author of the github action [coverlet-action](https://github.com/b3b00/coverlet-action). I've recently added a way to configure a coverage threshold. 
I use the native coverlet threshold mechanism. But it appears that github actions hide the coverlet message stating thrhesold error.
So I was thinking to manage it myself. But to do so I need an easy way to get the computed coverage percentage from coverlet.
I looked at different output format but did not find any that embed it. Is there a way to get it ? 
Standard output parsing is a way to do it but I've always find this to be really brittle.

**Comment by daveMueller** [comment]
Sorry for the late response. Thanks for working with coverlet. AFAIK there currently isn't a way besides the output parsing.
 
I once had nearly the same issue and I also didn't want to parse the stdout. I then generated a `cobertura` report and created a summary report with [ReportGenerator](https://github.com/danielpalme/ReportGenerator). Back then I were using powershell and thus it was super easy to get the values from the `JsonSummary`.

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
