### ISSUE TITLE
impossible to exclude multiple items

### ISSUE THREAD

**Issue by brignolij** [coverlet-coverage/coverlet#1242]
Hi,
I'm using coverlet to export code coverage result in xml. To read it through aws.

i have a solution .net 5 with multiple projects.

i tested following commands on powershell and on zsh / ubuntu

I use it like this :
`dotnet test  --results-directory ./testresults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*Sky.Api]*"`

When excluding 1  items, it work well, but when i want to exclude more than one item, like this :
`dotnet test  --results-directory ./testresults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*Sky.Api]*,[*Sky.RequestModel]*"`
i get a syntax error :
```
MSBUILD : error MSB1006: Property is not valid.
Switch: [*Sky.RequestModel]*
```

I also tried to replace comma by asci character like 
`dotnet test  --results-directory ./testresults /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*Sky.Api]*%3B[*Sky.RequestModel]*"`

Command work, but nothing is excluded.

I probably make a mistake, what's wrong ?
Thanks in advance

**Comment by KinNeko-De** [comment]
I used %2c to separate two excludes.. worked for me in azure pipelines

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.

**Comment by abdul-wahab-ejaz-pikessoft** [comment]
I have the same issue can anyone provide me the solution?
