### ISSUE TITLE
Attempt to install latest version return error 	"The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long." 

### ISSUE THREAD

**Issue by rpietkiewicz** [coverlet-coverage/coverlet#1244]
Trying to install latest version (3.1.0) for my new C# Unit Test Project on my VS 2019 Community
I am returned the error:
The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  C:\Users\robpi\source\repos\UnitTestProject1\packages\coverlet.msbuild.3.1.0\build\coverlet.msbuild.targets				

coverlet.msbuild does not install

Note: I try to install earlier version (2.7.0) - same outcome

**Comment by daveMueller** [comment]
Most likely the same as #1119?

The documentation states

> Coverlet supports only SDK-style projects https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

Can you try to convert your project files?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed.
