### ISSUE TITLE
Coverlet.collector: upgrade from 3.0.2 to 3.1.0 breaks dotnet publish - it ships old version of Newtonsoft.Json (9.0.1)

### ISSUE THREAD

**Issue by ZlobnyiSerg** [coverlet-coverage/coverlet#1258]
I have big solution with tests referring to `coverlet.collector` version `3.1.0` nuget package. Some projects in this solution are referred to Newtonsoft.Json 13.0.1.
When I publish my project with 
```
dotnet publish -o ./app
```
I'm getting old version of `Newtonsoft.Json` - `9.0.1` instead of `13.0.1` in published folder, and my application can't start as result.

Everything is ok with `3.0.2`, broken after `3.1.0` upgrade.

**Comment by petli** [comment]
I think this is the same problem that's been fixed by #1243, but it has not yet been released.

**Comment by daveMueller** [comment]
Yes seems like it's the same issue. @ZlobnyiSerg you can try to consume the nightly build [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md) to see if this fixes your issue.

**Comment by MarcoRossignoli** [comment]
@ZlobnyiSerg were you able to give it a try?

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
