### ISSUE TITLE
Standalone ASP.NET 6 API coverage (zero percent)

### ISSUE THREAD

**Issue by AnthonyIacono** [coverlet-coverage/coverlet#1261]
Hello!

We are attempting to use the standalone coverlet console application to get coverage inside our API when running our external integration test suite (it's basically a test suite that makes HTTP requests to our API). We are interesting in seeing how much of our API codebase is covered by these tests.

We have the following command being executed:
```
~/.dotnet/tools/coverlet /app/bin/Debug/net6.0/ --target "dotnet" --output "/tmp/CollectApi"  --format cobertura --verbosity detailed --targetargs "run -c Debug"
```

The API runs fine, and our test suite is able to run it. I trigger a graceful shutdown by using an HTTP endpoint that triggers:
```
hostApplicationLifetime.StopApplication();
```

The following text is printed to the console:
```
Calculating coverage result...
Hits file:'/var/folders/b_/c5vfxz3j1pzfrrh7nhk6sm_r0000gn/T/Common_79efe341-4e8d-4bd7-9d26-151b73e4220c' not found for module: 'Common'
Hits file:'/var/folders/b_/c5vfxz3j1pzfrrh7nhk6sm_r0000gn/T/Api_79efe341-4e8d-4bd7-9d26-151b73e4220c' not found for module: 'Api'
Hits file:'/var/folders/b_/c5vfxz3j1pzfrrh7nhk6sm_r0000gn/T/Data_79efe341-4e8d-4bd7-9d26-151b73e4220c' not found for module: 'Data'
Hits file:'/var/folders/b_/c5vfxz3j1pzfrrh7nhk6sm_r0000gn/T/Shared_79efe341-4e8d-4bd7-9d26-151b73e4220c' not found for module: 'Shared'
  Generating report '/tmp/CollectApi.cobertura.xml'
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+
| Common | 0%   | 0%     | 0%     |
+--------+------+--------+--------+
| Api    | 0%   | 0%     | 0%     |
+--------+------+--------+--------+
| Data   | 0%   | 0%     | 0%     |
+--------+------+--------+--------+
| Shared | 0%   | 0%     | 0%     |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
```

I'm not sure what I'm doing wrong. We installed the `coverlet.collector` package in our API code, just incase. Any help would be greatly appreciate! :)

**Comment by AnthonyIacono** [comment]
Okay, I think I figured it out. Apparently `--no-build` is super important, since it prevents DLLs from being re-generated right after they were instrumented. So if you run into this issue, make sure your `dotnet run` or `func host start` command has the `--no-build` command!

**Comment by MarcoRossignoli** [comment]
Hi @AnthonyIacono, sorry for the late answer, but yes --no-build means that process will load instrumented libs and so coverlet will be able to collect hits at the end.

Feel free to close if solved.
