### ISSUE TITLE
Coverage result uses comma instead of dot for decimals

### ISSUE THREAD

**Issue by boldt** [coverlet-coverage/coverlet#1263]
When I run `dotnet coverlet` on an **english Linux** machine, the result uses a dot:

```
+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 35.41% | 24.31% | 51.41% |
+---------+--------+--------+--------+
```

When I run the same on a **german Windows**, the result uses a comma:

```
+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 35,41% | 24,31% | 51,41% |
+---------+--------+--------+--------+
```

I tried to set `$Env:DOTNET_CLI_UI_LANGUAGE = "en"`, but it still uses the comma.

Is there any way to configure the output format?

**Comment by daveMueller** [comment]
Thanks for reporting this. I would suggest we use invariant culture here because the rest of our cli output is also english.

![image](https://user-images.githubusercontent.com/19378678/144579586-1e380914-d164-496e-a60b-2516659f5eba.png)

**Comment by boldt** [comment]
Thanks for the quick response and (upcoming) fix.
