### ISSUE TITLE
DoesNotReturnAttribute does not count correctly

### ISSUE THREAD

**Issue by sirkiza** [coverlet-coverage/coverlet#1265]
Hi people! I am facing an issue coverlet. Looking forward for help :)

## Background
I noticed some inconsistency in calculation of code coverage using methods marked with `DoesNotReturnAtttribute`. First of all the method marked with `DoesNotReturnAtttribute` evaluate fine only in `Release` mode (not in `Debug` one). That worked good till until recently.

## Description

The code can be found [here](https://github.com/sirkiza/coverlet-test).

In the code sample you can see `Helper.ArgumentException` which is forcing no inline and marked with `DoesNotReturnAtttribute`.
And the most confusing part, that the results will remain the *same* after deleting `DoesNotReturnAtttribute` from static `Helper.ArgumentException`!

After running tests that should fully cover `Add` method of `NameDict` I got:

### Debug Configuration:
![image](https://user-images.githubusercontent.com/30002731/145021353-15845370-9a44-4afd-b1ec-76be866bece7.png)

### Release Configuration:
![image](https://user-images.githubusercontent.com/30002731/145022662-09a3af3c-816c-4b24-84cb-d5b01b981b32.png)

## Expected Behavior

100% coverage with `DoesNotReturnAtttribute` at least in `Release` configuration (ideally in both).

Thank you for help!

**Comment by daveMueller** [comment]
Thanks for reporting this and providing a repro. :pray:

**Comment by sungam3r** [comment]
The same situation here: 
https://app.codecov.io/gh/graphql-dotnet/parser/blob/master/src/GraphQLParser/LexerContext.cs
![изображение](https://user-images.githubusercontent.com/21261007/152432250-d68fb4a8-aeb1-491f-aea2-b4275d34425e.png)
![изображение](https://user-images.githubusercontent.com/21261007/152432292-1f6fff8a-724b-46ff-b89a-1abd10552885.png)
ping @Shane32 FYI

**Comment by MarcoRossignoli** [comment]
Can you try to enable the feature? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#methods-that-do-not-return

**Comment by sungam3r** [comment]
WOW! 👍  It works, thanks! https://github.com/graphql-dotnet/parser/pull/233

**Comment by Bertk** [comment]
> Can you try to enable the feature? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#methods-that-do-not-return (same element for the collector integration)
> 
> it's disabled by default because we had some issue with this feature that lead to hang.
> 
> For the release/debug it's expected...coverlet is sequence point based at the moment and for release/debug compilers emits different sequences.

**Resolved enabling optional feature.**
