### ISSUE TITLE
Negative sequence point coverage when line executions exceed int.MaxValue

### ISSUE THREAD

**Issue by Malivil** [coverlet-coverage/coverlet#1266]
_Package_: coverlet.msbuild
_Version_: 3.1.0
_Format_: opencover

In a project where a particular line of code gets called _a lot_, the sequence point coverage value for that line can become negative if the line is hit more than `int.MaxValue` times. The value in the XML is negative and shows in the generated report as uncovered.

I created a simple repro of this because I cannot show the actual code that caused the problem (it's from my job).

XML:
![image](https://user-images.githubusercontent.com/1238511/145092755-f886ba93-e52a-4cd9-958c-fb7d857ba9b6.png)

Report:
![image](https://user-images.githubusercontent.com/1238511/145092722-8519dc87-0e64-45aa-b84f-f9bd5de79d8a.png)

Repro code: https://github.com/Malivil/Coverlet1266Repro

**Comment by daveMueller** [comment]
Thanks for reporting and thanks for the repro. 🙏

**Comment by daveMueller** [comment]
Mhh, we could change the tracker to stop tracking hits when `int.MaxValue` is reached. Something like 
``` csharp
public static void RecordHit(int hitLocationIndex)
{
    if(HitsArray[hitLocationIndex] < int.MaxValue)
        Interlocked.Increment(ref HitsArray[hitLocationIndex]);
}
```

I just tested it with the repro provided by @Malivil and it would work.

![image](https://user-images.githubusercontent.com/19378678/145115178-55697675-8ac8-4620-bfa6-ad7ef4ef8008.png)

What do you think, @MarcoRossignoli @petli @tonerdo? Any other ideas for solutions?

**Comment by MarcoRossignoli** [comment]
I prefer to avoid a new branch on tracker...we're injecting it to probe, maybe we can try to move to `uint32` https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.increment?view=net-6.0#System_Threading_Interlocked_Increment_System_UInt32__ and let it overflow  but always as positive. 
We need to understand during report generation what's happen if we put a uint istead of int for instance for cobertura+report generator.

**Comment by petli** [comment]
An alternative is to translate negative numbers to `int.MaxValue` when collecting the results.

**Comment by MarcoRossignoli** [comment]
> An alternative is to translate negative numbers to int.MaxValue when collecting the results.

Yep, if we're ok with int.MaxValue, @Malivil from your perspective does it make sense have "correct very huge value" there? I mean are you paying attention to that?

**Comment by petli** [comment]
I think that if you hit 31 bits you may be likely to hit 32 bits too, and then the only real solution would be to go to `long`, doubling the memory usage. (But maybe not slow down execution, on 64-bit machines?)

**Comment by Malivil** [comment]
> > An alternative is to translate negative numbers to int.MaxValue when collecting the results.
> 
> Yep, if we're ok with int.MaxValue, @Malivil from your perspective does it make sense have "correct very huge value" there? I mean are you paying attention to that?

We're not paying attention to the number, specifically. As long as it's positive and it makes sense with the surrounding lines we wouldn't even notice. Keeping it at `int.MaxValue` would work fine from our perspective.

**Comment by daveMueller** [comment]
> An alternative is to translate negative numbers to `int.MaxValue` when collecting the results.

Then should we go with this solution? I could prepare a PR in the next days.

**Comment by MarcoRossignoli** [comment]
@daveMueller looks like we're all in agreement for the translation, feel free to tackle it if you want! Thanks a lot!
