### ISSUE TITLE
Branch coverage 100% when line coverage 0%

### ISSUE THREAD

**Issue by johnradke** [coverlet-coverage/coverlet#1268]
Methods with no branches are considered to have 100% branch coverage even when they have 0% line coverage. However, methods with at least one branch are considered to have 0% branch coverage if none of the lines are covered.

Example `coverage.coberatura.xml`:
```xml
<method name="NoConditionCovered" signature="()" line-rate="1" branch-rate="1" complexity="1">
  <lines>
    <line number="21" hits="1" branch="False" />
    <line number="22" hits="1" branch="False" />
    <line number="23" hits="1" branch="False" />
  </lines>
</method>
<method name="NoConditionUncovered" signature="()" line-rate="0" branch-rate="1" complexity="1">
  <lines>
    <line number="26" hits="0" branch="False" />
    <line number="27" hits="0" branch="False" />
    <line number="28" hits="0" branch="False" />
  </lines>
</method>
<method name="ConditionUncovered" signature="()" line-rate="0" branch-rate="0" complexity="2">
  <lines>
    <line number="31" hits="0" branch="False" />
    <line number="32" hits="0" branch="True" condition-coverage="0% (0/2)">
      <conditions>
        <condition number="16" type="jump" coverage="0%" />
      </conditions>
    </line>
    <line number="33" hits="0" branch="False" />
  </lines>
</method>
```

`NoConditionCovered` method has no condition and is covered by unit test, so has expected line and branch rates of 1.
`NoConditionUncovered` method is identical but is NOT covered by unit tests and so has a line rate of 0, but yet a branch rate of 1.
`ConditionUncovered` method has a condition and is not covered by unit tests, and so has expected line and branch rates of 0.

Is this expected behavior? Is there any option to force uncovered methods to be considered to have 0% branch coverage?

**Comment by MarcoRossignoli** [comment]
Can you provide the repro of the above so we can check better what you mean?

But in general coverlet splits line and branch and account these as a separate. So if you have a method with 1 branch and 3 line and nothing is coverlet you'll have 0% branch and 0% lines. If you have 0 branch and all line covered you have 100% branch covered, 0 branch in code means that you didn't skip any branch so 100% sounds reasonable. If we put 0% branch covered inside a method with no branch looks like some coverage is missing or?

> Is there any option to force uncovered methods to be considered to have 0% branch coverage?

Do you mean that if you have a method with 10 lines and 0 branch and it's not covered you'd like to see 0% lines and 0% branch?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed.
