### ISSUE TITLE
Re-configure coverlet from Visual studio data collector configuration...

### ISSUE THREAD

**Issue by tapika** [coverlet-coverage/coverlet#1269]
For .net core it's possible to configure code coverage testing using instructions like this:

https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=windows

For Visual studio itself code coverage is configured via .runsettings file:

https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#sample-runsettings-file
(1)

I don't know all pieces of puzzle, but suspect coverlet "data collector" is not the same as visual studio own 
`Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector` data collector.

Coverlet can be indeed reconfigured with additional filtering rules, but same configuration is configured from command line:

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage

for example `/p:Exclude=[Assembly-Filter]Type-Filter`. (2)

Which basically duplicates everything within .runsettings versus command line arguments.

Suspect similar ticket was raised on issue: https://github.com/coverlet-coverage/coverlet/issues/926

But don't know to what it concluded to.

Would it be possible to parse `.runsettings` file and reconfigure same settings as for command line option ?

So configuration file would be (1), but it would expect the same result as configured via (2).

Maybe one approach to provide `.runsettings` via custom parameter for coverlet so coverlet can parse file and re-configure itself.

**Comment by petli** [comment]
The coverlet VSTest collector driver is configured with a runsettings file, you can find the documentation for that here:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

The first link you provided is about coverlet, which as you correctly suspect is different from the standard code coverage analysis in Visual Studio.

As an aside, the MSBuild driver is not recommended, since the hit count reporting may in some cases not be processed fully, due to limitations in the execution environment for that driver:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by tapika** [comment]
I have tried now to create projects & builders to show how whole system will work:

https://github.com/tapika/test_codecov

And now documented two code coverage methods - both using coverlet.

And in root folder I have 
.runsettings - this is for Visual studio code coverage.
coverlet.runsettings - this is for coverlet code coverage.

But both methods using in this demo projects are not using .runsettings file.

What is puzzling to me is that Microsoft included coverlet as de-facto standard 
code coverage tool, but Visual studio does not use that tool at all.

Maybe Microsoft guys will switch they code coverage tool later on ?

**Comment by petli** [comment]
@tapika  Have you specified the runsetting files for coverlet on the command line? There's an example at
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration :

    dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings

The Visual Studio code coverage solution is only available in the Enterprise edition, so I think Microsoft intend to keep that as their commercial offering for code coverage integrated in the IDE, while recommending coverlet as an open source solution for users who doesn't have or want to buy VS Enterprise.

There are third-party VS extensions that allow you to run coverlet from within VS and get the results in the code directly if you are looking for an integrated code coverage solution without going to VS Enterprise, but I haven't used any of them myself.

**Comment by tapika** [comment]
Now I started to understand why there are all these options to enable code coverage - I have now updated pros/cons list for each code coverage test method into here: https://github.com/tapika/test_codecov

If you have more pros/cons for coverlet, let me know, I'll try to write them down as well.

But now I also suspect I should raise similar ticket for Visual studio team or into VSTest platform.

**Comment by MarcoRossignoli** [comment]
@tapika  You can try FineCodeCoverage https://github.com/FortuneN/FineCodeCoverage
