### ISSUE TITLE
Question: dotnet standard

### ISSUE THREAD

**Issue by KyleSchoonover** [coverlet-coverage/coverlet#1280]
With full framework already at end of life, will you be moving to .Net Core 3.1 (which has an EOL of December 22nd, 2022)?

**Comment by MarcoRossignoli** [comment]
Hi, I don't get it what you mean, coverlet is shipped in three flavors, msbuild task(netstandard2.0), collector(netstandard2.0) and .NET Tool(net5.0) and for the moment I think we'll keep it as-is to be able to run everywhere.

> With full framework already at end of life

Despite the fact that is no more developed there are around tons and tons of .NET Framework app that we like to support.

**Comment by Bertk** [comment]
coverlet supports .NET framework (netstandard2.0) and .NET 6.0 (LTS)
