### ISSUE TITLE
CoreLib's coverage measurement is broken

### ISSUE THREAD

**Issue by ViktorHofer** [coverlet-coverage/coverlet#1285]
[After figuring out why CoreLib doesn't write the result file when being instrumented by coverlet](https://github.com/dotnet/runtime/issues/51058#issuecomment-1025853537) and working around the issue, I noticed that the `WriteLog` and `WriteHits` methods in the `ModuleTrackerTemplate` throw:

```
  Unhandled exception. System.TypeLoadException: Could not load type 'System.Diagnostics.Process' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
     at Coverlet.Core.Instrumentation.Tracker.System.Private.CoreLib_19e73ecb-b988-441a-913d-54373b41abc8.WriteLog(String)
     at Coverlet.Core.Instrumentation.Tracker.System.Private.CoreLib_19e73ecb-b988-441a-913d-54373b41abc8.UnloadModule(Object, EventArgs)
     at System.AppContext.OnProcessExit() in C:\git\runtime3\src\libraries\System.Private.CoreLib\src\System\AppContext.cs:line 88
```

- https://github.com/coverlet-coverage/coverlet/blob/df968b862687aeb9ac86ae47938da04d95c10452/src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs#L176
- https://github.com/coverlet-coverage/coverlet/blob/df968b862687aeb9ac86ae47938da04d95c10452/src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs#L200

That's because CoreLib doesn't have access to the Process type and even though those code paths aren't running by default, they are in the IL and hence the types are tried to be resolved. To unblock dotnet/runtime it would be great if these code paths that rely on `Process` could be changed to not include the process id.

cc @stephentoub

**Comment by ViktorHofer** [comment]
cc @MarcoRossignoli

**Comment by jkotas** [comment]
You can get process ID using `Environment.ProcessId` in recent .NET runtimes.

**Comment by MarcoRossignoli** [comment]
We instrument and after tests can run in different runtime(after in the workflow), so I don't think that we can use #ifdef here(we build for netstandard2.0).

Anyway that id is used only to avoid filename clash  and are used for debugging purpose, so to not complicate too much the code we can substitute with a Guid. Is it available on CoreLib?

**Comment by stephentoub** [comment]
> we can substitute with a Guid. Is it available on CoreLib?

yes

**Comment by MarcoRossignoli** [comment]
We'll ship nightly build at midnight, would be great is someone tomorrow give it a try to check if this first issue is solved https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by stephentoub** [comment]
Thank you for working on the fixes, @MarcoRossignoli.
