### ISSUE TITLE
c# 10 top level statements not reported

### ISSUE THREAD

**Issue by jbockle** [coverlet-coverage/coverlet#1289]
I'm guessing this is by design, strangely enough vstest with coverlet .runsettings reports it under a "Global Classes" namespace, using dotnet test with the same runnsettings file doesn't report it

**Comment by MarcoRossignoli** [comment]
Hi, I don't get it, can you provide a repro?

**Comment by jbockle** [comment]
sure, checkout https://github.com/jbockle/coverlet.csharp10.issue
some sample test output from `vs2022` and `dotnet test`

**Comment by daveMueller** [comment]
The IL of the top level statement file has a `CompilerGeneratedAttribute`.

![grafik](https://user-images.githubusercontent.com/19378678/156269032-02d68b8e-7c89-4a7d-957f-e99667dd9c26.png)

If you remove the `CompilerGeneratedAttribute` from the `ExcludeByAttribute` in the `.runsettings` of your repro, the top level statement file is reported.

![grafik](https://user-images.githubusercontent.com/19378678/156269390-ce5861dc-2682-4f7d-ad35-8c3bb2767a58.png)

**Comment by daveMueller** [comment]
Closed as designed.
