### ISSUE TITLE
cannot access the file, because it is being used by another process

### ISSUE THREAD

**Issue by ChristopherPope** [coverlet-coverage/coverlet#1296]
I understand this problem was fixed by #869 but I am experiencing the issue at my work and I believe this has to do with our environment at work because I cannot reproduce it at home.

I am using Coverlet.Collector 3.1.2, NUnit 3.13.2, and .Net Core 3.1 and have created a minimal test project to reproduce this at work (but not at home)

I see  the RetryAttempts count in InstrumentationHelper, could this be modified to accept a parameter given to the dotnet CLI so that I could increase it and perhaps fix my problem?

I cannot build Coverlet at work because it is using an older version of Newtonsoft.Json, nor can I use the language features of C# 8.0

Thanks.

**Comment by MarcoRossignoli** [comment]
Hi, do you have antivirus on that machine?
Users sometimes has got that issue and the solution is to remove the dev dirs from antivirus check.

**Comment by MarcoRossignoli** [comment]
Another solution we were thinking about is to avoid to "restore" instrumented assemblies at the end if the compilation is no more used.
