### ISSUE TITLE
Unable to instrument module  pdb without local source files

### ISSUE THREAD

**Issue by madhugilla** [coverlet-coverage/coverlet#1297]
hi,

i am running into the following when trying to generate code coverage for a particular assembly Fulfillment.Function.dll, this assembly contains sourcegenerated files , from what i gathered so far, coverlet will not instrument assemblies with source generators that do not contain ".g.cs", 

tried the following options without any luck

`coverlet .\bin\Debug\net6.0\Fulfillment.UnitTests.dll --target "dotnet" --targetargs "test --no-build" --verbosity detailed --exclude="[FunctionEndpointTrigger]*"
`

`coverlet .\bin\Debug\net6.0\Fulfillment.UnitTests.dll --target "dotnet" --targetargs "test --no-build" --verbosity detailed --exclude-by-file=\"**/XYZ_FunctionEndpointTrigger.cs/"
`

how do i overcome this ?

thanks -madhu

Unable to instrument module: .\bin\Debug\net6.0\Fulfillment.Function.dll, pdb without local source files, [D:\ft\src\Function.Fulfillment\XYZ.AzureFunctions.SourceGenerator\XYZ.AzureFunctions.SourceGenerator.TriggerFunctionGenerator2\XYZ__FunctionEndpointTrigger.cs

**Comment by petli** [comment]
There is currently no way around this, but #1164 suggests a new option to let the user control this heuristic. I haven't had any time to work on it, but it should be a fairly straight-forward contribution since it doesn't touch any of the instrumentation logic itself, just a check before it gets going.

**Comment by MarcoRossignoli** [comment]
Closing as dup and I've referenced this issue inside the other one
