### ISSUE TITLE
`ExcludeFromCodeCoverage` attribute is ignored on local function

### ISSUE THREAD

**Issue by meggima** [coverlet-coverage/coverlet#1302]
Having the following code:

```csharp
public class ExcludedLocalFunctionReproduction
{
    public void SomethingThatIsUsingALocalFunction()
    {
        MethodThatTakesALambda(NewMethod());

        [ExcludeFromCodeCoverage(Justification = "Not testable")]
        static Func<string, bool> NewMethod()
        {
            return myString => myString.Length == 10;
        }
    }

    private void MethodThatTakesALambda(Func<string, bool> function)
    {
        // Do something - the actual function is not invoked to show the issue
        bool _ = function != null;
    }
}
```

Coverlet reports the line `return myString => myString.Length == 10;` as uncovered even though the local method is excluded from code coverage:

![image](https://user-images.githubusercontent.com/22348611/154082159-e8f3cb87-33e2-49c7-b27d-45dbd590be80.png)

I would expect the local function to be shown as excluded.

The full code (along with other reproductions for already reported issues) is here: https://github.com/meggima/coverlet-reproductions

**Comment by meggima** [comment]
A similar issue is already mentioned here:

> It should also come as no surprise that C#7.0 local functions are similarly not excluded even if the enclosing method is.

_Originally posted by @SteveGilham in https://github.com/coverlet-coverage/coverlet/issues/82#issuecomment-386737795_

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this.

**Comment by daveMueller** [comment]
I start to work on this.
