### ISSUE TITLE
Set line coverage threshold for PRs (Pull Requests)

### ISSUE THREAD

**Issue by duyn9uyen** [coverlet-coverage/coverlet#1310]
Is it possible to set the line coverage threshold % to PRs instead of the entire project? I would like to know that for a given PR, at least 70% of that new code is covered.

**Comment by petli** [comment]
@duyn9uyen, this kind of more advanced analysis is a bit outside the scope of coverlet, but can be solved with additional tools (see e.g. #1174 for a discussion about it). In the project I work we use coverlet together with Sonarqube for this kind of PR coverage analysis, which works really well.

**Comment by duyn9uyen** [comment]
Thanks for the tip.
