### ISSUE TITLE
Error after adding coverlet.msbuild 3.0+ to .NET Framework 4.8

### ISSUE THREAD

**Issue by aminzar-access** [coverlet-coverage/coverlet#1317]
Hi,
I have been trying to follow the instructions to add `coverlet.msbuild` to a **UnitTest Project (.NET Framework)** v4.8 but I can only add up to 2.9 version, anything higher I get the following error and then I can reload the project anymore and I get the following error:

`error  : The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  ...\.nuget\packages\coverlet.msbuild\3.0.0\build\coverlet.msbuild.targets`

![image](https://user-images.githubusercontent.com/77307027/159389522-35607f94-c611-4249-b857-b1513ffba8a7.png)

Is .NET Framework still supported after 3.0? 

Thanks.

**Comment by petli** [comment]
Hi @aminzar-access, coverlet should support .NET Framework, but only SDK-style project files:
https://github.com/coverlet-coverage/coverlet#quick-start

Your error message looks similar to closed issues where this was the problem. If you can convert your solution to SDK-style projects, you should be able to use coverlet.
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

**Comment by aminzar-access** [comment]
Hi @petli, thanks for your reply. I have created the project using **Unit Test Project (.NET Framework)** template in VS2022, is that not supported? I am not very sure what SD-style project means? Is it **Microsoft.NET.Sdk** projects only?

![image](https://user-images.githubusercontent.com/77307027/159643208-ec670f2a-306b-4170-8d21-7c70eeda7424.png)

**Comment by petli** [comment]
@aminzar-access I don't know more myself, since I only work in .NET Core/6 and haven't used .NET Framework for a long time. The link https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022 shows a little what the SDK looks like, and I find https://docs.microsoft.com/en-us/dotnet/architecture/modernize-desktop/example-migration#migrating-from-net-framework when searching for how to convert.

**Comment by aminzar-access** [comment]
@petli thanks for your help. Just converted the project to .NetCore.
