### ISSUE TITLE
Making coverlet.msbuild msbuild properties more descriptive

### ISSUE THREAD

**Issue by kovianyo** [coverlet-coverage/coverlet#1324]
I have a csproj using **coverlet.msbuild** with the follwoing content:

```csproj
  <PropertyGroup>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Exclude>[xunit.*]*</Exclude>
    <CollectCoverage>true</CollectCoverage>
  </PropertyGroup>
```

When I first looked at it, I was wondering what the property **Exclude** could be.

The property name **Exclude** does not really hint to the fact that it is used by coverlet.msbuild. An extended name, for example CoverletExcludeFilters would better show what the property is used for, and could avoid possible conflicts.

What do you think?

**Comment by MarcoRossignoli** [comment]
I think it's true, historically the naming for the msbuild runner wasn't never been good.
We can think to change it if we'll have enough request for that, I'll keep this issue open for some time to see if there's some interest.

This is the list of the used vars https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.props

**Comment by Bertk** [comment]
Information available in [MSBuildIntegration.md](https://github.com/coverlet-coverage/coverlet/blame/master/Documentation/MSBuildIntegration.md). 

The _coverlet.msbuild_ property names will not be updated/renamed (**breaking change**).
