### ISSUE TITLE
Return in await using without braces in if statement has uncovered line

### ISSUE THREAD

**Issue by manuelamateo** [coverlet-coverage/coverlet#1333]
I may have discovered a wrong line coverage. To reproduce it four different circumstances must be met:

1. Use await using (only using works correctly)
2. await using must be inside a if statement (maybe reproduction works with other statements too)
3. await using must be used without braces
4. A value must be returned in context of using inside the if statement

See reproduction https://github.com/meggima/coverlet-reproductions AwaitUsingReturnInIfStatementReproduction.cs & AwaitUsingReturnInIfStatementReproductionFixture.cs

![image](https://user-images.githubusercontent.com/12097975/167671810-da140b61-1d72-46b8-a932-01bf8d374666.png)

Thank you for steadily improving this software!

**Comment by daveMueller** [comment]
Thanks for reporting this. 🙏
