### ISSUE TITLE
Empty coverage when running on GitHub Actions

### ISSUE THREAD

**Issue by daviddesmet** [coverlet-coverage/coverlet#1341]
Somehow, when running the tests with coverage collector, the XML is empty on GitHub Actions but locally the same command works.

I'm using Cake to execute the testing with the command `dotnet cake --target=Test` which is configured as follows:

```
Task("Test")
    .Description("Runs unit tests and outputs test results to the artifacts directory.")
    .DoesForEach(GetFiles("./tests/**/*.Tests.csproj"), project =>
    {
        Information($"Preparing {project.GetFilename()} for test");

        DotNetTest(
            project.ToString(),
            new DotNetTestSettings()
            {
                Blame = true,
                Collectors = new string[] { "XPlat Code Coverage" },
                Configuration = configuration,
                Framework = "net6.0",
                Loggers = new string[]
                {
                    $"trx;LogFileName={project.GetFilenameWithoutExtension()}.trx",
                    $"html;LogFileName={project.GetFilenameWithoutExtension()}.html",
                },
                NoBuild = true,
                NoRestore = true,
                ResultsDirectory = artefactsDirectory,
                Settings = "CodeCoverage.runsettings"
            });
    });
```

I also did run it using the command:

```bash
dotnet test -f net6.0 --no-restore --logger trx -r ${{env.BUILD_ARTIFACT_PATH}} --settings "CodeCoverage.runsettings"
```

And got the same output on GitHub Actions.

The `runsettings` si configured as:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <TargetFrameworkVersion>net6.0</TargetFrameworkVersion>
  </RunConfiguration>
  <!-- Configurations for data collectors -->
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <Format>cobertura,opencover</Format>
          <Include>.*(common prefix of all csproj files in the solution).*</Include><!-- [Assembly-Filter]Type-Filter -->
          <ExcludeByAttribute>ExcludeFromCodeCoverageAttribute,Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

This is the output from GitHub Actions:

```xml
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1653068861" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

I did a last run with the `--diag:log.txt` parameter, the logs are located in the artifacts [published here](https://github.com/daviddesmet/paseto-dotnet/actions/runs/2359825066).

The `log.txt` file doesn't show any log related to `[coverlet]` as per the instructions on the [troubleshooting](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration) guide.

I've been trying with several combinations and all combinations locally works and I get the expected coverage but on GitHub Actions is always empty. Any help on this would be greatly appreciated.

**Comment by daveMueller** [comment]
I was able to reproduce your described behaviour but couldn't find the issue up to now. When executing your build script locally you can see in the `log.datacollector` the line 
```
[coverlet]Instrumented module: 'D:\Repos\paseto-dotnet\tests\Paseto.Tests\bin\Release\net6.0\Paseto.dll'
```
But when run inside the github action it seems that coverlet isn't even trying to instrument the assembly. You can see that coverlet is starting its work by analyzing other assemblies
```
[coverlet]Unable to instrument module: D:\a\paseto-dotnet\paseto-dotnet\tests\Paseto.Tests\bin\Release\net6.0\xunit.core.dll
```
But it never touches the `Paseto.dll` even when directly adding it to the `include` tag in the runsettings. I don't really have an idea why this happens inside the github action. @MarcoRossignoli @petli Any ideas?
Would be much easier to analyze if we could reproduce this locally.

**Comment by petli** [comment]
I can't see anything except that it's a very old version of `coverlet.collector`, 1.3.0:
https://github.com/daviddesmet/paseto-dotnet/blob/master/tests/Paseto.Tests/Paseto.Tests.csproj#L77

It's worth trying to upgrade to the latest.

**Comment by daviddesmet** [comment]
Oh boy! This is embarrassing... that was the issue 😅
