### ISSUE TITLE
Examples Contain Side Effects

### ISSUE THREAD

**Issue by josephdrake-stahls** [coverlet-coverage/coverlet#1344]
My particular issue came from trying to resolve an issue with Fine Code Coverage not reporting any results in my repository.
At first there were no results, so I created a new solution with a minimum viable product to get FCC working, no dice.  I compared my settings against the Examples in this repo and had everything configured similarly and couldn't get a working example.

After those 2 failed attempts, I cloned this repo to run the Examples and to my surprise (specifically the VSTest/HelloWorld) reports coverage no problem.  This is where things go a bit oblong.

This repository contains:
[Directory.Build.props](https://github.com/coverlet-coverage/coverlet/blob/master/Directory.Build.props)
[Directory.Build.targets](https://github.com/coverlet-coverage/coverlet/blob/master/Directory.Build.targets)
[DeterministicBuild.targets](https://github.com/coverlet-coverage/coverlet/blob/master/DeterministicBuild.targets)

These files introduce side effects to the examples.  Additionally I tried to find the specific properties that allowed the coverage to work, but it isn't an issue of msbuild configuration.  Deleting these files and running the coverage will reproduce my issue, but if you keep the files and comment out all of the content inside the `<Project />` elements, it works.

To further corroborate the issue, running the coverage from the command line produces the same results with and without the targets/props files.

I don't want this thread to turn into debugging my problems, but instead to bring attention to the examples being contaminated with side effects due to the Driectory.Build.props and Driectory.Build.targets at the top level of the repo since this has resulted in a significant amount of time lost due to the side effects.  I will look into the other open/closed issues to resolve my specific issues surrounding the lack of coverage results.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this, I'll take a look to isolate the samples from the repo.
