### ISSUE TITLE
In coverage.cobertura.xml not getting data locally.

### ISSUE THREAD

**Issue by vishnuprakash9845** [coverlet-coverage/coverlet#1356]
Hi All,

I developed sample Dot Net Core project with 3 UI Tests.
Installed the dotnet tool install --global coverlet.console
Check the Microsoft.NET.Test.Sdk which is 17.2.0

I am trying to generate the coverage file locally first. Ran the below command

**dotnet test --collect:"XPlat Code Coverage"**

Code coverage file got generated at "*\TestsDotNetCore\TestResults\589ed878-3fe6-4b0e-893a-594a5bf32a53" location

**when I open the file getting "No data XML"**

![image](https://user-images.githubusercontent.com/24207575/176371441-2aa4ff5c-3592-4313-abdc-e7adaaf5cc0a.png)

===================================================================================

But If I run the same tests using Visual Studio -> Test -> Analyze Code Coverage for all the tests I am getting coverage data.

![image](https://user-images.githubusercontent.com/24207575/176371366-76a492b0-80a5-464e-a25d-772706f674c8.png)

**I went through the below link didn't get where I am going wrong. Can any one please help me** 

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

Context:

OS: Windows 10 64 bit,
Coverlet Collector: 3.1.2,
MsTest: 2.2.10,

![image](https://user-images.githubusercontent.com/24207575/176372326-354d51f7-08e8-4adc-a0b5-a7b3aced57c1.png)

**Comment by MarcoRossignoli** [comment]
> But If I run the same tests using Visual Studio -> Test -> Analyze Code Coverage for all the tests I am getting coverage data. 

Visual Studio is using another product for code coverage, if you want the same behavior you should use:

`dotnet test --collect:"Code Coverage"`

For more information on settings you can follow this guide(format etc...) https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022
