### ISSUE TITLE
Coverage locally though CLI returns 0% when ran though Visual Studio Test -> Analyze Code Coverage for All Tests getting correct data

### ISSUE THREAD

**Issue by vishnuprakash9845** [coverlet-coverage/coverlet#1362]
I'm currently facing a different problem, which may be related to using the latest .NET Core 6.0 . (I don't know for sure).

On my computers coverage works fine with Visual Studio IDE , but when running on a CLI getting coverage as 0%. Not sure what's going wrong.

Through IDE:
![image](https://user-images.githubusercontent.com/24207575/178481881-00e47688-8e98-4c69-bd4e-9bfb20a227bf.png)

In the CLI:

Below command is used to run
coverlet .\bin\debug\net6.0\XunitTestFramework.dll --target "dotnet" --targetargs "test --no-build"

![image](https://user-images.githubusercontent.com/24207575/178482153-b19f5989-545a-456d-9ec3-389012e8c44d.png)

Following packages I used in my project:

![image](https://user-images.githubusercontent.com/24207575/178482534-174dd0a3-8037-402b-863f-3e0039ebe684.png)

I'm completely blank why this kind on different behavior, can anyone help me to solve this issue. 

Thanks for your time!

**Comment by andrei-epure-sonarsource** [comment]
Hi @vishnuprakash9845 

Did you read the Known issues? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#known-issues

One of the mentioned symptom is:
> zero coverage result (often only on CI but not on local)

**Comment by vishnuprakash9845** [comment]
@andrei-epure-sonarsource 

Thanks for the response. 

I missed to see that known issue. But bit surprised to see the issue still open for some time. 

For time being I got the workaround for the issue from the link you shared. 

![image](https://user-images.githubusercontent.com/24207575/180371841-0ae69150-4596-4d3b-a242-45bd52900d25.png)

Its working fine. 

![image](https://user-images.githubusercontent.com/24207575/180371965-2a9ab32b-148e-4bc9-9b4a-85b01c426b8f.png)
