### ISSUE TITLE
Failed to install package in .NET Framework 4.7.2 - The expression "[System.Version]::Parse('')" cannot be evaluated

### ISSUE THREAD

**Issue by bdzevel** [coverlet-coverage/coverlet#1372]
I am receiving the following error when installing the package:

The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  C:\Users\bdzevel\workspace\insight\packages\coverlet.collector.3.1.2\build\netstandard1.0\coverlet.collector.targets				

Seems this is similar to issues found by others as well. Eg: https://github.com/coverlet-coverage/coverlet/issues/1317

The advice is to convert the project to an "SDK-Style" project - but I'm not clear on what this means. I read the documentation provided (https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019) but it doesn't offer any advice. I've tried adding the "Sdk" attribute to the project XML but it causes issues (VS doesn't like it, doesn't build, and seems to have issues loading dependencies).

Is there a guide or steps to include coverlet in a .NET Framework test project? Is there an option to enable the project as an "SDK-Style" project? Or does coverlet simply not support .NET Framework anymore?

**Comment by bdzevel** [comment]
bump ?

**Comment by bdzevel** [comment]
I am assuming that .NET framework is not supported. This should be changed in the documentation as apparently this is inaccurate:
`It works with .NET Framework on Windows and .NET Core on all supported platforms.`

**Comment by daveMueller** [comment]
Sorry for the late response. Like already described in the the other issue [(#1317)](https://github.com/coverlet-coverage/coverlet/issues/1317). .NET framework is supported, but only SDK-style project files. Unfortunately Visual Studio doesn't have support to convert the old project files as there are too many ways something can fail while converting.
You can try this tool [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017/). Alternatively you can try to use the official [try-convert](https://github.com/dotnet/try-convert) or [upgrade-assistant](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant) tool and change the target framework moniker back to .NET framework (e.g. `net48`) after the conversion. A default console application template then will look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>
```

**Comment by bdzevel** [comment]
Thanks for the reply. I think this will be helpful to others. I went in a different direction using `dotCover`. In the future I will have to try the above tools.
