### ISSUE TITLE
.NET Standard 1.x + async - Wrong branch coverage

### ISSUE THREAD

**Issue by vers-one** [coverlet-coverage/coverlet#1376]
I think this is the same issue as #113 but affecting only .NET Standard 1.x projects. (Unfortunately, I have to use .NET Standard 1.3 in my project.)

Reproduction: https://github.com/vers-one/AsyncCoverageIssue

Coverage report:
![CoverageReport](https://user-images.githubusercontent.com/12114169/187346268-377ea087-be80-4215-ad13-59a51ffaa8ac.png)

Projects targeting .NET or even .NET Standard 2.x don't exhibit this issue.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting it.

**Comment by daveMueller** [comment]
@vers-one Thanks for the repro. I created a PR for this #1433. 

If someone wants to check this, I locally compiled this and uploaded the NuGet packages here. 
[Packages.zip](https://github.com/coverlet-coverage/coverlet/files/10394215/Packages.zip)

**Comment by vers-one** [comment]
@daveMueller, it works! Thank you!
