### ISSUE TITLE
Coverlet showing 0% code coverage 

### ISSUE THREAD

**Issue by ketanmehra30** [coverlet-coverage/coverlet#1378]
I have build a Roslyn analyzer with custom rules  in .net standard2.0 framework and I have written test cases for rules in .net 4.8 framework project using Xunt.  I have setup my coverlet code coverage and install all the required packages in test project but when ever I run the coverlet command :  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura. it gives me 0% in all the coverages

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+

**Comment by MarcoRossignoli** [comment]
Most probably you're suffering of a known issue https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

You should move to the datacollector integration https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by GDonets** [comment]
I tried to follow instructions for datacollector integration, but generated coverage.cobertura.xml still shows 0 coverage

**Comment by earloc** [comment]
I have a similar issue and tracked it down so far, that coverlet seems to be unable to instrument files generated by the source-generator.
Details can [be found here](https://github.com/earloc/TypealizR/issues/30#issuecomment-1319691057)

(copied from my comment)
```
Target "InstrumentModules" in file "...\.nuget\packages\coverlet.msbuild\3.2.0\build\coverlet.msbuild.targets" from project "...\repros\30_Empty_CodeCoverage\XUnit.Tests\XUnit.Tests.csproj" (target "InstrumentModulesAfterBuild" depends on it):
       Using "Coverlet.MSbuild.Tasks.InstrumentationTask" task from assembly "...\.nuget\packages\coverletTask "Coverlet.MSbuild.Tasks.InstrumentationTask"
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\ConsoleApp.dll, pdb without local source files, [...\repros\30_Empty_CodeCoverage\ConsoleApp\TypealizR.SourceGenerators\TypealizR.SourceGenerators.StringLocalizer.SourceGenerator\IStringLocalizerExtensions_ConsoleApp.Resource1.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.assert.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Assert.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.core.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\common\ExceptionExtensions.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.execution.dotnet.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.runner.reporters.netcoreapp10.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.runner.reporters\Utility\EnvironmentHelper.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.runner.utility.netcoreapp10.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.runner.utility\Extensions\DisposableExtensions.cs]
         [coverlet] Unable to instrument module: ...\repros\30_Empty_CodeCoverage\XUnit.Tests\bin\Debug\net6.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll, embedded pdb without local source files, [/_/src/xunit.runner.visualstudio/obj/Release/netcoreapp2.1/xunit.runner.visualstudio.dotnetcore.testadapter.Version.cs]
       Done executing task "Coverlet.MSbuild.Tasks.InstrumentationTask".
```

This does not look connected to https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early for me.

**Comment by earloc** [comment]
switching to `coverlet.collector`does not seem to solve my issue.

**Comment by earloc** [comment]
When I fall back to coverlet.msbuild 2.5.1, everthing seems to be ok.

Starting with coverlet.msbuild 2.6.0 I get empty coverages. (this is no exhaustive analysis, just tested some combinations)

**Comment by earloc** [comment]
@MarcoRossignoli would you be so kind and have a look at this? Or should I better create another issue?

**Comment by earloc** [comment]
nevermind...my issue was related to https://github.com/coverlet-coverage/coverlet/issues/1322. Could fix it.

**Comment by daveMueller** [comment]
It is not really clear what the issue is here because of a pretty stale conversation. 
The source generator issue mentioned was fixed in the current nightly.
I would suggest to try out the current nightly as we changed the heuristic for detecting assemblies which
most likely also solves this problem ([consume nightly](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md#consume-nightly-build)). I'm closing this issue now but feel free to reopen.
