### ISSUE TITLE
Test Assembly included in coverage Reports

### ISSUE THREAD

**Issue by IanChamberlain-SMS** [coverlet-coverage/coverlet#1382]
I have a scenario where I have a test fixture class that inherits from a another test fixture class in a separate project within the same solution.
The project of the inherited test fixture class is erroneously included in the test coverage report.
i.e.
ThisClassTests.cs in project This.Tests.csproj contains tests for ThisClass.cs in This.csproj.
ThatClassTests.cs in project That.Tests.csproj contains tests for ThatClass.cs in That.csproj 
ThatClass.cs inherits from ThisClass.cs and ThatClassTests.cs inherits from ThisClassTests.cs.
In addition to coverage reports for This.csproj and That.csproj I also get coverage for That.Tests.csproj.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/113707239/190681611-479e5f77-19b4-42b4-8c3e-35656575d96f.png">

**Comment by daveMueller** [comment]
It seems like the algorithem that excludes test assemblies only excludes the currently executed test assembly. If this assembly has a reference to another test assembly it isn't excluded automatically. @MarcoRossignoli please correct me if I'm wrong.

But you can easily exclude it on your own by adding a filter expression. You can read more about the filter expressions [here](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#filters).

E.g. for the `msbuild` driver it would look like this:
```
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  /p:Exclude="[*]Integration.Domain.Tests.*" /p:ExcludeByAttribute="TestSDKAutoGeneratedCode"
```

**Comment by MarcoRossignoli** [comment]
@daveMueller is right, test assembly for coverlet is only the module specified for the testing all dependencies are instrumented. You should exclude with a filter.

**Comment by IanChamberlain-SMS** [comment]
The module being included contains tests. These tests are performed as well as being inherited to test subclasses conform to the expected behaviour of the superclass.

**Comment by IanChamberlain-SMS** [comment]
> dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  /p:Exclude="[*]Integration.Domain.Tests.*" /p:ExcludeByAttribute="TestSDKAutoGeneratedCode"
>

This doesn't work in Azure DevOps Pipelines as no coverage files are produced for any assembly. I've tried this without any filters at all and still got no coverage files.

This is what my working dotnet pipeline task looks like:
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration) --collect "XPlat Code Coverage"'
    testRunTitle: 'Development Unit Tests'

**Comment by petli** [comment]
@IanChamberlain-SMS When you use the vstest collector (which you should in CI, so that's good!) you need to put the filters in a runsettings file and specify the path to that file on the command line. There's documentation on that here:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration

**Comment by IanChamberlain-SMS** [comment]
This worked:
--configuration $(BuildConfiguration) --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*.Tests]*"

**Comment by MarcoRossignoli** [comment]
> Couldn't that just be the default setting? I expect that would fit with most peoples expectations.

Default filtering is tricky. I had issue fixing the filter for the user and at the moment we don't have a good default.
