### ISSUE TITLE
Output parameter is misleading

### ISSUE THREAD

**Issue by savornicesei** [coverlet-coverage/coverlet#1387]
Hi all,

I've been looking at how to generate coverage results in a custom path, with a custom file name. Pretty basic flow, I would say BUT:

1. coverlet.collector does not support custom file names and paths.= while coverlet.console and coverlet.msbuild provide such options
    - Why? 
2. `output` parameter of coverlet.console is not working as expected. Documentation just states that it represents "Output of the generated coverage report" - not sure if it should be a directory or a file path.  
So I did a quick test in LINQPad, on .net 5.0, with the relevant code from `coverlet.console`:
```
void Main()
{
	List<string> paths = new List<string>{
		@".\reports",  //relative dir
		@"C:\Temp\", //full dir path
		@"C:\Temp",  //full dir path
		@"C:\Temp\aaa", //full dir path
		@"C:\Temp\aaa.xml", //full file path
	};
	paths.ForEach(p => DeterminePath(p));
}

public void DeterminePath(string dOutput)
{
	string directory = Path.GetDirectoryName(dOutput);
	if (directory == string.Empty)
	{
		directory = Directory.GetCurrentDirectory();
	}
	else if (!Directory.Exists(directory))
	{
		Console.WriteLine("create dir");
		//Directory.CreateDirectory(directory);
	}

	string filename = Path.GetFileName(dOutput);
	filename = (filename == string.Empty) ? $"coverage.xml" : filename;
	filename = Path.HasExtension(filename) ? filename : $"{filename}.xml";

	string report = Path.Combine(directory, filename);
	Console.WriteLine($"Output dir '{dOutput}', report dir '{report}'");
}
```
This outputs the following:
```
Output dir '.\reports', report dir '.\reports.xml'
Output dir 'C:\Temp\', report dir 'C:\Temp\coverage.xml'
Output dir 'C:\Temp', report dir 'C:\Temp.xml'
Output dir 'C:\Temp\aaa', report dir 'C:\Temp\aaa.xml'
Output dir 'C:\Temp\aaa.xml', report dir 'C:\Temp\aaa.xml'
```
Observe that the 3rd and 4th results are incorrect given the intended input paths.

I would like to propose the following:

1. deprecate `--output` parameter
2. introduce 2 more parameters: 
    - `-d | --output-dir` : directory where the coverage file will be placed; always interpreted as a directory path in code
    -  `-n | --filename`: name of the coverage file. If more than one formats are given, the file extension will be the extension of the formats.

This would make it clear where the coverage results should be stored. And these 2 parameters should be available in all 3 coverlet packages so that they can be used in all scenarios.

Thank you.

Best,
Simo

**Comment by Bertk** [comment]
The behavior is documented in [GlobalTool.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md).

> The above command will write the results to the supplied path, if no file extension is specified it'll use the standard extension of the selected output format. To specify a directory instead, simply append a / to the end of the value.
>
> `coverlet <ASSEMBLY> --target <TARGET> --targetargs <TARGETARGS> --output "/custom/directory/" -f json -f lcov`
