### ISSUE TITLE
Report file

### ISSUE THREAD

**Issue by artcrespo** [coverlet-coverage/coverlet#1393]
Hi,

I would like to know the default values for the file path of the report file and also if there is any documentation regarding how to read those values. My purpose is to build CD/CI automation process which includes running test projects, check a minimum % for code coverage and then package and deploy nuget packages.

All of this being made with Powershell scripts.

Thank you very much

Rafael

**Comment by daveMueller** [comment]
Hi @artcrespo,

I think you can find all the answers to that in our documentation. For example a powershell script could look like this:
```powershell
#execute the test and collect coverage
dotnet test /p:CollectCoverage=true /p:Threshold=80 /p:CoverletOutputFormat=cobertura /p:CoverletOutput="./TestResults/"
#visualize coverage report with reportgenerator
reportgenerator "-reports:.\TestResults\coverage.cobertura.xml" "-targetdir:.\TestResults\Report"
#display report
& .\TestResults\Report\index.html
```

Here the test are executed, coverage is collected and checked against an threshold of 80%. If line, branch or method coverage is below the specified threshold, the execution will fail. The coverage reports will be saved in `./TestResults/`.
In addition I'm using the reportgenerator [https://github.com/danielpalme/ReportGenerator](https://github.com/danielpalme/ReportGenerator) to visualise the coverage report.
Detailed documentation can be found at [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md)  for the `msbuild` driver. 
For the global tool the documentation is here [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md).
For the collector it is  here [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md).
