### ISSUE TITLE
Running Coverage step in pipeline does not create anything

### ISSUE THREAD

**Issue by eliassal** [coverlet-coverage/coverlet#1398]
I have a stel in azure devops pipeline

I tried

> - task: DotNetCoreCLI@2
>       displayName: dotnet test
>       inputs:
>         command: 'test'
>         projects: '**/*.Tests.csproj'
>         arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
>         publishTestResults: true
> 
> # Publish code coverage report to the pipeline
>     - task: PublishCodeCoverageResults@1
>       displayName: 'Publish code coverage'
>       inputs:
>         codeCoverageTool: Cobertura
>         summaryFileLocation: $(Agent.TempDirectory)/*/coverage.cobertura.xml

as well as

> - task: DotNetCoreCLI@2
>   displayName: Test
>   inputs:
>     command: test
>     projects: '$(Parameters.TestProjects)'
>     arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage"'

I always get in the logs

> ##[warning]No code coverage results were found to publish

I have installed coverlet.console on the build machine
dotnet tool install --global coverlet.console

added reference to test projects as follows

> <PackageReference Include="coverlet.collector" Version="3.1.0">
>       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
>       <PrivateAssets>all</PrivateAssets>
>     </PackageReference>
> 

so what is missing?

**Comment by petli** [comment]
Is #1399 related to this issue, and maybe the cause of the problems you see here?

**Comment by eliassal** [comment]
Thanks peti, those are 2 different issues, the other one is I am wondering why it should in _temp. In any case, coverage file is created nowhere, I searched the whole working directory on the build agent
