### ISSUE TITLE
Azure devops pipeline - Why Coverage file is created in the temp directory of the build agent and not in System.DefaultWorkingDirectory

### ISSUE THREAD

**Issue by eliassal** [coverlet-coverage/coverlet#1399]
HI,
Can you please tell me why coverlet-coverage creates coverage files inside the _temp directory of the build agent and not in System.DefaultWorkingDirectory.
The _temp directory is a place for all working directories for all pipelines so if 2 pipelines run at the same time, and coverlet-coverage uses this directory, how concurrency/identification to which pipline the coverage file belong to which pipeline will happen?
Thanks

**Comment by petli** [comment]
The output directory is controlled by vstest, and can be configured in your runsettings file:

```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>./coverage/raw/unittests</ResultsDirectory>
  </RunConfiguration>

  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
            <!-- Your coverlet coverage here -->
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

If the files end up in an unexpected place check if you have any configuration there, otherwise this is likely just the current directory when the build is run in your build agent.

**Comment by eliassal** [comment]
> The output directory is controlled by vstest, and can be configured in your runsettings file:
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <RunSettings>
>   <RunConfiguration>
>     <ResultsDirectory>./coverage/raw/unittests</ResultsDirectory>
>   </RunConfiguration>
> 
>   <DataCollectionRunSettings>
>     <DataCollectors>
>       <DataCollector friendlyName="XPlat code coverage">
>         <Configuration>
>             
>         </Configuration>
>       </DataCollector>
>     </DataCollectors>
>   </DataCollectionRunSettings>
> </RunSettings>
> ```
> 
> If the files end up in an unexpected place check if you have any configuration there, otherwise this is likely just the current directory when the build is run in your build agent.

What is or where is the location of this file?

**Comment by eliassal** [comment]
So if I understand well, I should add a file , named something like

> test.runsettings

then include the xml text you mentioned, then added to the project repo in Azure Devops, then modify the step in azure pipeline by adding  a key 

> -s test.runsettings

to the test step?
Am I correct?

**Comment by eliassal** [comment]
Ok, I did all, added runsettings, 
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>./coverage/raw/unittests</ResultsDirectory>
  </RunConfiguration>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura,lcov</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>

```
updated pipeline but still getting


> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> **Data collection : Unable to find a datacollector with friendly name 'XPlat code coverage'.**
> Data collection : Could not find data collector 'XPlat code coverage'
> Results File: C:\Projects\agent-AzureDevOps2K20Update15\_work\_temp\salam_SALAM7_2022-10-26_15_32_23.trx
> 
> Passed!  - Failed:     0, Passed:    77, Skipped:     0, Total:    77, Duration: 312 ms - Benday.Presidents.UnitTests.dll (netcoreapp2.1)

**Comment by eliassal** [comment]
Yeeeees, you are the man :-) so many thanks. However, in spite of the fact that we indicated
 <ResultsDirectory>./coverage/raw/unittests</ResultsDirectory>

pipeline created reports in the workindirectory\_temp

![image](https://user-images.githubusercontent.com/8447864/198050225-5587f809-7448-494f-94a8-1be8e52d12e5.png)

**Comment by eliassal** [comment]
Also, I would like to benefit from this discussion as I have another issue with the coverage created. I during the build pipeline, I call the 3 tasks for analysing code with sonarQube
1 - Prepare SQ Analysis
2- Build
3-Test
4- Publish code coverage from $(Agent.TempDirectory)/*/coverage.cobertura.xml (which are now created)
5- Run SQ Code Analysis
6-SQ Publish Quality Gate Result

At the end when I visit the project in sonarqube, it seems that it does not get the coverage details? Should I add something for sonarqube?

Thanks again

**Comment by petli** [comment]
I guess (but don't know) that the `--results-directory` parameter you show in the test output might override what's in the runsettings file, and that's why you've been getting the output in that directory the whole time.

**Comment by eliassal** [comment]
OK, I will try to force this parameter. Any idea why sonarqube does not get the results?

**Comment by eliassal** [comment]
I tried 
--results-directory $(System.DefaultWorkingDirectory)/test/coverage/raw/unittests)
in the test step but fails with an error indicating that paramaeter expects 1 argument where as 2 were provided , very strange, I dont knnow where it sees the 2nd param!!!

**Comment by petli** [comment]
The issues you have now is something with how your build system runs your tasks, and I can't assist with that. For sonarqube you have to read their documentation on how to specify the coverage report path. You may find https://reportgenerator.io/ useful if you need to convert between report formats or if you have multiple coverlet output files that must be merged into a single report.

**Comment by eliassal** [comment]
Agree, I will check with Azure Devops community first, so ma,y thanks for your help
