### ISSUE TITLE
Coverlet.MSBuild stopped working after migration to MSBuild version 17.4.0

### ISSUE THREAD

**Issue by Serg046** [coverlet-coverage/coverlet#1407]
AppVeyor have recently updated MSBuild from 17.3.0 to 17.4.0 (might be related to .NET 7) and my job stopped working.

Successful build (2 days ago): https://ci.appveyor.com/project/Serg046/autofake/builds/45349147
Failing one from today: https://ci.appveyor.com/project/Serg046/autofake/builds/45359072

It just doesn't generate the files. However, it is still working fine locally on 17.2.0.

**Comment by Serg046** [comment]
Seems related to https://github.com/coverlet-coverage/coverlet/issues/1391

**Comment by petli** [comment]
@Serg046 It likely is the same issue, so I close this as a duplicate to focus the followup on that issue.
