### ISSUE TITLE
no report generated after upgrade to net7 

### ISSUE THREAD

**Issue by marcelbeeker** [coverlet-coverage/coverlet#1408]
After upgrading to net7 the dotnet test command doesn't generate any reports. I'm using this command: dotnet test <name of the solution file> /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /a:CoverletOutput=./MyCoverage/.

It works perfectly in .NET6 and previous versions. Unfortunately not in .NET7. Does anybody as a solution for this

**Comment by mikes-gh** [comment]
I just stumbled open this.  Was looking all around at coverlet codecov and finally realised the thing that changed was the sdk.  Its a big deal for us as we have a popular library and our PRs no longer have code coverage

**Comment by petli** [comment]
See #1391, this is a bug in dotnet. Various workarounds are discussed in that issue.

**Comment by mikes-gh** [comment]
Thanks @petli after reviewing my logs I can see it was when we started using SDK 7.0.100.  Thanks for the library 🚀  With the workarounds its all working again.
