### ISSUE TITLE
Collector Including Test Namespace in Coverage Despite RunSettings

### ISSUE THREAD

**Issue by kenziewritescode** [coverlet-coverage/coverlet#1418]
When running `dotnet test Solution.sln --logger trx --results-directory ./TestResults --collect:"XPlat Code Coverage" `, we are getting a single test project reporting in the coverage reports. We have other pipelines that leverage the msbuild integration that don't have this issue, but we're moving to the collector because of known issues.

Version:
"coverlet.collector" Version="3.2.0"

The project contains the same package references as other projects. Additionally, we have runsetting exclusions for auto generated code and the IncludeTestAssembly is false.

**Comment by daveMueller** [comment]
In general this should work. You have to add `coverlet.collector` to every test project in your solution you want to collect coverage from. Then there should be some randomly named folders (guid string) within the `./TestResults` directory where each one contains a report for a project.

**Comment by kenziewritescode** [comment]
The coverlet collector is a part of the project and is collecting coverage. However, the collector is reporting coverage on the test assembly itself. And only a single file. This does not occur for us when using the msbuild integration. But no other test assemblies are incorrectly included. All other reports generated are correct.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by daveMueller** [comment]
OK now I understand. Without having the actual assembly it's hard to tell why it's missed by the exclusion. But can't you just add it in your runsettings file? Something like:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>          
          <Exclude>[coverlet.*.tests?]*</Exclude>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

**Comment by kenziewritescode** [comment]
I realized now this is still open. We did add a specific exclusion, but it's not respected. https://github.com/coverlet-coverage/coverlet/issues/1489 I had forgotten we had this pending, but I closed it and added more information.

**Comment by Bertk** [comment]
related #1503
