### ISSUE TITLE
Exclude by Base class \ Interface?

### ISSUE THREAD

**Issue by gdoron** [coverlet-coverage/coverlet#1419]
We have many projects with EF migrations and no one is using the `Down` Method to revert a migration, so we don't care of covering it with UTs.

Ideally it would be best to exclude only the `Down` method, but assuming that is impossible without decorating each method with `[ExcludeFromCodeCoverage]`, we would like to ignore all classes deriving from the BaseClass `Microsoft.EntityFrameworkCore.Migrations.Migration`.

Is it possible with coverlet?

**Comment by petli** [comment]
It's not possible now, but for migrations specifically you can try to use `Exclude` to exclude them by the namespace they end up in, or `ExcludeByFile` by the directory: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage

**Comment by gdoron** [comment]
Yes, this what we ended up doing:
`<ExcludeByFile>**/*.DataAccess/*Migrations/*.cs,...`
I was wondering if there is a better and more explicit way for that (and hopefully only ignore specific a method though assumed this one is impossible).

**Comment by Bertk** [comment]
> Yes, this what we ended up doing: `<ExcludeByFile>**/*.DataAccess/*Migrations/*.cs,...` I was wondering if there is a better and more explicit way for that (and hopefully only ignore specific a method though assumed this one is impossible).

Solution available. Issue closed.
