### ISSUE TITLE
/p:CoverletOutputFormat=cobertura only produces the coverlet coverage.json

### ISSUE THREAD

**Issue by ricardo-noyolalozano** [coverlet-coverage/coverlet#1425]
When I run the 'dotnet test --% /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura' in one of my solutions I get the cobertura format but in another solution I only get the coverlet format. What could I be doing wrong?

**Comment by petli** [comment]
Is the problematic solution using .NET 7? See #1391 for an issue tracking an error in the .NET 7.0.0 SDK which stops the coverlet.msbuild driver from getting the options. There's workarounds in that issue, and you can also consider switching to the coverlet.collector driver which isn't affected: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by daveMueller** [comment]
Hi, the issue @petli mentioned was fixed by the microsoft guys with sdk 7.0.101 that was released last week https://github.com/microsoft/vstest/issues/4014. I just checked it with a repro from another related issue and it works fine. Please give it a try again.

**Comment by daveMueller** [comment]
I close this as the external issue is fixed. Feel free to reopen.

**Comment by ricardo-noyolalozano** [comment]
Could it be the fact that one is running the Microsoft testing framework and one is running XUnit? The former being the one that creates the cobertura file.
