### ISSUE TITLE
Instrumentation failure after upgrade to .NET 7

### ISSUE THREAD

**Issue by psiservices-dbrink** [coverlet-coverage/coverlet#1432]
I know this particular issue is out of your hands, but after upgrading to .NET 7 a project that depends on both aspnet/mvc and swashbuckle libraries no longer generated code coverage data.  The coverage was properly generated when targetting .NET 6.  None of the [recommended fixes](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#failed-to-resolve-assembly-during-instrumentation
) worked except for explicitly copying Microsoft.Extensions.Logging.Abstractions.dll to the unit test output folder.  

Simple repo in case it helps troubleshoot.  
https://github.com/psiservices-dbrink/CoverletInstrumentationFailure

**Comment by MarcoRossignoli** [comment]
fixed in https://github.com/coverlet-coverage/coverlet/pull/1449
