### ISSUE TITLE
Clarify how to supply format on the command line in the documentation

### ISSUE THREAD

**Issue by silkfire** [coverlet-coverage/coverlet#1441]
The [documentation](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#default-option-if-you-dont-specify-a-runsettings-file) specifies that the only option that one can provide without using a dedicated `coverlet.runsettings` file is the **Format** option. Unfortunately the documentation fails to detail exactly how to use this option on the command line.

Can this be amended to the section above the options table, please?

**Comment by daveMueller** [comment]
I think you misunderstood this. The documentation says that the only option that has a default value is the format option. In the first place there is no other way to change the format without a runsettings file. 
An alternative would be to pass the parameter with xml flat syntax which is described here: [https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline)

**Comment by silkfire** [comment]
This is actually not true. According to the [official documentation](https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#code-coverage-formats) it can be provided as follows:

`dotnet test --collect:"Code Coverage;Format=Cobertura"`

The current wording

> Results format in which coverage output is generated. Default format is cobertura. Supported format lcov, opencover, cobertura, teamcity, json (default coverlet proprietary format)

is misleading as it lists a series of possible options making the user believe these can be specified somehow without using a runsettings file.

**Comment by daveMueller** [comment]
OK so the documentation you are refering to is not `coverlet`. It is the data collector build in `vstest` (different collector name). 
**BUT**
I digged around a bit and found out that this is the default behavior of `vstest` datacollector base class we derive from. This can be seen here [https://github.com/microsoft/vstest/blob/main/src/vstest.console/Processors/CollectArgumentProcessor.cs#L247-L250](https://github.com/microsoft/vstest/blob/main/src/vstest.console/Processors/CollectArgumentProcessor.cs#L247-L250).
So even though this isn't officially documented by the `vstest` guys ([doc](https://github.com/Microsoft/vstest-docs/blob/main/docs/extensions/datacollector.md)) it is working. So you basically can pass parameters like:
```
dotnet test --collect:"XPlat Code Coverage;Format=json;Hello=world"
```

Do we want to add this to our documentation even though it isn't officially documentation by `vstest`? What do you think? @MarcoRossignoli @petli @tonerdo 

And I admit even without this the current wording is a bit misleading. I will change it once we have a decision to the question above.

**Comment by silkfire** [comment]
Interesting finds there and thanks for clarifying the source of the confusion. Documentation should strive to be extensive and correct as possible, in my opinion.

**Comment by fhnaseer** [comment]
> I digged around a bit and found out that this is the default behavior of `vstest` datacollector base class we derive from. This can be seen here https://github.com/microsoft/vstest/blob/main/src/vstest.console/Processors/CollectArgumentProcessor.cs#L247-L250. So even though this isn't officially documented by the `vstest` guys ([doc](https://github.com/Microsoft/vstest-docs/blob/main/docs/extensions/datacollector.md)), it is working. So you basically can pass parameters like:
> 
> ```
> dotnet test --collect:"XPlat Code Coverage;Format=json;Hello=world"
> ```

This change adds/updates elements inside collector element in the runsettings file. It was added to specify output format without using a runsettings or overriding runsettings file for MS code coverage scenario.
```
dotnet test --collect:"Code Coverage;Format=Cobertura"

<DataCollectors>
  <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0">
    <Configuration>
      <Format>Coverage</Format>
```

However, the implementation is generic and can be used by others as well. So, coverlet can also use similar command to specify format.

**Comment by silkfire** [comment]
The wording is much clearer now and in-tune with the official documentation. I really appreciate it, thank you.
