### ISSUE TITLE
Coverlet not showing code coverage

### ISSUE THREAD

**Issue by rtmyo** [coverlet-coverage/coverlet#1443]
When trying to run this through our AWS CI/CD Pipeline using the coverlet global tool using this command:
`coverlet ~path/Tests.dll --verbosity "detailed" --target "dotnet" --targetargs "test ~path/Tests.csproj --no-build --filter FullyQualifiedName~Tests" -f=json  -o="./Results/coverage.json"`

We get the following result:

Calculating coverage result...
Generating report './Results/coverage.json'
+--------+------+--------+--------+
| Module | Line  | Branch  | Method  |
+--------+------+--------+--------+

+---------+------+--------+---------+
|               | Line  | Branch  | Method  |
| +-------+------+--------+----------+
| Total      | 0%    | 0%        | 0%          |
| +-------+------+--------+----------+
| Average | 0%   | 0%        | 0%          |

This doesn't happen when it's run locally.  We're using these tools globally:
dotnet-sonarscanner --version  5.8.0
coverlet.console --version 3.2.0

**Comment by rtmyo** [comment]
@petli I get no warning message. Haven't used vtest yet not sure how to filter using vtest.

**Comment by rtmyo** [comment]
@petli Yes that's correct I don't get any warning and the Hit file doesn't appear on the Console

**Comment by rtmyo** [comment]
@petli We're running this in the context of AWS Code Build and in other projects it has been working as expected. 
We've ran this locally in windows and in linux and it has returned the coverage files. I guess my question would be if that known issue that you linked me to is only happening when using vstest? Because we're not using that we're using the coverlet global tool. Is there some way we can analyze this error? We've changed the verbosity to detailed but haven't got anything useful.
I would appreciate the help.

**Comment by petli** [comment]
@rtmyo, it's the opposite, the problem in CI builds affects the standalone tool and the msbuild driver, not the vstest collector. It The issue depends on the amount of code to cover, so if a project is large it may run in this in some CI environments where smaller projects work fine.

My question was if you can try the collector and see if it helps. It is also generally an easier way to use coverlet since you can just run `dotnet test --collect:"XPlat Code Coverage"`, instead of going the roundabout way of running dotnet test through the global tool.

**Comment by rtmyo** [comment]
@petli But now reading further the `dotnet test --collect:"XPlat Code Coverage" `doesn't allow to merge with other json coverage files and that's something that we need.

**Comment by petli** [comment]
You can solve that by merging in a separate step after running the tests using https://reportgenerator.io/ .

**Comment by rtmyo** [comment]
@petli That's not going to work for my case because report generator merges files into Cobertura files and I need opencover because I'm sending those files to Sonarqube.

**Comment by petli** [comment]
Good news then: ReportGenerator can produce Sonarqube's generic code coverage format. :)  See https://reportgenerator.io/usage where you can build up a command line suitable for your environment.

The project I work on uses that combination of coverlet.collector, ReportGenerator and SonarQube.  We aalso let ReportGenerator produce status for TeamCity and HTML reports at the same time (as an alternative to SonarQube).

**Comment by Bertk** [comment]
@rtmyo Hi, could you please update the issue or close it. Thanks.
