### ISSUE TITLE
Support .coverage format

### ISSUE THREAD

**Issue by ghost** [coverlet-coverage/coverlet#1445]
Support Visual Studio's .coverage format. This is critical to show Diff coverage in PR's in Azure Dev ops. I wish, ADO supported more formats for PR diff but they don't. Developing a new format for coverlet may be an easier way to achieve this goal. I'm open to contributing this, if somebody can guide me!

**Comment by daveMueller** [comment]
@MarcoRossignoli Any idea why `coverlet`doesn't have support for this? Can the `vstest` team provide a specification of `.coverage` format?

**Comment by jakubch1** [comment]
@abhadauria1 could you please add support for cobertura format in Azure DevOps? You can use our packages to merge and load data regarding cobertura reports.

**Comment by Bertk** [comment]
Code Coverage in Azure DevOps pipeline is also available using 

* extension [ReportGenerator](https://marketplace.visualstudio.com/items?itemName=Palmmedia.reportgenerator)
* task [PublishCodeCoverageResults@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines)

example: https://github.com/Bertk/arcade-light/blob/main/eng/azuredevops/pipelines/steps/CoverageResults.yml

**Comment by Bertk** [comment]
see: 
- https://github.com/microsoft/codecoverage
- https://learn.microsoft.com/de-de/dotnet/core/additional-tools/dotnet-coverage

> **Microsoft code coverage functionality is closed source.**

The details for the coverge format is not available for the puplic.
