### ISSUE TITLE
Cannot access the file because it is being used by another process on Windows

### ISSUE THREAD

**Issue by seesharper** [coverlet-coverage/coverlet#1454]
Hi :)

We  spent the last couple of days hunting down a weird bug when running coverlet collector on windows.

The problem as it turned out came down to that we had an assembly named `GatCollector` and that somehow created an error that caused the file `GatCollector.dll` to be locked. 

We suspect that there is some pattern matching on the assembly names causing the `GatCollector.dll` assembly to be considered a part of CoverLet or something similar. 

In our case, the workaround was to rename the assembly so that it did NOT contain the word `Collector`.

**Comment by daveMueller** [comment]
I'm closing this as it is a duplicate. Feel free to reopen.
