### ISSUE TITLE
Coverage incorrectly reported as 0% for integration tests

### ISSUE THREAD

**Issue by TheMagnificent11** [coverlet-coverage/coverlet#1461]
I have a open source project that is using Coverlet to calculate test coverage.

The coverage seems to work correctly for unit tests.

However, coverage doesn't get reported for integration tests.

The integration tests I'm running use `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory` to bring up a ASP.Net Web API application in memory and then uses a HTTP client to make API calls to this in-memory application.

However, none of the code executed is being included in the coverage.  It doesn't even get the top-level controllers that get hit when the HTTP request is executed.

See [this pull request](https://github.com/TheMagnificent11/Lewee/pull/5#issuecomment-1483148215) for more details.

The `dotnet test` command is in the [GitHub Action](https://github.com/TheMagnificent11/Lewee/pull/5/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f) (`dotnet test ./Lewee-CI.sln --configuration Release --no-build --collect "XPlat Code Coverage" --results-directory ./coverage`).

**Comment by mklpanasiuk** [comment]
Hello @TheMagnificent11. I'm not the developer of Coverlet, but I faced with the same issue while worked with WebApplicationFactory. The root cause in my case of missing coverage results was OneTimeTearDown method (global one), which disposed WebApplicationFactory and their http client. A solution for us was just to remove disposing of them from OneTimeTearDown =)

**Comment by TheMagnificent11** [comment]
> Hello @TheMagnificent11. I'm not the developer of Coverlet, but I faced with the same issue while worked with WebApplicationFactory. The root cause in my case of missing coverage results was OneTimeTearDown method (global one), which disposed WebApplicationFactory and their http client. A solution for us was just to remove disposing of them from OneTimeTearDown =)

@mklpanasiuk my `WebApplicationFactory`  doesn't implement `IDisposable`, it's very simple.

```cs
public class RestaurantWebApplicationFactory : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Testing");
    }
}
```

Also, I don't have to dispose of the HTTP client because each tests creates and disposes of it.  I've got a common method for executing HTTP requests.

```cs
protected async Task<HttpResponseMessage> HttpRequest(HttpMethod method, string apiPath)
{
    using (var request = new HttpRequestMessage(method, apiPath))
    using (var httpClient = this.factory.CreateClient())
    {
        return await httpClient.SendAsync(request);
    }
 }
```

Maybe my issue is related to how I'm using my `WebApplicationFactory` as a constructor dependency for my implementation of `Xunit.IClassFixture`.

Are you using `Xunit`?

**Comment by TheMagnificent11** [comment]
> Hello @TheMagnificent11. I'm not the developer of Coverlet, but I faced with the same issue while worked with WebApplicationFactory. The root cause in my case of missing coverage results was OneTimeTearDown method (global one), which disposed WebApplicationFactory and their http client. A solution for us was just to remove disposing of them from OneTimeTearDown =)

I implemented `IDisposable` on base test class that has a constructor dependency on my implementation of `WebApplicationFactory` and disposed of it.

Also, each of my tests creates and disposes of the HTTP client.  All the tests use the following method to make HTTP requests.

```cs
protected async Task<HttpResponseMessage> HttpRequest(HttpMethod method, string apiPath)
{
    using (var request = new HttpRequestMessage(method, apiPath))
    using (var httpClient = this.factory.CreateClient())
    {
        return await httpClient.SendAsync(request);
    }
}
```

However, I still get 0% coverage for my integration tests 🤷 

I wonder if my issue has anything to do with the fact that I'm implementing `Xunit.IClassFixture` for my base test class.

Are you using `Xunit`?

**Comment by TheMagnificent11** [comment]
#901 seems to be related/duplicate of this issue

**Comment by TheMagnificent11** [comment]
I created a more minimum implementation of integration test using `WebApplicationFactory` [here](https://github.com/TheMagnificent11/coverlet-experiment).

`Coverlet` correctly calculates coverage, even when I added a `await Task.Delay(TimeSpan.FromSeconds(3))` to the API controller to slow it down.

So I'm not sure why the coverage does work in project from my original comment 🤷

**Comment by MarcoRossignoli** [comment]
Can you try to take a log and verify that all expected dll are instrumented? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

**Comment by TheMagnificent11** [comment]
Here's my run settings file.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector
		  assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null"
          friendlyName="XPlat Code Coverage"
          enabled="True"
          codebase="coverlet.collector.dll" />
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>
```

And here are the logs.

[log.datacollector.23-03-31_21-18-58_26559_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121228/log.datacollector.23-03-31_21-18-58_26559_1.txt)
[log.datacollector.23-03-31_21-18-58_40758_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121229/log.datacollector.23-03-31_21-18-58_40758_1.txt)
[log.datacollector.23-03-31_21-19-06_23002_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121230/log.datacollector.23-03-31_21-19-06_23002_1.txt)
[log.datacollector.23-03-31_21-19-16_04337_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121231/log.datacollector.23-03-31_21-19-16_04337_1.txt)
[log.host.23-03-31_21-19-00_72381_10.txt](https://github.com/coverlet-coverage/coverlet/files/11121232/log.host.23-03-31_21-19-00_72381_10.txt)
[log.host.23-03-31_21-19-01_36061_10.txt](https://github.com/coverlet-coverage/coverlet/files/11121233/log.host.23-03-31_21-19-01_36061_10.txt)
[log.host.23-03-31_21-19-08_13813_10.txt](https://github.com/coverlet-coverage/coverlet/files/11121234/log.host.23-03-31_21-19-08_13813_10.txt)
[log.host.23-03-31_21-19-21_76198_7.txt](https://github.com/coverlet-coverage/coverlet/files/11121235/log.host.23-03-31_21-19-21_76198_7.txt)
[log.txt](https://github.com/coverlet-coverage/coverlet/files/11121236/log.txt)

**Comment by MarcoRossignoli** [comment]
You don't need to set the `InProcDataCollector` pls remove it.

**Comment by TheMagnificent11** [comment]
@MarcoRossignoli I updated the settings and ran it again.

Here's the updated settings.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Here are the new logs.

[log.txt](https://github.com/coverlet-coverage/coverlet/files/11121538/log.txt)
[log.host.23-03-31_22-00-10_35130_9.txt](https://github.com/coverlet-coverage/coverlet/files/11121534/log.host.23-03-31_22-00-10_35130_9.txt)
[log.host.23-03-31_22-00-11_09346_10.txt](https://github.com/coverlet-coverage/coverlet/files/11121535/log.host.23-03-31_22-00-11_09346_10.txt)
[log.host.23-03-31_22-00-17_67089_10.txt](https://github.com/coverlet-coverage/coverlet/files/11121536/log.host.23-03-31_22-00-17_67089_10.txt)
[log.host.23-03-31_22-00-31_55099_7.txt](https://github.com/coverlet-coverage/coverlet/files/11121537/log.host.23-03-31_22-00-31_55099_7.txt)
[log.datacollector.23-03-31_22-00-08_62380_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121531/log.datacollector.23-03-31_22-00-08_62380_1.txt)
[log.datacollector.23-03-31_22-00-15_69739_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121532/log.datacollector.23-03-31_22-00-15_69739_1.txt)
[log.datacollector.23-03-31_22-00-25_34881_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121533/log.datacollector.23-03-31_22-00-25_34881_1.txt)
[log.datacollector.23-03-31_22-00-07_79695_1.txt](https://github.com/coverlet-coverage/coverlet/files/11121530/log.datacollector.23-03-31_22-00-07_79695_1.txt)

**Comment by TheMagnificent11** [comment]
@MarcoRossignoli I've created a [repository](https://github.com/TheMagnificent11/coverlet-experiment) with a more minimal replication of the issue.

The `readme` explains how to replicate the issue (there is a `PowerShell` script that runs the appropriate `dotnet test` command and the generates a coverage report using the Report Generator dotnet tool (it also creates the logs in the `./coverage-logs` directory).

My hypothesis is that using an implementation of `Xunit.ICollectionFixture<T>` to "reset" a database before each test is what causes the issue (there is a very minimal `Sqlite` database).

Here are the logs I got on my laptop.

[log.datacollector.23-04-01_15-39-28_26818_1.txt](https://github.com/coverlet-coverage/coverlet/files/11128541/log.datacollector.23-04-01_15-39-28_26818_1.txt)
[log.datacollector.23-04-01_15-39-28_90615_1.txt](https://github.com/coverlet-coverage/coverlet/files/11128542/log.datacollector.23-04-01_15-39-28_90615_1.txt)
[log.host.23-04-01_15-39-29_10233_7.txt](https://github.com/coverlet-coverage/coverlet/files/11128543/log.host.23-04-01_15-39-29_10233_7.txt)
[log.host.23-04-01_15-39-29_84693_7.txt](https://github.com/coverlet-coverage/coverlet/files/11128544/log.host.23-04-01_15-39-29_84693_7.txt)
[log.txt](https://github.com/coverlet-coverage/coverlet/files/11128545/log.txt)

**Comment by TheMagnificent11** [comment]
@MarcoRossignoli was that repository that contained more minimal replication of my issue useful?

**Comment by MarcoRossignoli** [comment]
I didn't have time to check yet, I'm pretty busy this period.

let's see if @daveMueller @petli has got some fresh ideas.

**Comment by TheMagnificent11** [comment]
I feel rather embarrassed.

I the tests that weren't getting coverage (in both my original repository and the experiment repository) were using [BDDfy](https://github.com/TestStack/TestStack.BDDfy), but I wasn't adding the `BDDfy()` method call at the end of my test 🤦 

Sorry about the hassle.
