### ISSUE TITLE
coverlet.collector produces empty report when BuilGenerator is referenced

### ISSUE THREAD

**Issue by jvmlet** [coverlet-coverage/coverlet#1464]
`coverlet.collector` produces empty report when [BuilGenerator ](https://github.com/MelGrubb/BuilderGenerator) is referenced (https://github.com/MelGrubb/BuilderGenerator/issues/22)

**Comment by jvmlet** [comment]
@petli , thanks for quick response, yes , with `6.0.0-preview.7.gd93613826b` I'm getting the expected coverage

**Comment by daveMueller** [comment]
I'm closing this as it seems to be resolved in the upcoming version. Feel free to reopen.
