### ISSUE TITLE
How to execute XUnit Test Suite?

### ISSUE THREAD

**Issue by agray** [coverlet-coverage/coverlet#1469]
Does Coverlet support running XUnit Selenium Test suites?

https://github.com/Sauceforge/Saucery/actions/runs/4713229931/jobs/8359042382

Am I doing something stupid?

Works for NUnit but failing for the XUnit suite.

**Comment by MarcoRossignoli** [comment]
Coverlet can cover whatever test project and reafferences used if .NET assemblies, so I think it's supported by design. Clearly if there're native or non .NET Assembly component coverlet cannot collect nothing.
