### ISSUE TITLE
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by behroozAmrj** [coverlet-coverage/coverlet#1470]
The active test run was aborted. Reason: Test host process crashed: Unhandled Exception:Unhandled Exception:Unhandled System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Unhandled Exception: System. AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
Passed! - Failed:
0, Passed: 111, Skipped:
0, Total:
111, Duration: 22 m 49 g - Test.dll (net48) 
Test Run Aborted with error System. Exception: One or more errors occurred.
-> System. Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host . .
---> System. Exception: An existing connection was forcibly closed by the remote host. at System.Net. Sockets. NetworkStream. Read (Span '1 buffer)
- - - End of inner exception stack trace ---at System. Net. Sockets. NetworkStream. Read (Span' 1 buffer) at System. Net. Sockets. NetworkStream. ReadByte () at System. IO. BinaryReader. Read7BitEncodedInt () at System. IO. BinaryReader. ReadString ()
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable() at Microsoft. VisualStudio. TestPlatform. CommunicationUtilities. IcClientExtensions.MessageLoopAsync(IcpClient client,
[ICommunicationChannel channel, Action'1 errorHandler, CancellationToken cancellationToken)
--- End of inner exception stack trace

**Comment by MarcoRossignoli** [comment]
This issue should be opened here https://github.com/microsoft/vstest looks unrelated to the coverage
