### ISSUE TITLE
Documentation clarification...

### ISSUE THREAD

**Issue by kabua** [coverlet-coverage/coverlet#1482]
In the `readme.md`, the first paragraph states:

> ... It works with **.NET Framework on Windows** ...

It works with `.NET Framework` that's great!

However, under the Quick Start section, the documentation then states
> Coverlet supports only SDK-style projects

Meaning what exactly?

Only the test project itself must be a SDK-style project? 
Or 
Any and all DLLs/Execs under test must also have been created from a SDK-style project?

**Comment by Bertk** [comment]
We do not use classic project style at all please use latest release and test project with SDK-style test project.

test/coverlet.tests.projectsample.netframework/coverlet.tests.projectsample.netframework.csproj

**Comment by Bertk** [comment]
Please try the test only SDK style project file approach. 

By the way, in the past I used [MSBuild.SDK.SystemWeb SDK](https://www.nuget.org/packages/MSBuild.SDK.SystemWeb) for this migration. The SDK has some [limitations](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/tree/main/docs#known-limitations) but we did this transition successfully with a small effort.

Microsoft has also a new version of [upgrade assistant](https://www.nuget.org/packages/upgrade-assistant/) which supports the migration.

<img width="404" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/628f0c06-8406-40ac-ba1d-2568b676bd4e">
