### ISSUE TITLE
CoverletSourceRootsMapping file does not respect configured OutDir

### ISSUE THREAD

**Issue by BaZzz01010101** [coverlet-coverage/coverlet#1485]
I configured the `$(OutDir)` for all my projects using **Directory.Build.props** located in the root solution folder. All the artifacts now are created in this folder except the **CoverletSourceRootsMapping** file. This file still created in `$(ProjectDir)\bin\$(Configuration)\$(TargetPlatform)` folder.

Is there a way to make it create in the `$(OutDir)` ?

**Comment by Bertk** [comment]
Please try VSTest.Console.exe option `ResultsDirectory` see

https://learn.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2022

**Comment by Bertk** [comment]
Solved with PR #1559 which uses .NET 8.0 SDK [Artifacts output layout](https://learn.microsoft.com/en-us/dotnet/core/sdk/artifacts-output).
