### ISSUE TITLE
Integrate into dotnet run

### ISSUE THREAD

**Issue by alexl0gan** [coverlet-coverage/coverlet#149]
Would it be possible to integrate the coverage collection into dotnet build. I have integration tests that run on a server so would like to run

`dotnet run IntegrationServer /p:CollectCoverage=true`

and get a coverage report.

**Comment by JDeuce** [comment]
I tried to do something like:

    coverlet  path/to/assembly.dll --target "dotnet" --targetargs "run --project X --no-build" 

With some trickery to shutdown the server after doing a run. I tried just killing dotnet, and also a dummy request to gracefully shut down the server in case the kill was preventing coverage from collecting.

But the coverage would never show meaningful output.

**Comment by alexl0gan** [comment]
Why would it not show meaningful output? We do something similar in javascript where we use Istambul to instrument the source before starting a web server, and collect coverage on shutdown.

I tried something similar to no avail

**Comment by JDeuce** [comment]
I just mean it would be like all zeroes or something, not showing me the actual expected code coverage for the run.

This pull mentions similar functionality https://github.com/tonerdo/coverlet/pull/174

**Comment by MarcoRossignoli** [comment]
@alexl0gan why don't create a simple test project/case that start integration test and simply use `dotnet test`?

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
