### ISSUE TITLE
Zero code coverage even though there are unit tests

### ISSUE THREAD

**Issue by padmanabhanp12** [coverlet-coverage/coverlet#1496]
We are seeing a weird issue where code is covered properly but code coverage is showing a zero on some lines.

![image](https://github.com/coverlet-coverage/coverlet/assets/138065970/8b1fef03-2698-48f3-b957-d948b21950c9)

The report shows line 187 to 195 is not covered while line 197 is covered. Line 197 can not be reached without passing through 187 to 195

Please help!!

**Comment by Bertk** [comment]
Hi,

please provide more details.

- are you using coverlet.collector or coverlet.console or coverlet.msbuild package
- which coverlet version did you use for test execution
- …

Please run test enabling verbosity e.g. `dotnet test --logger "console;verbosity=detailed"`

You find also some hints here: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md

**Comment by Bertk** [comment]
@padmanabhanp12
 Hi, could you please close or update the issue.

**Comment by Bertk** [comment]
Issue closed (insufficient information).
