### ISSUE TITLE
Coverlet.MSBuild occasionally fails on upgrade to 6.0.0

### ISSUE THREAD

**Issue by J-Biers** [coverlet-coverage/coverlet#1500]
Hi there!

I'm working on updating the dependencies for my project, which has several repos for individual microservices. We've been using Coverlet.MSBuild version 2.9.0 and it's been working great. However, when I go to upgrade to version 6.0.0 (or any version past 2.9.0 for that matter) I end up with an empty coverage file. This happens in some of my repositories but not others.

I looked at the known issues and think this is most likely due to vstest killing the process, since I could see the testing taking longer in the repos where the upgrade failed. So I'm trying to set up coverlet.collector, but I'm running into the same issue and get an empty coverage file. This happens both locally and on my CI pipelines. I've created a runsettings file according [to this post](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#upgrade-coverletcollector-to-version--100), but I'm not sure if I need additional setup, or where to go from here.

Any help would be greatly appreciated!

**Comment by Bertk** [comment]
Hi,
did you run the test from `publish` folder? Please also try the [nightly build nuget packages](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly).

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-integration-with-vstest-aka-visual-studio-test-platform

**Comment by Bertk** [comment]
Please try the pre-view version and share your experience. 
https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly
