### ISSUE TITLE
coverlet msbuild + ReportGenerator: Empty reports

### ISSUE THREAD

**Issue by Schinwinkwinsky** [coverlet-coverage/coverlet#1501]
Hi, I'm trying to use coverlet msbuild and ReportGenerator to generate test reports of my solution. 

I'm following the documentations at:
- https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md
- https://github.com/danielpalme/ReportGenerator

My solution csproj is:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.collector" Version="6.0.0">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="coverlet.msbuild" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="ReportGenerator" Version="5.1.23" />
  </ItemGroup>
  <Target Name="GenerateHtmlCoverageReport" AfterTargets="GenerateCoverageResultAfterTest">
	<ReportGenerator
		ReportFiles="@(CoverletReport)" 
		TargetDirectory="./coverage-report"/>
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\src\School.WebAPI\School.WebAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
```

When I run the following command:

`dotnet test /p:CollectCoverage=true`

I got the results on terminal:

![image](https://github.com/coverlet-coverage/coverlet/assets/13337108/2a7ab608-d061-442e-96aa-b766fa2c6a23)

And the following files are added to test project.
![image](https://github.com/coverlet-coverage/coverlet/assets/13337108/29bdbc7e-f0f1-4f2b-abdf-d5b68fb1482b)

I know there's no test yet. I'm still setting the coverlet and ReportGenerator. But notice the result on terminal show all modules (4 assemblies/namespaces) of my solution. But the result report is empty. 

![image](https://github.com/coverlet-coverage/coverlet/assets/13337108/c1d3700b-0842-485e-8a61-7c7f85b46c07)

What am I doing wrong?

My solution is available at: https://github.com/Schinwinkwinsky/School

**Comment by Schinwinkwinsky** [comment]
I suspect that's because reportgenerator doesn't work with json files. It worked when I used the following command:

`dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura`

**Comment by Bertk** [comment]
@Schinwinkwinsky Hi, did you already resolve this issue? Could you please close it or update the current status.
