### ISSUE TITLE
coverage not reported when some tests fail

### ISSUE THREAD

**Issue by nreddipalle** [coverlet-coverage/coverlet#1509]
I am using following command

dotnet test "$(Build.SourcesDirectory)/Tests/ResourcePlanning.Tests/ResourcePlanning.Tests.csproj" --logger "trx;logfilename=resourceplanningtests-testResults$count.trx" --results-directory "$(Agent.TempDirectory)" --configuration Release --no-build --verbosity minimal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(Agent.TempDirectory)\TestResults\Coverage\ResourcePlanningTests-TestResults.opencover.xml

On successful run, it generates code coverage fine.. but some tests are flaky and fails sometimes and pass on rerun.. 
so when rerun codecoverage is reported only for the flaky tests that passed on second run..

so during 1st run of 3000 tests if 2900 pass and 100 fail.. dotnet test command doesn't generate code coverage
during rerun of 100 tests when all 100 pass then it generates code coverage but only for 100 tests

How to achieve proper code coverage in this case? Thanks.

**Comment by Bertk** [comment]
Hi,
are you using coverlet.msbuild package? 
There is a [known issue](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early)

**Comment by Bertk** [comment]
This is not a coverlet issue and I think this is related to Azure DevOps pipeline and retry failed tests scenario. 

I guess there are 2 options:
- disable `rerunFailedTests` and always run all tests
- merge the coverage results for partial tests [**MergeWith** parameter](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Examples/MSBuild/MergeWith/HowTo.md)
