### ISSUE TITLE
Nightly build fails

### ISSUE THREAD

**Issue by daveMueller** [coverlet-coverage/coverlet#1511]
Our nightly builds are failing since 4.Juli.

![grafik](https://github.com/coverlet-coverage/coverlet/assets/19378678/ea52718e-ac73-465a-85e0-8953c2e2741b)

**Comment by Bertk** [comment]
Please check whether **SDK 5.0.401** installation is necessary. I guess it is not used.

https://github.com/daveMueller/coverlet/blob/a8c32cc5c6e9f1cd02efa837b9b33b2cf0176358/eng/azure-pipelines-nightly.yml#L10C1-L13C45
