### ISSUE TITLE
System.EntryPointNotFoundException : Entry point was not found

### ISSUE THREAD

**Issue by sungam3r** [coverlet-coverage/coverlet#1517]
On net6.0 I faced with weird issue. See https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1980 and especially https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1980#issuecomment-1666717402 .

I narrowed it down to `--collect "XPlat Code Coverage"` and opencollector package.

Steps to reproduce:
1. Check out code from my branch in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1980
2. Run `dotnet test ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj --collect "XPlat Code Coverage" -f net6.0` locally from the repo root. Test run fails.
 

Additional notes:
1. No such error without `--collect "XPlat Code Coverage"`.
2. No such error if explicitly add `<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />` into test project.
3. No such error on net7.0.

**Comment by daveMueller** [comment]
Thanks for reporting 🙏

**Comment by Bertk** [comment]
@daveMueller I used the latest nightly build and the problem still occurs but this will be solved with PR #1513. Nuget package System.Text.Json V7.0.3 is using Microsoft.Bcl.AsyncInterfaces V7.0.

<img width="1243" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/b5584e32-c605-460a-b886-3fe4f89c099f">

**Comment by daveMueller** [comment]
@Bertk I just tried it out real quick with our [nightly](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md) and it seems this is still an issue. Maybe you can double check when you find some time.

**Comment by Bertk** [comment]
@daveMueller The versions in the nuget package are correct but this will not be available in the bin folder of test project (`<PrivateAssets>all</PrivateAssets>`). The PackageReferenze should be added to test project **test\HealthChecks.Gremlin.Tests\HealthChecks.Gremlin.Tests.csproj** 

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
  </ItemGroup>
```

and the _System.EntryPointNotFoundException_ will vanish.

**Comment by Bertk** [comment]
@sungam3r  Please try again with latest version from [coverlet-nightly feed](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly/NuGet/coverlet.collector) e.g.
`<PackageVersion Include="coverlet.collector" Version="6.0.1-preview.20.g3ec85e7a33" />`

**Comment by Bertk** [comment]
related #1601

**Comment by sungam3r** [comment]
@Bertk I checked `6.0.1-preview.20.g3ec85e7a33` and see no error.

**Comment by Bertk** [comment]
[coverlet V6.0.1](https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.1) is released.
