### ISSUE TITLE
Certificate "Coverlet (.NET Foundation)" has expired (valid until 16th June 2023).

### ISSUE THREAD

**Issue by Bertk** [coverlet-coverage/coverlet#1518]
The certificate is not valid anymore (valid until 16th June 2023).

<img width="430" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/10aca059-8eae-443e-8836-794f742df3b1">

**Comment by MarcoRossignoli** [comment]
@clairernovotny is there a way to renew it?

**Comment by clairernovotny** [comment]
@chrissfanos can help with that.

**Comment by ChrisSfanos** [comment]
I've started the renewal process - will keep you updated

**Comment by MarcoRossignoli** [comment]
@ChrisSfanos  this is how we do atm https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ReleasePlan.md#how-to-manually-release-packages-to-nugetorg

**Comment by daveMueller** [comment]
@ChrisSfanos @clairernovotny we plan to make a new release in the near future and we don't really want to do this with an expired certificate. Is there still anything missing that we can help with? cc: @MarcoRossignoli

**Comment by ChrisSfanos** [comment]
Hi @daveMueller  - from what I can tell, you have everything from a config standpoint.  The tool itself is owned by @clairernovotny team and can help with actual implementation

**Comment by Bertk** [comment]
[coverlet V6.0.1](https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.1) is released.

**Comment by MarcoRossignoli** [comment]
> [coverlet V6.0.1](https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.1) is released.

Actually we have an issue with the cert..we're waiting some help from @clairernovotny and @ChrisSfanos 
As soon as solved we will re-release it cc: @daveMueller

**Comment by ChrisSfanos** [comment]
The latest cert was published to NuGet, so this likely will be resolved very soon

**Comment by daveMueller** [comment]
> The latest cert was published to NuGet, so this likely will be resolved very soon

Yes we successfully re-released now.

https://www.nuget.org/packages/coverlet.collector/6.0.1
https://www.nuget.org/packages/coverlet.msbuild/6.0.1
https://www.nuget.org/packages/coverlet.console/6.0.1
