### ISSUE TITLE
When exclude assambly in xml ouput show that assambly but empty tag

### ISSUE THREAD

**Issue by allnnde** [coverlet-coverage/coverlet#1526]
Hi, I am trying to generate a coverage report, but when I exclude a namespace it appears in the xml but without data.  

Sorry for my english

my runsettings
![image](https://github.com/coverlet-coverage/coverlet/assets/8978118/dfce15db-e99f-4954-bd71-b548299a9107)

de command to run
dotnet test --no-build --verbosity d --collect:"XPlat Code Coverage" --settings .runsettings --results-directory ./coverage

xml ouput
![image](https://github.com/coverlet-coverage/coverlet/assets/8978118/2c5eadfc-fd13-46fd-8b69-57180bc58cb7)

thx

**Comment by Bertk** [comment]
Hi,

thank you for reporting this issue.

I assume you are using the latest version of coverlet.collector. Please try again using the latest pre-release form nightly build. You should also use the verbosity option `dotnet test --logger "console;verbosity=detailed"`.

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly/NuGet/coverlet.collector

**Comment by allnnde** [comment]
hello, I did the test with that version that you have indicated me and the same thing happened to me, I attach the log of the testing step[](url)
[6_Test.txt](https://github.com/coverlet-coverage/coverlet/files/12538858/6_Test.txt)

**Comment by Bertk** [comment]
Thanks for the log file. Could you please try to use `ExcludeByFile` instead.

[MSBuildIntegration.md#excluding-from-coverage](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage) (related issue: #56)

**Comment by allnnde** [comment]
same result :(
![image](https://github.com/coverlet-coverage/coverlet/assets/8978118/70b06472-2865-4caf-a6a3-33ae9c7911ef)
![image](https://github.com/coverlet-coverage/coverlet/assets/8978118/1a379572-3e42-43f2-a683-f82c3f64aa17)

**Comment by allnnde** [comment]
I attach the last log of the testing step
[6_Test.txt](https://github.com/coverlet-coverage/coverlet/files/12565725/6_Test.txt)

**Comment by Bertk** [comment]
There is another related issue #830 and ExcludeByFile example which use directory filter.

<img width="1027" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/f2312710-b532-42bd-8f71-95c3466d81fa">

Maybe you can use `**/elearming-backend/**/*`

**Comment by allnnde** [comment]
I can't use the filter `**/elearming-backend/**/*`  because otherwise it ignores the whole project.

**Comment by Bertk** [comment]
@allnnde The coverlet [build.yml](https://github.com/coverlet-coverage/coverlet/blob/91acb458849ef0dde7b00a446d68606aa9c2761f/eng/build.yml#L30C1-L30C1) uses now **exclude parameter** (uses coverlet.msbuild) but the syntax for `exclude `is identical.

_The following lines are an excerpt from #1503_
A) Using coverlet.collector Exclude option (special CLI syntax " -- " separator for command and settings)

`dotnet test bug-tests-in-coverage.sln -c Release --collect="XPlat Code Coverage" --results-directory="TestResults/" --  DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="-[MyApp.Application.Tests]"`

B) Using reportgenerator assemblyfilters option

`reportgenerator -reports:"TestResults/*/coverage.cobertura.xml" -targetdir:"CoverageReports/" -reporttypes:"HtmlSummary;TextSummary" -assemblyfilters:"-MyApp.Application.Tests" `

Please try:  `<Exclude>-[Elearning_Backend.Domain]</Exclude>`
