### ISSUE TITLE
Cobertura report filenames different based on Operating System

### ISSUE THREAD

**Issue by adc-cjewett** [coverlet-coverage/coverlet#1527]
Based on previous issues it seems like the expectation is Cobertura reports should output a relative path. I noticed that when building and testing one of our repositories on Windows and Linux I was seeing differing behavior. The Windows machine uses the absolute path in the filename while the Linux machine uses the relative path. What is the expectation there?

You can use this repo to replicate by running https://github.com/adc-cjewett/PartialClassCodeCoverage 
`dotnet test --collect "Code Coverage;Format=Cobertura"` at the root of the repo then checking the results.

**Comment by daveMueller** [comment]
Hi, the collector you are using is not `coverlet`. It is the data collector build in vstest (different collector name). For using `coverlet` you need to add our `coverlet.collector` nuget package to your test projects and then run `dotnet test --collect:"XPlat Code Coverage;Format=cobertura"`

**Comment by adc-cjewett** [comment]
Ah, apologies! I'll create an issue over on the Microsoft.CodeCoverage project.

**Comment by daveMueller** [comment]
I was curious myself and tried out your repo. For `cobertura` reports we use relative paths by default regardless of the operating system.

Windows:
![grafik](https://github.com/coverlet-coverage/coverlet/assets/19378678/b2388b18-9c2b-49e8-905f-0ce6dc694375)

Linux:
![grafik](https://github.com/coverlet-coverage/coverlet/assets/19378678/d78ace5d-c848-4651-a832-4700f8a8f8ab)
