### ISSUE TITLE
Empty coverage report when using the `--configuration` flag

### ISSUE THREAD

**Issue by tumbledwyer** [coverlet-coverage/coverlet#1545]
**Describe the bug**
When using anything but the default configuration, code coverage report is empty. Default configuration works perfectly with the following command:
`dotnet test --no-restore --verbosity minimal ./MySolution.sln --collect:"XPlat Code Coverage" --results-directory ./coverage`

**To Reproduce**
Run `dotnet test --no-restore --configuration Test --verbosity minimal ./MySolution.sln --collect:"XPlat Code Coverage" --results-directory ./coverage`

**Expected behavior**
Complete coverage report

**Actual behavior**
Empty report
```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0" branch-rate="0" version="1.9" timestamp="1698739959" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```

**Configuration:**
Here is the csproj of the test project
```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props"></Import>
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>MySolution.Tests</AssemblyName>
    <PackageId>MySolution.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <Configurations>Test;Stage;Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Test|AnyCPU' ">
    <IntermediateOutputPath>obj\Test</IntermediateOutputPath>
    <DebugType></DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Test</OutputPath>
    <DefineConstants></DefineConstants>
    <WarningLevel>4</WarningLevel>
    <NoWarn></NoWarn>
    <NoStdLib>false</NoStdLib>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
    <PackageReference Include="MockQueryable.NSubstitute" Version="7.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

Is there something I'm missing?

**Comment by Bertk** [comment]
Hi,

please provide binary build log and diagnosis test log.

1)
- binary build log: `-bl`
- test log : ` --diag:".\log)\test.log;tracelevel=diagnostic"`

2)
please also check the [latest preview from coverlet-nightly build](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md)

**Comment by Bertk** [comment]
I will close the issue because there is no additional information provided. 

Code coverage will be available with default configurations `[Debug|Release]`. Customized build configurations has to be supported by the user.

**Comment by ChristoWolf** [comment]
I found the cause of the issue:
`<DebugType></DebugType>` disables PDB generation, which seems to be needed for coverlet to properly collect coverage data.
I had the same issue because I used `<DebugType>none</DebugType>` in the configuration that I used for testing.

**Comment by Bertk** [comment]
Thank you for the clarification. 

https://github.com/coverlet-coverage/coverlet/blob/8eecb425ac32b0863e30ca770fc0080a75c48d41/README.md?plain=1#L131

see also:
https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#badimageformatexception-net-framework-47x-48x
