### ISSUE TITLE
Uncovered lines in .NET 8

### ISSUE THREAD

**Issue by samuel-utbult-oborgen** [coverlet-coverage/coverlet#1555]
**Describe the bug**
When creating a record inheriting another record in a .NET 8 project, the initial line containing `public record` is reported as not covered by tests even though the record is used in the tests.

**To Reproduce**
1. Create a record.
2. Create another record inheriting that record.
3. Create a test using the second record.
4. Run the test with test coverage.
5. The line containing `public record` on the second record is reported as not tested.

Here is an example project showcasing the problem: https://github.com/samuel-utbult-oborgen/coverlet-missing-line-example

**Expected behavior**
The uncovered line should either be covered or ignored.

**Actual behavior**
The line is reported as uncovered.

**Configuration**
The following environment it used:
- coverlet 6.0.0
- .NET 8
- macOS Sonoma 14.0
- x64
- I have not encountered this problem in .NET 7 but coverlet 3.2.0 seems to have the same problem.

**Comment by gburkecw** [comment]
we are also seeing this same issue on .NET 7 projects, but GH Actions updated their latest agents to use MSBUILD 17.8 and we started seeing this issue.

For now as a workaround we are building with older agents that still have MSBuild 17.7, but I'm also going to see if I can specify an older language version in the csproj or something.

Still, it seems like this might prevent us from updating to .NET 8

**Comment by samuel-utbult-oborgen** [comment]
> I'm also going to see if I can specify an older language version in the csproj or something.

I can confirm that this does not work at least when it comes to updating to .NET 8. My computer has .NET 8 installed but all .csproj files in the project I'm working on have `<TargetFramework>net7.0</TargetFramework>` specified and the coverage problem is still present.

**Comment by Bertk** [comment]
Hi, thank you for the information but I can not reproduce the error.

<img width="580" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/f92f44af-3cb7-4c59-afa1-6d9eee2c5ab4">

```
C:\GitHub\coverlet-missing-line-example>dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

C:\GitHub\coverlet-missing-line-example>
```

**Comment by Bertk** [comment]
Thanks I will check it tomorrow.

By the way, please use this command to generate a valid .gitignore file for the example git repository:
 `dotnet new gitignore -force`

**Comment by Bertk** [comment]
The coverlet.runsetting excludes **generated code** and therefore uncovered line is removed.

`dotnet test --collect:"XPlat Code Coverage;Format=lcov" --settings coverlet.runsettings`

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

<img width="690" alt="Screenshot 2023-12-04 153837" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/88fc3976-d173-476c-a7e2-cb4e01c7f259">

<img width="1241" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/a68a2ae5-3f89-4747-8bc7-4c168d958eb0">

Please check whether this is an acceptable solution. This will also remove async methods from the coverage results (more details #1561).

**Comment by samuel-utbult-oborgen** [comment]
I can confirm the proposed solution removes the uncovered line in `InheritedRecord`. However, the tradeoff of not covering asynchronous methods is not acceptable in my situation as the project I am aiming to upgrade to .NET 8 consists in a large part of asynchronous methods. The branch `exclude_generated_code` in my example project showcases this problem.

**Comment by camp-007** [comment]
@daveMueller Awesome! Thank you for your work on this. Can you explain the release cadence or when this change will be available on nuget?

**Comment by pinkfloydx33** [comment]
@daveMueller Any idea when this will make it into the nightly build? The last nightly was two days prior to merging this in.... it'd be nice to have these fixes there as well

**Comment by daveMueller** [comment]
@pinkfloydx33 we are working on fixing the nightly pipeline. @camp-007 a new release currently has a really high priority among the maintainers but we had some issues with that in the last months. I'm optimistic that we can publish a new release in the near future. Until then you can consume the [nightly build](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md).

**Comment by joe-camp-nelnet** [comment]
@daveMueller Any news or updates on when this will make it to a formal release on nuget?
