### ISSUE TITLE
Coverlet is generating 0% coverage

### ISSUE THREAD

**Issue by Oblutack** [coverlet-coverage/coverlet#1557]
I test with `dotnet test` using msbuild v6.0.0. It doesn't generate anything. I tried using collector and running `dotnet test --collect:"XPlat Code Coverage"` and it only displays zeros in the report aswell.
https://github.com/Oblutack/TS_Zadaca2

**Comment by Bertk** [comment]
Hi, sorry but the current information is not sufficient. 

We use a GitHub issue template which should be used to reduce additional question on the topic.

## Observation

- I only could find a test project `Testiranje/Testiranje.csproj` but it does not have a project reference for the test object
- The XML in `Testiranje/Testiranje.csproj` is invalid and line 20 should be removed
- the test project uses **MSTest**. We use typically **xunit** only.


Please find buildable and testable csproj files: 
[TSZadaca2.zip](https://github.com/coverlet-coverage/coverlet/files/13548209/TSZadaca2.zip)


Microsoft.CodeCoverage shows this in Visual Studio:

<img width="617" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/d5bb459f-54ca-4fd6-9443-22359a249e4e">

**Comment by Bertk** [comment]
Using the updated csproj files will generate code coverage output.

```
dotnet test --no-build -bl:test.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
reportgenerator -reports:"**/*.opencover.xml" -targetdir:"artifacts\reports" - reporttypes:"Html;HtmlInline_AzurePipelines_Dark;Cobertura"
```
<img width="1022" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/d1757028-1aed-48b4-9607-02ba446bf254">

[ReportGenerator](https://www.nuget.org/packages/dotnet-reportgenerator-globaltool) can be used for HTML report.

<img width="533" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/aef2b08f-c686-48cc-872e-eb5a21c59e25">

[reports.zip](https://github.com/coverlet-coverage/coverlet/files/13556479/reports.zip)

**Comment by Bertk** [comment]
I close the issue and recommend to read the Microsoft and coverlet documentation

- https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test
- https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md
