### ISSUE TITLE
C# record constructors are not covered when SkipAutoProps is true

### ISSUE THREAD

**Issue by jlawrence** [coverlet-coverage/coverlet#1561]
**Describe the bug**
C# record constructors are marked as uncovered whenever _SkipAutoProps_ is true. But if _SkipAutoProps_ is false, the coverage is correct.

**To Reproduce**

1. Create a file with a simple record
```public record MyRecord(int A);```

2. Create a test that constructs the record
```var myRecord = new MyRecord(1);```

Minimal Example: https://github.com/jlawrence/coverlet-missing-line-example/tree/main

**Expected behavior**
The record constructor should be covered regardless of the value of _SkipAutoProps_.

**Actual behavior**
Observed behavior: If _SkipAutoProps_ is _true_, the record constructor will not be covered. If it is _false_, the record constructor will be covered.

**Configuration:**
    * Coverlet package: "coverlet.collector" Version="6.0.0"
    * .NET 8
    * Windows 10 x64

**Comment by daveMueller** [comment]
Thanks for reporting. I didn't find time to look into this in detail but I guess the problem is the primary constructor. When there a new C# language features we often need to adapt to them. Especially if it's a feature where the compiler generates a lot of things like with primary constructors. 
@Bertk @MarcoRossignoli I think we should look into primary constructors in general. Besides the primary constructors for `records` there is now also a variant of them for `classes` in C# 12. 
Probably the easiest solution would be to skip them from coverage as they are just **mere method signatures**. On the other hand we could try to handle them like e.g. auto properties or so.
What do you think about it?
There is already another issue that also reports issues with primary constructors #1555.

**Comment by Bertk** [comment]
@daveMueller @MarcoRossignoli I am not sure whether it is possible to ignore primary constructors without a method attribute. Maybe the [skip auto property](https://github.com/coverlet-coverage/coverlet/blob/21d3964f0399a8b353894806f774fdcf973b4324/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L1316C1-L1322C6) solution will be possible.

<img width="1042" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/e9935a44-c447-4644-a106-4aed3a833b2e">

By the way, the current VS2022 preview (Version 17.9.0 Preview 1.1) also shows it as "Not Covered (Lines)"
 
<img width="613" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/99cc3857-a278-402e-9a5f-100a50597d0e">

**Comment by Bertk** [comment]
I am not sure whether this is an acceptable solution for your issue but you can use a coverlet.runsetting file to ignore generated code.

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

`dotnet test --collect:"XPlat Code Coverage;Format=lcov" --settings coverlet.runsettings`

without runsetting file:
<img width="992" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/f4488092-ea37-4aef-b5e4-b585619d39b0">


with runsetting file
<img width="689" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/cded258c-4eec-433b-88d1-e8b2161ebbd0">

**Comment by Bertk** [comment]
@jlawrence I see, So you have to wait until @daveMueller will provide a better solution.

**Comment by daveMueller** [comment]
OK I found some time to look into this now. It seems we don't have an issue with primary constructors on `classes` as the compiler only generates fields without any additional methods or assignments. For `records` we already tackled this issue years back with this PR #1159. But it seems the roslyn team changed something in the generated IL. There now is a second `ctor` generated that has a sequence point that we instrument erroneously.
I already prototyped a fix for that and will create a PR in the next days. 

What I noticed while analyzing this is that there already is a unit test for this scenario that should have failed our CI build (`SkipRecordWithProperties`). The test also fails when I execute it locally. But the current CI build doesn't report any failed test. Looking into the test report of our latest CI build I found some entries that I can't really interpret. First of all it says this test is skipped, but I couldn't figure out the reason.
```bash
TpTrace Verbose: 0 : 5880, 11, 2023/12/22, 08:42:59.352 ... Coverlet.Core.Tests.CoverageTests.SkipRecordWithProperties [SKIP]"}}
``` 
And a bit deeper in the test log it says it failed for unknown reason, but the build job still succeeds?
```json
"TestCase": {
    "Id": "f1fa401c-81a1-f20c-97b5-c97033736c40",
    "FullyQualifiedName": "Coverlet.Core.Tests.CoverageTests.SkipRecordWithProperties",
    "DisplayName": "Coverlet.Core.Tests.CoverageTests.SkipRecordWithProperties",
    "ExecutorUri": "executor://xunit/VsTestRunner2/netcoreapp",
    "Source": "D:\\a\\1\\s\\artifacts\\bin\\coverlet.core.tests\\debug\\coverlet.core.tests.dll",
    "CodeFilePath": null,
    "LineNumber": 0,
    "Properties": []
},
"Attachments": [],
"Outcome": 3,
"ErrorMessage": "fails reason unknown (no session debug possible)",
"ErrorStackTrace": null,
"DisplayName": "Coverlet.Core.Tests.CoverageTests.SkipRecordWithProperties",
"Messages": [],
"ComputerName": "fv-az902-962",
"Duration": "00:00:00.0010000",
"StartTime": "2023-12-22T08:42:59.3532843+00:00",
"EndTime": "2023-12-22T08:42:59.3532844+00:00",
"Properties": []
```

@MarcoRossignoli @Bertk Any idea why this test is skipped on CI build?

**Comment by Bertk** [comment]
@daveMueller I am not sure why the test is skipped but I noticed failed tests of **CoverageTests.SkipRecordWithProperties** with PR #1570. 
By the way, master branch uses an old version V2.10.0 of _Microsoft.CodeAnalysis.CSharp_ nuget package. The current version is V**4.8.0**.

**Comment by daveMueller** [comment]
OK thanks, I'll check this again once I'm finalizing the fix.
