### ISSUE TITLE
[BUG] I am getting 100% branch coverage but 0% line coverage 

### ISSUE THREAD

**Issue by sa-y-an** [coverlet-coverage/coverlet#1563]
**Describe the bug**
I am getting 100% branch coverage but 0% line coverage 
![image](https://github.com/coverlet-coverage/coverlet/assets/55195504/0055166b-147e-4487-b173-9fe7b4c6a27a)
Can anyone tell me how is this possible ?

**Expected behavior**
Both line and branch coverage should be 0 

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
- Getting the same issue on both linux and windows machine 
- Running using dotnet 6 
- 
```sh
dotnet test --collect:"XPlat Code Coverage" -c Release -f net6.0 --filter Category!=Integration --logger "trx;LogFileName=$2.trx" --results-directory TestResults $1 --settings ./conveyor.runsettings
```
and generating report using report-generator 
```sh
reportgenerator "-reports:$COVERAGE_FILES" "-targetdir:./.coverage/html" "-classfilters:-VMware.*" "-reporttypes:Html" "-title:Conveyor"
```

### Note 

In the files I found in branch coverage, all branches showed 0%
![image](https://github.com/coverlet-coverage/coverlet/assets/55195504/2e1241b2-533f-4536-bf00-304c1c9a41e6)

**Comment by daveMueller** [comment]
I think this has already been answered here: #1268 and #1384. Does this help?

**Comment by sa-y-an** [comment]
Thanks, I got my answer.
