### ISSUE TITLE
Generate CHANGELOG.md using changelog-from-release tool

### ISSUE THREAD

**Issue by Bertk** [coverlet-coverage/coverlet#1579]
The CHANGELOG.md can be generated using available tools and should be updated within the PR. This might require addition conventions for PR and git commits. 

- [**changelog-from-release**](https://github.com/rhysd/changelog-from-release) 
  -  uses git releases to generate CHANGELOG.md
  -  GitHub action [rhysd/changelog-from-release/action@v3](https://github.com/rhysd/changelog-from-release/blob/master/action/README.md)
- [**Versionize**](https://github.com/versionize/versionize) using [conventional commit messages](https://conventionalcommits.org/).
   - This might require addition conventions for PR and git commits. 
   -  Versionize is a dotnet tool 
- [**github-changelog-generator**](https://github.com/github-changelog-generator/github-changelog-generator)
  - allows to add existing manual created CHANGELOG.md 
- ...

There are many tools and my favored for coverlet is [**changelog-from-release**]. I created a CHANGELOG.md for coverlet with this tools (see attachment) with command `changelog-from-release -r https://github.com/coverlet-coverage/coverlet`.

_Proposal:_ 
Create GitHub action which created CHANGELOG.md  and upload the file as build artifact. This can be used for release activity or using draft releases even for PR.

@daveMueller @MarcoRossignoli 
Please share your thoughts on this topic .  

[CHANGELOG.md](https://github.com/coverlet-coverage/coverlet/files/13858058/CHANGELOG.md)

see also: 

- https://github.com/marketplace/actions/release-drafter

Draft release is updated every time the pipeline with the release-drafter action is called. 🚀 
<img width="1035" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/8dc5cba7-a910-49d0-a157-ed962063496d">

**Comment by MarcoRossignoli** [comment]
looks interesting, @daveMueller what you think?

**Comment by daveMueller** [comment]
Nothing against that. As long as it is just `release-drafter` and `changelog-from-release` and I don't need to look into additional tools to fix something when it breaks. What I think is a bit annoying that you need `changelog-from-release` to create the markdown as `release-drafter` doesn't have a option to also create it.
What I'm also missing a bit is the option to manually add something to the markdown, e.g. description of breaking changes etc... Do I then need to update the draft release first with my manual information so that it is included in the changelog?

**Comment by Bertk** [comment]
Yes, the (draft) release information will be the source for CHANGELOG.md. `release-drafter` will create information which can be used and modified/extended but the information depends on the correct labeling.

Maybe we can just active `release-drafter` draft now and `changelog-from-release` as the next step.

`changelog-from-release` will update the format of CHANGELOG.md and the current template is not using e.g.  a preamble. The existing coverlet releases need also updates to resolve markdown format issues. By the way, have cannot modify the release 

<img width="843" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/680265a4-a44c-4efa-b854-82934ad42a0b">
