### ISSUE TITLE
[BUG] cobertura.XML receives an unwanted BOM

### ISSUE THREAD

**Issue by DominikRoB** [coverlet-coverage/coverlet#1602]
When running coverlet on Win10 on .NET 6, the resulting XML is saved with an encoding "UTF-8 BOM". This seems to break my Jenkins pipeline and I see no configuration to avoid this.

Given that I see no reports on this, I figure this is an edge case with my environment?

**Comment by Bertk** [comment]
[coverlet V6.0.1](https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.1) is released.
