### ISSUE TITLE
[BUG] coverlet does not support multiple report formats using CoverletOutput parameter

### ISSUE THREAD

**Issue by Bertk** [coverlet-coverage/coverlet#1610]
**Describe the bug**
coverlet.msbuild.tasks overrides code coverage result file using file name of given **CoverletOutput** parameter.

**To Reproduce**

execute command:
`dotnet test test\coverlet.core.tests\coverlet.core.tests.csproj --configuration debug /p:CollectCoverage=true /p:CoverletOutputFormat="json%2copencover" /p:CoverletOutput="C:\GitHub\coverlet\artifacts\Reports\coverlet.core\coverage.json" /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.xunit.extensions]*%2c[coverlet.tests.projectsample]*%2c[testgen_]*" --results-directory:"C:\GitHub\coverlet\artifacts\Reports\coverlet.core" --diag:"C:\GitHub\coverlet\artifacts\log\debug\coverlet.core.test.diag.log;tracelevel=diag"`

**Expected behavior**
2 code coverage result files are available (formats: json, opencover)

**Actual behavior**
Only one code coverage result file is available.
<img width="850" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/41d76a48-7c5b-4945-a983-1b16f9d03a60">

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
    * Which coverlet package and version was used?  6.0.1-preview.39.g9321d2e2cc
    * Which version of .NET is the code running on? net8.0
    * What OS and version, and what distro if applicable? windows 11
    * What is the architecture (x64, x86, ARM, ARM64)? x64

**Additional context**
none

**Comment by Bertk** [comment]
fix [CoverletOutput folder location](https://github.com/coverlet-coverage/coverlet/pull/1601/commits/90246329cd4bde7bde7710d7c79a7195040cbdef)

**Comment by Bertk** [comment]
Filename for multiple report formats is currently not supported. 
**CoverletOutput** parameter without file shall be used instead e.g. `/p:CoverletOutput="C:/GitHub/coverlet/artifacts/Reports/coverlet.core/"`

<img width="872" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/8b549420-273d-4c39-8fdb-4821be70dfd9">

**Comment by daveMueller** [comment]
I've seen that we have the same issue for `coverlet.console`. The idea to just use the output directory in those cases sounds good to me.

![grafik](https://github.com/coverlet-coverage/coverlet/assets/19378678/d68c239e-3eef-48ab-a18b-cc61eda0755a)

**Comment by Bertk** [comment]
Update of [GlobalTool.md](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md) should be sufficient e.g.

**_whenever more than one coverage format is used in combination with output parameter only a folder shall be used_**

_current paragraph_

> The above command will write the results to the supplied path, if no file extension is specified it'll use the standard extension of the selected output format. To specify a directory instead, simply append a / to the end of the value.
>
> `coverlet <ASSEMBLY> --target <TARGET> --targetargs <TARGETARGS> --output "/custom/directory/" -f json -f lcov`
