### ISSUE TITLE
[BUG] 6.0.1 requires dotnetsdk 8 but doesn't say that

### ISSUE THREAD

**Issue by drdamour** [coverlet-coverage/coverlet#1625]
**Describe the bug**
Had a build tied to 6.* for a version using sdk 6 and it failed with 

```
Data collector 'XPlat code coverage' message: [coverlet]System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetDefaultServiceCollection(TestPlatformEqtTrace eqtTrace, TestPlatformLogger logger, String testModule)
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender, SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 135.
```

**To Reproduce**
build with dotnet6

**Expected behavior**
Expect coverlet to run and report successfully

**Actual behavior**
fails to generate report

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
    * Which coverlet package and version was used?
      * reproduceable with 6.0.1
    * Which version of .NET is the code running on?
      * 6.0.x (tried a few versions...all reproduced) 
    * What OS and version, and what distro if applicable?
      * window 10 and linux ubuntu (whatever azdo is using now a days)
    * What is the architecture (x64, x86, ARM, ARM64)?
      * x64
    * Do you know whether it is specific to that configuration?
      * seems not to be

**Additional context**
the changes in this PR https://github.com/coverlet-coverage/coverlet/pull/1601 seems to force having dotnet 8 installed so that thinks like System.Text.Json will load the 8.0 version from the shared framework.

> :exclamation:  Please also read [Known Issues](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md)

doesn't appear to be any

overall, seems like mistake to break backwards compatability between 6.0.0 and 6.0.1 like this...doesn't seem to match semver...but maybe that was your intent?   understand 6 is EOL at end of year so we should be moving to 8 sdk soon...

**Comment by Bertk** [comment]
Thank you for reporting.

I used the [coverlet HelloWord example](https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld) and the test was executed successfully.

<img width="878" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/eb4ff1d0-81f6-440c-acc3-8b6c4f4b99b2">

The .NET SDK 8.0 was installed.

Could you please add this packages to your test project and run the test again.

```
<PackageReference Include="System.Text.Json" Version="8.0.2" />
<PackageReference Include="System.Reflection.Metadata" Version="8.0.0" />
```

**Comment by SeWieland** [comment]
Same problem here.. All our CI pipelines are failing because we are adding coverlet.collector dynamically to our test solutions via dotnet add package.

@Bertk the hello world example still uses `PackageReference Include="coverlet.collector" Version="6.0.0" >` => Version 6.0.0

dotnet add package will install version 6.0.1 (a patch update that must not contain breaking changes according to SemVer) and this package does not include any dependency to system.text.json at all.

**Comment by andreycha** [comment]
Have same issue. We're using .NET 6 SDK and have `coverlet.collector` referenced as `6.0.*`. Having such a breaking change in a patch version is quite a surprise. Changes described in https://github.com/coverlet-coverage/coverlet/pull/1626 require at least new minor version.

**Comment by Bertk** [comment]
Sorry, I missed the to update the version.

@MarcoRossignoli @daveMueller We should update the version to `6.1.0`.

**Comment by SeWieland** [comment]
Another idea: "SuppressDependenciesWhenPacking" set on the collector. Would it be possible to [pack these two required package references as dependencies instead](https://til.cazzulino.com/dotnet/nuget/suppress-dependencies-when-packing) or something similar?
The breaking behaviour could thus probably be reverted for .NET < 8

**Comment by andreycha** [comment]
@Bertk would it be also possible to release 6.0.2 with reverted changes?

**Comment by Bertk** [comment]
@SeWieland Thank you for the hint but **coverlet.collector** package has no dependencies. The dilemma is the support for framework net6.0, net7.0 and net8.0 and this works with the latest packages for

```xml
    <PackageReference Include="System.Reflection.Metadata" VersionOverride="8.0.0" />
    <PackageReference Include="System.Collections.Immutable" VersionOverride="8.0.0" />
```

<img width="338" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/4cb51d7f-80ce-4de5-866d-3ae3240e10a8">

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli @daveMueller We should update the version to 6.1.0.

Why? we bump the patch we will bump the minor if we ship a new feature and a major if we do breaking change.

**Comment by Bertk** [comment]
@MarcoRossignoli  coverlet 6.0.1 is a __bugfix version__ but requires a  .NET 8.0 SDK. 

semver 2.0 has this [paragraph](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)

> **What should I do if I update my own dependencies without changing the public API?**
>
>That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. We would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

**Comment by MarcoRossignoli** [comment]
>  but requires a .NET 8.0 SDK.

Why? we ship for 
<img width="251" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/7894084/563d1113-ca08-40fa-970c-2553d01fe2f9">

so we're good for .NET Framework and every project with tfm >= 6.0

**Comment by drdamour** [comment]
> > but requires a .NET 8.0 SDK.
> 
> Why? we ship for <img alt="image" width="251" src="https://private-user-images.githubusercontent.com/7894084/306656366-563d1113-ca08-40fa-970c-2553d01fe2f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Mjk2NDQsIm5iZiI6MTcwODUyOTM0NCwicGF0aCI6Ii83ODk0MDg0LzMwNjY1NjM2Ni01NjNkMTExMy1jYTA4LTQwZmEtOTcwYy0yNTUzZDAxZmUyZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTUyOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI5ZjUwMTQ3ZGQ1ODc4N2NlNzMyY2MwOGM4NWY5NTYyNzdkZGRlZWI3OGE3MjM3MWRmOWIzOWIwNDQyOWQxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NahNgPeQe9TeHHGjm0MbCxiNwzGkeiEqKQTzdlPDPA8">
> 
> so we're good for .NET Framework and every project with tfm >= 6.0

Doesnt matter what u target or if u declare a dependency or not...u now require system.text.json 8 in 6.0.1…when u used to NOT..just cause u do not claim a dependendency doesnt mean u dont have one.

in fact by not claiming a dependency u seem to have..u’ve made yourself backwards incompatible.

So let me be clearer..i think its a mistake to require json 8 and think you should revert that change back to 6 unless u require some functionality in json 8.  Thats wouldnbe the better solution IMO.

If u MUST use json 8 you should bump a major version since users bow need it to implicitly be present or declare that dependency.

i too must pin to 6.0.0 when using sdk 6

**Comment by MarcoRossignoli** [comment]
> u now require system.text.json 8 in 6.0.1

I saw now what you mean https://github.com/coverlet-coverage/coverlet/pull/1601/files#diff-1d12ae6a5243ca16cfc9b56abc8423c15a917dd1adcdc3d7dd3482ccff2208da this was wrong...

@Bertk @daveMueller we cannot declare > 6.0 and insert non 6 lib...this needs to be fixed.

**Comment by tvbishan** [comment]
I have the same question. Works well with the coverlet.collector Version="6.0.0". But when upgraded to the coverlet.collector Version="6.0.1", it failed.

```
Data collector 'XPlat code coverage' message: [coverlet]System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

**Comment by cremor** [comment]
I suggest to release 6.0.2 with that fix ASAP.

**Comment by akutuev** [comment]
Hi @Bertk, can you please confirm, did you decide to keep .NET 8 for this and further versions yes?

**Comment by MarcoRossignoli** [comment]
> Hi @Bertk, can you please confirm, did you decide to keep .NET 8 for this and further versions yes?

It's fixed here https://github.com/coverlet-coverage/coverlet/pull/1628 cc: @daveMueller

**Comment by akutuev** [comment]
> > Hi @Bertk, can you please confirm, did you decide to keep .NET 8 for this and further versions yes?
> 
> It's fixed here #1628 cc: @daveMueller

Ah I see, thanks for heads up! Hope [NuGet repo](https://www.nuget.org/packages/coverlet.collector#versions-body-tab) will be updated soon

**Comment by drdamour** [comment]
hope we see a release soon

**Comment by JeroenDeHaan1980** [comment]
When do  you expect to have a new version released with the issue solved?

**Comment by daveMueller** [comment]
Hi guys, we finally merged everything we broke with the last release. We would really appreciate if someone could give it a try.
Here is how to consume the nightly:  https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by tvbishan** [comment]
@daveMueller 

It is working now.
Tested with `image: mcr.microsoft.com/dotnet/sdk:6.0` and `coverlet.collector --version 6.0.2-preview.8.g892d86e16b`

**Comment by daveMueller** [comment]
We now have a new official release `6.0.2` that can be consumed from nuget.org.
