### ISSUE TITLE
[BUG] Type initializer errors after updating from 6.0.0 to 6.0.1

### ISSUE THREAD

**Issue by joaorosado** [coverlet-coverage/coverlet#1629]
**Describe the bug**
After upgrading from 6.0.0 to 6.0.1 the tests fail with errors initializing Coverlet

**To Reproduce**
Updated from 6.0.0 to 6.0.1.
Project being tested targets netstandard2.0. Only external reference is Newtonsoft.Json 13.0.3
Test project targets 4.7.2 and has the following references:

```
    <PackageReference Include="coverlet.msbuild" Version="6.0.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="NSubstitute" Version="5.1.0" />
    <PackageReference Include="Nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="WireMock.Net" Version="1.5.40" />
```

**Expected behavior**
Tests to run without crashing

**Actual behavior**

```
   System.TypeInitializationException : The type initializer for 'Coverlet.Core.Instrumentation.Tracker.OutSystems.Auditing_cbebb53f-99cc-461e-8124-db81357fd8a1' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Stack Trace:
     at Coverlet.Core.Instrumentation.Tracker.OutSystems.Auditing_cbebb53f-99cc-461e-8124-db81357fd8a1.RecordHit(Int32 )
   at Auditing.Tests.AuditConfigTests.AuditConfigRequestTimeoutTest() in D:\a\1\s\tests\UnitTests\Auditing.Tests\AuditConfigTests.cs:line 12
--FileNotFoundException
   at Coverlet.Core.Instrumentation.Tracker.OutSystems.Auditing_cbebb53f-99cc-461e-8124-db81357fd8a1..cctor()
```

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
    * Which coverlet package and version was used? 6.0.1
    * Which version of .NET is the code running on? 4.7.2
    * What OS and version, and what distro if applicable? Windows 2022 (Azure CI agent windows-latest)
    * What is the architecture (x64, x86, ARM, ARM64)? 
    * Do you know whether it is specific to that configuration? Don't know

**Additional context**
Current command being used to execute the tests:

dotnet test D:\a\1\s\tests\UnitTests\Auditing.Tests --configuration Release --no-restore --no-build --logger trx --framework net472  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=**/GitVersionInformation.* /p:CoverletOutput=D:\a\TestResults\coverage.net472.1.xml

Currently I'm not able to switch execution mode to the --collect version due to the test CI templates being shared by all our or organizational repositories. So cannot test with the --collect:"XPlat Code Coverage" option

**Comment by valadas** [comment]
I got the same issue, interestingly the build worked fine on ubuntu github runner but failed on local builds/tests (on windows)

**Comment by santisq** [comment]
I believe I have the same issue too:

![image](https://github.com/coverlet-coverage/coverlet/assets/23342410/9efabcb9-e641-48dc-8fce-d8a9a9cd23df)


https://github.com/santisq/PSCompression/actions/runs/8039618762/job/21956826632?pr=22#step:5:49

**Comment by daveMueller** [comment]
Thanks a lot for reporting this. I can reproduce it with simply `dotnet test /p:CollectCoverage=true`. Repro is attached here.
[Issue1629.zip](https://github.com/coverlet-coverage/coverlet/files/14398204/Issue1629.zip)

**Comment by sungam3r** [comment]
The same here https://github.com/destructurama/attributed/pull/109

**Comment by daveMueller** [comment]
I start working on this and see if I can figure something out.

**Comment by MarcoRossignoli** [comment]
> I see two options here. We could move back to build coverlet.core only targeting netstandard2.0. I already tried that out and it is working. Or try to work with some other condition.

I would go for now `netstandard2.0` and we will work if needed to multi-tfm but with completely different packaging...like be fair and do not cheat nuget.

**Comment by daveMueller** [comment]
I think I would have found a condition that works but keeping it `netstandard2.0` for now is fine for me. I'll create a PR.

**Comment by tmp64** [comment]
I'm getting a similar error with `net7.0-windows`. It attempts to load `System.Collections.Immutable, Version=8.0.0.0`. There are no errors with `coverlet.collector 6.0.0`

<details>
<summary>Test log</summary>

```
> dotnet test --collect "XPlat Code Coverage"

Microsoft (R) Test Execution Command Line Tool Version 17.9.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.41]     REDACTED [FAIL]
[xUnit.net 00:00:00.42]     REDACTED [FAIL]
  Failed REDACTED [190 ms]
  Error Message:
   REDACTED
The type initializer for 'REDACTED' threw an exception.
---- System.TypeInitializationException : The type initializer for 'REDACTED' threw an exception.
-------- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (0x80131621)
  Stack Trace:
     at REDACTED.<>c__DisplayClass14_0.<REDACTED>g__REDACTED|1(<>c__DisplayClass14_1&) in REDACTED
   at REDACTED
----- Inner Stack Trace -----
   at REDACTED
----- Inner Stack Trace -----
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at REDACTED
  Failed REDACTED [< 1 ms]
```
</details>

<details>
<summary>Runtimes</summary>

```
Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

<details>
<summary>SDKs</summary>

```
7.0.304 [C:\Program Files\dotnet\sdk]
7.0.406 [C:\Program Files\dotnet\sdk]
8.0.201 [C:\Program Files\dotnet\sdk]
```
</details>

**Comment by daveMueller** [comment]
Hi guys, we finally merged everything we broke with the last release. We would really appreciate if someone could give it a try.
Here is how to consume the nightly:  https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by sungam3r** [comment]
Fixed in https://github.com/destructurama/attributed/pull/109

**Comment by sungam3r** [comment]
Thank you.
