### ISSUE TITLE
When using .NET 6 (with .NET 8 installed) picking wrong version of System.Text.Json [BUG]

### ISSUE THREAD

**Issue by clinington** [coverlet-coverage/coverlet#1639]
**Describe the bug**
So I have both sdks installed, i have a global json pinning the version to `6.0.419`.

The version of `coverlet.collector` is `6.0.1`.

Running:

```
dotnet test --configuration Release --filter Category!=Manual --logger trx --collect:"XPlat Code Coverage;Format=opencover,cobertura"
```

gets this result:

> Data collector 'XPlat code coverage' message: [coverlet]System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

However, if you switch `coverlet.collector` to version `6.0.0` and run the same command again then the issue goes away - assuming that it has something to do with the switch from newtonsoft to system.text.json

> :exclamation:  Please also read [Known Issues](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md)

**Comment by niravmsoni** [comment]
Faced the same issue in one of our pipeline after updating the package to the latest version. After downgrading it to 6.0.0, it works for me. Thanks for the workaround @clinington

**Comment by patelriki13** [comment]
Same issue for me... Downgrade to version 6.0.0 and working fine.

**Comment by clinington** [comment]
Yeah - that was my fix - then went to .net8 and bumped back up again.

However, the there's a security vulnerability with the newtonsoft package that is used by version `6.0.0` so it's not a great workaround...

**Comment by daveMueller** [comment]
We now have a new official release `6.0.2` that can be consumed from nuget.org.
