### ISSUE TITLE
Coverage can be merged with `dotnet-coverage` tool

### ISSUE THREAD

**Issue by tillig** [coverlet-coverage/coverlet#1656]
Currently [in the docs](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration) it directs folks trying to merge coverage reports to look at a comment from 2020 with some Powershell script to help merge coverage reports.

Since then, [the `dotnet-coverage` tool has been released](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage) and allows you to merge coverage reports pretty easily.

For example, if your coverage reports are under `artifacts/coverage` and you have Cobertura format, you can use glob patterns to work around the randomly named directories VSTest creates and merge them like this:

```sh
dotnet-coverage merge artifacts/coverage/**/coverage.cobertura.xml -f cobertura -o artifacts/coverage/coverage.xml
```

It might be interesting to update the docs accordingly - this is far easier than the current suggestion.

**Comment by LiviuSosu** [comment]
Yep...sur it helped when I saw hat the "recursive" parameter is obsolete. Thanks a bunch!!
