### ISSUE TITLE
[BUG] System.IndexOutOfRangeException using coverlet collector

### ISSUE THREAD

**Issue by peibol71** [coverlet-coverage/coverlet#1682]
I can't get the coverage.coverture.xml file because of this exception error

I'm using this command:
dotnet test -c Release --collect:"XPlat Code Coverage"

And get this error message:
Data collector 'XPlat code coverage' message: Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to get coverage report
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Coverlet.Core.Reporters.CoberturaReporter.Report(CoverageResult result)
   at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageReport(CoverageResult coverageResult)
   --- End of inner exception stack trace ---
   at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageReport(CoverageResult coverageResult)
   at Coverlet.Collector.DataCollection.CoverageManager.GetCoverageReport()
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionEnd(Object sender, SessionEndEventArgs e).

.NET configuration:
    * coverlet.collector v6.0.2
    * .NET 6.0
    * Windows 11 Pro x64
    * Also reproducible on azure devops pipeline

Any idea?

Thanks.

**Comment by Bertk** [comment]
Please check whether PDB files are available in the output folder.
> Locates the unit test assembly and selects all the referenced assemblies that have PDBs.

https://github.com/coverlet-coverage/coverlet?tab=readme-ov-file#how-it-works

**Comment by peibol71** [comment]
There is one PDB file (<projectname>.pdb) in <projectfolder>\obj\Release\net6.0

**Comment by Bertk** [comment]
Maybe diagnostic logs will provide more information.

> dotnet test --collect:"XPlat Code Coverage" --settings runsettings --diag:log.txt

**Comment by peibol71** [comment]
Sorry, that's not a bug.
There was a misconfigured Directory.Build.props file and the project was using coverlet.collector v1.0 instead of v6.0.2

**Comment by Bertk** [comment]
No problem. Please close the issue.
