### ISSUE TITLE
Coverlet.collector is impossible to use for mixed C++ / C# projects

### ISSUE THREAD

**Issue by ClancyWalters** [coverlet-coverage/coverlet#1703]
We use `MSBuild.exe` and `vstest.console.exe` rather than the `dotnet` cli due to incompatibility with mixed C++ / C# projects. The trouble is, both suggested uses of `coverlet.collector` require either `dotnet test` or `dotnet publish`. Ideally coverlet.collector should have a method of triggering the deployment that isn't via the `dotnet` cli tool unless there is some inherent incompatibility with mixed C++ / C# projects.

**Comment by Bertk** [comment]
Did you try `dotnet vstest` already? The build output is created before the test is started.

```
"C:\hostedtoolcache\windows\dotnet\dotnet.exe" vstest "D:\a\1\s\artifacts\bin\DotNetDev.ArcadeLight.Sdk.Tests\Debug\net8.0\DotNetDev.ArcadeLight.Sdk.Tests.dll" /collect:"XPlat Code Coverage" --ResultsDirectory:"D:\a\1\s\artifacts\TestResults\Debug" --logger:"trx
LogFileName=DotNetDev.ArcadeLight.Sdk.Tests_net8.0_x64.trx" --Diag:"D:\a\1\s\artifacts\log\Debug\DotNetDev.ArcadeLight.Sdk.Tests_net8.0_x64.diag.log
tracelevel=verbose" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile="**/*.Version.cs" > "D:\a\1\s\artifacts\log\Debug\DotNetDev.ArcadeLight.Sdk.Tests_net8.0_x64.log" 2>&1
```

**Comment by ClancyWalters** [comment]
Hey I've finished deep diving into getting this working now, `dotnet vstest` has the same problem as `vstest.console.exe` where we really need to run a `dotnet publish` first. The solution to my problem was realizing that you can run `MSBuild.exe` with the arguments `/p:DebugType=portable /p:PublishProfile=<profile name> /t:Publish` in order to get an output that includes the required coverlet files. This really isn't a problem with coverlet but perhaps is an opportunity to improve documentation.

**Comment by Bertk** [comment]
Great. You solved the problem already and this issue is obsolete.

We have already a section in **Known Issues** which mentions the [DebugType](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#badimageformatexception-net-framework-47x-48x) setting.

Unfortunately, you did not use the default issue template which requests more details for troubleshooting.
