### ISSUE TITLE
MSBuild coveragexml format

### ISSUE THREAD

**Issue by jchesshir** [coverlet-coverage/coverlet#224]
I would like to be able to import the Coverlet output into Visual Studio Enterprise (VSE) to get the same view of coverage.  I'm finding differences in the percentages in Coverlet and VSE, so it would be nice to have a VSE view of what Coverlet is actually seeing.

VSE can export its coverage in the form of a coveragexml, which I hope (fingers-crossed) would be fairly easy to replicate so that Coverlet's results can be imported into VSE.

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
