### ISSUE TITLE
Don't track branch coverage for Debug.Assert

### ISSUE THREAD

**Issue by hughbe** [coverlet-coverage/coverlet#258]
E.g. https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/System.Collections_BitArray.htm
![image](https://user-images.githubusercontent.com/1275900/49683621-338bc000-fac8-11e8-9775-c2b4c331ca02.png)

Doesn't seem very useful as we don't expect this to happen

**Comment by ViktorHofer** [comment]
The whole System.Diagnostics.Debug type can be excluded with the `--exclude` switch. We can definitely do that in corefx but I'm not sure if @tonerdo wants that set globally.

**Comment by ViktorHofer** [comment]
Oh you are right but wouldn't/shouldn't a) also imply b)?

**Comment by hughbe** [comment]
Apparently not!

**Comment by tonerdo** [comment]
Excluding a class means that non of the methods belonging to that class are instrumented. It's a non-trivial amount of work to have that exclusion rule apply the usages of the class itself

**Comment by sungam3r** [comment]
I also encountered this problem.
