### ISSUE TITLE
Use ConsoleTables package once it has a strong name

### ISSUE THREAD

**Issue by sharwell** [coverlet-coverage/coverlet#304]
The ConsoleTables dependency was eliminated in #303 (specifically 5ba3f6007113240bbd172b9657c0a527a91d04d6) due to a bug in the source package. Once the source package has a strong name, it can be include via a `<PackageReference>` again (i.e. the previous commit can be reverted).

See khalidabuhakmeh/ConsoleTables#30

**Comment by Bertk** [comment]
This is issue is outdated.
