### ISSUE TITLE
Settings file

### ISSUE THREAD

**Issue by viceice** [coverlet-coverage/coverlet#319]
It would be helpful to have coverlet settings file to pass complex excludes.
This would reduce the comandline length.

This would solve any shell escaping errors too.

Regards
Michael

**Comment by ViceIce** [comment]
Currently not, but have had issues with escaping the arguments.
Now i'm using a [response file](https://github.com/tonerdo/coverlet/issues/30#issuecomment-383623772)

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
