### ISSUE TITLE
Option to ignore field/property initializers and auto-implemented properties

### ISSUE THREAD

**Issue by rickardp** [coverlet-coverage/coverlet#328]
Consider a class, e.g.

    class MyClass
    {
        public int MyValue { get; set; }
    }

The property would be excluded because it's getter/setter has the CompilerGeneratedAttribute set. Now consider this class:

    class MyClass
    {
        public int MyValue { get; set; } = 42;
    }

The line is included in coverage. I think this is because in the IL code, the initializers are actually part of the constructor. While this may be a sensible default even if explicitly opting out of compiler generated code, there should be an option to exclude initializers from coverage analysis. 

The use case for this is when you have large model objects that contain code that you actually want coverage on, but also contains lots of pure data members.

Suggestion is to include an option, e.g. `ExcludeInitializers`, that ignores all initializers from coverage.

I saw e.g. issue #316, but I would argue something more specific than an arbitrary "IgnoreTrivial" is more suitable.

**Comment by MarcoRossignoli** [comment]
For reference OpenCover has got [`-skipautoprops`](https://github.com/OpenCover/opencover/wiki/Usage) 
/cc @tonerdo

**Comment by rickardp** [comment]
@MarcoRossignoli Auto properties without initializers are already handled. Does OpenCover handle initializers?

**Comment by MarcoRossignoli** [comment]
Closing because we can use `/p:ExcludeByAttribute=\"CompilerGeneratedAttribute\"`

![image](https://user-images.githubusercontent.com/7894084/66736192-ce7fc400-ee68-11e9-899b-26eb99e59ef9.png)

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli Auto properties without initializers are already handled. Does OpenCover handle initializers?

Not at the moment
https://github.com/OpenCover/opencover/blob/67980c8132b1d574beb1feaa7d269c9dca47b812/main/OpenCover.Framework/Symbols/CecilSymbolManager.cs#L328

**Comment by svengeance** [comment]
For reference I was able to use this today effectively, as the overall coverage % wasn't valuable to me while I was unable to skip such trivial code.

So thank you, this was wonderful timing.

**Comment by ulrichb** [comment]
As of _coverlet.collector 1.3.0_ this still doesn't seem to work:

![image](https://user-images.githubusercontent.com/388796/94678129-50892700-031e-11eb-9467-037e6c929e12.png)

My config:
```xml
<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
    <DataCollectionRunSettings>
        <DataCollectors>
            <DataCollector friendlyName="XPlat code coverage">
                <Configuration>
                    <Format>opencover</Format>
                    <Include>[...snip...]</Include>
                    <ExcludeByAttribute>GeneratedCodeAttribute,TestSDKAutoGeneratedCode</ExcludeByAttribute>
                    <ExcludeByFile>**/*.Designer.cs</ExcludeByFile>
                    <IncludeTestAssembly>true</IncludeTestAssembly>
                    <SkipAutoProps>true</SkipAutoProps>
                </Configuration>
            </DataCollector>
        </DataCollectors>
    </DataCollectionRunSettings>
</RunSettings>

```

**Comment by ulrichb** [comment]
... oh just saw that #912 has't been released yet. Right?

**Comment by MarcoRossignoli** [comment]
> Right?
Right 😁

**Comment by wdspider** [comment]
```csharp
    public sealed record RouteResponse
    {
        public string Id { get; init; } = string.Empty;
    }
```

I'm still experiencing that autoprops like these in records are still counting against coverage even though SkipAutoProps is set to true.  Will the fix mentioned in the thread above fix this issue too?  If so, when will it be released for the coverlet.collector ?

**Comment by Malivil** [comment]
This change has already been implemented and doesn't cover the case where an auto-prop has an inline assignment like that.
I would file another issue about that so it can be handled separately.

**Comment by wdspider** [comment]
> 
> 
> This change has already been implemented and doesn't cover the case where an auto-prop has an inline assignment like that.
> I would file another issue about that so it can be handled separately.

Opened #1139 as requested.

**Comment by StingyJack** [comment]
> Consider a class, e.g.
> 
> ```
> class MyClass
> {
>     public int MyValue { get; set; }
> }
> ```
> 
> The property would be excluded because it's getter/setter has the CompilerGeneratedAttribute set. Now consider this class:

@rickardp - If its reporting a class member that is unused or untouched by any of the unit tests it should be reported as not covered. Is this what you mean?
