### ISSUE TITLE
Coverage output file name

### ISSUE THREAD

**Issue by andreacassioli** [coverlet-coverage/coverlet#378]
Is there a way to set the output file name so that it will include the project name and a timestamp, pretty much as standard unit test trx files? I cannot find any mention of this.

**Comment by MarcoRossignoli** [comment]
At the moment no 
https://github.com/tonerdo/coverlet/blob/0956d1e8da6b7265b0b5e4f93af3499c4be99cc8/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L99-L106

but the idea is not bad /cc @tonerdo

**Comment by alexanderkozlenko** [comment]
```xml
<Target Name="AdjustCoverletOutputName"
        BeforeTargets="GenerateCoverageResult">
  <PropertyGroup>
    <CoverletOutput>$(VSTestResultsDirectory)\$(MSBuildProjectName).CodeCoverage_$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd_HH_mm_ss_fff")).xml</CoverletOutput>
  </PropertyGroup>
</Target>
```

**Comment by tonerdo** [comment]
I like this idea, but I'm afraid it'll break existing build scripts that expect a predictable output file name

**Comment by sasivishnu** [comment]
By default, we generate output file name as it is now. May be add a new command line option? An option like "--output -uf" means we generate unique file name (CodeCoverage_timestamp).

**Comment by MarcoRossignoli** [comment]
Maybe `--output-includetimestamp`(with a default) and `--output-timestampformat` for custom format
```bash
... --output "/custom/path/result.json" --output-includetimestamp --output-timestampformat yyyy-MM-dd_HH_mm_ss_fff
```
To produce 
`result.json_2019-05-06_14_42_22_222.json`

**Comment by MarcoRossignoli** [comment]
@tonerdo @andreacassioli @alexanderkozlenko our great contributor @daveMueller started to work on this, I would like to know if we are in agreement with switches!
I think that in case we're in agreement we should provide those on msbuild and .net tool, I don't know if we can apply to collectors, to investigate.

**Comment by MarcoRossignoli** [comment]
Moved to discussion https://github.com/coverlet-coverage/coverlet/discussions/1254
