### ISSUE TITLE
Specifying threshold level for each threshold type.

### ISSUE THREAD

**Issue by arun-subramanian-1** [coverlet-coverage/coverlet#379]
Threshold command-line option `/P:Threshold` seems to use a single value for all threshold type.
I would like to specify different threshold level for each threshold types.

like 100% method but give like 50% branch for ex.

`/p:Threshold=\"50,100\" /p:ThresholdType=\"branch,method\"`

But this doesnt  work, it throws error

```
.... error : The minimum branch coverage is below the specified 50100  ....
.... error : The minimum method coverage is below the specified 50100 ....
```

```
 > coverlet --version
Cross platform .NET Core code coverage tool
1.5.0.0
 > 
```

**Comment by MarcoRossignoli** [comment]
Confirm at the moment we use only single value https://github.com/tonerdo/coverlet/blob/226455ece9760c72d3d09ca6c377efb8cb61d686/src/coverlet.core/CoverageResult.cs#L164

**Comment by thetoxicsoul** [comment]
Created a pull request for this option

https://github.com/tonerdo/coverlet/pull/385

**Comment by oherik** [comment]
I would also like to request this feature. It would be very valuable for me to have, since my team has a specified a minimum test coverage for both lines and branches (with different percentages for each type).

**Comment by MarcoRossignoli** [comment]
cc: @tonerdo https://github.com/tonerdo/coverlet/pull/385#issuecomment-515797242

**Comment by FourierFormed** [comment]
I would also find this feature very useful.

**Comment by MarcoRossignoli** [comment]
closed in https://github.com/coverlet-coverage/coverlet/actions/new
