### ISSUE TITLE
Flag to prevent copy of assemblies

### ISSUE THREAD

**Issue by pms1969** [coverlet-coverage/coverlet#38]
It would be handy to have a way of preventing the file copies in situations where the build artefacts are throw away; i.e. Build systems.

File copying can take up a fair amount of time in a sufficiently large solution, and if you don't care about saving the original, there are 2 file copies that don't need to happen - the backup, and the restore.  All in all, this could have a considerable time saving in build pipelines where the output is throw away anyway.

**Comment by MarcoRossignoli** [comment]
Closed for too few thumbs up/interest from community.
