### ISSUE TITLE
On-Board project to the .NET Foundation

### ISSUE THREAD

**Issue by tonerdo** [coverlet-coverage/coverlet#386]
We're getting ready to bring the project into the .NET Foundation, but before we
do we need to do the following:

## Getting into the .NET Foundation
- [x] Make sure the project has a good name that is easy to remember and 
 spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [x] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [x] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [x] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [x] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [x] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation
- [x] Sign the contribution / assignment agreement
- [x] Agree a date to move into the .NET Foundation
- [x] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [x] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), 
      [link to it in your code](be-nice.md) and 
      understand what to do if you are concerned about any behaviour or have
      concerns reported to you.
- [x] Tell the world we have joined!
- [x] Get CLA Automation enabled to ensure contributors can easily sign the 
      [Contribution License Agreement](https://github.com/dotnet/home/blob/master/guidance/net-foundation-contribution-license-agreement.pdf)
- [x] Send a PR to add the Project into the .NET Foundation 
      [list](https://github.com/dotnet/home/tree/master/projects)
- [x] Ensure the repo contents are up to date with [.NET Foundation guidance](https://github.com/dotnet/home/blob/master/guidance/repo-guide.md)
- [x] Review the [README guidance](readme-guide.md) and update if necessary
- [ ] If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation
      and look to update any file headers.
- [ ] If applicable, update any copyright statements in websites owned by the project to reflect 
      assignment to the .NET Foundation
- [x] If applicable, update any websites associated with the project to include
      "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or
      similar link back to the .NET Foundation in the footer. If applicable, please
      include image links from [our swag repo](https://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [x] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [x] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing,
      Secret Management, Build Servers etc)

**Comment by tonerdo** [comment]
cc @petli @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
@tonerdo can we close this?We joined foundation so I think that unresolved points aren't fundamental.

**Comment by MarcoRossignoli** [comment]
@clairernovotny I don't understand if coverlet has officially joined .NET Foundation or if we need to do something else.

**Comment by tonerdo** [comment]
One final thing we have to do is add coverlet to the .net foundation repo so it'll show up on their website

**Comment by tonerdo** [comment]
Also looking into setting up CLA license

**Comment by MarcoRossignoli** [comment]
Could be great add CLA license, I can open a PR to .net foundation

**Comment by MarcoRossignoli** [comment]
@tonerdo project added https://github.com/dotnet/foundation/pull/173

**Comment by MarcoRossignoli** [comment]
We added also signature to package I think we can close this.
