### ISSUE TITLE
Save json with coverage output

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#542]
We've some issue related to the possibility to read coverage output and use it.
At the moment there are only 2 way
1) Manually calculate throught reports data https://github.com/tonerdo/coverlet/issues/520#issuecomment-522846008
2) Or use RegEx to extrapolate numbers https://github.com/tonerdo/coverlet/issues/148 https://github.com/tonerdo/coverlet/issues/284

I wonder if could be useful add a switch or two(for file name) to produce coverage output in a json format.

On this issue I'd like to collect opinions/name proposal/usage(I'll keep updated this top issue with best proposal)

## Open question

Switch name?
Sample usage?

cc: some guys collected on issues @desmondgc @m4cx @pintomic @mggrand @anaether @yauhenyaulampyeu @NicoDujde @Nusserdt @gach87 @ithepunisher @kwentinn

cc: @tonerdo @petli

**Comment by desmondgc** [comment]
From my perspective, there needs to be an easy way to use the coverage output programmatically in scripts. That is, make it easy to pipe the output to another command or parse it for use in CI/CD tools to generate coverage badges or use in conditional statements. 98% of the time I just want a single value based on my preferred way of calculating coverage. Coverlet already gets very close to this behavior with the existing --threshold, --threshold-type, and --threshold-stat options and is just currently lacking the option to output the actual value used in the threshold calculation.

Consider adding a --format option "threshold" that outputs the threshold value with a fixed number of decimal points. This would satisfy my requirements with the smallest impact.

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
