### ISSUE TITLE
coverlet.collector format: possible to specify without runsettings file?

### ISSUE THREAD

**Issue by escalonn** [coverlet-coverage/coverlet#563]
[This section of the docs](https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#default) suggests that it's possible to set the Format option without needing a runsettings file. (Possibly with a runsettings command line argument after `--` ?)

If so, provide an example.

If not, please clarify in the docs that changing any options, including format, requires a runsettings file. (If true, this is pretty obnoxious compared to the way it works with MSBuild integration.)

**Comment by MarcoRossignoli** [comment]
> This section of the docs suggests that it's possible to set the Format option without needing a runsettings file.

Sorry @escalonn maybe the guide is not clear...we mean that the format parameter is the only "default" parameter passed and the default format is cobertura.

> If not, please clarify in the docs that changing any options, including format, requires a runsettings file. (If true, this is pretty obnoxious compared to the way it works with MSBuild integration.)

I agree with you users experience with runsettings is not so great.
We talked a bit in past with vstest team(on our side we cannot do nothing for it) cc: @vagisha-nidhi to understand if there are plan by vstest team to improve user experience.

**Comment by ItsVeryWindy** [comment]
In case anyone wants to know, It is possible to set the format although it's a bit long winded, for example.

`DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover`

**Comment by MarcoRossignoli** [comment]
Oh, sorry I misunderstood the question...every parameters inside runsettings can be specified by using xml flat syntax, I meant that there is no `--` style parameters for collectors parameters.

@ItsVeryWindy thanks for your addition!

**Comment by escalonn** [comment]
> 
> 
> In case anyone wants to know, It is possible to set the format although it's a bit long winded, for example.
> 
> `DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover`

That's exactly what I was looking for. Thanks

**Comment by tremblaysimon** [comment]
Really interesting! I think it should be officially documented if it's not already.

**Comment by MarcoRossignoli** [comment]
Asap I'll add documentation on it, not the best way but better than nothing for now
