### ISSUE TITLE
Import exclusions from file

### ISSUE THREAD

**Issue by thviQit** [coverlet-coverage/coverlet#605]
We got the idea, that it would be nice to have a file with all your source file exclusions, instead of providing a long list to the build task.
In this way, you can have the exclusions under version control and you do not have to edit your build every time you need to exclude a file.

I missed the CONTRIBUTION.md (even though it is upper case ...), so I already have an implementation, but I have refrained from creating a pull request.

I hope it is something you would be interested in.

**Comment by thviQit** [comment]
You can see it here: https://github.com/thviQit/coverlet/tree/exclusions-from-file

**Comment by MarcoRossignoli** [comment]
Hi @thviQit thank's for the idea...you could open a PR without problem when you want and we can discuss on it.

First thing I'm not so "happy" is that we've at the moment 3 types of exclusion
-by types
-by file
-by attributes
so we should include all types of filters and not favour one, I mean I used a lot types filtering in my experience but never used files...depends on "usage".

the second one is that we've also the opposite concept that is "include" so to be symmetric in design we should also add inclusion filter file.

I wonder if someone can reach same goal on CI simply composing run script with a "script" that take exclusion from file(versionable).

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
