### ISSUE TITLE
Exclude argument is not working for dotnet test command

### ISSUE THREAD

**Issue by venkikonda** [coverlet-coverage/coverlet#613]
Hi Team,
Greetings For The Day!!

we are using coverlet.Msbuild package to get the code coverage for .NetCore.
when i executed the  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[wwwroot.*]*"  command from test folder able to retrieve the coverage.xml for code module ( Models ..controllers etc) ..i am not able to exclude some folders which are having more lines of code ..

used pattern : dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[BSH.MES.CloudGateway.*.*wwwroot]*

need to exclude whole wwwroot folder from ../home/MES/mes-platform/services/BSH.MES.CloudGateway/wwwroot path  which has 460000 lines of code

Could you please kindly assist on this how to exclude not required folders fro project?
Your help would be more appreciable here.

Thanks
Venkat
+91-8886710001

**Comment by petli** [comment]
Exclude works on assembly names, which wwwroot is probably not a part of, if you need to exclude based on path you should look at ExcludeByFile according to the docs:
https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#source-files

**Comment by MarcoRossignoli** [comment]
Also you need to use last version to be sure that exclude by file works correctly 2.7.0 https://github.com/tonerdo/coverlet/pull/524

**Comment by venkikonda** [comment]
@MarcoRossignoli and @petli 

Thanks much for your inputs on this issue.
let me try ExcludeByFiles parameter to exclude source files and will come back to you .

if you have installation link to 2.7.0 for coverlet ..please proide me that i can use it.

**Comment by venkikonda** [comment]
@MarcoRossignoli and @petli 

I got the package installation command ..will try and let you guys know..

dotnet add package coverlet.msbuild --version 2.7.0

**Comment by venkikonda** [comment]
@MarcoRossignoli and @petli 

I have installed the latest version of coverlet-2.7.0 and tried to exclude the source folder wwwroot from the dot-net command and able to exclude from coverage.

dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"../BSH.MES.CloudGateway/wwwroot/*.html,../Constants/**/*.cs,../Contollers/**/*.cs,../Exceptions/**/*.cs,../BSH.MES.CloudGateway/wwwroot/css/*.css,../BSH.MES.CloudGateway/wwwroot/js/*.js\"
wile executing sonar end analysis i could see wwwroot excluded from code module .

INFO: Excluded sources:
INFO: ../BSH.MES.CloudGateway/wwwroot/.html,../Constants//.cs,../Contollers/*/.cs,../Exceptions/*/.cs,../BSH.MES.CloudGateway/wwwroot/css/.css,../BSH.MES.CloudGateway/wwwroot/js/.js

I could see sonar.exclusions property in the sonar-project file .

sonar.exclusions="../BSH.MES.CloudGateway/wwwroot/.html,../Constants//.cs,../Contollers/*/.cs,../Exceptions/*/.cs,../BSH.MES.CloudGateway/wwwroot/css/.css,../BSH.MES.CloudGateway/wwwroot/js/.js"

But After pushing end analysis to sonar dashboard , i could see wwwroot folder which should not push which having 45000 lines of code which dev team is not covering.

could you please suggest on it why wwwroot folder is pushing though we ignored..

code structure:

root@ip-172-31-5-249:/home/MES-FETCH/services/BSH.MES.CloudGateway# ls -ltr
total 52
-rwxrwxrwx 1 root root 2991 Nov 11 11:34 README.md
drwxrwxrwx 2 root root 4096 Nov 11 11:34 Properties
-rwxrwxrwx 1 root root 4341 Nov 11 11:34 Program.cs
drwxrwxrwx 3 root root 4096 Nov 11 11:34 Models
drwxrwxrwx 2 root root 4096 Nov 11 11:34 Exceptions
-rwxrwxrwx 1 root root  454 Nov 11 11:34 Dockerfile
drwxrwxrwx 2 root root 4096 Nov 11 11:34 Controllers
drwxrwxrwx 2 root root 4096 Nov 11 11:34 Constants
-rwxrwxrwx 1 root root 1410 Nov 11 11:34 BSH.MES.CloudGateway.csproj
drwxrwxrwx 5 root root 4096 Nov 11 11:34 wwwroot
drwxrwxrwx 3 root root 4096 Nov 11 11:36 obj
drwxrwxrwx 3 root root 4096 Nov 11 11:36 bin
root@ip-172-31-5-249:/home/MES-FETCH/services/BSH.MES.CloudGateway#

**Comment by MarcoRossignoli** [comment]
@venkikonda can you enable coverlet logging so we can check if the parameter are correct.
You're using `dotnet test` so you can follow this guide https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration (msbuild integration)
with `-verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger` msbuil will log a file `msbuild.binlog` and with tool http://msbuildlog.com/ we can check if exclusion parameters come in a correct way to coverlet.

**Comment by venkikonda** [comment]
@MarcoRossignoli  - I have gone through the links provided by you but i am unable to see any exclusions in generated msbuild.binlog file.

I have used the below command ,

dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"../BSH.MES.CloudGateway/wwwroot/*.html,../Constants/**/*.cs,../Contollers/**/*.cs,../Exceptions/**/*.cs,../BSH.MES.CloudGateway/wwwroot/css/*.css,../BSH.MES.CloudGateway/wwwroot/js/*.js\" -verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger

please find the below attached reference link ..

[msbuild-binlog.zip](https://github.com/tonerdo/coverlet/files/3841109/msbuild-binlog.zip)

Could you please let me know if you need any other  information.

**Comment by MarcoRossignoli** [comment]
Try with

```
/p:ExcludeByFile="**/BSH.MES.CloudGateway/wwwroot/.html,**/Constants/**/.cs,**/Contollers//*.cs,**/Exceptions//.cs,**/BSH.MES.CloudGateway/wwwroot/css/.css,**/BSH.MES.CloudGateway/wwwroot/js/*.js"
```

The filter should be one of https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=dotnet-plat-ext-3.0

and from your log I don't see any file filtered, seem that filter is not correct.
![image](https://user-images.githubusercontent.com/7894084/68766374-0d976580-061f-11ea-80b6-39a710d86cd3.png)

**Comment by venkikonda** [comment]
@MarcoRossignoli 
Thank you so mush for your response!
I appreciate your help on this..

I used the below filter command in the dotnet test command.
for me  "," was not worked so that i have used %2c .

dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/BSH.MES.CloudGateway/wwwroot/.html%2c **/BSH.MES.CloudGateway/wwwroot/css/.css%2c **/BSH.MES.CloudGateway/wwwroot/js/*.js" -verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger

I am able to excluded files filter in log file..please see attached log file..
![coverletlog](https://user-images.githubusercontent.com/28502358/68792664-cbe3da80-0671-11ea-8558-ac4774eb7953.JPEG)

But still while doing sonar end analysis for dotnet .Core wwwroot whole folder pushing to sonar dashboard..

Please give any inputs on this.

**Comment by MarcoRossignoli** [comment]
@venkikonda sorry for the delay, bit busy,
for command `dotnet test /p:collectCoverage=true /p:excludebyfile="**/*.cs"` (did on root of coverlet repo)
you should see 
![image](https://user-images.githubusercontent.com/7894084/69335193-a865f480-0c5c-11ea-85f1-496e6608acca.png)

So seem the filter is not correct...try with `/p:excludebyfile="**/wwwroot/*.*"` `

**Comment by MarcoRossignoli** [comment]
@venkikonda  any news?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to re-open if needed!

**Comment by vsix27** [comment]
if you put notation according https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#source-files, it should work - escape " by \
instead of 
`/p:ExcludeByFile="**/Properties/Resources.*,**/Program.cs"`
put
`/p:ExcludeByFile=\"**/Properties/Resources.*,**/Program.cs\"`
