### ISSUE TITLE
Do we need to exclude the test file or is this automatically excluded?

### ISSUE THREAD

**Issue by PureKrome** [coverlet-coverage/coverlet#658]
I'm trying to learn how to use the coverlet code coverage tool. 

I usually have the following:

- 1x class library project
- 1x test project which tests that class library project

or

- 1x web api
- 1x test project which tests that web api project.

.. and my solution has multiple of these inside.

To get coverage, do I need to always exclude each test project? Or is this automatic? The prefered way to get coverage with coverlet is to use the VSTest engine, so if we need to manually exclude the test project I'll then need to make a runsettings.xml file?

**Comment by MarcoRossignoli** [comment]
> To get coverage, do I need to always exclude each test project? Or is this automatic?

There is a open debate on it https://github.com/tonerdo/coverlet/issues/618 by design test project is excluded at the moment.

>  The prefered way to get coverage with coverlet is to use the VSTest engine, so if we need to manually exclude the test project I'll then need to make a runsettings.xml file?

Yep the moment the only way to pass further parameters to vstest integration is runsettings file with hope to improve user experience in future.

**Comment by PureKrome** [comment]
Okay - so right now, the test project is EXCLUDED by default so I _do NOT_ need to provide a runsettings file.

---

How can I know which assemblies are included by default in the coverage? Is there an easy way? Is somehting like ReportViewer or codecov.io the easiest way to view the coverage report, which should list all assemblies covered?  And via that report, you can determine which ones to manually exclude, if required?

**Comment by MarcoRossignoli** [comment]
The default included modules are referenced modules by test projects where pdb/source file are present on local disk.
You can check using coverage report tool or you can force with `Include` prop to be sure that you're instrumenting what you want or you can check what is instrumented using logging.

VSTest integration https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration
Global tool https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#coverlet-global-tool
Msbuild https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to re-open if neeeded!
