### ISSUE TITLE
What is the latest version with 2.1 support? 

### ISSUE THREAD

**Issue by red8888** [coverlet-coverage/coverlet#721]
I get this error when trying to install in container **mcr.microsoft.com/dotnet/core/sdk:2.1**

error NU1202: Package coverlet.console 1.7.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any. Package coverlet.console 1.7.0 supports: netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any

what is the latest version of coverlet that supports 2.1? So I dont have to roll back versions until I find one that is compatible

**Comment by red8888** [comment]
For anyone else that has to support 2.1 the latest version I was able to install on **mcr.microsoft.com/dotnet/core/sdk:2.1** was:

**1.4.1**

**Comment by MarcoRossignoli** [comment]
@red8888 thank's for "investingating" by yourself.

One question why don't use collectors integration(target from 2.0 and is the preferred way to do coverage today)?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to re-open if needed!And use collectors integration if you can https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md!
