### ISSUE TITLE
Docker RUN with coverlet.msbuild 2.7 shows NaN% 

### ISSUE THREAD

**Issue by rshelby5** [coverlet-coverage/coverlet#726]
This used to work but now for some odd reason it is not. Running this command.

`RUN dotnet test -c Release /AttestationService.Test/AttestationService.Test.csproj --logger "junit;LogFilePath=/unit-test-results/unit-test-report.xml" --results-directory /unit-test-results /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/code-coverage-results/CodeCoverage`

Using this package version:
```
<PackageReference Include="coverlet.msbuild" Version="2.7.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

**Comment by MarcoRossignoli** [comment]
Likely you're hitting know msbuild issue https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#1-vstest-stops-process-execution-earlydotnet-test

can you try with collectors? 
https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed.

**Comment by goolzerg** [comment]
Have the same issue

**Comment by MarcoRossignoli** [comment]
@goolzerg can you open new issue and give some repro code?
