### ISSUE TITLE
100% coverage but empty result file

### ISSUE THREAD

**Issue by ColBiernot** [coverlet-coverage/coverlet#732]
Hi at all,

I am trying to collect coverage data for our UnitTest project. Therefore I added 
`<PackageReference Include="coverlet.msbuild Version="2.8.0"`
and used:
`dotnet test project.csproj --configuration Release p:/CollectCoverage=true`

After the successful nunit testrun, coverlet starts to calculate coverage result. The result is always _100%_. The generated json file only contains _{}_ do I miss something?

**Comment by MarcoRossignoli** [comment]
> After the successful nunit testrun, coverlet starts to calculate coverage result. The result is always 100%. The generated json file only contains {} do I miss something?

Are running some tests or are you running the command on empty tests project as a test?

**Comment by ColBiernot** [comment]
I'm executing some tests. Actually I managed to get it work.
My tests are executed in Release configuration. So after my acutal test build

`dotnet test example.csproj --configuration Release`

I need to execute the collection of coverage seperately

`dotnet test exaple.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CopyLocalLockFileAssemblies=true`

This works fine if I execute the second command manually. Executing the command on my CI pipeline results in the following warning which causes an empty result file:

`/Users/%USER%/.nuget/packages/coverlet.msbuild/2.8.0/build/coverlet.msbuild.targets(7,5): warning : [coverlet] Unable to instrument module: /Users/%USER%/Development/%BUILD_DIR%/src/Tests.Project/bin/Debug/netcoreapp3.0/Dependend.Project.dll because : Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'. Could not find or load a specific file. (0x80131621) [/Users/%USER%/Development/%BUILD_DIR%/src/Tests.Project/Tests.Project.csproj]`

**Comment by MarcoRossignoli** [comment]
> My tests are executed in Release configuration. So after my acutal test build

You should run coverage in debug if possible...release pdb has got less information and the coverage is less precise.

Can you try to do a `git clean -fdx` from root after the second run?That resolve exception doesn't make sense to me, can you share you csproj or is it a private project?

**Comment by MarcoRossignoli** [comment]
@ColBiernot any news?Does this issue solved?

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation, feel free to reopen if needed!

**Comment by balasun3** [comment]
@MarcoRossignoli, I tried and  still getting the empty result files, Can you suggest to get respone on coverage%

**Comment by MarcoRossignoli** [comment]
@balasun3 please can you open a new issue?

**Comment by safv12** [comment]
I'm having the same problem running the tests in debug mode. Did you solve the problem @ColBiernot?
