### ISSUE TITLE
"-v" is used more than once in the command line

### ISSUE THREAD

**Issue by Smurf-IV** [coverlet-coverage/coverlet#734]
V 1.7.0
Coverlet.Console

This leads to the Command not running

![image](https://user-images.githubusercontent.com/2418812/74748995-58013180-5261-11ea-9479-62c7c7b779bd.png)

![image](https://user-images.githubusercontent.com/2418812/74749057-76ffc380-5261-11ea-9c95-f9f34fd107af.png)

**Comment by MarcoRossignoli** [comment]
yep we know...for now please use double dash.

**Comment by MarcoRossignoli** [comment]
Close for too few thumbs up/interest from community.
