### ISSUE TITLE
MissingMethodException - SessionStartEventArgs.GetPropertyValue

### ISSUE THREAD

**Issue by YulerB** [coverlet-coverage/coverlet#748]
This new issue is related to https://github.com/tonerdo/coverlet/issues/456, requested by @MarcoRossignoli

The difference is, this issue is to see if a fall-back in the code below would address the issue and allow us to use Coverlet using .net core 2.1.400. 

**Exception:**

    Data collector 'XPlat code coverage' message: System.MissingMethodException: Method not 
    found: '!!0 
    Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.SessionStartEventArgs.GetProperty    Value(System.String)'.
       at     Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetTestModules(SessionStartEventArgs sessionStartEventArgs)
       at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender,     SessionStartEventArgs sessionStartEventArgs).

**Fallback:**

        private static IEnumerable<string> GetPropertyValueWrapper(SessionStartEventArgs sessionStartEventArgs)
        {
            try
            {
                return sessionStartEventArgs.GetPropertyValue<IEnumerable<string>>(CoverletConstants.TestSourcesPropertyName);
            }
            catch (MissingMethodException)
            {
                using (var enumProperties = sessionStartEventArgs.GetProperties())
                {
                    while (enumProperties.MoveNext())
                    {
                        if (enumProperties.Current.Key == CoverletConstants.TestSourcesPropertyName &&
                            enumProperties.Current.Value is IEnumerable<string> propertyValue)
                        {
                            return propertyValue;
                        }
                    }
                }
                throw;
            }
        }

**Comment by YulerB** [comment]
From what I can tell, looks like test sources was added only in 2.1.7 in https://github.com/dotnet/cli/pull/11312

**Comment by MarcoRossignoli** [comment]
@vagisha-nidhi does it make sense?

cc: @nohwnd

**Comment by MarcoRossignoli** [comment]
Possible related PR https://github.com/microsoft/vstest/pull/1962
Spec https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0026-Passing-TestPlatform-Properties-to-DataCollector.md
Cannot find in release changelog https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation.
