### ISSUE TITLE
Show how to specify format on command line with VSTest integration

### ISSUE THREAD

**Issue by IGx89** [coverlet-coverage/coverlet#755]
Hello! The documentation appears to indicate that Format can be specified on the command line for the VSTest integration (see https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration), but it provides no examples on how to do so and I've had zero luck figuring it out myself. Assuming that is indeed possible, would someone be able to share an example? Would be helpful for others to have it added to the docs as well I imagine.

**Comment by MarcoRossignoli** [comment]
> Hello! The documentation appears to indicate that Format can be specified on the command line for the VSTest integration

Maybe the guide is not clear...I'll update removing that confusing section, it's not possible passing format through command line, the intent of guide was tell which is the default format it you don't specify a runsetting file.

**Comment by IGx89** [comment]
I was afraid of that, thanks! Our code analysis system (SonarQube) just supports OpenCover and dotCover reports, not cobertura, so that means we'll have to check in a runsettings file for every project. Not a big deal though, just annoying.

**Comment by MarcoRossignoli** [comment]
I know and I agree, I'm in contact with vstest team to understand how to improve user experience, unfortunately vstest integration is the best one due to strict integration/coordination of workflow, but lacks of user-friendliness, sorry for that.

FYI @nohwnd we could try to improve this in some way(it's a past desire, right from the start of integration) I'm available to help on this side.

**Comment by MarcoRossignoli** [comment]
> we'll have to check in a runsettings file for every project.

@IGx89 you can share one in root test folder and pass it to `dotnet test`

**Comment by MarcoRossignoli** [comment]
It's possible pass parameters through commandline using test platform `--`  and xml flat syntax https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline

I'm going to close this one.
