### ISSUE TITLE
Coverlet doesn't track coverage of method with a LINQ query in an if statement

### ISSUE THREAD

**Issue by Shkeeny** [coverlet-coverage/coverlet#760]
When a method has a LINQ query in an `if` :
```c#
 public async Task<IAccessResponse> CreateAsync(DocumentEntity entity)
            {
            var list = new List<DocumentEntity> { new DocumentEntity { id = "1" }, new DocumentEntity { id = "2" } };

            if (list.Count(l => l.id == "1") > 1)
                throw new Exception();

            return new AccessResponse();
            }
```
We get a result in the code coverage, that looks something like this: 
![image](https://user-images.githubusercontent.com/23721921/76773110-99c2c080-67aa-11ea-9a74-83c368c49e1e.png)

But if we extract the query to a variable, it seems to work fine:
![image](https://user-images.githubusercontent.com/23721921/76772958-641dd780-67aa-11ea-9697-4075896b8e47.png)

Seems like the issue is reproducible in coverlet.msbuild versions 2.7.0 and 2.8.0. 
Version 2.6.3 works fine.

**Comment by MarcoRossignoli** [comment]
Possible dup of https://github.com/tonerdo/coverlet/issues/730
Can you try with our nightly build to understand if bug was fixed? https://github.com/tonerdo/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by Shkeeny** [comment]
Tried on version `2.8.38-g34d6dc5ff6`, still the same issue.

**Comment by MarcoRossignoli** [comment]
Debug or Release config?

**Comment by MarcoRossignoli** [comment]
cc: @matteoerigozzi

**Comment by jutrera** [comment]
Hi Marco.

The issue is happening with Linq in some different ways. I will show some pictures with different code for the same method. Hope it helps.

First approach **fails**
![image](https://user-images.githubusercontent.com/5177257/79543467-cad62f80-808d-11ea-9323-919d48e50e72.png)

Remove Any() instead of Count() -> **Fails**
![image](https://user-images.githubusercontent.com/5177257/79543622-112b8e80-808e-11ea-9c66-1b1251c2df54.png)

Remove Linq expression instead a for loop -> **Runs**
![image](https://user-images.githubusercontent.com/5177257/79543804-4e901c00-808e-11ea-9194-17fbd03cb853.png)

Remove Any and/or Count expressions instead of FirstOrDefault -> **Fails**
![image](https://user-images.githubusercontent.com/5177257/79543990-94e57b00-808e-11ea-8bc8-01323704e2cd.png)

Extracting from a method -> **Runs**
![image](https://user-images.githubusercontent.com/5177257/79544162-dc6c0700-808e-11ea-845e-f159e3bf7660.png)

![image](https://user-images.githubusercontent.com/5177257/79544215-f60d4e80-808e-11ea-8a9c-4c6146cb6034.png)

**Comment by MarcoRossignoli** [comment]
Can someone provide a repro project?

**Comment by petli** [comment]
I've run into something similar, and have a repro project here that also shows it to be an issue with foreach:
https://github.com/petli/coverlet-issue-760-demo/blob/master/Demo/Demo/Implementation.cs

Coverage:
https://github.com/petli/coverlet-issue-760-demo/blob/master/coverage.cobertura.xml

It seems to be the combination of IEnumerable<> and the async state engine that causes coverlet to ignore all lines except the if/foreach line.

**Comment by cdjc** [comment]
Zip file attached, but in short, to repro, you can create the example webapi app:
`$ dotnet new webapi`
And then add these methods to WeatherForecastController.cs:

```csharp
        [HttpGet]
        public async Task<IActionResult> Not_Seen_By_Coverage() // except the lambdas
        {
            var rng = new Random();
            var rval = Enumerable.Range(1, 5).Select(index => new WeatherForecast  // lambda is seen by coverage
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
            await Task.Delay(100);
            var sumList = Summaries.ToList();
            if (sumList.Any(s => 0 >= 3))  // lambda is seen by coverage
            {
                return StatusCode(400);
            }
            return StatusCode(500);
        }

        [HttpGet]
        public async Task<IActionResult> Seen_By_Coverage()
        {
            var rng = new Random();
            var rval = Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
            await Task.Delay(100);
            var sumList = Summaries.ToList();
            var foo = sumList.Any(s => 0 >= 3);
            if (foo)
            {
                return StatusCode(400);
            }
            return StatusCode(500);
        }
```
[example_issue_760.zip](https://github.com/coverlet-coverage/coverlet/files/4783490/example_issue_760.zip)

**Comment by MarcoRossignoli** [comment]
thanks guys I'll take a look asap!

**Comment by MarcoRossignoli** [comment]
Atm I can repro with @petli repro https://github.com/coverlet-coverage/coverlet/issues/760#issuecomment-644265756

**Comment by MarcoRossignoli** [comment]
Hi guys can someone of you give it a try using our nightly(tomorrow we release every midnight)? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by AdamDotNet** [comment]
@MarcoRossignoli - Nightly version
```xml
<PackageReference Include="coverlet.msbuild" Version="2.9.1-preview.19.ge99520eb06">
```
fixes the issue I was seeing with
```csharp
if (!foo.Any(r => r.Bar == bar))
{
   // code was previously not detected as covered, but now works with nighly.
}
```
Thank you for your effort! Looking forward to a Nuget.org release.

**Comment by MarcoRossignoli** [comment]
Glad to hear that, thanks for the test!
