### ISSUE TITLE
Change `CecilSymbolHelper` as instance class and inject with DI

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#774]
We don't like static stuff, we should avoid it, are not testable and more subject to race condition issues.
We should move `CecilSymbolHelper` to instance class extract an interface with only `GetBranchPoints` and `SkipNotCoverableInstruction` methods  and inject like other services.
We should remove static memebers https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L22

https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L19

**Comment by MarcoRossignoli** [comment]
cc: @daveMueller if you're interested.

**Comment by daveMueller** [comment]
> cc: @daveMueller if you're interested.

OK I would work on it. Could you assign it to me?

**Comment by MarcoRossignoli** [comment]
Sure thanks!
