### ISSUE TITLE
Coverlet report not generating for dotnet core project

### ISSUE THREAD

**Issue by WattsC-90** [coverlet-coverage/coverlet#776]
This appears to be a common ticket, so apologies if you roll your eyes and point me to an existing ticket..

I am running this in TeamCity:

```
dotnet test `
%teamcity.build.checkoutDir%\UnitTests\UnitTests.csproj `
--no-build `
-c Release `
-l "console;verbosity=normal" `
-a %teamcity.build.checkoutDir%\UnitTests\bin\Release\netcoreapp3.1 `
/p:CollectCoverage=true `
/p:CoverletOutputFormat=teamcity `
/p:CoverletOutput='./coverlet/'
```

in the build log, it is clearly generating the correct output (unfortunately have to show a partial screenshot due to this being work code *sigh*..)

![image](https://user-images.githubusercontent.com/10712792/77420258-a013f680-6dc1-11ea-896b-b6d66d842ad1.png)

but on the build agent, there is no report, in fact.. just an empty folder..

![image](https://user-images.githubusercontent.com/10712792/77420342-c2a60f80-6dc1-11ea-903f-3691dc335a70.png)

Can you help me out here? I am obviously getting the stats raw into TC, which is progress from an hour or so ago.. but I am clearly missing something somewhere!

**Comment by MarcoRossignoli** [comment]
No probs, welcome to coverlet repo,

out implementation of teamcity is based on service message https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Reporters/TeamCityReporter.cs

https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-Reporting.NETCodeCoverageResults

**Comment by WattsC-90** [comment]
ahh ok, so the way to get the full reporting in would be to use multiple formats?

**Comment by MarcoRossignoli** [comment]
> ahh ok, so the way to get the full reporting in would be to use multiple formats?

Yep...if you're using .NET core app you should use vstest plat integration https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md because other way suffer of known issues https://github.com/tonerdo/coverlet/blob/master/Documentation/KnownIssues.md

**Comment by WattsC-90** [comment]
Ok, thanks for the info.. bit unclear though with regards to: 

> vstest plat integration https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

can that be used in addition to the output format flags/properties above?

**Comment by MarcoRossignoli** [comment]
> can that be used in addition to the output format flags/properties above?

No no it's a complete different way to do coverage, coverlet is used through three "drivers"  msbuild(your way), .net tool and vstest integration.
Vstest integration is the most reliable(due to some test plat behaviour), so you should use the new way, take a look at our hello world sample https://github.com/tonerdo/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld

**Comment by MarcoRossignoli** [comment]
`runsetting.xml` is the way used by vstest platform to pass parameters in https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings

**Comment by MarcoRossignoli** [comment]
@WattsC-90 any news?Feel free to close if solved!

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed.
