### ISSUE TITLE
Object reference not set to instance of a object error

### ISSUE THREAD

**Issue by ashleybeshir** [coverlet-coverage/coverlet#780]
Hello,
we have multiple projects that are very similar but it seems on some of the projects when trying to run coverlet i get this error in the title. Object reference not set to instance of a object error. The error comes from "\coverlet.msbuild.target(7, 5): warning : [coverlet] unable to instrument module: *non test project name* because: Object reference not set to instance of a object error"

dotnet test --no-build --logger:trx --logger:xunit --results-directory *** /p:CollectionCoverage=true /p:CoverletOutput=*** /CoverletOutputFormat=cobertura /p:Exclude="[xunit.*]*"

All projects use this same line and we using latest version of
coverlet.collection
coverlet.msbuild
xunit test logger 
But i get a reference error on some of the projects. was wondering if their is a reason behind it

**Comment by MarcoRossignoli** [comment]
Can you try with vstest integration and upgrade to last version `1.2.0` https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by ashleybeshir** [comment]
Hey Marco,
i did what guide said and tried both dotnet test / vstest . The error is not their anymore but the generated code coverage file is a empty xml ? we have loads of test in the file . so their should be code coverage. the test and normal project target netcore 3.1 only . dont know if that would help

**Comment by MarcoRossignoli** [comment]
Can you share you test project csproj and the command line you used?Is the project open source?

**Comment by MarcoRossignoli** [comment]
Can you also enable logging https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration and share if possible, here or on a private github repository, because logging could expose sensitive data.

**Comment by MarcoRossignoli** [comment]
@ashleybeshir any news?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed.
