### ISSUE TITLE
Branch coverage is not showing the correct number

### ISSUE THREAD

**Issue by dannyBies** [coverlet-coverage/coverlet#800]
I have two different situations in which I believe the reported coverage is incorrect. Please let me know if this is the expected behaviour and if/how I could get these branches covered.

**Situation 1:**

![image](https://user-images.githubusercontent.com/3967506/78748760-ec198a80-79c0-11ea-8689-18e7aa945df2.png)
```
<method name="GetPendingInvitationsByTypeAsync" signature="()" line-rate="1" branch-rate="1" complexity="NaN">
  <lines>
    <line number="111" hits="18" branch="false" />
    <line number="112" hits="18" branch="false" />
    <line number="113" hits="18" branch="false" />
    <line number="114" hits="18" branch="false" />
    <line number="117" hits="18" branch="false" />
    <line number="121" hits="18" branch="false" />
    <line number="123" hits="18" branch="false" />
    <line number="124" hits="18" branch="false" />
  </lines>
</method>
```

I would have expected line 118, 119 and 120 to show coverage as well just like line 112, 113 and 114. I also expected that due to the .Where clause this would create multiple different branches.

**Situation 2:**

I'm using EFCore and calling AddAsync seems to have resulted in 2 different branches. 
![image](https://user-images.githubusercontent.com/3967506/78749274-07d16080-79c2-11ea-8eb7-5ea5c89a37ec.png)

**Comment by MarcoRossignoli** [comment]
Which version/driver are you using?

**Comment by dannyBies** [comment]
.NET Core sdk v3.1.201
coverlet.collector v1.2.1
coverlet.msbuild v2.8.1
Microsoft.NET.Test.Sdk 16.5.0
xunit v2.4.1
xunit.runner.visualstudio v2.4.1

**Comment by MarcoRossignoli** [comment]
Ok seem an issue on instrumentation, can you try to create a simple repro?

**Comment by dannyBies** [comment]
I've tried running ``` /p:CollectCoverage=true ``` and ```--collect:"XPlat Code Coverage"```. Both have the same issue.

Trying with version 2.8.0 and 1.2.0 does not fix the issue.
Downgrading to 2.7.0 and 1.1.0 resulted in:
![image](https://user-images.githubusercontent.com/3967506/78759244-779c1700-79d3-11ea-92d4-49854cdbc198.png)

which seems more reasonable. Even with the downgrade situation 2 is not working.

I'll see if I can create a repro now.

**Comment by MarcoRossignoli** [comment]
> I'll see if I can create a repro now.

Thank's

**Comment by dannyBies** [comment]
I've tried to create a repro at https://github.com/dannyBies/CoverletIssueRepro. Unfortunately it doesn't seem like I can get the issue to appear and I'm not sure why.

**Comment by MarcoRossignoli** [comment]
Ok np thank's a lot for your time/help, very appreciated!

**Comment by Bertk** [comment]
The issue might be out-dated because new releases are available.

Please reopen the issue if the bug still exists and can be reproduced with latest preview from [coverlet nightly build](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly).

see [Consume nightly build](https://github.com/coverlet-coverage/coverlet/blob/9295fca754531d6badd0185d0709d41a6eeddd5f/Documentation/ConsumeNightlyBuild.md)
