### ISSUE TITLE
Coverlet is not considering the excludefromCoverage attribute at method level

### ISSUE THREAD

**Issue by VenkateshSrini** [coverlet-coverage/coverlet#809]
Hi,
I'm using the Coverlet to measure .NET core 3.1 Web API code coverage. I have used entity framework for creating by repository. There are some methods have anonymous object as return types and hence could not be unit tested. I want those methods to be alone excluded from coverage so I used [ExlcudeFromCodeCoverage] on those methods only. But Coverlet is not considering that at all and still generated the code coverage for the same. Please see the method EditTask in the TaskRepo class as an example in the attached code.
[TaskApi.zip](https://github.com/tonerdo/coverlet/files/4465812/TaskApi.zip)

**Comment by MarcoRossignoli** [comment]
Thank's for repro, I'll take a look asap.

**Comment by MarcoRossignoli** [comment]
@VenkateshSrini can you tell me where is these method I searched `[ExlcudeFromCodeCoverage]` inside a solution but didn't found anything.

**Comment by MarcoRossignoli** [comment]
@VenkateshSrini any news?

**Comment by VenkateshSrini** [comment]
In the repository folder, there is a file called TaskRepo.cs. In that, there is a method called EditTask that has [ExcludeFromCodeCovergae]

**Comment by MarcoRossignoli** [comment]
I cannot see the attribute what am I missing?
![image](https://user-images.githubusercontent.com/7894084/81505303-74f05280-92ee-11ea-9fa0-a2a30382271a.png)

**Comment by VenkateshSrini** [comment]
N. I just downloaded the attached code bit I'ma able to see the same. Let me upload it once again
[TaskApi.zip](https://github.com/coverlet-coverage/coverlet/files/4606176/TaskApi.zip). please see the code below
![image](https://user-images.githubusercontent.com/1167152/81505552-ae848600-930d-11ea-81bf-fcd3117e3366.png)

**Comment by MarcoRossignoli** [comment]
Ok now I can repro, seems a bug, btw you cannot use `/p:ExcludeByAttribute="CompilerGenerated"` with new version because we fixed a bug and now you lose coverage with every async state machine generated https://github.com/coverlet-coverage/coverlet/issues/794#issuecomment-612067552

Thanks for reporting this.

**Comment by VenkateshSrini** [comment]
@MarcoRossignoli ,
But that cannot be the way forward that I loose coverage with every async statement. We need to have a standard way out of this problem. What would be your suggestion in such cases?

**Comment by MarcoRossignoli** [comment]
Why are you using that attribute filter?What do you want to filter out?

**Comment by sac80644** [comment]
Glad I found this thread.  I was just about to report this bug.  ExcludeFromCodeCoverage attribute seems to work for non-async methods but not async in my case.

**Comment by MarcoRossignoli** [comment]
Thanks for the information s

**Comment by VenkateshSrini** [comment]
@MarcoRossignoli ,
As you can see I want to exclude a few methods fro test coverage as I will not be able to write a proper test for these methods. The reason is they contain a complex inline LINQ query that could not be mocked. Also, those kinds of methods are tested in  Functional tests and from coverage statistics. Hence I'm decorating my method with  ExcludeFromCodeCovarge on async method.

**Comment by MarcoRossignoli** [comment]
@VenkateshSrini I understood I meant that you cannot use `CompilerGenerated` anymore as value for `/p:ExcludeByAttribute` because it will exclude also all async methods(unrelated to this bug on `ExlcudeFromCodeCoverage`), I saw it in your command line.

**Comment by VenkateshSrini** [comment]
ok. So how should I go about this in the current scenario

**Comment by MarcoRossignoli** [comment]
I'm fixing, for the moment you could use partials and put method you don't want into it and filter out with exclude by filename

**Comment by MarcoRossignoli** [comment]
Should be fixed, feel free to reopen if needed.

**Comment by romainf-ubi** [comment]
Is it possible that `[ExlcudeFromCodeCoverage]` only works with `coverlet.msbuild` package and not `coverlet.collector`?

**Comment by MarcoRossignoli** [comment]
> Is it possible that [ExcludeFromCodeCoverage] only works with coverlet.msbuild package and not coverlet.collector?

Engine is the same so I expect same behavior
