### ISSUE TITLE
Combine/Merge/Union/Collect results and print without running tests

### ISSUE THREAD

**Issue by PeterOeClausen** [coverlet-coverage/coverlet#822]
We have just begun using Coverlet for code coverage in the project I'm working on.

We have two NET CORE projects for testing, one "quick" for unit testing, and one "slow" for functional tests that queries a real database.

These two test projects run in parallel in a GitLab environment through GitLab pipeline jobs (which is like GitHub actions).

As these run in parallel, I do not believe `MergeWith` is an option, because it requires us to run one test project, then the next, combining with the first.

We want to collect Coverlet coverage reports and combine/merge/union/collect (many words for the same thing) the results and print them in a final pipeline job.

**Question:** Is there a way to run Coverlet in a way, to give it reports as arguments, to combine these, and then print the result?

I know that tools like ReportGeneration and Coveralls.io exists for combining reports and visualizing them for analysis. But what we want for now is just to print the result as if we were running tests, without having to re-run our tests. Is that currently possible?

**Comment by MarcoRossignoli** [comment]
> Question: Is there a way to run Coverlet in a way, to give it reports as arguments, to combine these, and then print the result?

No this is not supported at the moment, we're discussing about adding these features to coverlet dotnet tool driver https://github.com/tonerdo/coverlet/pull/704

There is also some plan of vstest team that in future could help with this(only if you run collectors version and run in parallel in the same "test session") https://github.com/microsoft/vstest/issues/1811.

**Comment by MarcoRossignoli** [comment]
Close for solved issue, feel free to re-open if needed!
