### ISSUE TITLE
Closing brace considered as not visited in async method

### ISSUE THREAD

**Issue by Giorgi** [coverlet-coverage/coverlet#823]
In my project I have an [async method SaveChangesAsync](https://github.com/Giorgi/EntityFramework.Exceptions/blob/ad59b8358fe41f27bb8870f9dc41cae76d54c409/EntityFramework.Exceptions.Common/ExceptionProcessorStateManager.cs#L54) which is identical to the [sync version of the method](https://github.com/Giorgi/EntityFramework.Exceptions/blob/ad59b8358fe41f27bb8870f9dc41cae76d54c409/EntityFramework.Exceptions.Common/ExceptionProcessorStateManager.cs#L35):

```
//Sync method
        public override int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            try
            {
                return base.SaveChanges(acceptAllChangesOnSuccess);
            }
            catch (DbUpdateException originalException)
            {
                var exception = GetException(originalException);

                if (exception != null)
                {
                    throw exception;
                }

                throw;
            }
        }
```

```
//Async method
        public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken())
        {
            try
            {
                return await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
            }
            catch (DbUpdateException originalException)
            {
                var exception = GetException(originalException);

                if (exception != null)
                {
                    throw exception;
                }

                throw;
            }
        }
```

Both of the methods are executed by the same set of tests but for the async method coverlet reports that the closing brace is not covered by the test. You can see the coverage here: [Coveralls coverage report](https://coveralls.io/builds/30220451/source?filename=C/projects/entityframework-exceptions/EntityFramework.Exceptions.Common/ExceptionProcessorStateManager.cs#L71)

I tried using nightly builds but the results is the same.

**Comment by MarcoRossignoli** [comment]
Thank's for reporting this

**Comment by MarcoRossignoli** [comment]
@Giorgi are you running coverage in `Release` if so you should run in `Debug` because compiler emits different metadata in pdb and it's not accurate with lines.
If you're running in `debug` I needs repro to understand because I did some tests in my local but I cannot see the issue https://github.com/coverlet-coverage/coverlet/compare/master...MarcoRossignoli:issue_823

![image](https://user-images.githubusercontent.com/7894084/87228766-97acef00-c3a3-11ea-887c-202c2e489731.png)

**Comment by Giorgi** [comment]
I switched to Debug mode but the result is the same: [https://coveralls.io/builds/32010193/source?filename=C%2Fprojects%2Fentityframework-exceptions%2FEntityFramework.Exceptions.Common%2FExceptionProcessorStateManager.cs#L71](https://coveralls.io/builds/32010193/source?filename=C%2Fprojects%2Fentityframework-exceptions%2FEntityFramework.Exceptions.Common%2FExceptionProcessorStateManager.cs#L71)

Also, in [UseExceptionProcessor](https://coveralls.io/builds/32010193/source?filename=C%2Fprojects%2Fentityframework-exceptions%2FEntityFramework.Exceptions.SqlServer%2FSqlServerExceptionProcessorStateManager.cs#L44) method lines with only the opening and closing braces are now being treated as relevant. Is that how it should be?

**Comment by MarcoRossignoli** [comment]
> Also, in UseExceptionProcessor method lines with only the opening and closing braces are now being treated as relevant. Is that how it should be?

Yep it's ok compiler emit pdb also with that line.

> I switched to Debug mode but the result is the same

I need a repro to understand, I cannot repro on my local(as you can see above) 😞

**Comment by Giorgi** [comment]
> 
> 
> > >Also, in UseExceptionProcessor method lines with only the opening and closing braces are now being treated as relevant. Is that how it should be?
> 
>> Yep it's ok compiler emit pdb also with that line in debug mode.
>
> I understand that compiler emits info about that line too but that line isn't really relevant right? Perhaps you can check for opening/closing braces and exclude those from relevant lines?
> 
> > I switched to Debug mode but the result is the same
> 
> I need a repro to understand, I cannot repro on my local(as you can see above) 😞

For the repro I don't think I can do better than the current repo that I have at [https://github.com/Giorgi/EntityFramework.Exceptions/](https://github.com/Giorgi/EntityFramework.Exceptions/)

**Comment by MarcoRossignoli** [comment]
> I understand that compiler emits info about that line too but that line isn't really relevant right? Perhaps you can check for opening/closing braces and exclude those from relevant lines?

Coverlet is language agnostic, I mean doesn't know if source code is C# F# or some other language that can compile in IL code, so we don't do any assumption on it, we work at IL level and simply map sequence point/branches with "line: reported on pdb.

> For the repro I don't think I can do better than the current repo that I have at https://github.com/Giorgi/EntityFramework.Exceptions/

Oh sorry I messed up this issue with another didn't see the repro 😅

**Comment by Giorgi** [comment]
Any updates on this issue?

**Comment by daveMueller** [comment]
Isn't this fixed by now? When I look at your most recent build.

https://coveralls.io/builds/37320328/source?filename=C%2Fprojects%2Fentityframework-exceptions%2FEntityFramework.Exceptions.Common%2FExceptionProcessorStateManager.cs#L63

![image](https://user-images.githubusercontent.com/19378678/108791959-899d8e80-7580-11eb-902e-275eb21c8f11.png)

**Comment by Giorgi** [comment]
Yes, looks like it has been fixed. Thanks!

**Comment by jeff-paredes** [comment]
@Giorgi What was your solution?
