### ISSUE TITLE
Coverlet is generating 0% line coverage

### ISSUE THREAD

**Issue by VenkateshSrini** [coverlet-coverage/coverlet#824]
Hi,
code coverage with coverlet.mbuild and .NET core 3.1 is giving issue. It is showing 0% code coverage when run using dotnet test command. The code can be been at 
https://github.com/VenkateshSrini/FSEPMAPI. 

The command that is used to generate code coverage is provided in runCoverage.cmd

**Comment by MarcoRossignoli** [comment]
I did some test and seem you're hitting know issue with msbuild driver https://github.com/tonerdo/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test
We have an old issue that uses RavenDB with same problem https://github.com/tonerdo/coverlet/issues/342
I did a test with vstest integration throught collectors and works https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md
![image](https://user-images.githubusercontent.com/7894084/80219509-de136d00-8642-11ea-81ee-660b0610bd3d.png)

**Comment by VenkateshSrini** [comment]
Is there some work around that I can adopt to get the report. I need this to be submitted to management

**Comment by MarcoRossignoli** [comment]
Yes as I've said you need to use collectors integration and not use msbuild follow guide https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

I cloned your repo, added to test project
```xml
 <PackageReference Include="coverlet.collector" Version="1.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```
Run from root repo
```
dotnet test --collect:"XPlat Code Coverage"
```
and with report generator I generated html reports in same way.

**Comment by VenkateshSrini** [comment]
Hi,
I tried it. It works well. I have only a small problem. I used the following code `dotnet test --collect:"XPlat Code Coverage" -r "_codeCoverage"` inside the _codeCoverage another directory whole name is a Guid is getting generated. It is becoming difficult to generate the reports as the GUID is unpredictable. Is there a way how we can avoid this GUID subdirectory

**Comment by MarcoRossignoli** [comment]
> Is there a way how we can avoid this GUID subdirectory

Unfortunately not, I opened an issue on vstest repo https://github.com/microsoft/vstest/issues/2378 it's not related to coverlet.

**Comment by MarcoRossignoli** [comment]
Feel free to close if resolved!

**Comment by MarcoRossignoli** [comment]
Close because solved!Feel free to re-open if needed!
