### ISSUE TITLE
MSBuild Integration not Cleaning Up Temp Folder?

### ISSUE THREAD

**Issue by Stefanie899** [coverlet-coverage/coverlet#827]
When coverlet runs for my solution, it generates a number of files in my `%localappdata%\Temp` folder. These files range from 50MB to 100MB, and there are ~15 each time it runs. This obviously adds up quickly given we are running tests with coverage every 2 hours (over 1GB of temp files every time).

I'm wondering if this is a bug or if we need to write a script to automate this (seems potentially dangerous if another process writes `.tmp` files to that folder, as there's no real way to determine which files came from coverlet). Currently we are manually cleaning up our Jenkins server periodically as it fills up the disk, which is not ideal.

Should the MSBuild integration be deleting these files after it finishes collecting coverage?

**Comment by MarcoRossignoli** [comment]
At the moment coverlet produce a tmp hit file that is removed after tests
https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L105

and backup/restore instrumented file that should be cleaned up
https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Helpers/InstrumentationHelper.cs#L184-L231
inside backup path https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Helpers/InstrumentationHelper.cs#L398-L404

Can you tell me which file you see?

**Comment by Stefanie899** [comment]
@MarcoRossignoli It's almost exclusively the tmp hit files. Occasionally it does appear that the backup/restore instrumented files are not cleaned up but that seems to be sporadic, the tmp hit files don't ever seem to clean up correctly.

I'm using `/p:CollectCoverage=true` and the version of my `coverlet.msbuild` package is `2.6.3`

**Comment by Stefanie899** [comment]
After further testing, this appears to already be resolved in version `2.8.1`. My bad, I should have verified that first 🤦 .

**Comment by MarcoRossignoli** [comment]
Glad to hear you solved!

**Comment by reaction1989** [comment]
@MarcoRossignoli i am hitting this with v2.8.1

I saw that you are logging warnings when you can not delete a file. Is there a way to see those warnings, or should they always be there in the console?

Sorry haven't digged to deep into this. 

My problem is that my C:\Windows\temp folder is increasing 1GB per day.

**Comment by MarcoRossignoli** [comment]
We have one place where we log if we cannot remove tmp coverage file, but I shouldn't be so big https://github.com/coverlet-coverage/coverlet/blob/570cfc971b5556e6a7930a05a53c5143d988c70c/src/coverlet.msbuild.tasks/CoverageResultTask.cs#L109

> My problem is that my C:\Windows\temp folder is increasing 1GB per day.

Can you tell me the name of files?

**Comment by reaction1989** [comment]
![image](https://user-images.githubusercontent.com/873751/81732760-3c3cae80-9491-11ea-87c8-805c25651b4f.png)

here is a picture from the folder

**Comment by MarcoRossignoli** [comment]
Can you open one and past a piece of content?

**Comment by reaction1989** [comment]
Here it is.

I stripped the content

`<CoveragePrepareResult xmlns="http://schemas.datacontract.org/2004/07/Coverlet.Core" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
	<Identifier>b83dcf6f-2d3d-43d0-bf2b-e079a3963be6</Identifier>
	<MergeWith i:nil="true"/>
	<Module>xxx</Module>
	<Results xmlns:a="http://schemas.datacontract.org/2004/07/Coverlet.Core.Instrumentation">
	<a:InstrumenterResult>
    </a:InstrumenterResult>
	</Results>
	<UseSourceLink>false</UseSourceLink>
</CoveragePrepareResult>`

**Comment by MarcoRossignoli** [comment]
Yep that is coverlet file, do you see any warning in console?Can you enable logging and check with msbuild logger viewer?Seem something related to file locking on your machine.
Guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration
Do you have antivirus?If so can you try to shutdown it?In past we listen some issue with antivirus or other tool.

**Comment by reaction1989** [comment]
Yes we have an Antivirus on that build machine. I will try to get it disabled and have a look again probably the files will get deleted :)

I do not have any warnings in my console. When disabling the antivirus does not help, i will try to active the logging over my cake build. 

Already ty for your fast replies

**Comment by MarcoRossignoli** [comment]
Let me know

**Comment by MarcoRossignoli** [comment]
@reaction1989  any news?Please can you file a new issue to avoid confusion with @Stefanie899 one?Thank you.
