### ISSUE TITLE
Update documentation for excluding source files from code coverage

### ISSUE THREAD

**Issue by Mikilll94** [coverlet-coverage/coverlet#830]
I have problems with excluding source files from code coverage.

Here is my file structure:
App.UnitTests -- runsettings.xml, <other irrelavant files>
 App                 -- obj, < project files >

I want to exclude from code coverage the `obj` folder which is located inside the `App` folder. So I have navigated in the terminal to `App.UnitTests` folder and executed this command:

```
dotnet test --collect:"XPlat Code Coverage" --settings runsettings.xml
```

Here is my `runsettings.xml` file.
```
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>cobertura</Format>
          <ExcludeByFile>../obj/**/*,</ExcludeByFile>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Unfortunately this is not working. The code coverage is including files in `obj` folder. Why is this happening? I will be glad for any help.

**Comment by MarcoRossignoli** [comment]
Can you try to enable verbose logging as explained here and copy/paste the result? https://github.com/tonerdo/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration
Is it the project OSS?A repro could be very useful in case.

**Comment by Mikilll94** [comment]
@MarcoRossignoli 
Unfortunately, it is not open source. Thus, I have a question for you.

I don't understand how relative paths work. If I have a configuration like this:
```
<ExcludeByFile>../MyFile.cs</ExcludeByFile>
```

What is the starting path for Coverlet when evaluating the relative path? Does Coverlet start from the same directory where `runsettings.xml` file is located?

Because in my case something is not working with relative paths.

**Comment by MarcoRossignoli** [comment]
We need to update the guide sorry, the filter is globbing one so you don't need to add `..` relative fragment, take a look at sample on code https://github.com/tonerdo/coverlet/blob/master/test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs#L290-L389
We use `Matcher` take a look at samples here https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=dotnet-plat-ext-3.1&viewFallbackFrom=aspnetcore-2.2

**Comment by Mikilll94** [comment]
@MarcoRossignoli 
Ok. Thanks for the response. Yeah, the docs need to be updated because they are very misleading, i.e. here:

https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md
https://github.com/tonerdo/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage

And the docs even explicitly says:
> Use absolute or relative paths (relative to the project directory)

So since the relative path is not working, right now I am using this filter:
```
**/obj/**/*
```

This filter excludes all files in the `obj` folder from code coverage.

**Comment by MarcoRossignoli** [comment]
I'll keep this open until doc fix.

**Comment by metacoder-feff** [comment]
@MarcoRossignoli 
This works:
              `  <Source>/obj/.*\.g\.cs$</Source>`

this is the pattern of the middle and the end of the path.
implicitly any begging of the path matches this pattern
