### ISSUE TITLE
Coverage results aren't stable

### ISSUE THREAD

**Issue by ViktorHofer** [coverlet-coverage/coverlet#834]
We (dotnet/runtime) recently switched from coverlet's global tool to `dotnet test` with the coverlet data collector. With the data collector driver I just noticed that the produce coverage results file isn't stable and varies between multiple invocations.

See the generated reports for five invocations of `C:\git\runtime\src\libraries\System.Text.RegularExpressions\tests>dotnet test -f netcoreapp5.0 /p:Coverage=true`: [coverage-RegularExpressions.zip](https://github.com/coverlet-coverage/coverlet/files/4580159/coverage-RegularExpressions.zip)

Something that immediately points out is the difference in the summary:
```
  <Summary numSequencePoints="10557" visitedSequencePoints="7413" numBranchPoints="4982" visitedBranchPoints="3491" sequenceCoverage="70.21" branchCoverage="70.07" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="53" numClasses="55" visitedMethods="727" numMethods="817" />
  <Summary numSequencePoints="10557" visitedSequencePoints="7431" numBranchPoints="4982" visitedBranchPoints="3516" sequenceCoverage="70.38" branchCoverage="70.57" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="53" numClasses="55" visitedMethods="727" numMethods="817" />
  <Summary numSequencePoints="10557" visitedSequencePoints="8415" numBranchPoints="4982" visitedBranchPoints="4107" sequenceCoverage="79.71" branchCoverage="82.43" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="54" numClasses="55" visitedMethods="768" numMethods="817" />
  <Summary numSequencePoints="10557" visitedSequencePoints="8181" numBranchPoints="4982" visitedBranchPoints="4029" sequenceCoverage="77.49" branchCoverage="80.87" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="54" numClasses="55" visitedMethods="758" numMethods="817" />
  <Summary numSequencePoints="10557" visitedSequencePoints="8376" numBranchPoints="4982" visitedBranchPoints="4092" sequenceCoverage="79.34" branchCoverage="82.13" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="54" numClasses="55" visitedMethods="768" numMethods="817" />
```

VSTest reports the same number of tests being discovered and executed for all the five runs:
```
Test Run Successful.
Total tests: 7204
     Passed: 7204
```

I'm wondering if hit points aren't correctly propagated back to the hits file?

cc @MarcoRossignoli @sharwell @petli @stephentoub

**Comment by MarcoRossignoli** [comment]
Can you attach command line/runsetting?

**Comment by MarcoRossignoli** [comment]
Could be related to other file lock issue, I'll take a look asap, bit busy week

**Comment by ViktorHofer** [comment]
I just compared the results with xunit.console and coverlet.console:

```
  <Summary numSequencePoints="10557" visitedSequencePoints="10258" numBranchPoints="4982" visitedBranchPoints="4652" sequenceCoverage="97.16" branchCoverage="93.37" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="55" numClasses="55" visitedMethods="807" numMethods="817" />
```

[xunitconsole_coverage.zip](https://github.com/coverlet-coverage/coverlet/files/4580663/xunitconsole_coverage.zip)

**Comment by ViktorHofer** [comment]
So the instrumentation is working as expected as the `numSequencePoints`, `numBranchPoints`, `maxCyclomaticComplexity`, `minCyclomaticComplexity`, `numClasses` and `numMethods` values are the same.

The visited ones differ largely...

**Comment by MarcoRossignoli** [comment]
Thanks for infos

**Comment by ViktorHofer** [comment]
> Could be related to other file lock issue, I'll take a look asap, bit busy week

Unsure if that's really the reason. Just cleared my temp directory and test outdir and ran the command again and now get: 

`<Summary numSequencePoints="10557" visitedSequencePoints="8994" numBranchPoints="4982" visitedBranchPoints="4285" sequenceCoverage="85.19" branchCoverage="86" maxCyclomaticComplexity="5476" minCyclomaticComplexity="5476" visitedClasses="54" numClasses="55" visitedMethods="796" numMethods="817" />`

The visited* numbers are still way too low. Any recommendation how to diagnose this further? How is coverlet.console behaving differently in respect to hitfile tracking than coverlet.collectors?

**Comment by MarcoRossignoli** [comment]
> How is coverlet.console behaving differently in respect to hitcount tracking than coverlet.collectors?

The only difference is that collectors does not rely on process exit to flush hits but using in proc collector 

https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.collector/InProcDataCollection/CoverletInProcDataCollector.cs#L46

The out of proc collector do same thing as msbuild instrumentation task

https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs#L135

**Comment by MarcoRossignoli** [comment]
Question, is possible that same instrumented sets of files run in more than one tests?

**Comment by ViktorHofer** [comment]
The instrumented assemblies are only used throughout one "test session". But this might have to do with our RemoteExecutor tooling which loads the test assembly as well.

**Comment by MarcoRossignoli** [comment]
If the issue is RemoteExectutor we try to find a way to avoid process exit flush in case of collectors usage because we can rely on in-proc flush at the end of tests.

**Comment by ViktorHofer** [comment]
@MarcoRossignoli we currently support both `xunit.console` and VSTest at the moment. I plan to obsolete the former as soon as all features are on parity. Ideally we can fix the non-stable results before 7/6 (which is the dotnet/runtime infrastructure rollout date after the next one). 

Do you believe https://github.com/coverlet-coverage/coverlet/pull/835 will fix this issue?

**Comment by MarcoRossignoli** [comment]
> Do you believe #835 will fix this issue?

Unfortunately cannot be sure until try some repro with fix on my local, next days I'll try to repro on my local your sample and come back.

cc: @tonerdo

**Comment by ViktorHofer** [comment]
> One question xunit.console run collectors?

No. We are using coverlet.console in combination with xunit.console. That's what we want to get rid off in the future when the coverage results become stable.

**Comment by MarcoRossignoli** [comment]
Ok so the drift between `xunit.console` and direct `dotnet test` is always using same coverlet engine underneath

**Comment by ViktorHofer** [comment]
> Ok so the drift between xunit.console and direct dotnet test is always using same coverlet engine underneath

Sorry not sure if I follow. Are you saying that the underlying engine isn't the same?

**Comment by MarcoRossignoli** [comment]
> Sorry not sure if I follow. Are you saying that the underlying engine isn't the same?

No no sorry, I wasn't clear, was a "state" it wasn't clear to me that `xunit.console` runs `coverlet.console`, I thought that the difference above were related to different coverage engine(like `xunit.console` has got something like that), my fault.
Are the same.

**Comment by ViktorHofer** [comment]
Got it.

> Do you believe #835 will fix this issue?

Just tried that and it doesn't help with this issue unfortunately.

**Comment by MarcoRossignoli** [comment]
Can you link here the branch with vstest settings?I saw your rollback, so I can try on my local asap.

**Comment by ViktorHofer** [comment]
I didn't roll anything back :) You can try it in dotnet/runtime master with:

```
build.cmd clr+libs -rc Release
dotnet test -f net5.0 /p:Coverage=true src\libraries\System.Text.RegularExpressions\tests\
```

**Comment by MarcoRossignoli** [comment]
> I didn't roll anything back :)

Ah I read PR above :) btw today it's hard to me, I'm a bit busy, I think during weekend I'll have more time to investigate.

**Comment by ViktorHofer** [comment]
Thanks a lot :)

**Comment by MarcoRossignoli** [comment]
Marked `as-designed` found that issue is a missing switch `--collect:"XPlat Code Coverage"`

@ViktorHofer feel free to close if solved.

**Comment by MarcoRossignoli** [comment]
@ViktorHofer any news?have you tried nightly?when you'll confirm correct behavior of coverage I'll release official package with deterministic build support cc: @clairernovotny

**Comment by MarcoRossignoli** [comment]
Solved
