### ISSUE TITLE
Build fails in bitbucket pipeline with solution testing and merged test results

### ISSUE THREAD

**Issue by johnabbott72** [coverlet-coverage/coverlet#838]
I have been trying coverlet in my .net core 2.1 solution in bitbucket pipelines and after this step it fails and all of the reports are generated and look good...  There is no error that I can see.  I had been playing with setting threshold values to get it to move to the next end step for sonarscanner but it just stops after the last test.  Any ideas?

dotnet test --filter "FullyQualifiedName~.Tests." /p:CollectCoverage=true /p:CoverletOutput="/build/TestResults/" /p:MergeWith="/build/TestResults/coverage.json"
            /maxcpucount:1 /p:CoverletOutputFormat="json%2copencover" /p:Threshold="0" /p:ThresholdStat="average"

**Comment by MarcoRossignoli** [comment]
Can you share your tests csproj?Do you run this command on sln folder?

**Comment by johnabbott72** [comment]
This is being run from the sln folder. Here is the contents of csproj:
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.3.0" />
        <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
        <PackageReference Include="Amazon.Lambda.TestUtilities" Version="1.1.0" />
        <PackageReference Include="coverlet.msbuild" Version="2.8.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="5.7.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
        <PackageReference Include="Moq" Version="4.13.1" />
        <PackageReference Include="xunit" Version="2.4.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\Platform.Shared.Test.Helpers\Platform.Shared.Test.Helpers.csproj" />
        <ProjectReference Include="..\..\shared\Platform.Lambda.ExternalStatus.Shared.Tests\Platform.Lambda.ExternalStatus.Shared.Tests.csproj" />
        <ProjectReference Include="..\Platform.Lambda.ExternalStatus.Update\Platform.Lambda.ExternalStatus.Update.csproj" />
    </ItemGroup>
</Project>

**Comment by johnabbott72** [comment]
Actually I have identified the problem we have a set of 16 shared tests projects that don't actually have tests in them.  I need to filter these out.  I apologize for not figuring this out earlier...

**Comment by MarcoRossignoli** [comment]
No problem, you can add this attribute to non tests project https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.tests.remoteexecutor/coverlet.tests.remoteexecutor.csproj#L8
