### ISSUE TITLE
Where is method coverage?

### ISSUE THREAD

**Issue by Mikilll94** [coverlet-coverage/coverlet#839]
On the main page of coverlet Github repo it is written:

> Coverlet is a cross platform code coverage framework for .NET, with support for <ins>**line, branch and method**</ins> coverage. It works with .NET Framework on Windows and .NET Core on all supported platforms.

However, I have noticed that in my case only line and branch coverage is calculated. The method coverage is not calculated. I don't know if I need to configure something to enable it or maybe coverlet just doesn't support method coverage.

**Comment by MarcoRossignoli** [comment]
Which report type are you using?

**Comment by Mikilll94** [comment]
@MarcoRossignoli 
Cobertura

**Comment by MarcoRossignoli** [comment]
```xml
 <class name="ClassLibrary1.Class1" filename="Class1.cs" line-rate="1" branch-rate="1" complexity="1">
          <methods>
            <method name="Method" signature="()" line-rate="1" branch-rate="1">
              <lines>
                <line number="8" hits="1" branch="False" />
                <line number="9" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="8" hits="1" branch="False" />
            <line number="9" hits="1" branch="False" />
            <line number="10" hits="1" branch="False" />
          </lines>
        </class>
```
`line-rate` and `branch-rate` 1 is 100% 
This is the code that calculate data https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Reporters/CoberturaReporter.cs#L68-L73

**Comment by Mikilll94** [comment]
Ok. But I would expect that coverlet should output total method coverage in % as it does for line and branch coverage.

So, in this XML we have `line-rate`, `branch-rate` and additionally there should be also `method-rate`.

**Comment by MarcoRossignoli** [comment]
Cobertura format AFAIK doesn't have that attribute and format spec is not designed by us.
If you find official cobertura spec with that attribute we'll add it.

**Comment by Mikilll94** [comment]
@MarcoRossignoli 
Ok, thanks. I have checked the Cobertura format and it does not provide method coverage.

IMO, It would be nice to include in the docs a brief overview of all code coverage formats supported by coverlet. For every format there should be:
- short description
- supported metrics
- source link
- and maybe some other stuff

**Comment by MarcoRossignoli** [comment]
Thanks for the advice we have the list inside msbuild command https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverage-output but I agree that a shared section on readme could be useful!
I'll keep this open for documentation

**Comment by MarcoRossignoli** [comment]
Feel free to propose a PR if you want also on documentation!

**Comment by MarcoRossignoli** [comment]
For now I think we won't add docs on reports, are not under our handling and so they can change also in future, would be good add some external reference to the docs.
