### ISSUE TITLE
Support for Visual Studio .coverage format

### ISSUE THREAD

**Issue by Mikilll94** [coverlet-coverage/coverlet#840]
Right now on Azure DevOps the pull request code coverage is supported only for Visual Studio .coverage format.

You read about that here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops

>  Note
> 
> While you can collect and publish code coverage results for many different languages using Azure Pipelines, the code coverage for pull requests feature discussed in this document is currently available only for .NET and .NET core projects using the Visual Studio code coverage results format (file extension .coverage). Support for other languages and coverage formats will be added in future milestones.

It would be nice if coverlet supports Visual Studio .coverage format.

**Comment by MarcoRossignoli** [comment]
cc: @jakubch1 do you know where I can find the format specification?

**Comment by jakubch1** [comment]
.coverage format is not public and there is no specification for it. Probably in near future we will stop generating it and move to cobertura. So it doesn't make sense to invest into it.

**Comment by MarcoRossignoli** [comment]
Thank's for the anwer.
@Mikilll94 I'm going to close this issue as Jakub said there is no sense to invest in new format.
