### ISSUE TITLE
Test Inheritance not recognized in coverage calculation?

### ISSUE THREAD

**Issue by ervinpeters** [coverlet-coverage/coverlet#842]
I had some database tests on a project, which works fine and sonarqube then recognized a test coverage around 80%. Then I moved the tests to an abstract base class to be able to vary the whole testclass setup by overriding testclass construction or testinitialization.
VS Test explorer still finds, displays and executes all the tests as expected. But the code coverage displayed in sonarcube went down to zero. Same is shown in the pipeline log at "generating coverage results".

```csharp
[TestClass]
public concreteTestClass : abstractBaseClass {

    public concreteTestClass() {}

    [TestInitialize]
    public override void initContext(){}
}

public abstract class abstractBaseClass 
{
    ...

    [TestInitialize]
    public virtual void initContext()
    {
        ...
    }

    [TestMethod]
    public void read_and_count_inserted_values()
    {}
}
```
Though I have no ressources now to explore that deeper, it might be of interrest.

**Comment by MarcoRossignoli** [comment]
Can you tell me the driver are you using msbuild/vstest/.net tool?Can  you attach command line?

**Comment by ervinpeters** [comment]
invalid, it was an accidential change in csproj. Excuse the noise.
