### ISSUE TITLE
Nunit and coverlet

### ISSUE THREAD

**Issue by santhosh-James** [coverlet-coverage/coverlet#843]
Is it possible to generate code coverage from Nunit functional tests?

Here the test solution and the Application under test is two different application. Does this work in coverlet? Or coverlet just handle the unit test ?

**Comment by MarcoRossignoli** [comment]
If you're referring to something like https://github.com/coverlet-coverage/coverlet/issues/781 no at the momento coverlet is not usable as "stand alone" so you cannot instrument dll put it on line and do coverage testing outside a classic test project.

Let me know if I understood well.

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to close if needed!
