### ISSUE TITLE
All async methods seems to be excluded in coverlet.msbuild 2.8.1

### ISSUE THREAD

**Issue by PolarbearDK** [coverlet-coverage/coverlet#845]
Just upgraded from coverlet.msbuild 2.6.3 to 2.8.1.
Report no longer shows coverage for any methods with the **async** keyword

This is the most simple example I could find in our code base:
```CSharp
public async Task<ConductedInterview[]> GetConductedInterviews(Guid citizenId)
{
  return (await GetInterviewInfo(citizenId)).Conducted;
}
```
The async methods were covered/not covered in 2.6.3. 
With 2.8.1 they are ignored (grey in report).

**Comment by MarcoRossignoli** [comment]
Are you using `/p:ExcludeByAttribute=CompilerGeneratedAttribute`?Possible dup of https://github.com/coverlet-coverage/coverlet/issues/794

**Comment by PolarbearDK** [comment]
We do indeed have that exclution. Looks much better without it.
