### ISSUE TITLE
Coverlet Generating empty reports

### ISSUE THREAD

**Issue by Trejden** [coverlet-coverage/coverlet#847]
Hello,
I'm running tests with this command:
`dotnet test -c Release --logger trx --results-directory (path to repo)\TestResults --collect:"XPlat Code Coverage" --settings (path to repo)\codecoverage.runsettings
`
the code coverage settings:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage">
        <Configuration>
          <Format>json,cobertura</Format>
          <Include>.*(common prefix of all csproj files in the solution).*</Include><!-- [Assembly-Filter]Type-Filter -->
          <ExcludeByAttribute>ExcludeFromCodeCoverageAttribute,Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

libraries referenced in unit tests:
```
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="Moq" Version="4.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.1" />
    <PackageReference Include="coverlet.collector" Version="1.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

report generated looks like this:
cobertura:
```
<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="1" branch-rate="1" version="1.9" timestamp="1589460377" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">
  <sources />
  <packages />
</coverage>
```
json:
`{}`

couple of notes: results are same wether or not I use the --collect:"XPlat Code Coverage", and even on Microsoft.Net.Test.Sdk 16.5.0 (as it is in the guide), friends of mine running same configuration and calls by with tests on xunit, have their reports generated correctly, as well as other friends who share identical configuration, but instead of having tests scattered around the multiple projects have it all condensed into single megaproject. I attempted to remove all but one test projects and it still failed to generate any report.

Best Regards
Trejden

**Comment by MarcoRossignoli** [comment]
Can you try to check logs to understand if the filters are the issue? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

You should see all coverlet log starting with `[coverlet]`. Log reports all instrumented/non instrumented assemblies

**Comment by Trejden** [comment]
Hello, Thanks for response.

I've run the tests with logging enabled, and I don't see any indication of anything going wrong in there. What exactly am I looking for?

The only reference to filters in those logs:

> TpTrace Verbose: 0 : 22536, 1, 2020/05/15, 09:27:20.038, 1516178970352, datacollector.dll, [coverlet]Excluded module filter '[coverlet.*]*'
> TpTrace Verbose: 0 : 22536, 1, 2020/05/15, 09:27:20.039, 1516178974159, datacollector.dll, [coverlet]Included module filter '[*](common project name prefix).*'

the next log with [coverlet] is

> TpTrace Verbose: 0 : 22536, 1, 2020/05/15, 09:27:23.141, 1516209996527, datacollector.dll, [coverlet]CoverletCoverageDataCollector: SessionEnd received
> TpTrace Information: 0 : 22536, 1, 2020/05/15, 09:27:23.309, 1516211682477, datacollector.dll, [coverlet]CoverletCoverageDataCollector: Saved coverage report to path: '(filepath)\coverage.json'

I have also asked friends who have it working to generate some log files for comparision, will see how their logs differs.

I don't see any listing of instrumented/noninstrumented assemblies per name listed in those logs.

**Comment by MarcoRossignoli** [comment]
You should see a log with `[coverlet]Instrumented...` with the name of the library instrumented and skipped

**Comment by Trejden** [comment]
I see no such logs in there. Word "Instrumented" does not show up even once in neither of logs generated

**Comment by MarcoRossignoli** [comment]
I mean something like 
```
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.884, 12831152271, datacollector.dll, [coverlet]Instrumented module: 'F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\ClassLibrary1.dll'
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.888, 12831186268, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.assert.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Assert.cs]
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.888, 12831190552, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.core.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\common\ExceptionExtensions.cs]
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.891, 12831222117, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.execution.dotnet.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs]
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.892, 12831226699, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.runner.reporters.netcoreapp10.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.runner.reporters\Utility\EnvironmentHelper.cs]
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.893, 12831233436, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.runner.utility.netcoreapp10.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.runner.utility\Extensions\DisposableExtensions.cs]
TpTrace Verbose: 0 : 14056, 1, 2020/05/15, 12:42:05.893, 12831239010, datacollector.dll, [coverlet]Unable to instrument module: F:\git\coverlet\Documentation\Examples\VSTest\HelloWorld\XUnitTestProject1\bin\Debug\netcoreapp3.1\xunit.runner.visualstudio.dotnetcore.testadapter.dll, embedded pdb without local source files, [C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\Utility\ExceptionExtensions.cs]
```

Unable messages are ok we instrument only dll with local sources. 
So do you see correct dll instrumented?

**Comment by Trejden** [comment]
I do not see any of such listings in most of my log files (it creates separate file for each test project) and in one it lists only project that would be in exclude listings if I was not troubleshooting lack of coverage results.

So if I understand you correctly the core issue is that none of dll's get's actually instrumented?
What could be reason for failure to instrument most of dll's except the one that would be irrelevant for coverage? I don't see any noticeable differences between that one project and the rest of them.

**Comment by MarcoRossignoli** [comment]
Every test project emits different logs and will produce one reports for every test project. If your report is empty usually is due to no dll instrumented but we can understand it looking at log file by file, the `*collector*` ones.

**Comment by Trejden** [comment]
[coverletlog1.txt](https://github.com/coverlet-coverage/coverlet/files/4634813/coverletlog1.txt)
[coverletlogs2.txt](https://github.com/coverlet-coverage/coverlet/files/4634814/coverletlogs2.txt)
here are two "types" of logs I am seeing in these executions narrowed down to just [coverlet] entries and with confidential information snipped out.
in one there is irrelevant library instrumented (occurs in two test projects using this library, the other (all the rest of the executions) nothing gets instrumented.

**Comment by MarcoRossignoli** [comment]
I cannot see dll instrumented can you try to remove completely che include filters and excludeByAttribute?

**Comment by Trejden** [comment]
I tried removing include filter(same results), will try removing excludeByAttribute

**Comment by MarcoRossignoli** [comment]
> EDIT: I have tried a run without either include or exclude markers in settings, (only format) and the only change in the logs is that there is less excludes/includes listed in configuration part of the logs.

Ok can you attach the logs?The issue I see is that you're not instrumenting any dll so the coverage will be null

**Comment by Trejden** [comment]
Sorry for very late response,
After Your latest request for logs I've decided to generate new ones and I have noticed some relevant dll's finally being instrumented in the logs. Seeing progress I have deployed the scan in the pipeline (as we usually do) but the results got interpreted as empty. as I have been fiddling with generating and publishing logs from the agent, I have noticed that one of the consumer of the reports started showing coverage when I have dropped <format>json,cobertura</format> line from the settings.
here is the log from that execution:
[coverletpipelinelog.txt](https://github.com/coverlet-coverage/coverlet/files/4710056/coverletpipelinelog.txt)
but as soon as I have readded the format line this happened:
[coverletpipelinelog2.txt](https://github.com/coverlet-coverage/coverlet/files/4710102/coverletpipelinelog2.txt)
and empty reports were generated again.
at this point I have noticed include/exclude flags are back in, so I removed them, and results were exactly same.
[coverletpipelinelog3.txt](https://github.com/coverlet-coverage/coverlet/files/4710109/coverletpipelinelog3.txt)
Interesting bit I find in there is that despite the fact that pipeline was run on commit version that removed the include/exclude filters completely, coverlet initialized as if they were still there. And coverage results published were empty in both formats

**Comment by Trejden** [comment]
Ok it turns out my previous post is not exactly correct - cobertura reports were published after all 3 executions, the interpreted just lagged with showing them. It's only json report that's empty (or consumed as empty)

**Comment by Trejden** [comment]
and another update because whole things starts to get really confusing what works where exactly and which file is a problematic.

so in overal what works:
Azure pipeline (whichever file format it uses) receives non-empty code coverage result.
Sonarqube (which claims to be reading file "coverage.cobertura.xml" receives empty coverage result

**Comment by Trejden** [comment]
ok, after verifying coverage files from the pipeline it appears that whatever issue was, it no longer is a case as coverlet has just generated valid coverage files, it's just one of consumers of the reports (SonarQube) for some reason does not parse it correctly

**Comment by MarcoRossignoli** [comment]
Ok so you've verified that coverlet generates non empty xml file?if you want to validate content you could try to use different generation tool like reportgenerator https://www.palmmedia.de/OpenSource/ReportGenerator

**Comment by Trejden** [comment]
Yes, as of now coverlet generates non-empty xml file. Data provided seems valid. Thank You for Your assistance.

**Comment by jkone27** [comment]
also, have this issue, what was the solution? on mac net7 SDK 7.0.401, .net6 proj
