### ISSUE TITLE
Deterministic build results in missing coverage

### ISSUE THREAD

**Issue by danielpalme** [coverlet-coverage/coverlet#850]
I'm trying to setup a deterministic build with code coverage. After wasting several hours I was not able to create a working setup.

I followed this sample project:
https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/MSBuild/DeterministicBuild

As soon as I enable the deterministic build in `Directory.Build.props`:
```xml
  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
```

Coverage is no longer available. Output of `dotnet test /p:CollectCoverage=true /p:DeterministicSourcePaths=true`:  
```
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+
```
I created a sample project here:
https://github.com/danielpalme/DeterministicBuild

The CI pipeline results are here:
https://github.com/danielpalme/DeterministicBuild/actions?query=is%3Asuccess

The latest build is 'Deterministic' and coverage is missing (see step ` Run tests with coverage`)

Any ideas what's wrong in my setup? Any help is really appreciated.

**Comment by MarcoRossignoli** [comment]
We havent released official package yet you've to use nightly https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by danielpalme** [comment]
Thanks. Will try the nightly build.
