### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by DaGrisa** [coverlet-coverage/coverlet#865]
Hi,

every now and then we get the following error:
```
Test Run Successful.
07:15:22
    Total tests: 23
07:15:22
         Passed: 23
07:15:22
     Total time: 31.4479 Seconds
07:15:22
    07:15:22
    Calculating coverage result...
07:15:22
    C:\Users\teamcity\.nuget\packages\coverlet.msbuild\2.8.1\build\coverlet.msbuild.targets(36,5): error : Unable to read beyond the end of the stream.
07:15:22
    C:\Users\teamcity\.nuget\packages\coverlet.msbuild\2.8.1\build\coverlet.msbuild.targets(36,5): error :    at System.IO.BinaryReader.InternalRead(Int32 numBytes)
07:15:22
    C:\Users\teamcity\.nuget\packages\coverlet.msbuild\2.8.1\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.Core.Coverage.CalculateCoverage() in c:\git\coverletToRelease\src\coverlet.core\Coverage.cs:line 355
07:15:22
    C:\Users\teamcity\.nuget\packages\coverlet.msbuild\2.8.1\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.Core.Coverage.GetCoverageResult() in c:\git\coverletToRelease\src\coverlet.core\Coverage.cs:line 137
07:15:22
    C:\Users\teamcity\.nuget\packages\coverlet.msbuild\2.8.1\build\coverlet.msbuild.targets(36,5): error :    at Coverlet.MSbuild.Tasks.CoverageResultTask.Execute() in c:\git\coverletToRelease\src\coverlet.msbuild.tasks\CoverageResultTask.cs:line 113
```

We have a solution with multiple projects, but this happens not always at the same project.

Coverlet version: coverlet.msbuild:2.8.1
Test SDK version: Microsoft.NET.Test.Sdk:16.5.0

I've seen issues with the same problem here, but none of the solutions worked so far.

Best regards,
Daniel

**Comment by MarcoRossignoli** [comment]
You're hitting know issue https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test
You should use collectors integration https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md(released `1.3.0` version some days ago so update the reference).

**Comment by MarcoRossignoli** [comment]
any news?

**Comment by DaGrisa** [comment]
Yes, thank you, now it works for us.

**Comment by jeoffm** [comment]
i tried the fix & it worked once, but has continued to fail since

**Comment by MarcoRossignoli** [comment]
> i tried the fix & it worked once, but has continued to fail since

What do you mean?Can you post command line?

**Comment by jeoffm** [comment]
> > i tried the fix & it worked once, but has continued to fail since
> 
> What do you mean?Can you post command line?

in my azure devops pipeline, i had a task to ensure coverlet.msbuild was included/updated:
dotnet add package coverlet.msbuild

and then my next step was to run the dotnet test command
so i inserted a task between the 2 to ensure the coverlet.collector was included/update:
dotnet add package coverlet.collector

so the order was:
1. update msbuild
2. update collector
3. run tests

this worked on the first run, but failed on the next 2, however after reordering steps 1 & 2 (now collector is 1st), it seems to be working every time :), Oh, I also changed my build configuration from Release to Debug. Anyway for the moment I think it's all good, thanks, sorry to have bugged you

**Comment by MarcoRossignoli** [comment]
@jeoffm can you open another issue?This is resolved.

You MUST use collectors only integration if you want to avoid this issue, no msbuild reference. Follow this guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md and this sample https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld

**Comment by MarcoRossignoli** [comment]
Hi @matteotrapani 

If you're suffering of this issue yep, you should move to the collector integration or the dotnet tool where the testhost shutdown is "correctly" coordinated between the test platform and coverlet

**Comment by matteotrapani** [comment]
Wow, thank you for your quick response :D 
What I don't understand is: what do you mean by "collector integration"? And so you're telling me to remove coverlet references from our project?

**Comment by MarcoRossignoli** [comment]
Here you can find how the "data collector testing platform integration" is setup https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by matteotrapani** [comment]
Ok, I may finally understood what you mean :D 
The usage of `--collect:"XPlat Code Coverage";Format=opencover` rather than `/p:CollectCoverage=true /p:CoverletOutputFormat=opencover` actually uses the data collector as we should. Is it correct?
(I'm making different tests meanwhile and it actually seems more stable this way)

**Comment by MarcoRossignoli** [comment]
> The usage of --collect:"XPlat Code Coverage";Format=opencover rather than /p:CollectCoverage=true /p:CoverletOutputFormat=opencover actually uses the data collector as we should. Is it correct?

Yes...the `/p:CollectCoverage` is using the MSBuild infrastructure and can lead to the issue you saw...the --collect:"XPlat Code Coverage;Format=opencover" is using another type of integration point offered by the VSTest platform that will correctly work and solve the issue. The features are the same, the coverage engine are shared and are the same.
