### ISSUE TITLE
No coverage for Integration Tests

### ISSUE THREAD

**Issue by bottocusbr** [coverlet-coverage/coverlet#867]
I have a dotnet core 3.1 webapp and have unit tests and integration tests setup. Coverlet works for the unit tests perfectly, but the code the integration tests are testing are being reported as not being covered at all.

The integration tests are for some controller methods which in turn call some business logic in separate project (within the same solution).

Here's the output of coverlet.console:

	Instrumented module: 'C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Api.dll'
	Instrumented module: 'C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Application.dll'
	Instrumented module: 'C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Domain.dll'
	Instrumented module: 'C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Persistence.dll'
	Test run for C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Api.IntegrationTests.dll(.NETCoreApp,Version=v3.1)
	Microsoft (R) Test Execution Command Line Tool Version 16.5.0
	Copyright (c) Microsoft Corporation.  All rights reserved.
	Starting test execution, please wait...
	A total of 1 test files matched the specified pattern.
	Test Run Successful.
	Total tests: 3
		 Passed: 3
	 Total time: 2.3391 Seconds

	Calculating coverage result...
	Hit file 'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Api_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' deleted
	Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Application_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Application'
	Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Domain_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Domain'
	Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Persistence_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Persistence'
	  Generating report 'C:\git\myapp\Requests\coverage.json'
	+------------------------------------+--------+--------+--------+
	| Module                             | Line   | Branch | Method |
	+------------------------------------+--------+--------+--------+
	| myapp.Requests.Api         | 90.47% | 70%    | 90.9%  |
	+------------------------------------+--------+--------+--------+
	| myapp.Requests.Application | 0%     | 0%     | 0%     |
	+------------------------------------+--------+--------+--------+
	| myapp.Requests.Domain      | 0%     | 100%   | 0%     |
	+------------------------------------+--------+--------+--------+
	| myapp.Requests.Persistence | 0%     | 0%     | 0%     |
	+------------------------------------+--------+--------+--------+

	+---------+--------+--------+--------+
	|         | Line   | Branch | Method |
	+---------+--------+--------+--------+
	| Total   | 33.85% | 35%    | 13.88% |
	+---------+--------+--------+--------+
	| Average | 22.61% | 42.5%  | 22.72% |
	+---------+--------+--------+--------+

I ran coverlet with the following command in Visual Studio:

	coverlet C:\git\myapp\Requests\Api.IntegrationTests\bin\Debug\netcoreapp3.1\myapp.Requests.Api.IntegrationTests.dll --verbosity detailed --target "dotnet" --targetargs "test C:\git\myapp\Requests\Api.IntegrationTests\Api.IntegrationTests.csproj --no-build"

and here's the Api.IntegrationTests.csproj package ref:

	<PackageReference Include="coverlet.msbuild" Version="2.9.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>

I am expecting to see results for myapp.Requests.Application which is where the business logic is.

Some more background, we are using a CQS pattern with MediatR in our controller to send commands/requests. The Command objects and handlers are all held in Application project.
Each integration test calls an end point on the controller using an HttpClient.

I will try and get a simple repro project setup, but for now any help would be appreciated.

**Comment by MarcoRossignoli** [comment]
> Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Application_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Application'
Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Domain_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Domain'
Hits file:'C:\Users\user1\AppData\Local\Temp\myapp.Requests.Persistence_9f522bf0-fe26-4bb1-b1af-eca3b0cb45b4' not found for module: 'myapp.Requests.Persistence'


Can you use collector integration?These messages are suspecting I think you're hitting known issue https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test
Take a look at guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by bottocusbr** [comment]
Thanks @MarcoRossignoli using the collector works perfectly! I also have it working on our build pipeline too.
Thanks for you help
