### ISSUE TITLE
Assemblies loaded at runtime break with coverlet.collectors on MacOS / Linux

### ISSUE THREAD

**Issue by jherby2k** [coverlet-coverage/coverlet#868]
Hi, weird issue that's only happening for me in CI (Azure Devops), and only on MacOS and Linux build machines.

I switched to using coverlet.collectors to work around the known issue, and it works fine except when add an IncludeDirectory in my runsettings which refers to assemblies loaded at runtime. This works fine under Windows, and i get code coverage results for my extension assemblies.

On MacOS, i'm seeing

`  Error Message:
   System.BadImageFormatException : Index not found. (Exception from HRESULT: 0x80131124)
`

On Linux, the test host process simply crashes.

These tests work fine if i remove the IncludeDirectory option. It seems like instrumenting the assemblies is breaking them in some way that prevents me from dynamically loading them. On Mac and Linux.

This all worked fine when i was using the old msbuild method. Been trying to reproduce on a Linux VM without success - seems CI-specific.

**Comment by MarcoRossignoli** [comment]
> IncludeDirectory in my runsettings which refers to assemblies loaded at runtime.

Some questions:
Are the dll inside a custom dir under bin/debug?
Are you running more than one test project in parallel?

**Comment by jherby2k** [comment]
the DLLs are in a totally separate folder under %LOCALAPPDATA%, although they're built as part of the same solution. Tests aren't run in parallel, no.

It's all at https://github.com/jherby2k/AudioWorks. If you click on the DEV build tags you should be able to see where its failing. The test command line is:

`/usr/bin/dotnet test /home/vsts/work/1/s/AudioWorks/AudioWorks.sln --logger trx --results-directory /home/vsts/work/_temp --framework netcoreapp3.1 --configuration Release --no-build --collect:"XPlat Code Coverage" --settings /home/vsts/work/1/s/netcoreapp3.1.runsettings`

(we run the same command again under netcoreapp2.1, but it fails the same).

**Comment by MarcoRossignoli** [comment]
Can you try to appen `-nr:false -m:1` to your command?

**Comment by MarcoRossignoli** [comment]
> Tests aren't run in parallel, no.

You have more than one test project and run command from sln so every test project run in a custom process and tests run in parallel(I mean more than one project at same time) and if all are using same include directory maybe there is an issue on concurrent assembly instrumentation.

**Comment by jherby2k** [comment]
the console output is sequential so i'd assume it was not in parallel, but let me try changing that.

So interestingly, i looked at the Windows output and although i get valid code coverage results for my "extensions", i do see a bunch of errors like this in the console:

' Data collector 'XPlat code coverage' message: [coverlet]Coverlet.Collector.Utilities.CoverletDataCollectorException: CoverletCoverageDataCollector: Failed to get coverage result
 ---> System.AggregateException: One or more errors occurred. (The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\AudioWorks\Extensions\netcoreapp3.1\AudioWorks.Extensions.Flac.Windows.1.8.1\AudioWorks.Extensions.Flac.dll' because it is being used by another process.)'

**Comment by MarcoRossignoli** [comment]
> the console output is sequential so i'd assume it was not in parallel, but let me try changing that.

Console is synched so you see one write line at time.

**Comment by jherby2k** [comment]
Oh wow, okay, so this seems to be my problem *facepalm*. What out of curiosity does `-nr:false -m:1` do? You can close this i believe.

**Comment by MarcoRossignoli** [comment]
`-nr:false` tell to msbuild to not reuse process for different test run
`-m:1` max parallel worker process(max tests in parallel) https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild?view=vs-2019

**Comment by MarcoRossignoli** [comment]
Feel free to close!

**Comment by jherby2k** [comment]
Not sure if those msbuild switches fix it or not, but I just broke the test projects out into separate steps which seems to work well.

**Comment by MarcoRossignoli** [comment]
I think that separate steps means not overlapped instrumentation so no race condition
