### ISSUE TITLE
Consolidate drivers versions 

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#874]
Release workflow for coverlet is not simple due to different versions of drivers.
Now that we're ready to sign our package the things will be worse.
My proposal and after @clairernovotny's advice is to consolidate coverlet version since next release `3.0.0` to allow automatic sign/deploy from pipeline.
Sure, we have different features supported for different drivers, but we can document with a md.

Possible new release workflow:
1) Move all version on master to `x.x.x-preview.{height}` and release on nightly release once a day if there are new commits.
2) When release remove `-preview.{height}` create a release  branch `rel/vx.x.x` where we fix the version on `version.json` of packages.
3) Update pipeline to manual release a signed version to nuget directly from release branch.

@tonerdo can you enable master protection(merge only using PR)?So I can work using branch(no more fork) without fear 😄 
@clairernovotny can you take a look at plan and give further advice if you see something wrong or improvable?

**Comment by MarcoRossignoli** [comment]
ping @tonerdo

**Comment by tonerdo** [comment]
No idea how to enable branch protection. Any pointers?

**Comment by MarcoRossignoli** [comment]
@tonerdo added protected branch for master https://github.com/coverlet-coverage/coverlet/settings/branches 1 approver no direct push allowed to master also for admin.

**Comment by tonerdo** [comment]
@MarcoRossignoli one question. What happens when we have to make a patch to a single driver, do we have to update the version numbers of the other drivers as well?

**Comment by MarcoRossignoli** [comment]
Yep, if we consolidate we'll lose the "per driver patch" and we should release all drivers every time we fix one.
This is the "only" drawaback.

**Comment by petli** [comment]
In case you're waiting on my opinion here, I think this all looks good.

**Comment by tonerdo** [comment]
@MarcoRossignoli I'm willing to allow this since it better answers the question "What feature set of coverlet am I currently using?". Feel free to implement this in the next release
