### ISSUE TITLE
Include/Exclude Priority Help

### ISSUE THREAD

**Issue by antoinne85** [coverlet-coverage/coverlet#878]
First of all, thanks to everyone who's worked to make this project what it is. Super cool stuff.

I was hoping you'd help me pin down an issue I'm having with my folder layout and includes/excludes lists.

I've got a folder/project structure similar to:
```
root/
├── DomainA/
│   ├── DomainA.Service/
│   ├── DomainA.Client/
│   ├── DomainA.Tests/
├── DomainB/
│   ├── DomainB.Service/
│   ├── DomainB.Client/
│   └── DomainB.Tests/
└── Shared/
    ├── Shared.LibraryC/
    └── Shared.LibraryD/
```

In our setup, each domain folder has its own build/test/deploy pipeline. As part of that, when we're running the pipeline for a domain, we run the tests from that domain and are hoping to get the code coverage _just for that domain_.

Currently, because the domains reference projects from other domains (the `.Client` projects) as well as shared libraries from the `/Shared` folder, the entire project reference hierarchy winds up in the code coverage results. Makes sense.

I'm trying to pare that back so that we only show the code coverage for the projects inside that particular domain. So, for example, if I'm building/testing the projects in `DomainA`, only the projects in that folder would appear in the code coverage results. (Presumably the code coverage and test results for the projects they depend on would appear in the pipeline for their specific domain.)

I've tried several things so far without any luck. Because the _exclude_ rules take precedence over the _include_ rules, it seems I'm limited to explicitly calling out every assembly that I don't want included in the code coverage results (which would require me to recursively examine the project references to build the list).

Things that I've considered so far that seem like they might work:
* I could try to exclude by file/folder, which would require me to examine the folders on disk to build a list of folders to exclude at test-run time.
* I _could_ recursively examine the project references to build an assembly exclusion list, but this seems like overkill when the previous option nets roughly the same result.

Are there other options out there that I've not yet thought of?

I realize that this isn't actually a _problem with Coverlet_, so thank you in advance for any help you're able to provide.

**Comment by MarcoRossignoli** [comment]
If you include only your desired lib something like `[DomainB*]*` you should get coverage only for all asm start with `DomainB`

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed!
