### ISSUE TITLE
Force specific path?

### ISSUE THREAD

**Issue by ffMathy** [coverlet-coverage/coverlet#879]
When I run:

```
dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=json,cobertura,lcov,teamcity,opencover
```

The output directory for the coverage files seems to be random (with a random GUID in the path). Is there a way where I can customize where these files are saved?

**Comment by MarcoRossignoli** [comment]
Unfortunately not, it's related to VSTest platform

Dup of https://github.com/coverlet-coverage/coverlet/issues/500
I opened an issue on VSTest repo here https://github.com/microsoft/vstest/issues/2378
