### ISSUE TITLE
Coverlet generates empty results when DebugType is embedded and Fody is referenced

### ISSUE THREAD

**Issue by Brainman643** [coverlet-coverage/coverlet#881]
Hello,
When property `DebugType` is `embedded` and Fody with plugin is referenced coverage results are empty.
My project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Equals.Fody" Version="4.0.1" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```
If  `DebugType` is changed to `portable` or Fody packages are removed, then it will work.

**Comment by MarcoRossignoli** [comment]
Coverlet supposed to work with `portable` and `embedded`, can you try to remove `Fody` and set only `embedded` to understand if the issue is the pari `embedded`+`Fody`?

**Comment by Brainman643** [comment]
Yes, the issue is that `DebugType` is `embedded` and `Fody` is added.
`embedded` with `Fody` - doesn't work.
`embedded` without `Fody` - works.
`portable` with `Fody` - works.

**Comment by MarcoRossignoli** [comment]
@Brainman643 is this resolved?Seem an issue related to how `Fody` re-write IL for embedded version, maybe it write non portable embedded pdb?

**Comment by MarcoRossignoli** [comment]
Close for stale conversation, feel free to reopen if needed!
