### ISSUE TITLE
Attribute exclusion does not work if attribute name does not end with "Attribute"

### ISSUE THREAD

**Issue by bddckr** [coverlet-coverage/coverlet#883]
I came across the same issue as #604 and added `TestSDKAutoGeneratedCode` to my `ExcludeByAttribute` usage (I'm using the MSBuild integration).

However, it looks like coverlet assumes all attributes' type names will end with `Attribute`:
https://github.com/coverlet-coverage/coverlet/blob/f7c3fd4e3a52de4eda4d3aa26918487e23f2aaa1/src/coverlet.core/Instrumentation/Instrumenter.cs#L696-L697
That isn't the case for `TestSDKAutoGeneratedCode`:
https://github.com/microsoft/vstest/blob/50b5b33261f7593eb92ae221dae1b9c74234207e/src/Microsoft.TestPlatform.ObjectModel/CodeCoverage/TestSDKAutoGeneratedCode.cs#L10

I believe the fix would be to do something like this, to keep the original functionality:
```c#
return excludeAttributeNames.Any(a =>
    a.EndsWith("Attribute")
        ? customAttribute.AttributeType.Name.Equals(a)
        : customAttribute.AttributeType.Name.Equals($"{a}Attribute"));
```

**Comment by MarcoRossignoli** [comment]
Thank's for reporting this, feel free to provide a PR with some tests if you want(not obligated at all btw).

**Comment by bddckr** [comment]
Thanks for checking in!

Will do, hopefully during the next 7 days.

**Comment by MarcoRossignoli** [comment]
No probs at all, at your pace!
