### ISSUE TITLE
MergeWith does not respect framework suffix in output file

### ISSUE THREAD

**Issue by jpdillingham** [coverlet-coverage/coverlet#885]
I'm testing two binaries in my pipeline with the following (truncated) options:

```
dotnet test -p:CollectCoverage=true -p:CoverletOutput="../coverage.json"
dotnet test -p:CollectCoverage=true -p:MergeWith="../coverage.netcoreapp3.1.json" -p:CoverletOutput="../opencover.xml"
```

This produces an intermediate coverage file `coverage.netcoreapp3.1.json` and a final report `opencover.netcoreapp3.1.json`

Omitting `netcoreapp3.1` in the `MergeWith` option value leads to a result which is not merged.

My expectation would be that the output files are either produced with the framework suffix and that the `MergeWith` option would respect this suffix (requiring only `coverage.json` as input to function properly), or that (ideally) the framework suffix is not added at all.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this.

**Comment by MarcoRossignoli** [comment]
One question, in your `csproj` are you using more than one tfm version? https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks

I mean `<TargetFramework>netcoreapp3.1</TargetFramework>` or `<TargetFrameworks>netcoreapp3.1</TargetFrameworks>`

**Comment by jpdillingham** [comment]
There's just `netcoreapp3.1`, but the enclosing node is `TargetFrameworks`.  The project is here: https://github.com/jpdillingham/Soulseek.NET/blob/master/tests/Soulseek.Tests.Unit/Soulseek.Tests.Unit.csproj

Worth noting is that I've never edited this file manually, so the plural node must be the default behavior.

**Comment by MarcoRossignoli** [comment]
I did a tests and seem that default is `TargetFramework` you should update to it if you don't have more tfm.
![image](https://user-images.githubusercontent.com/7894084/87230423-553ddf00-c3b0-11ea-93ed-9b97f41a4a78.png)

**Comment by MarcoRossignoli** [comment]
Feel free to close of solved!

**Comment by jpdillingham** [comment]
Thanks, changing both .csproj files to use `TargetFramework` instead of `TargetFrameworks` corrected the issue.  This must have been an artifact of the upgrade from 2.1 to 3.1.
