### ISSUE TITLE
Where should coverlet.runsettings be located?

### ISSUE THREAD

**Issue by robertlarkins** [coverlet-coverage/coverlet#889]
What is the recommended practice for where coverlet.runsettings file(s) live in a solution? Should there be a single coverlet.runsettings that sits at the root of the solution and is applied to *all* projects, or a coverlet.runsettings in each project?

The way I see it is having it at the solution level means that nothing special has to be done to find coverlet.runsettings in each project when running a command like `dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings`, nor having to determine if a project has a coverlet.runsettings (or making each project have one). No hierarchical structure is needed for linking different runsettings, nor alternatively duplicating settings between coverlet.runsettings files if a heirarchical structure isn't available. Additionally each project doesn't need to know about or contain a file specific to code coverage.

The advantage of a project level coverlet.runsettings is that it can have project specific settings in it.

Ok, having written that, I think the answer is obviously a single coverlet.runsettings at the solution root. Is this what everybody else thinks?

**Comment by MarcoRossignoli** [comment]
It depends...if you've only one configuration for every test project your settings is ok...the only drawback is that if you need some custom settings(filtering etc...) for some test project in future you'll need to create a new one inside test folder. BTW there is no "standard" so is up to you.
Usually I organize my project in folders like 
```
src/project1.csproj
src/project2.csproj
test/functional/functional.csproj
test/functional/runsettings.xml
test/units/units.csproj
test/runsettings.xml
```

So root of tests folder for share and a custom one if I need under expected sets of test.
BTW there isn't a standard.
Remember you can also pass parameters to command line https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline
