### ISSUE TITLE
Unable to get coverage of Referenced dll

### ISSUE THREAD

**Issue by manishi2V** [coverlet-coverage/coverlet#892]
Hello Folks,

I am trying to get coverage of a dll file. I am able to get coverage using "Collect coverage" tool where I am able to use runsettings file like below where I have mentioned dll name but I didn't found an option in coverlet where I can specify a dll file.
```
          <CodeCoverage>
            <ModulePaths>
              <Include>
                <ModulePath>.*Controller.dll</ModulePath>
              </Include>
            </ModulePaths>
            <!-- We recommend you do not change the following values: -->
            <UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            <CollectFromChildProcesses>True</CollectFromChildProcesses>
            <CollectAspDotNet>False</CollectAspDotNet>
          </CodeCoverage>
```

I am using following command using coverlet...
`dotnet test "myproject.csproj" /p:DebugType=pdbonly p:CollectCoverage=true /#p:CoverletOutputFormat=\"cobertura,lcov\" /p:CoverletOutput="testcoverage" /#p:CopyLocalLockFileAssemblies=true `

I want to know that how should I specify .*Controller.dll in this command so that it will display coverage result of only this assembly?

**Comment by MarcoRossignoli** [comment]
Seem you're using two drivers at same time, take a look at guide for collectors https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md `p:CollectCoverage=true` is for msbuild integration not for collectors
Here you can find an hello world sample https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld
Your filter should be something like `[*Controller]*` inside runsetting `Include` element.
Also check logs to understand how filters are working https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration and search for `[coverlet]` inside generated file, we log dll filtering in it.

**Comment by manishi2V** [comment]
Hi @MarcoRossignoli Thank you for your response. This works in my local machine however still not working when try to deploy in Azure

**Comment by MarcoRossignoli** [comment]
Can you copy paste output?

**Comment by manishi2V** [comment]
Which output are you talking about? I am getting an empty result.

**Comment by manishi2V** [comment]
<img width="213" alt="empty" src="https://user-images.githubusercontent.com/12082065/87146420-8cd15c00-c2c8-11ea-96c3-4ff2e9aa5f64.png">

**Comment by MarcoRossignoli** [comment]
I mean enable logs in CI and download to check https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#collectors-integration

**Comment by manishi2V** [comment]
I have attached log file for your reference.
I used below command

`dotnet test --collect:"XPlat Code Coverage" --settings ParallelRunsettings.Runsettings --diag:log.txt `

I also included runsettings file and coverage report. In order to insert attachments with this mail I made runsettings file as a text file.

My test case coverage should display  ***_Controller.dll assembly as well in report.

[ParallelRunsettings.Runsettings.txt](https://github.com/coverlet-coverage/coverlet/files/4904092/ParallelRunsettings.Runsettings.txt)

[log.datacollector.20-07-10_15-39-29_79547_4.txt](https://github.com/coverlet-coverage/coverlet/files/4904079/log.datacollector.20-07-10_15-39-29_79547_4.txt)
[log.host.20-07-10_15-39-31_21988_4.txt](https://github.com/coverlet-coverage/coverlet/files/4904081/log.host.20-07-10_15-39-31_21988_4.txt)
[log.txt](https://github.com/coverlet-coverage/coverlet/files/4904082/log.txt)

**Comment by MarcoRossignoli** [comment]
> TpTrace Warning: 0 : 8856, 1, 2020/07/10, 15:39:30.472, 1265359359591, datacollector.dll, [coverlet]BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if module has got local source.

I see this line in logs, you should setup portable pdb in you build, coverlet supports only portable pdb.
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019 
```
DebugType | All | Defines the level of debug information that you want generated. Valid values are "full," "pdbonly," "portable", "embedded", and "none."
```
> ParallelRunsettings.Runsettings.txt

The runsettings you've attached doesn't work with coverlet, that is settings for default .NET Framework build-in coverage, for .NET Core(cross plat coverage) you need to use another section `RunSettings/DataCollectionRunSettings/DataCollectors/DataCollector` as you can see in our guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings

**Comment by manishi2V** [comment]
Hi @MarcoRossignoli I do as per your instructions and set all my projects portable and I saw inside log files and not getting `[coverlet]BadImageFormatException` in logs.
I also removed my code to use runsettings file but still I'm not able to get coverage.
Please find this log file...
[log.datacollector.20-07-13_14-58-20_17787_4.txt](https://github.com/coverlet-coverage/coverlet/files/4913313/log.datacollector.20-07-13_14-58-20_17787_4.txt)
[log.host.20-07-13_14-58-21_27981_4.txt](https://github.com/coverlet-coverage/coverlet/files/4913314/log.host.20-07-13_14-58-21_27981_4.txt)
[log.txt](https://github.com/coverlet-coverage/coverlet/files/4913315/log.txt)

I used `dotnet test --collect:"XPlat Code Coverage" /p:Include="[*Controller]*" --diag:log.txt `command for logs and also tried test `"EngineCommon.Test.csproj" /p:DebugType=portable /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,lcov\" /p:CoverletOutput="testcoverage" /p:CopyLocalFileAssemblies=true` command

**Comment by MarcoRossignoli** [comment]
Hi @manishi2V you cannot pass parameter with `/p:` if you're using collectors, you can only pass using runsettings or flat xml to command line, take a look at guide and to our hello world sample

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld

**Comment by manishi2V** [comment]
Hi @MarcoRossignoli I tried that approach but still issue is same

**Comment by MarcoRossignoli** [comment]
Can you attach `--diag=log.txt` to command and send logs so we can see what's happening?

**Comment by manishi2V** [comment]
[log.datacollector.20-07-16_12-24-05_41267_4.txt](https://github.com/coverlet-coverage/coverlet/files/4931712/log.datacollector.20-07-16_12-24-05_41267_4.txt)
[log (1).txt](https://github.com/coverlet-coverage/coverlet/files/4931713/log.1.txt)
[log.host.20-07-16_12-05-47_82080_4.txt](https://github.com/coverlet-coverage/coverlet/files/4931714/log.host.20-07-16_12-05-47_82080_4.txt)

**Comment by manishi2V** [comment]
I have seen following lines in logs ...
The type "Coverlet.Collector.DataCollection.CoverletCoverageCollector" defined in "coverlet.collector.dll" does not have ExtensionUri attribute.

[logs.datacollector.20-07-17_12-59-01_22289_4.txt](https://github.com/coverlet-coverage/coverlet/files/4936342/logs.datacollector.20-07-17_12-59-01_22289_4.txt)

**Comment by MarcoRossignoli** [comment]
The strange thing is that there is no dll instrumented(`Include module` log), are you testing code inside a test project?
```
TpTrace Information: 0 : 19816, 1, 2020/07/17, 12:59:01.480, 989221714843, datacollector.dll, [coverlet]CoverletCoverageDataCollector: TestModules: 'C:\Users\manish.jain\Downloads\EngineTest\Compiled\netcoreapp3.1\EngineTest\EngineCommon.Test.dll'
TpTrace Verbose: 0 : 19816, 1, 2020/07/17, 12:59:01.482, 989221735074, datacollector.dll, [coverlet]CoverletCoverageDataCollector: Initializing coverlet process with settings: "TestModule: 'C:\Users\manish.jain\Downloads\EngineTest\Compiled\netcoreapp3.1\EngineTest\EngineCommon.Test.dll', IncludeFilters: '', IncludeDirectories: '', ExcludeFilters: '[coverlet.*]*', ExcludeSourceFiles: '', ExcludeAttributes: '', MergeWith: '', UseSourceLink: 'False'SingleHit: 'False'IncludeTestAssembly: 'False'"
TpTrace Verbose: 0 : 19816, 1, 2020/07/17, 12:59:01.505, 989221966663, datacollector.dll, [coverlet]Excluded module filter '[coverlet.*]*'
TpTrace Verbose: 0 : 19816, 1, 2020/07/17, 12:59:01.510, 989222021020, datacollector.dll, [coverlet]Excluded module: 'C:\Users\manish.jain\Downloads\EngineTest\Compiled\netcoreapp3.1\EngineTest\coverlet.collector.dll'
TpTrace Verbose: 0 : 19816, 1, 2020/07/17, 12:59:01.511, 989222022596, datacollector.dll, [coverlet]Excluded module: 'C:\Users\manish.jain\Downloads\EngineTest\Compiled\netcoreapp3.1\EngineTest\coverlet.core.dll'
```
If so you have to pass a flag to instrument also a test project https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#advanced-options-supported-via-runsettings `<IncludeTestAssembly>true</IncludeTestAssembly>`

**Comment by manishi2V** [comment]
I am using 

dotnet test EngineCommon.Test.dll --collect:"XPlat Code Coverage" command

However when I run this command in my local repository, then I am able to get coverage but strange thing is that I am not getting this in my deployed location.

In my deployed location however dotnet test EngineCommon.Test.dll --collect:"Code Coverage" command works

**Comment by MarcoRossignoli** [comment]
> However when I run this command in my local repository, then I am able to get coverage but strange thing is that I am not getting this in my deployed location.

It's not clear what you mean for "in my deployed location"...are you talking about CI?

**Comment by manishi2V** [comment]
Yes. I am taking about CI Pipeline of Azure

**Comment by manishi2V** [comment]
I tried to set <IncludeTestAssembly>true</IncludeTestAssembly> but still having same issue

**Comment by MarcoRossignoli** [comment]
It's not a problem(never seen or noticed that, maybe is there since start I'll take a look but it's unrelated to your issue) collector is loaded correctly the issue is that doesn't find any dll to instrument, in that log we have to see the name of instrumented assemblies, try to enable log in your local(the working one) and compare logs you'll see that the libs are instrumented.

**Comment by MarcoRossignoli** [comment]
close for stale conversation, feel free to reopen if needed!
