### ISSUE TITLE
Remove deterministic build feature hack for 3.1.300+ SDK

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#900]
Ref issue https://github.com/coverlet-coverage/coverlet/issues/882#issuecomment-657547636

**Comment by gitfool** [comment]
@MarcoRossignoli I'd also love to see this fixed and published in a stable version.

**Comment by clairernovotny** [comment]
You should be able to depend on `InitializeSourceRootMappedPaths` to return the `SourceRoot` items directly.
https://github.com/dotnet/roslyn/blob/c64d1e3a7b3e2b6d5a71ca4ceb5848bcd79a0970/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L186-L202

**Comment by MarcoRossignoli** [comment]
Some notes for version checking https://github.com/novotnyllc/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/RIDs.targets#L145-L151

**Comment by MarcoRossignoli** [comment]
@gitfool pls can you try(tomorrow, we build at midnight) to test with nightly removing the workaround to confirm that with sdk >= 3.1.100 the workaround is not needed anymore? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md

**Comment by gitfool** [comment]
@MarcoRossignoli it's now midnight (GMT) but I don't see a new preview for [coverlet.collector](https://www.myget.org/feed/coverlet-dev/package/nuget/coverlet.collector). I guess I need to wait another day?

**Comment by MarcoRossignoli** [comment]
Oh issue with myget quota https://dev.azure.com/tonerdo/coverlet/_build/results?buildId=1197&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94 cc: @tonerdo can you cleanup all version older than last month?

@clairernovotny is there some unlimited nuget feed service provided by foundation?Or what is the most used way by other?

@gitfool I attach here master packages, move to a local folder and use it as nuget feed source.


[preview.34.zip](https://github.com/coverlet-coverage/coverlet/files/5376327/preview.34.zip)

**Comment by gitfool** [comment]
@MarcoRossignoli it works!

Specifically, I removed the `Directory.Build.targets` workaround so `coverlet.collector` `1.3.1-preview.27.gdd2237a3be` reported no coverage; then I bumped it to `1.3.1-preview.34` via local NuGet source and it reported coverage as expected. 🎉

**Comment by MarcoRossignoli** [comment]
Great thanks a lot for your time! Really appreciated!

**Comment by gitfool** [comment]
You're welcome. If you don't mind me asking, will we see this in a _stable_ release soonish?

**Comment by MarcoRossignoli** [comment]
> soonish

Is on plan...but I don't have ETA atm, my desire is to fix other 3 nasty issues and align versions to 3.0.0

Simple ones https://github.com/coverlet-coverage/coverlet/issues/874 https://github.com/coverlet-coverage/coverlet/issues/705 (waiting for vstest team answer)
Complex https://github.com/coverlet-coverage/coverlet/issues/936 every new c# compiler release we have some pain on new pattern

**Comment by clairernovotny** [comment]
We recommend moving away from MyGet. Artifacts/Pipelines is free for opens source projects so you can use your own account or we can set you up on the .NET Foundation one.

**Comment by MarcoRossignoli** [comment]
OK thanks!

**Comment by eduherminio** [comment]
@MarcoRossignoli Please let us know as soon as you have any ETA for the next stable version.

**Comment by JimBobSquarePants** [comment]
Is there a `1.3.1-preview.34` available to anyone else?

**Comment by MarcoRossignoli** [comment]
We're in the middle of nightly update(https://github.com/coverlet-coverage/coverlet/issues/969) so for the moment the last version is on my tmp feed https://f.feedz.io/marcorossignoli/coverletunofficial/nuget/index.json

**Comment by JimBobSquarePants** [comment]
Thanks!

**Comment by MarcoRossignoli** [comment]
> Is there a 1.3.1-preview.34 available to anyone else?

Also we consolidate all versions to `3.0.0`(since next release).

**Comment by StefH** [comment]
Hello @MarcoRossignoli , is it possible that you already provide a 3.0.0-preview on NuGet ?
