### ISSUE TITLE
Class contrsuctor - Line not covered

### ISSUE THREAD

**Issue by gparissis** [coverlet-coverage/coverlet#902]
I am having a problem to understand why the constructor's line is not showing as covered.
Below is the class

```
    public class Id
    {
        public int Value { get; }

        public Id(int value)
            => Value = CheckIdIsPositive(value).Match(_ => value, err => throw new ArgumentException(err.Message));

        public static implicit operator Id(int value) => new Id(value);
    }
```

And the test

```
[TestMethod]
        public void When_Id_Is_Positive_Instantiation_Succeeds()
            => Assert.AreEqual(1, TestWithValue(1).Value);
```
After running coverlet command

```
dotnet test /p:CollectCoverage=true /p:CoverletOutput='./TestResults/' /p:coverletoutputformat=cobertura /p:include="[*]Alpha.Agreements.Business.*"
```
an XML file is created, as expected.

But when i check the XML contents i see that for the constructor's the line reports zero hits.

```
        <class name="Alpha.Agreements.Business.Vendors.Types.Fields.Id" filename="Types\Fields.cs" line-rate="0.75" branch-rate="1" complexity="3">
          <methods>
            ...
            <method name=".ctor" signature="(System.Int32)" line-rate="0.5" branch-rate="1" complexity="1">
              <lines>
                <line number="11" hits="3" branch="False" />
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
            ...
          </methods>
          <lines>
            <line number="9" hits="2" branch="False" />
            <line number="14" hits="1" branch="False" />
            <line number="11" hits="3" branch="False" />
            <line number="12" hits="0" branch="False" />
          </lines>
        </class>
```
You can see that hits on line number 12 is zero.

I am wondering why is this happening. How can i made the constructor's lines to be included and be counted. This class should have 100% line coverage but now it doesn't.

Thank you.

**Comment by gparissis** [comment]
After further testing when i included a test, that was testing the scenario where a negative number was passed to the constructor, thus causing the constructor to raise the exception, the line was included in coverage results.

Now the generated line contains the below:

```
<method name=".ctor" signature="(System.Int32)" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="11" hits="4" branch="False" />
                <line number="12" hits="8" branch="False" />
              </lines>
</method>
```

Is this normal?

**Comment by MarcoRossignoli** [comment]
From coverage perspective it's ok 😄 I mean you didn't cover che exception case, btw try something like that and remote exception test I want to understand if it's related to lambda closure
```
11    public Id(int value)
12            => Value = CheckIdIsPositive(value)
13                  .Match(_ => value, err => 
14                  throw new ArgumentException(err.Message));
```
Put statements in different lines

**Comment by gparissis** [comment]
Yes @MarcoRossignoli you are correct. The lambda statements should be put in different lines and now correctly marks only the last lambda with the exception, as not visited. Thinking about it after we resolve the issue, it makes sense that coverlet didn't count the line initially as visited, when both lambda were in the same line. Because not all cases were tested. 

Thank you for the tip.

**Comment by MarcoRossignoli** [comment]
Feel free to close if solved!
