### ISSUE TITLE
Is it possible to use coverlet to get coverage of API testing

### ISSUE THREAD

**Issue by mattbzhang** [coverlet-coverage/coverlet#906]
We have a restful API written in .NET core. We heavily depend on API testing to make sure the quality is good. We are thinking to get code coverage of those API test cases.

what we want to achieve is：
- instrument the source code of our restful API during build
- run all the API test cases
- get the code coverage

From the document, I see coverlet instruments assemblies before test run. So I think maybe we can use coverlet to do that.

Thank you very much in advance.

**Comment by MarcoRossignoli** [comment]
It's not a supported scenatio at the moment you can follow discussion on feat here https://github.com/coverlet-coverage/coverlet/issues/781

**Comment by mattbzhang** [comment]
Thank you very much for your reply. I will follow that ticket.
