### ISSUE TITLE
Incorrect branch coverage with await ValueTask

### ISSUE THREAD

**Issue by a-jackson** [coverlet-coverage/coverlet#907]
Awaiting a ValueTask shows an uncovered branch. I made a test project to show the difference between a ValueTask and a Task.
![image](https://user-images.githubusercontent.com/2199309/88040280-936d9800-cb40-11ea-8fc9-9a0bf236bff8.png)
Task is not showing any branches while ValueTask is showing 2 branches and one of the uncovered.

The source of the test project is [here](https://github.com/a-jackson/CoverletValueTaskCoverageIssue), I then used the command `dotnet test --collect:"XPlat Code Coverage" Tests` and used report generator to get the above image.

I think the issue is that `"System.Runtime.CompilerServices.ValueTaskAwaiter"` needs adding to `SkipIsCompleteAwaiters` along with `"System.Runtime.CompilerServices.TaskAwaiter"` in `CecilSymbolHelper` but I don't really understand half that code to be confident enough to make a PR.

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this!

**Comment by alexthornton1** [comment]
I took a crack at fixing this, based on the suggestion by @a-jackson, and that seems to do the trick.

**Comment by MarcoRossignoli** [comment]
closed in https://github.com/coverlet-coverage/coverlet/pull/949
