### ISSUE TITLE
Why there is a difference in line coverage of coverlet version 1.0.1 and >1.0.1

### ISSUE THREAD

**Issue by manishi2V** [coverlet-coverage/coverlet#909]
I am getting two different coverage results for same assembly in version 1.0.1 and >1.0.1 of coverlet.

You can see differences in these files

<img width="328" alt="Coverage using version 1 0" src="https://user-images.githubusercontent.com/12082065/88052790-6ccb5380-cb78-11ea-8b41-47c3ca982cac.PNG">
<img width="344" alt="Coverage using version 1 2" src="https://user-images.githubusercontent.com/12082065/88052799-6e951700-cb78-11ea-9b88-f26b6e4a0eca.PNG">

I used --collect:"XPlat Code Coverage" on windows machine.

I checked with --collect:"Code Coverage" and found that reports generated using this command generating same report as we are getting in coverlet version 1.0.1

**Comment by MarcoRossignoli** [comment]
You should move to last version `1.3.0` https://www.nuget.org/packages/coverlet.collector/  
It's normal have some difference between versions, every release we fix also coverage bugs where for instance we skip to measure some corner case code. Coverlet work at IL level(not c#) so sometimes we have to handle complex case where compiler generate IL code non comparable with C# one that lead to coverage bug(code not instrumented or not correctly measured)
