### ISSUE TITLE
Coverlet - Xunit code coverage returns 

### ISSUE THREAD

**Issue by balasun3** [coverlet-coverage/coverlet#913]
I took the sample source, and included Coverlet but i get the coverage generating as empty files, ANy thoughts from your end.

**Comment by MarcoRossignoli** [comment]
Can you elaborate?Which sample have you used?One of our?

https://github.com/coverlet-coverage/coverlet/tree/master/Documentation/Examples/VSTest/HelloWorld

**Comment by MarcoRossignoli** [comment]
Close for stale conversation feel free to reopen if needed!
