### ISSUE TITLE
[assembly: ExcludeFromCodeCoverage] doesn't seem to work on an xunit project in VS 2019

### ISSUE THREAD

**Issue by pedramrezaei** [coverlet-coverage/coverlet#915]
```
VS 2019 version 16.6.5
Microsoft.NET.Test.Sdk- 16.6.1
NSubstitute - 4.2.2
xunit - 2.4.1
xunit.runner.visualstudio - 2.4.2
coverlet.collector - 1.3.0
```

Running the code analysis from inside VS still includes my test assembly that should have been excluded.

**Comment by MarcoRossignoli** [comment]
> doesn't seem to work on an xunit project in VS 2019

What does in VS 2019 mean?Coverlet is not integrated in visual studio you can only run by console and use output artifacts(coverage formats) to generate a report using one of report generator in the market(reportGenerator etc...)

**Comment by pedramrezaei** [comment]
Ah... totally posted this to the wrong forum.
