### ISSUE TITLE
Zero code coverage when running on GHActions

### ISSUE THREAD

**Issue by eddynaka** [coverlet-coverage/coverlet#918]
Hi,

I have created a pipeline in GHActions that tests all projects. I have one specific project that targets only net452 and net46. Just this project doesn't seem to output the correct values when running on GHActions.

When I execute the command locally (windows), it does output normally.

Below the command:
`dotnet test --collect:"XPlat Code Coverage" --results-directory:"TestResults" --configuration Release --no-build -- RunConfiguration.DisableAppDomain=true`

Anyway to debug this and understand why does this happen only in GHActions?

Thank you.

**Comment by eddynaka** [comment]
Just forgot to say: using the latest version of coverlet.collector:
```xml
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

**Comment by eddynaka** [comment]
I saw that this isn't supported for .netframework. Do u have a plan to support it?

**Comment by tonerdo** [comment]
@eddynaka support for the .NET Framework isn't prioritiezed at this time

**Comment by eddynaka** [comment]
i see...i changed temporary to "Code Coverage" flag.

Thank you.
