### ISSUE TITLE
The type of dependency injection does not recognize coverage

### ISSUE THREAD

**Issue by 944332213** [coverlet-coverage/coverlet#922]
I have reproduce successfully
For details, see: <https://github.com/944332213/Coverlet.Console.TestProject#the-current-conclusion>
source code: <https://raw.githubusercontent.com/944332213/Coverlet.Console.TestProject/master/README.md#the-current-conclusion>

----

I have removed a description of the original problem that is not clear enough (see history if you need to), and please see the description in the replay project

**Comment by 944332213** [comment]
I have reproduced the problem and changed the instructions

**Comment by 944332213** [comment]
I found the reason.

The problem `HostingAbstractionsHostBuilderExtensions.Start(this IHostBuilder hostBuilder);`, just change it to `IHostBuilder.Build();`.Using `Program.CreateHostBuilder(new string[0]).ConfigureWebHost(webBuilder => { }).Build();` replace `Program.CreateHostBuilder(new string[0]).ConfigureWebHost(webBuilder => { }).Start();`.I can't explain the deeper reason, if anyone knows, please let me know, I'd appreciate it

see also <https://github.com/944332213/Coverlet.Console.TestProject/blob/master/README.md#solution>
This document is a translation version, original text see:  [README_zh-cn](https://github.com/944332213/Coverlet.Console.TestProject/blob/master/README_zh-cn.md)

**Comment by 944332213** [comment]
If no one answers my question, I will close it after a while.Thank you for your time.

**Comment by 944332213** [comment]
In fact.If you are going to use Testserver.createclient (), you can never avoid ihost.start ().My current approach is to keep this part of the code as a separate project to avoid affecting coverage scans of other code.

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation, feel free to re-open if needed.
