### ISSUE TITLE
Risk Hotspot functionality similar to OpenCover

### ISSUE THREAD

**Issue by nehaoberoi26** [coverlet-coverage/coverlet#923]
Do we have a risk hotspot functionality similar o OpenCover code coverage tool, It generated report with Hotspot risk

https://www.palmmedia.de/Blog/2017/12/6/reportgenerator-new-release-with-risk-hotspots-analysis 

When I create report from coverlet(format=opencover) and report generator it gives report, but dont have any risk hotspot.

Example
![image](https://user-images.githubusercontent.com/50940636/90231561-01079e00-de39-11ea-9620-7e8eb96a7482.png)

**Comment by tonerdo** [comment]
@nehaoberoi26 can you please shed more light on what risk hotspot is and how it's calculated?

**Comment by nehaoberoi26** [comment]
It is a functionality avaibale in Opencover tool, you can have a look at https://www.palmmedia.de/Blog/2017/12/6/reportgenerator-new-release-with-risk-hotspots-analysis#:~:text=Summary%20report%20enhancements,more%20metrics%20exceed%20certain%20thresholds.&text=You%20can%20adjust%20those%20metrics%20in%20ReportGenerator.exe.

Not sure how it is calculated but it give some risk analysis at the top of report along with code coverage.

**Comment by nehaoberoi26** [comment]
If I generate report from coverlet + report generator it doesn't give these risk hotspot details, but If I use opencover tool it generates risk hotspot with a report generator tool

**Comment by petli** [comment]
Try outputing OpenCover format files from coverlet instead of the default format (cobertura?). I use OpenCover formats in the project I'm using coverlet for, and get the risk hotspots in the reportgenerator output.

**Comment by NehaOberoi92** [comment]
@petli : Thanks, may be in my code there are no risk hotspot so it was not showing, I tried another code with opencover format and it works. Thanks
