### ISSUE TITLE
[Question] - FileNotFoundException - Microsoft.Extensions.DependencyInjection, Version=2.2.0.0

### ISSUE THREAD

**Issue by mwasson74** [coverlet-coverage/coverlet#924]
When running the command `"C:\Program Files\dotnet\dotnet.exe" test C:\Users\ND57\source\repos\SCPWebAPI\Scp.Web.Integration.Tests\bin\Release\netcoreapp3.1\win-x86\Scp.Web.Integration.Tests.dll --logger trx --results-directory C:\temp\ND57 --configuration Release --runtime win-x86 --no-build --settings CodeCoverage.runsettings "--collect:XPlat Code Coverage"` I am getting a FileNotFoundException for Version 2.2.0.0 of Microsoft.Extensions.DependencyInjection. I believe this is because I have other packages that are using version 3.1.3 of that package.

dotnet.exe version 3.1.101
coverlet.msbuild version 2.9.0
coverlet.collector version 1.3.0

Full error:

> File name: 'Microsoft.Extensions.DependencyInjection, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetServiceProvider(TestPlatformEqtTrace eqtTrace, TestPlatformLogger logger)
at Coverlet.Collector.DataCollection.CoverletCoverageCollector.Initialize(XmlElement configurationElement, DataCollectionEvents events, DataCollectionSink dataSink, DataCollectionLogger logger, DataCollectionEnvironmentContext environmentContext) in c:\git\coverletToRelease\src\coverlet.collector\DataCollection\CoverletCoverageCollector.cs:line 82
at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.InitializeDataCollector()
at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.LoadAndInitialize(DataCollectorSettings dataCollectorSettings, String settingsXml)

Any guidance or help you can provide would be greatly appreciated.
I can provide any other files or logs that you need to assist me in resolving this.

Thanks,

Matt

**Comment by MarcoRossignoli** [comment]
Can you try with this? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#4-failed-to-resolve-assembly-during-instrumentation

**Comment by mwasson74** [comment]
@MarcoRossignoli, thank you for your response! I added the attribute to my project file and it didn't work. I have attached my project file for your review. [Scp.Web.Integration.Tests.csproj.txt](https://github.com/coverlet-coverage/coverlet/files/5084657/Scp.Web.Integration.Tests.csproj.txt)

**Comment by MarcoRossignoli** [comment]
Can you try to add `<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />` to your test project?

**Comment by MarcoRossignoli** [comment]
Can you run `dotnet --info` on machine that raise error?

**Comment by mwasson74** [comment]
This happens on both my development machine and our build server so I will include both.

[dotnet_info_BuildServer.txt](https://github.com/coverlet-coverage/coverlet/files/5103056/dotnet_info_BuildServer.txt)
[dotnet_info_DevMachine.txt](https://github.com/coverlet-coverage/coverlet/files/5103057/dotnet_info_DevMachine.txt)

**Comment by mwasson74** [comment]
@MarcoRossignoli, a colleague of mine took a look at my issue and we are blaming it on a build configuration issue for now. If I run into this again, I will get you a repro solution.

Thanks again for your continued help!

**Comment by MarcoRossignoli** [comment]
Ok, feel free to close this if solved and reopen if needed!

**Comment by mwasson74** [comment]
I didn't solve it necessarily but we are blaming this one on us not doing something correctly for now and will re-open if needed. Thanks!

**Comment by MarcoRossignoli** [comment]
Ok thanks, only to keep our issue list short as possible, less noise, thanks a lot for using coverlet and again feel free to reopen if needed, better with a repro, sometimes is very hard do troubleshooting without repro.
