### ISSUE TITLE
[Bug] Coverlet is not counting the model properties

### ISSUE THREAD

**Issue by ming-tsai** [coverlet-coverage/coverlet#930]
Hi there,
I'm using `coverlet.msbuild` to generate the coverlet and publish to SonarScanner, recently I upgrade **v2.7.0** to **v2.9.0**, but on v2.9.0 is not counting the model properties.

#### Evidence
**v2.9.0**
![image](https://user-images.githubusercontent.com/37890026/91088469-10000480-e620-11ea-94c4-3009cb1cc146.png)
**v2.7.0**
![image](https://user-images.githubusercontent.com/37890026/91088556-3887fe80-e620-11ea-9f47-eb1f06ceaf1d.png)

**Comment by petli** [comment]
This has been fixed in master (#328 #912) and will be included in the next release.

**Comment by ming-tsai** [comment]
Hi @petli, thanks

**Comment by petli** [comment]
Do you have any date planned already, @MarcoRossignoli ?

**Comment by MarcoRossignoli** [comment]
No atm...we need to talk about versions alignment cc: @tonerdo https://github.com/coverlet-coverage/coverlet/issues/874 and maybe if we've room we could fix this https://github.com/coverlet-coverage/coverlet/issues/900
We should also merge this new feat https://github.com/coverlet-coverage/coverlet/pull/904

**Comment by MarcoRossignoli** [comment]
BTW no sure that the issue here is related to that new feature...the new feat will exclude autoprops.

@ming-tsai can you attach your command line?

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli,
This the command that I use to generate the coverage.
```bash
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx
```
> The issue has nothing to do with auto-props

**Comment by MarcoRossignoli** [comment]
Can you try with `2.8.1`?

**Comment by ming-tsai** [comment]
Same than `2.9.0` and I get these warnings
```bash
warning : [coverlet] Unable to instrument module: source\repos\Project\Project.Test\bin\Debug\netcoreapp3.0\System.ComponentModel.Annotations.dll because : No symbol found for file: source\repos\Project\Project.Test\bin\Debug\netcoreapp3.0\System.ComponentModel.Annotations.dll [source\repos\Project\Project.Test\Project.Test.csproj]
warning : [coverlet] Unable to instrument module: source\repos\Project\Project.Test\bin\Debug\netcoreapp3.0\System.Text.Encodings.Web.dll because : No symbol found for file: source\repos\Project\Project.Test\bin\Debug\netcoreapp3.0\System.Text.Encodings.Web.dll [source\repos\Project\Project.Test\Project.Test.csproj]
```

**Comment by MarcoRossignoli** [comment]
Warnings are ok, but for your problem we need a repro because is not expected, we got similar issue on `2.9.0` because we fixed a bug on `ExcludeByAttribute` feature https://github.com/coverlet-coverage/coverlet/issues/794#issuecomment-612067552 but your command line seems ok.

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli,
I will try to create a example repo and publish to here.

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli,
Let me attach the example repo.
**v2.7.0**
![image](https://user-images.githubusercontent.com/37890026/91499832-33c98180-e890-11ea-957f-63cdf469a46c.png)
**v2.9.0**
![image](https://user-images.githubusercontent.com/37890026/91499855-3fb54380-e890-11ea-8221-418a9b8f22cb.png)

**Project**
[Example.zip](https://github.com/coverlet-coverage/coverlet/files/5138983/Example.zip)

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli,
Any updates?

**Comment by MarcoRossignoli** [comment]
Sorry @ming-tsai I'm bit busy these days...I'll think to work on it in the weekend 🙇

**Comment by ming-tsai** [comment]
Hiya 👋,
Any update?

**Comment by MarcoRossignoli** [comment]
@ming-tsai Sorry for the delay, busy times I'll take a look asap

**Comment by ming-tsai** [comment]
Ok @MarcoRossignoli, let me know when has any update

**Comment by MarcoRossignoli** [comment]
Thanks for the patience and sorry!

**Comment by ming-tsai** [comment]
> Thanks for the patience and sorry!

Don't worry 🧐, I will use v2.7.0 until fix this issue

**Comment by MarcoRossignoli** [comment]
@ming-tsai I cannot repro with your sample
![image](https://user-images.githubusercontent.com/7894084/98644711-308f4f00-2331-11eb-95d2-83af349f6da3.png)
Can you verify that my setup/command line is like your?

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli, I'm going to test in my pc

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli, sorry for the late response, you should change the package `coverlet.msbuild` to version `2.9.0` on the Example.Test project.
```xml
    <PackageReference Include="coverlet.msbuild" Version="2.9.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```
Upgrading to `v2.9.0`
![image](https://user-images.githubusercontent.com/37890026/99839907-e46ab880-2b41-11eb-8c0a-cfa8bbad3541.png)

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli, sorry for the late response, my output is the same as yours but I'm sure that it **is not counting the model properties**. 
The v2.7.0 coverage is 100% but on the v2.9.0 is 84%.
Why the previous version is counting and the new version is not? and what should I do with this type of unit test?

**Comment by MarcoRossignoli** [comment]
I'll take another deep look to understand the counting difference, I'm pretty sure that the culprit is some accounting fix

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli, please update the labels

**Comment by MarcoRossignoli** [comment]
@ming-tsai I did some test with nightly and 100% comes back
```
 C:\git\playground\coverlet\Example                                                                                                                                                                                                                                [15:21]
❯ dotnet test /p:CollectCoverage=true
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\git\playground\coverlet\Example\Example.Test\Example.Test.csproj]
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\git\playground\coverlet\Example\Example.Test\Example.Test.csproj]
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Example.Core -> C:\git\playground\coverlet\Example\Example.Core\bin\Debug\netstandard2.0\Example.Core.dll
  Example.Test -> C:\git\playground\coverlet\Example\Example.Test\bin\Debug\netcoreapp3.0\Example.Test.dll
C:\Users\mrossignoli\.nuget\packages\coverlet.msbuild\3.0.0-preview.18.g183cbed8a6\build\coverlet.msbuild.targets(39,5): warning : [coverlet] Unable to instrument module: C:\git\playground\coverlet\Example\Example.Test\bin\Debug\netcoreapp3.0\System.ComponentModel.Annotations.dll because : No symbol found for file: C:\git\playground\coverlet\Example\Example.Test\bin\Debug\netcoreapp3.0\System.ComponentModel.Annotations.dll [C:\git\playground\coverlet\Example\Example.Test\Example.Test.csproj]
Test run for C:\git\playground\coverlet\Example\Example.Test\bin\Debug\netcoreapp3.0\Example.Test.dll (.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 114 ms - Example.Test.dll (netcoreapp3.0)

Calculating coverage result...
  Generating report 'C:\git\playground\coverlet\Example\Example.Test\coverage.json'

+--------------+------+--------+--------+
| Module       | Line | Branch | Method |
+--------------+------+--------+--------+
| Example.Core | 100% | 100%   | 100%   |
+--------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | 100% | 100%   | 100%   |
+---------+------+--------+--------+
```
Can you try with nightly and confirm? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md version
```xml
<PackageReference Include="coverlet.msbuild" Version="3.0.0-preview.18.g183cbed8a6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

**Comment by ming-tsai** [comment]
Hi @MarcoRossignoli,
So should I wait for 3.0.0?

**Comment by MarcoRossignoli** [comment]
Yep, btw a double check could help to be sure of it and close this, release is very close.

**Comment by ming-tsai** [comment]
Thanks guys, it is work
