### ISSUE TITLE
Method coverage based on access level?

### ISSUE THREAD

**Issue by goyzhang** [coverlet-coverage/coverlet#931]
Is it possible to limit the method coverage to public methods only? In case I just want to make sure public interfaces are always covered so I can set the threshold to 100%

**Comment by MarcoRossignoli** [comment]
No coverlet doesn't support this feature, also I don't know if there are coverage tool that works in that way, do you have some names?Just for curiosity.

**Comment by goyzhang** [comment]
Nope, I don't really know any, I used some GUI based code coverage tool and recently try to migrate to coverlet😋. 

In my case I build a bunch of psedo tests that only make fake calls to the library public interfaces to ensure that the interface is backward compatible. So I want it to be 100% for public methods only and CI can reject if the interface is broken. The real test cases for functionalities are in another test project.

Thanks for the information. Close this issue for now.

**Comment by goyzhang** [comment]
It's possible, however, indirectly if only the JSON test reports can provide access level.

**Comment by MarcoRossignoli** [comment]
Json report is an internal format, we should also provide a way to calculate coverage/convert to standard format, at the moment you can cleanup file using reflection on assembly (check accessibility) and removing non public members
