### ISSUE TITLE
Fix typo under the section, "Excluding From Coverage"

### ISSUE THREAD

**Issue by pkErbynn** [coverlet-coverage/coverlet#933]
Consider comma(**,**) separation after 
> method

in

>Attributes
You can ignore a method an entire class or assembly from code coverage by creating and applying the ExcludeFromCodeCoverage attribute present in the System.Diagnostics.CodeAnalysis namespace.

**Comment by MarcoRossignoli** [comment]
Thanks, feel free to propose a PR with doc fix!(not obligated at all).

**Comment by MarcoRossignoli** [comment]
Closing for stale conversation, feel free to reopen if needed.
