### ISSUE TITLE
/p:CoverletOutput does not use specified value

### ISSUE THREAD

**Issue by mabead** [coverlet-coverage/coverlet#934]
I run tests on an assembly using this command:

> dotnet.exe test "C:/git/MicroServices.Core/tests/LANDR.MicroServices.Core.UnitTests/LANDR.MicroServices.Core.UnitTests.csproj" --configuration Release --no-build --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=C:/git/MicroServices.Core/artifacts/tests/LANDR.MicroServices.Core.UnitTests/coverage.xml /p:Include="[LANDR.*]*" /p:ExcludeByAttribute="ExcludeFromCoverageAttribute%2cGeneratedCode" --logger "trx;LogFileName=C:/git/MicroServices.Core/artifacts/tests/LANDR.MicroServices.Core.UnitTests.trx"

I then see this in the output:

```
Calculating coverage result...
  Generating report 'C:\git\MicroServices.Core\artifacts\tests\LANDR.MicroServices.Core.UnitTests\coverage.netcoreapp3.1.xml'
```

As you can see, it writes result in the file `coverage.netcoreapp3.1.xml` instead of the file that I requested (`coverage.xml`)

I am using `coverlet.msbuild` version 2.9.0

**Comment by mabead** [comment]
I have replaced `<TargetFrameworks>netcoreapp3.1</TargetFrameworks>` by `<TargetFramework>netcoreapp3.1</TargetFramework>` in my csproj and it now fails differently:

```
       "C:\git\MicroServices.Core\tests\LANDR.MicroServices.Core.UnitTests\LANDR.MicroServices.Core.UnitTests.csproj" (VSTest target) (1) ->
       (GenerateCoverageResult target) ->
         C:\Users\mbeaudry\.nuget\packages\coverlet.msbuild\2.9.0\build\coverlet.msbuild.targets(60,5): error MSB4044: The "Coverlet.MSbuild.Tasks.CoverageResultTask" task was not given a value for the required parameter "Threshold". [C:\git\MicroServices.Core\tests\LANDR.MicroServices.Core.UnitTests\LANDR.MicroServices.Core.UnitTests.csproj]
```

This looks like a breaking change in 2.9.0. Could you please let me know how to disable this threshold check?

**Comment by MarcoRossignoli** [comment]
Can you try to clean the workspace and nuget packages?
`Threshold` is provided by default in props import https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.props#L15
And used by task https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.msbuild.tasks/coverlet.msbuild.targets#L64

So I do not expect that strange error(no other users reported similar error), I don't remember any changes to this part of code in past releases.

**Comment by mabead** [comment]
After a `git clean -dfx` and `dotnet nuget locals all --clear`, everything works as expected. 🤷 

Thanks for your help @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
Glad to hear!
