### ISSUE TITLE
Error MSB4181 VSTestTask returned false but did not log error

### ISSUE THREAD

**Issue by MHacker9404** [coverlet-coverage/coverlet#937]
When a test throws an uncaught exception - coverlet fails to provide the coverage report.  I've created a repo that reproduces this error message:
Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error.

[https://github.com/MHacker9404/coverlet-demo](repo)

**Comment by MarcoRossignoli** [comment]
I think it's a dup of https://github.com/microsoft/vstest/issues/2384 unrelated to coverlet(it rely on  vstest platform collectors integrations).
Pls add a message on that issue.

**Comment by MHacker9404** [comment]
Got it - tanks

Phil Boyd

**Comment by MarcoRossignoli** [comment]
I'm going to close for the moment, we have the other issue already open on vstest
