### ISSUE TITLE
Coverage being generated only with a filter argument

### ISSUE THREAD

**Issue by kblok** [coverlet-coverage/coverlet#944]
I'm trying to setup coverage on [playwright-sharp](https://github.com/hardkoded/playwright-sharp).
I added this to the csproj:

```cs
 <PackageReference Include="coverlet.msbuild" Version="2.8.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

It seems to be working with these command arguments:
```
dotnet test ./PlaywrightSharp.Tests.csproj -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --filter ClassName~PlainTextContentEditableTests
```

But it doesn't work without the filter argument:
```
dotnet test ./PlaywrightSharp.Tests.csproj -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
```

Note: The full test suite is over 1,000 tests that could take over 5 minutes.

Ideas?

**Comment by MarcoRossignoli** [comment]
> But it doesn't work without the filter argument:

What does mean "doesn't work"?Are the process pending?It's slow?Can you try to run in local?Instrumentation is invasive and sometimes slow down a lot tests, we have some issue related to this for instance https://github.com/coverlet-coverage/coverlet/issues/777

**Comment by kblok** [comment]
With the filter argument, I'm getting the `Calculating coverage result...`, `Generating report` and the tiny report and the end, and the file is being generated.
Without that argument, I'm getting none of that.

These are the outputs with `/clp:PerformanceSummary`
[out-with-filter.txt](https://github.com/coverlet-coverage/coverlet/files/5174824/out-with-filter.txt)
[out-with-no-filter.txt](https://github.com/coverlet-coverage/coverlet/files/5174825/out-with-no-filter.txt)

**Comment by MarcoRossignoli** [comment]
Can you enable logging and attach result(be sure to not expose sensible data)? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#msbuild-integration

**Comment by kblok** [comment]
I can't do that on macOS, right?

**Comment by MarcoRossignoli** [comment]
`dotnet test` command should work also on macOS, I don't know if msbuildlog is cross plat.

**Comment by MarcoRossignoli** [comment]
Oh seems to work on it https://github.com/KirillOsenkov/MSBuildStructuredLog#running-the-avalonia-version-on-mac

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation, feel free to re-open if needed.

**Comment by kblok** [comment]
Sorry for the lack of feedback @MarcoRossignoli. I'll leave this in my To-Do
