### ISSUE TITLE
Add some integration tests for new [DoesNotReturn] feat

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#946]
@kevin-montrose did a great job on it https://github.com/coverlet-coverage/coverlet/pull/904 and added also some tests 

https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs#L647
https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Samples/Instrumentation.DoesNotReturn.cs

We should add also some integration tests with same sample to cover also parameter option passed in(i.e. `/p:DoesNotReturnAttribute="DoesNotReturnAttribute,OtherAttribute"`):
1) Add a file https://github.com/coverlet-coverage/coverlet/tree/master/test/coverlet.core.tests/Coverage called CoverageTests.DoesNotReturn.cs
2) Add one test for every samples in file https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Samples/Instrumentation.DoesNotReturn.cs

**Comment by daveMueller** [comment]
I would work on this but I got a questions on how this works. Currently in the test (https://github.com/coverlet-coverage/coverlet/blob/master/test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs#L647) the ```notReachableLines``` are not instrumented even when there is no ```DoesNotReturnAttributes```. 
What ever ```DoesNotReturnAttributes``` parameter I pass to the constructor (https://github.com/coverlet-coverage/coverlet/blob/dd2237a3be1ba8c99709e309aab9c3d5b9c7b34b/test/coverlet.core.tests/Instrumentation/InstrumenterTests.cs#L246-L247) the test always succeeds.

In my humble understanding the ```notReachableLines``` should only be excluded from instrumentation when the parameter is set? Or not?

**Comment by MarcoRossignoli** [comment]
By defauilt `DoesNotReturnAttribute` is always added https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/Instrumenter.cs#L83

New feat allows  also to add new users defined attributes

**Comment by daveMueller** [comment]
Ahh ok thanks. I didn't check what happens in ```PrepareAttributes(...)``` :see_no_evil:. You can assign this me then.

**Comment by MarcoRossignoli** [comment]
No worries, thanks!(I know I have your PR on queue)

**Comment by daveMueller** [comment]
@MarcoRossignoli Could you take a peek at https://github.com/daveMueller/coverlet/blob/946_Integration_Tests/test/coverlet.core.tests/Coverage/CoverageTests.DoesNotReturn.cs.
Is this what you intended? When using the samples in ```Instrumentation.DoesNotReturn.cs``` it doesn't really make sense to pass a ```doesNotReturnAttribute``` to the instrumenter because it defaults to ```DoesNotReturnAttribute```.

**Comment by MarcoRossignoli** [comment]
> When using the samples in Instrumentation.DoesNotReturn.cs it doesn't really make sense to pass a doesNotReturnAttribute to the instrumenter because it defaults to DoesNotReturnAttribute.

Yep we can for now avoid to add the attributes overload to test class, we use build-in `DoesNotReturnAttribute`
