### ISSUE TITLE
Visual Studio Addin Contribution

### ISSUE THREAD

**Issue by FortuneN** [coverlet-coverage/coverlet#953]
Hello,

I have been working on a Visual Studio extension that is powered by coverlet.
The goal of the extension to visualize coverlet output inside VS while you code and run tests.
It is free and open source.

- [View in Github](https://github.com/FortuneN/FineCodeCoverage)
- [View in Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage)

I am a fan of coverlet and I noticed that you list a Cake addin in the README.
It occurred to me that you may be willing to list this Visual Studio addin for those like me who use coverlet and VS.

I eagerly await any terms, conditions, suggestions or feedback that you may have for me.

Regards

**Comment by MarcoRossignoli** [comment]
Great!

Feel free to update readme with a PR, we'll do some tests with your extension!

cc: @tonerdo @petli
