### ISSUE TITLE
Document  -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

### ISSUE THREAD

**Issue by ffMathy** [coverlet-coverage/coverlet#955]
I didn't know this option existed: `-- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover` in the commandline variant. It's not documented. It should be shown in the docs.

**Comment by StefanOssendorf** [comment]
Hi. This is documented [here](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#passing-runsettings-arguments-through-commandline).

**Comment by MarcoRossignoli** [comment]
Yep is the documentation!
Thanks!
