### ISSUE TITLE
coverlet hang

### ISSUE THREAD

**Issue by chungvtran** [coverlet-coverage/coverlet#958]
Hi everyone, 

I have issue when run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
It hang due to it cannot access some pdb file.
I'm using Nunit and the project is .Net 4.7.2

(Inner Exception # 7) System.IO.IOException: The process cannot access file '...\xxx.pdb' because it is being used by another process.

![Screen Shot 2020-09-28 at 5 13 45 PM](https://user-images.githubusercontent.com/6937498/94421096-41d03200-01af-11eb-947d-5d64d147634b.png)

Thanks,

**Comment by MarcoRossignoli** [comment]
Which version are you using?
Do you have antivirus running? If so can you try to shutdown? Sometimes they interfere with instrumentation backup/restore

**Comment by chungvtran-clearwave** [comment]
Hi @MarcoRossignoli, 

Thanks for your reply.

I dont' have antivirus running. I also tried to restart the machine but it doesn't work. 
I have several test projects but the issue only happen with that one unit test project. 
I see that there are 2 instances of dotnet access that pdb file. I tried to set disable parallel test but it still didn't work.

Regards,

**Comment by chungvtran** [comment]
Hi @MarcoRossignoli,

Thanks for your reply.

I dont' have antivirus running. I also tried to restart the machine but it doesn't work.
I have several test projects but the issue only happen with that one unit test project.
I see that there are 2 instances of dotnet access that pdb file. I tried to set disable parallel test but it still didn't work.

Regards,

**Comment by MarcoRossignoli** [comment]
Are you running parallel test on the same dlls?

> I see that there are 2 instances of dotnet access that pdb file. I tried to set disable parallel test but it still didn't work.

Can you copy/paste the `dotnet` arguments(maybe using something like process explorer) to understand if you're sharing same test folder between more than one tests for some reason.

**Comment by MarcoRossignoli** [comment]
Closed for stale conversation
