### ISSUE TITLE
Unrecognized option '--does-not-return-attribute'

### ISSUE THREAD

**Issue by FortuneN** [coverlet-coverage/coverlet#962]
When trying to use the **--does-not-return-attribute** option i get the message **Unrecognized option '--does-not-return-attribute'**
coverlet.console v1.7.2

The option is documented here : https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md

**Comment by petli** [comment]
There hasn't yet been a regular release including that feature (see https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Changelog.md).
