### ISSUE TITLE
Why isn't the Azure DevOps build using CodeCoverage?

### ISSUE THREAD

**Issue by mikeblakeuk** [coverlet-coverage/coverlet#967]
Why isn't the Azure DevOps build using CodeCoverage?

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

![image](https://user-images.githubusercontent.com/1986660/95772984-88488500-0cb5-11eb-8f40-939fa516537c.png)

**Comment by MarcoRossignoli** [comment]
I apologize, I don't understand the question, can you elaborate more?

**Comment by TimHess** [comment]
Your builds _are_ running code coverage, but [they aren't publishing the reports](https://dev.azure.com/tonerdo/coverlet/_build/results?buildId=1202&view=codecoverage-tab)...

**Comment by MarcoRossignoli** [comment]
Ah the question was related to our build?can you confirm @mikeblakeuk ?

**Comment by mikeblakeuk** [comment]
Yes - https://dev.azure.com/tonerdo/coverlet/_build/results?buildId=1202&view=results
a) You should use the DevOps code coverage support that lets you download and open the code coverage in Visual Studio.
b) You should use Coverlet reporting to show the code coverage within the DevOps build directly

**Comment by MarcoRossignoli** [comment]
Thanks for the advice, we used to check on console usually, but we'll improve using AzDo!

**Comment by mikeblakeuk** [comment]
It would be nice when developer have a PR, they check the coverage
![image](https://user-images.githubusercontent.com/1986660/96131312-ee6d1c00-0ef0-11eb-928e-6d8c000e5480.png)

**Comment by Bertk** [comment]
Outdated issue.
<img width="722" alt="image" src="https://github.com/user-attachments/assets/6ec23ce8-4fb6-4faf-a321-a3f32c82dab2">
