### ISSUE TITLE
Move nightly to AzDo

### ISSUE THREAD

**Issue by MarcoRossignoli** [coverlet-coverage/coverlet#969]
Move nightly out of myget https://github.com/coverlet-coverage/coverlet/issues/900#issuecomment-708359611

@tonerdo can you enable Artifacts/Pipelines for coverlet AzDo pipeline account?

At the moment the master version are uploaded to my "debug" feed https://f.feedz.io/marcorossignoli/coverletunofficial/nuget/index.json

**Comment by tonerdo** [comment]
@MarcoRossignoli, took a while but I finally figured out how to do it

**Comment by tonerdo** [comment]
I also created a new feed "coverlet-nightly"

**Comment by gitfool** [comment]
@tonerdo please post the new link to use for nightly packages so I switch to it. 😄

**Comment by MarcoRossignoli** [comment]
Super great!I'll update guide asap!
Thanks al lot!

**Comment by MarcoRossignoli** [comment]
@tonerdo when you have time you should fix this script because you have to generate a PAT to authenticate to feeds, some infos

https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops#publish-a-nuget-package-by-using-the-nuget-cli
script to update https://github.com/coverlet-coverage/coverlet/blob/master/eng/nightly.ps1

**Comment by MarcoRossignoli** [comment]
FYI @saucecontrol

**Comment by jherby2k** [comment]
How can we consume these nightlies? The link in README.md still points to MyGet.

**Comment by MarcoRossignoli** [comment]
@jherby2k at the moment we're in the middle of movement to new feed for nighty and we don't have a master version available

**Comment by MarcoRossignoli** [comment]
@jherby2k for now you can use my unofficial feed used for testing is the most updated around https://f.feedz.io/marcorossignoli/coverletunofficial/nuget/index.json

**Comment by tonerdo** [comment]
Having some auth trouble. Should figure this out soon

**Comment by MarcoRossignoli** [comment]
> Having some auth trouble. Should figure this out soon

np thanks!

**Comment by tonerdo** [comment]
Nightly build feed is now on Azure DevOps: https://pkgs.dev.azure.com/tonerdo/coverlet/_packaging/coverlet-nightly/nuget/v3/index.json

**Comment by MarcoRossignoli** [comment]
Great thanks a lot Toni, I'll update the link on guide, keep this issue open until that.

**Comment by tonerdo** [comment]
@MarcoRossignoli I already have a PR out with the pipeline and documentation updates: https://github.com/coverlet-coverage/coverlet/pull/1020
