### ISSUE TITLE
Coverlet shows %NAN% average test result in linux server. But in windows its working fine. 

### ISSUE THREAD

**Issue by mohandass17** [coverlet-coverage/coverlet#974]
Hi Team,
 I am using coverlet for code coverage in my application. While I am running test command in windows its working fine. But in **Linux its showing 100% and **%NAN%** as average**. I tried both test project and solution file in test command both giving the same error.  I am attaching the error screenshot and sample project. 
Linux Output
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20855295/96973786-38e03100-14cd-11eb-8f9a-1fe151a28557.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20855295/96973788-3a115e00-14cd-11eb-8396-60af458fbfc8.png)

**Windows Server output**
![Windows_Result](https://user-images.githubusercontent.com/20855295/96974790-8dd07700-14ce-11eb-82cb-61eb05ad9aeb.jpg)

Sample Project 
[Sample.zip](https://github.com/coverlet-coverage/coverlet/files/5428182/Sample.zip)

**Comment by MarcoRossignoli** [comment]
Likely you're hitting known issue https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test it's a randomic issue.

Can you try with collectors? https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by mohandass17** [comment]
Hi ,
I used VSTEST, but that also giving empty coverage file. 
I have already included **Microsoft.NET.Test.Sdk** already in the project. Problem in linux Jenkins CI. from visual studio I am getting proper result. 
![Empty_Coverage](https://user-images.githubusercontent.com/20855295/100613765-e7944000-32c9-11eb-970f-91e894e46207.jpg)

**Comment by MarcoRossignoli** [comment]
Is this issue active yet?

Closing for stale conversation, feel free to reopen if needed.
