### ISSUE TITLE
Code coverage returns NAN% (empty lcov.info file)

### ISSUE THREAD

**Issue by sungam3r** [coverlet-coverage/coverlet#982]
Relates to #942 

@MarcoRossignoli Hi, I need your help. I try to solve this issue in my [build](https://github.com/graphql-dotnet/parser/pull/89) but I can't do it even after 100 times. I read the documentation, known issues, all this stuff, but I still have NAN% and empty coverage file:
![изображение](https://user-images.githubusercontent.com/21261007/97356552-7cf67b80-18a9-11eb-9afe-26a26358ba8e.png)

[Here](https://github.com/graphql-dotnet/parser/suites/1409364351/artifacts/23509664) you can download binlog from GitHub Action run. I would be very grateful for your advice. I don't even know what to try anymore.

Regarding this comment https://github.com/coverlet-coverage/coverlet/issues/942#issuecomment-717768368 
Yes, for my local build on Windows PC I get not empty lcov.info file.

> You should use collectors integrator(your project seem netcoreapp so it's fully supported) https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

Why? Is it better than coverlet.msbuild?  I tried to follow instructions and got `Data collection: The datacollector with the friendly name "XPlat Code Coverage" cannot be found.` It seems that using VSTest is not my case.

**Comment by MarcoRossignoli** [comment]
![image](https://user-images.githubusercontent.com/7894084/97774664-1cda3080-1b5a-11eb-9f02-78d38b8a67c6.png)

Seem that your filter is wrong, try with `[GraphQL-Parser]*` if you take a look at coverlet output you're not instrumenting anything so no results

**Comment by sungam3r** [comment]
@MarcoRossignoli  Thank you **VERY VERY** much! I was hoping that everything would be solved simply, and that's how it happened. Just my typo. I finally was able to get test coverage https://coveralls.io/builds/34609689 

Although I had to resort to this [workaround](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/DeterministicBuild.md#workaround-only-for-net-core-sdk--31100) though my builds use 3.1.403 SDK. Do you have plans to fix this problem?

**Comment by MarcoRossignoli** [comment]
It's fixed on master, it'll be part of next release

**Comment by sungam3r** [comment]
Thank you again.
