### ISSUE TITLE
Coverlet doesnot excludes cshtml files from coverage

### ISSUE THREAD

**Issue by tavisca-vkapoor** [coverlet-coverage/coverlet#986]
Coverlet.MsBuild:- 2.6.3
Framework Used:- .Net Core 2.1
Platform : Linux 

Tried below commands

1. dotnet2.1 test csprojfilename /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=TestResults.trx" /p:ExcludeByFile="\**/demo.services.host/Views/**/\*.cshtml\"

2. dotnet2.1 test csprojfilename /p:CollectCoverage=true /p:CoverletOutputFormat=opencover  --logger "trx;LogFileName=TestResults.trx" /p:Exclude=\"[xunit.\*]\*,[demo.services.host.*.cshtml]\*\" 

After trying both the commands the output is still same as shown below
+--------------------------------------------------+--------+--------+--------+
| Module                                           | Line   | Branch | Method |
+--------------------------------------------------+--------+--------+--------+
| demo.services.host.Views              | 0%     | 0%     | 0%     |

**Comment by MarcoRossignoli** [comment]
What version of coverlet you want to use?It's not clear you said Coverlet Console version:- 1.7.2 but used dotnet test as command

The console sample is https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage

**Comment by tavisca-vkapoor** [comment]
Hey Marco,

Sorry for the wrong details
Things i have used are below
Coverlet.MsBuild:- 2.6.3
Framework Used:- .Net Core 2.1
Platform : Linux 

I have also updated the details in original issue.
remaining commands are correct and will remain same.

In the dotnet command, all the files are getting excluded except the cshtml files.

**Comment by MarcoRossignoli** [comment]
> In the dotnet command, all the files are getting excluded except the cshtml files.

Coverlet instrument only dll assemblies...we cannot instrument any other file, what do you mean for "skip cshtml files"?

**Comment by tavisca-vkapoor** [comment]
yes, you are right coverlet instruments only dll assemblies. But when we run the code coverage command , module containing the front end files ( .cshtml ) is shown in the report with 0% coverage.
Assembly name:- Demo.Services.Host
Folder containing the frontend files:- Demo.Services.Host.Views

After running the command the output displayed:- 
+--------------------------------------------------+--------+--------+--------+
| Module | Line | Branch | Method |
+--------------------------------------------------+--------+--------+--------+
| demo.services.host.Views | 0% | 0% | 0% | 

how can we exclude the coverage shown for above module "demo.services.host.Views" containing frontend files.

**Comment by MarcoRossignoli** [comment]
I think you could use filtering like `[demo.services.host.Views]*`

**Comment by tavisca-vkapoor** [comment]
> es

Hey Marco, tried the command and working successfully. Thanks for helping out.

**Comment by MarcoRossignoli** [comment]
Glad to hear!

**Comment by LearCore** [comment]
Hi I am having same issue i am not able to exclude Views- .cshtml from coverge 
My Folder sstructure in solution is .Web /Views- .cshtml files 
in the coverge result it is showing as AspNetCoreGeneraterDocumnet is 0 % . Please help which command should be used to exclude .cshtml pages

**Comment by horusceridian** [comment]
> Hey Marco, tried the command and working successfully. Thanks for helping out.

Could you share the command line, please?
