### ISSUE TITLE
Running tests for coverlet hangs

### ISSUE THREAD

**Issue by phaniva** [coverlet-coverage/coverlet#987]
I downloaded latest code for coverlet and tried to run the tests following instructions in contribution guide.

I am using Windows 10 with dotnet core 3.1 sdk. I have tried with disabling antivirus as well.
The tests kick off but appear to get stuck in the middle without any progress. It always gets stuck at after the below output.
Appreciate any help.

A total of 1 test files matched the specified pattern.

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 2.9423 Seconds

Calculating coverage result...
  Generating report 'c:\personal-projects\coverlet-orig\test\coverlet.core.performancetest\coverage.json'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+

Test Run Successful.
Total tests: 43
     Passed: 43
 Total time: 6.6760 Seconds

Calculating coverage result...
  Generating report 'c:\personal-projects\coverlet-orig\test\coverlet.collector.tests\coverage.json'

+--------------------+--------+--------+--------+
| Module             | Line   | Branch | Method |
+--------------------+--------+--------+--------+
| coverlet.collector | 68.99% | 50%    | 74.03% |
+--------------------+--------+--------+--------+
| coverlet.core      | 9.65%  | 5.84%  | 19.62% |
+--------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 19.2%  | 9.46%  | 34.95% |
+---------+--------+--------+--------+
| Average | 39.32% | 27.92% | 46.82% |
+---------+--------+--------+--------+

Test Run Successful.
Total tests: 29
     Passed: 29
 Total time: 2.4048 Minutes

**Comment by MarcoRossignoli** [comment]
Thanks for reporting this!
